### ISSUE TITLE
SnapshotReplicationTest fails on Windows

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1050]
`io.zeebe.broker.it.clustering.SnapshotReplicationTest` fails 100% of the time.

A test case fails with something like the following stacktrace, and then all remaining tests fail with address-already-in-use errors.

```
java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Users\LINDHA~1\AppData\Local\Temp\279db8e3-7a65-4120-beba-056e5ed110d5\data\internal-system-0\snapshots\snap-1.snapshot: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:44)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.nio.file.FileSystemException: C:\Users\LINDHA~1\AppData\Local\Temp\279db8e3-7a65-4120-beba-056e5ed110d5\data\internal-system-0\snapshots\snap-1.snapshot: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at io.zeebe.util.FileUtil$1.visitFile(FileUtil.java:52)
	at io.zeebe.util.FileUtil$1.visitFile(FileUtil.java:1)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:46)
	at io.zeebe.broker.it.clustering.ClusteringRule.lambda$0(ClusteringRule.java:100)
	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:42)
	... 17 more
```

**Comment by ThorbenLindhauer** [comment]
Maybe related to https://github.com/zeebe-io/zeebe/issues/985.
