### ISSUE TITLE
GossipClusteringTest unstable 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1056]
Sometimes fails on Jenkins where it is not able to wait for new leader after stopping the broker.

```
[Tests] [ERROR] shouldRemoveLeaderFromCluster(io.zeebe.broker.it.clustering.GossipClusteringTest)  Time elapsed: 27.249 s  <<< FAILURE!
[Tests] org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
[Tests] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Tests] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Tests] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Tests] 	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:123)
[Tests] 	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:78)
[Tests] 	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:50)
[Tests] 	at io.zeebe.broker.it.clustering.ClusteringRule.waitForTopology(ClusteringRule.java:439)
[Tests] 	at io.zeebe.broker.it.clustering.ClusteringRule.waitForNewLeaderOfPartitions(ClusteringRule.java:425)
[Tests] 	at io.zeebe.broker.it.clustering.ClusteringRule.stopBroker(ClusteringRule.java:409)
[Tests] 	at io.zeebe.broker.it.clustering.ClusteringRule.stopBroker(ClusteringRule.java:397)
[Tests] 	at io.zeebe.broker.it.clustering.GossipClusteringTest.shouldRemoveLeaderFromCluster(GossipClusteringTest.java:92)
[Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Tests] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Tests] 	at java.lang.reflect.Method.invoke(Method.java:498)
[Tests] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[Tests] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[Tests] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[Tests] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[Tests] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
[Tests] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
[Tests] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Tests] 	at java.lang.Thread.run(Thread.java:748)
```

[io.zeebe.broker.it.clustering.GossipClusteringTest-output.txt](https://github.com/zeebe-io/zeebe/files/2197525/io.zeebe.broker.it.clustering.GossipClusteringTest-output.txt)

**Comment by menski** [comment]
Based on the log output it seems that non of the follower was able to fully join the raft group before the leader was shutdown, which explains why no new leader is elected.

**Comment by menski** [comment]
The same test exists in the class `GossipDifferentNodeJoinTest`. Also from another build it seems that it is also possible to end up in a vote loop. Which might be breakable if poll requests are rejected by candidates, not sure about that.

[io.zeebe.broker.it.clustering.GossipDifferentNodeJoinTest-output.txt](https://github.com/zeebe-io/zeebe/files/2197625/io.zeebe.broker.it.clustering.GossipDifferentNodeJoinTest-output.txt)

**Comment by menski** [comment]
We will replace the gossip module
