### ISSUE TITLE
Invalid mocking in raft rule

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1066]
Saw this once when running the five node raft test in a loop

```
[ERROR] shouldRejoinCluster(io.zeebe.raft.RaftFiveNodesTest)  Time elapsed: 24.722 s  <<< ERROR!
java.util.concurrent.ExecutionException: 

Unfinished stubbing detected here:
-> at io.zeebe.raft.util.RaftRule.lambda$reconnectTo$8(RaftRule.java:488)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed

        at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:152)
        at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:118)
        at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:28)
        at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:224)
        at io.zeebe.raft.util.RaftRule.reconnectTo(RaftRule.java:498)
        at io.zeebe.raft.util.RaftClusterRule.lambda$registerRaft$0(RaftClusterRule.java:90)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.zeebe.raft.util.RaftClusterRule.registerRaft(RaftClusterRule.java:88)
        at io.zeebe.raft.RaftFiveNodesTest.shouldRejoinCluster(RaftFiveNodesTest.java:172)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at io.zeebe.raft.util.RaftRule.lambda$reconnectTo$8(RaftRule.java:488)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed

        at io.zeebe.raft.util.RaftRule.lambda$reconnectTo$8(RaftRule.java:490)
        at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:145)
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76)
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187)
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154)
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135)
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112)
```

**Comment by Zelldon** [comment]
Had run this in a loop as well, but can't reproduce the problem. I think it is again a problem with concurrent access of the the mocked method and changing the mocking.
