### ISSUE TITLE
Raft allows two leaders to be elected in the same term

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1068]
On Jenkins we saw a failure of the should rejoin cluster test which shows in the log that two nodes became leader in the same term.

```
[ERROR] shouldRejoinCluster(io.zeebe.raft.RaftFiveNodesTest)  Time elapsed: 35.324 s  <<< FAILURE!
java.lang.AssertionError: Failed to wait for commit of event EventInfo{position=8589934816, term=2, message='world'} with message on all rafts
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:138)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:86)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:58)
	at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:277)
	at io.zeebe.raft.util.RaftClusterRule.awaitEventCommittedOnAll(RaftClusterRule.java:166)
	at io.zeebe.raft.RaftFiveNodesTest.shouldRejoinCluster(RaftFiveNodesTest.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

[surefire-output.log](https://github.com/zeebe-io/zeebe/files/2213774/surefire-output.log)

**Comment by Zelldon** [comment]
Saw this today as well on `shouldTruncateLog(io.zeebe.raft.RaftFiveNodesTest`

After interrupting connection and reconnect two raft become leader and send append request until the test dies.
```java
11:42:23.658 [] [main] DEBUG io.zeebe.raft - Interrupt connections for localhost:8002
11:42:23.668 [] [main] DEBUG io.zeebe.raft - Interrupt connections for localhost:8003
11:42:23.672 [] [main] DEBUG io.zeebe.raft - Interrupt connections for localhost:8004
11:42:23.675 [] [main] DEBUG io.zeebe.raft - Interrupt connections for localhost:8005
11:42:23.677 [] [main] DEBUG io.zeebe.raft - Interrupt connections for localhost:8001
11:42:24.846 [default-0-8004] [-zb-fs-workers-1] DEBUG io.zeebe.raft - poll request send to 4 other members
11:42:24.846 [default-0-8004] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Failed to receive poll response from RemoteAddress{streamId=3, addr=localhost:8001}
11:42:24.848 [default-0-8003] [-zb-fs-workers-1] DEBUG io.zeebe.raft - accept poll request
11:42:24.848 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - accept poll request
11:42:24.849 [default-0-8004] [-zb-fs-workers-1] DEBUG io.zeebe.raft - poll request successful with 3 votes for a quorum of 3
11:42:24.847 [default-0-8005] [-zb-fs-workers-0] DEBUG io.zeebe.raft - accept poll request
11:42:24.850 [default-0-8004] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_CANDIDATE, term=2} from state FOLLOWER
11:42:24.853 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - vote request send to 4 other members
11:42:24.853 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - poll request send to 4 other members
11:42:24.854 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Failed to receive poll response from RemoteAddress{streamId=1, addr=localhost:8001}
11:42:24.854 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to receive vote response from RemoteAddress{streamId=3, addr=localhost:8001}
11:42:24.855 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Received message with higher term 2 > 1
11:42:24.855 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state FOLLOWER
11:42:24.856 [default-0-8005] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Received message with higher term 2 > 1
11:42:24.856 [default-0-8005] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state FOLLOWER
11:42:24.857 [default-0-8005] [-zb-fs-workers-1] DEBUG io.zeebe.raft - accept poll request
11:42:24.856 [default-0-8003] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Received message with higher term 2 > 1
11:42:24.857 [default-0-8003] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state FOLLOWER
11:42:24.856 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state CANDIDATE in term 2
11:42:24.857 [default-0-8003] [-zb-fs-workers-0] DEBUG io.zeebe.raft - accept poll request
11:42:24.859 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - vote request successful with 4 votes for a quorum of 3
11:42:24.859 [default-0-8002] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Received message with higher term 2 > 1
11:42:24.860 [default-0-8002] [-zb-fs-workers-0] DEBUG io.zeebe.raft - poll request successful with 3 votes for a quorum of 3
11:42:24.860 [default-0-8002] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Setting next transition Transition{raftTranisiton=TO_CANDIDATE, term=2} during transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state FOLLOWER
11:42:24.860 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_LEADER, term=2} from state CANDIDATE
11:42:24.860 [default-0-8005] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2
11:42:24.866 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2
11:42:24.866 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_CANDIDATE, term=2} from state FOLLOWER
11:42:24.866 [default-0-8003] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2
11:42:24.884 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - vote request send to 4 other members
11:42:24.884 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to receive vote response from RemoteAddress{streamId=1, addr=localhost:8001}
11:42:24.884 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state CANDIDATE in term 2
11:42:24.887 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - vote request successful with 3 votes for a quorum of 3
11:42:24.888 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_LEADER, term=2} from state CANDIDATE
11:42:24.910 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Initial event for term 2 was appended on position 8589934592
11:42:24.911 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Transitioned to state LEADER in term 2
11:42:24.914 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Initial event for term 2 was committed on position 8589934592
11:42:24.932 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.933 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Initial event for term 2 was appended on position 8589934592
11:42:24.934 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state LEADER in term 2
11:42:24.935 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.936 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.937 [default-0-8002] [-zb-actors-0] DEBUG io.zeebe.raft - Initial event for term 2 was committed on position 8589934592
11:42:24.939 [default-0-8002] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.940 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.941 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.942 [default-0-8002] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.943 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.944 [default-0-8002] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.945 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.946 [default-0-8002] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.947 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.948 [default-0-8002] [-zb-actors-1] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.948 [default-0-8004] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.949 [default-0-8002] [-zb-actors-0] DEBUG io.zeebe.raft - Got Append request in leader state 
11:42:24.949 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Got Append request in leader state 
```

I think the main problem is in the following lines:
```java
[...]

11:42:24.856 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state CANDIDATE in term 2
11:42:24.857 [default-0-8003] [-zb-fs-workers-0] DEBUG io.zeebe.raft - accept poll request
11:42:24.859 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - vote request successful with 4 votes for a quorum of 3
11:42:24.859 [default-0-8002] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Received message with higher term 2 > 1
11:42:24.860 [default-0-8002] [-zb-fs-workers-0] DEBUG io.zeebe.raft - poll request successful with 3 votes for a quorum of 3
11:42:24.860 [default-0-8002] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Setting next transition Transition{raftTranisiton=TO_CANDIDATE, term=2} during transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state FOLLOWER
11:42:24.860 [default-0-8004] [-zb-actors-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_LEADER, term=2} from state CANDIDATE
11:42:24.860 [default-0-8005] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2
11:42:24.866 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2
11:42:24.866 [default-0-8002] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_CANDIDATE, term=2} from state FOLLOWER
11:42:24.866 [default-0-8003] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2

[...]
```
The 8004 becomes candidate and leader cleanly. The 8002 receives a message with a higher term and as well his poll request comes back so he becomes candidate as well. I think since he get a message with higher term he should no became candidate.
