### ISSUE TITLE
Occasional address already bind exception in test suite

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1072]
On Jenkins some builds randomly fail with a `BindException: Address already in use` failure. 
```
15:33:01.013 [service-controller] [0.0.0.0:51015-zb-actors-1] ERROR io.zeebe.servicecontainer - Service failed to start while in AwaitStartState
java.lang.RuntimeException: Failed to bind to address: /0.0.0.0:51016
	at io.zeebe.transport.impl.ServerSocketBinding.doBind(ServerSocketBinding.java:56) ~[zb-transport-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.transport.ServerTransportBuilder.buildTransportContext(ServerTransportBuilder.java:130) ~[zb-transport-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.transport.ServerTransportBuilder.buildBuffering(ServerTransportBuilder.java:118) ~[zb-transport-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.broker.transport.BufferingServerTransportService.start(BufferingServerTransportService.java:64) ~[classes/:?]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitDependenciesStartedState.onDependenciesAvailable(ServiceController.java:167) ~[zb-service-container-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitDependenciesStartedState.accept(ServiceController.java:121) ~[zb-service-container-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitDependenciesStartedState.accept(ServiceController.java:115) ~[zb-service-container-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController.onServiceEvent(ServiceController.java:105) ~[zb-service-container-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_162]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_162]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_162]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_162]
	at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157) ~[?:1.8.0_162]
	at io.zeebe.transport.impl.ServerSocketBinding.doBind(ServerSocketBinding.java:51) ~[zb-transport-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
```

We now ensure with #965 that all sockets are released correctly. Nevertheless we still see this happen quite often over a day on Jenkins.

When we use a tool like `ss` to list all TCP sockets at the moment of the exceptions we see a long list of sockets in the `TIME-WAIT`. This state is reached by the closing side of a TCP connection, so normally this is the client side of a connection. In the example listing below we see that port `51016` is also in the `TIME-WAIT` state. 

```
TIME-WAIT  0      0        ::ffff:127.0.0.1:51016     ::ffff:127.0.0.1:8001
```    

This indicates there was a TCP connection from port `51016` to `8001` and it was closed by the `51016` side of the connection. The port `8001` is used by the raft and gossip test suite. The port used by a client connection is assigned randomly on connect. Which means the test suite might always fail whenever some client connection randomly chooses a port which matches one of our Zeebe server ports, which unfortunately lay inside the ephemeral port range.

```
$ cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
```

This can also be a real world problem on a server which maybe also used this port for a previous connection, which would Zeebe prevent from starting.

##### Full socket listing during test failure
```
$ ss -tap
State      Recv-Q Send-Q      Local Address:Port          Peer Address:Port   
LISTEN     0      128                     *:ssh                      *:*       
ESTAB      0      0              172.17.0.6:ssh        192.168.178.125:39856   
LISTEN     0      50                     :::51015                   :::*        users:(("java",5399,105))
LISTEN     0      50                     :::51017                   :::*        users:(("java",5399,101))
LISTEN     0      128                    :::ssh                     :::*       
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55777   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54959     ::ffff:127.0.0.1:8002    
CLOSE-WAIT 1      0       ::ffff:172.17.0.6:55015   ::ffff:192.168.178.125:9201     users:(("java",981,250))
TIME-WAIT  0      0        ::ffff:127.0.0.1:51131     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55796   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55704   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55741   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54799     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55705   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54866     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51208     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55733   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54781   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54950     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51179     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:50853     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:50984     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51276     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54782     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54882   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54797   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40346   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51217     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54985     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:55014     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54836   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51284     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54903     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51009     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51287     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51014     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54948   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40310   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54813   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54767     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54556   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51171     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54847     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54884     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54561     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:50815     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52468   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54735   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54794   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55778   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51038     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51258     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51001     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54912     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51169     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51133     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:50862     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51161     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55612   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40361   
TIME-WAIT  0      0        ::ffff:127.0.0.1:50991     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55564   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51239     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54752   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51040     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52462   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54957   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54987   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51087     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54855   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55761   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51028     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54892   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55640   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55685   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54776     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55732   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54875     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:55011     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52461   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55657   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51236     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54760   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54602   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54733   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55714   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55359   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54920   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51267     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51273     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40311   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55009   
TIME-WAIT  0      0        ::ffff:127.0.0.1:52470     ::ffff:127.0.0.1:8004    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8001      ::ffff:127.0.0.1:50982   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55723   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55003   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55581   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55038   
TIME-WAIT  0      0        ::ffff:127.0.0.1:55389     ::ffff:127.0.0.1:8003    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40355   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51053     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40357   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54765   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51143     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54993   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54740   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51071     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54829     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55666   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54815     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52405   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54941     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55339   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54864   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55403   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55715   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51023     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51197     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52416   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51055     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54932     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40312   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54607     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8001      ::ffff:127.0.0.1:50989   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40356   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54804   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55589   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55751   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52451   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55769   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55648   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8001      ::ffff:127.0.0.1:50505   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55676   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51003     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40313   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51122     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:50863     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55742   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55588   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51215     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55597   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54857     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54968     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:55391     ::ffff:127.0.0.1:8003    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51188     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54614     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54757   
TIME-WAIT  0      0        ::ffff:127.0.0.1:55343     ::ffff:127.0.0.1:8003    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54774   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54838     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55620   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51270     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51199     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51255     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54894     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51011     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54910   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51242     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51150     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55621   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54930   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54265   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55694   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55658   
TIME-WAIT  0      0        ::ffff:127.0.0.1:50816     ::ffff:127.0.0.1:8001    
CLOSE-WAIT 1      0       ::ffff:172.17.0.6:55014   ::ffff:192.168.178.125:9201     users:(("java",981,247))
TIME-WAIT  0      0        ::ffff:127.0.0.1:54822     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55021   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51141     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51206     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55018   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51096     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54791     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:52422     ::ffff:127.0.0.1:8004    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51190     ::ffff:127.0.0.1:8001    
CLOSE-WAIT 1      0       ::ffff:172.17.0.6:55017   ::ffff:192.168.178.125:9201     users:(("java",981,254))
TIME-WAIT  0      0        ::ffff:127.0.0.1:51029     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55360   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51064     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51263     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54567   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52417   
TIME-WAIT  0      0        ::ffff:127.0.0.1:50807     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55611   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54605     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:50819     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55630   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54742   
TIME-WAIT  0      0        ::ffff:127.0.0.1:50865     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51260     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55006   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54966   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55549   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51227     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55677   
TIME-WAIT  0      0        ::ffff:127.0.0.1:55345     ::ffff:127.0.0.1:8003    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55750   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51078     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8005      ::ffff:127.0.0.1:40300   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51069     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51225     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55385   
CLOSE-WAIT 1      0       ::ffff:172.17.0.6:55016   ::ffff:192.168.178.125:9201     users:(("java",981,251))
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55604   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51115     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54976   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54789   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51124     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55760   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51278     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51106     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54978     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54820   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51048     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51152     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54568     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55629   
TIME-WAIT  0      0        ::ffff:127.0.0.1:55029     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54754     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54611   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55695   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51252     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51281     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51104     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55686   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54827   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51076     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51006     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51159     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54762     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:54559     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55667   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51016     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54845   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54806     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54901   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55035   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51244     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51094     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54939   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54873   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54995     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55032   
CLOSE-WAIT 1      0       ::ffff:172.17.0.6:55018   ::ffff:192.168.178.125:9201     users:(("java",981,255))
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55649   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51181     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8001      ::ffff:127.0.0.1:50805   
TIME-WAIT  0      0        ::ffff:127.0.0.1:50507     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8004      ::ffff:127.0.0.1:52415   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55639   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:54256   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51025     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8001      ::ffff:127.0.0.1:50851   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51043     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51046     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55550   
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55027   
TIME-WAIT  0      0        ::ffff:127.0.0.1:51085     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8002      ::ffff:127.0.0.1:55024   
TIME-WAIT  0      0        ::ffff:127.0.0.1:54922     ::ffff:127.0.0.1:8002    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51062     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:51113     ::ffff:127.0.0.1:8001    
TIME-WAIT  0      0        ::ffff:127.0.0.1:8003      ::ffff:127.0.0.1:55402  
```

**Comment by menski** [comment]
Hopefully fixed with move out of dynamic port range
