### ISSUE TITLE
CreateDeploymentMultiplePartitionsTest is unstable

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1250]
Seems to fail in approximately one out of ten runs.

Stack trace:

```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.973 s <<< FAILURE! - in io.zeebe.broker.workflow.CreateDeploymentMultiplePartitionsTest
[ERROR] shouldIncrementWorkflowVersions(io.zeebe.broker.workflow.CreateDeploymentMultiplePartitionsTest)  Time elapsed: 11.778 s  <<< ERROR!
java.lang.RuntimeException: no more events available
        at io.zeebe.test.broker.protocol.clientapi.RawMessageCollector.get(RawMessageCollector.java:51)
        at io.zeebe.test.broker.protocol.clientapi.RawMessageCollector.get(RawMessageCollector.java:25)
        at java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(StreamSpliterators.java:1356)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at one.util.streamex.TakeDrop$UnorderedTDOfRef.tryAdvance(TakeDrop.java:136)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at one.util.streamex.AbstractStreamEx.findFirst(AbstractStreamEx.java:462)
        at io.zeebe.broker.workflow.CreateDeploymentMultiplePartitionsTest.assertCreatedDeploymentEventResources(CreateDeploymentMultiplePartitionsTest.java:331)
        at io.zeebe.broker.workflow.CreateDeploymentMultiplePartitionsTest.shouldIncrementWorkflowVersions(CreateDeploymentMultiplePartitionsTest.java:198)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

**Comment by deepthidevaki** [comment]
[PushDeploymentRequestHandler](https://github.com/zeebe-io/zeebe/blob/23cdd720546b0bada9e95b73a2faffe1bd3f9bb4/broker-core/src/main/java/io/zeebe/broker/system/management/deployment/PushDeploymentRequestHandler.java#L111) respond with a success before the CREATE record is committed to the logstream. `tryWrite()` [here](https://github.com/zeebe-io/zeebe/blob/23cdd720546b0bada9e95b73a2faffe1bd3f9bb4/broker-core/src/main/java/io/zeebe/broker/system/management/deployment/PushDeploymentRequestHandler.java#L154) only writes to the dispatcher not to the logstorage. When the broker restarts after sending the response, but before writing persistently to the logstream, the deployment partition assumes that the previous distribution was successful and does not try to re-distribute. This might be the reason that `shouldCreateDeploymentOnAllPartitionsWithRestartBroker` fails sometimes.
