### ISSUE TITLE
RaftThreeNodesTests timeouts because no new leader is found

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1327]
Locally I have often the problem that the Raft tests fail with this error:

```java
[ERROR] shouldRejoinCluster(io.zeebe.raft.RaftThreeNodesTest)  Time elapsed: 31.778 s  <<< FAILURE!
java.lang.AssertionError: Failed to wait for a node to become leader in the cluster
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:138)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:86)
        at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:58)
        at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:283)
        at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:295)
        at io.zeebe.raft.util.RaftClusterRule.awaitLeader(RaftClusterRule.java:220)
        at io.zeebe.raft.RaftThreeNodesTest.shouldRejoinCluster(RaftThreeNodesTest.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

```

It seems that after removing the leader the remaining nodes became both candidate.
Node 2 steps down but node 3 does not became leader.

```java
15:00:58.672 [] [main] INFO  io.zeebe.test - Test started: shouldRejoinCluster(io.zeebe.raft.RaftThreeNodesTest)
15:00:58.678 [] [main] INFO  io.zeebe.raft - Created raft 0-1 with configuration RaftConfiguration{heartbeatInterval='250ms', electionInterval='1s', leaveTimeout='10s'}
15:00:58.678 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=0} from state null
15:00:58.679 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - Ignoring configuration request in single node cluster in term 0
15:00:58.679 [0-1] [-zb-actors-0] INFO  io.zeebe.raft - Joined raft in term 0
15:00:58.686 [0-1] [-zb-fs-workers-0] DEBUG io.zeebe.raft - poll request send to 0 other members
15:00:58.687 [0-1] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 0
15:00:58.687 [0-1] [-zb-fs-workers-0] DEBUG io.zeebe.raft - poll request successful with 1 votes for a quorum of 1
15:00:58.687 [0-1] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_CANDIDATE, term=1} from state FOLLOWER
15:00:58.689 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - vote request send to 0 other members
15:00:58.690 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - vote request successful with 1 votes for a quorum of 1
15:00:58.690 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - Setting next transition Transition{raftTranisiton=TO_LEADER, term=1} during transition Transition{raftTranisiton=TO_CANDIDATE, term=1} from state null
15:00:58.690 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - Transitioned to state CANDIDATE in term 1
15:00:58.690 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_LEADER, term=1} from state CANDIDATE
15:00:58.691 [] [main] INFO  io.zeebe.raft - Created raft 0-2 with configuration RaftConfiguration{heartbeatInterval='250ms', electionInterval='1s', leaveTimeout='10s'}
15:00:58.693 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=0} from state null
15:00:58.694 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Send join configuration request to node 1
15:00:58.694 [0-2] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 0
15:00:58.700 [0-1] [-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state LEADER in term 1
15:00:58.701 [0-1] [-zb-actors-1] DEBUG io.zeebe.raft - Initial event for term 1 was appended on position 4294967296
15:00:58.701 [0-1] [-zb-actors-1] DEBUG io.zeebe.raft - Initial event for term 1 was committed on position 4294967296
15:00:58.702 [] [main] INFO  io.zeebe.raft - Created raft 0-3 with configuration RaftConfiguration{heartbeatInterval='250ms', electionInterval='1s', leaveTimeout='10s'}
15:00:58.703 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '2' with address 'localhost:25632' on transport 'raft-1'
15:00:58.703 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '1' with address 'localhost:25631' on transport 'raft-2'
15:00:58.703 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '3' with address 'localhost:25633' on transport 'raft-1'
15:00:58.703 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '1' with address 'localhost:25631' on transport 'raft-3'
15:00:58.704 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '3' with address 'localhost:25633' on transport 'raft-2'
15:00:58.704 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '2' with address 'localhost:25632' on transport 'raft-3'
15:00:58.704 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=0} from state null
15:00:58.704 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Send join configuration request to node 1
15:00:58.707 [0-3] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 0
15:00:58.739 [0-1] [-zb-actors-0] DEBUG io.zeebe.raft - New member 3 joining the cluster
15:00:58.753 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Received message with higher term 1 > 0
15:00:58.753 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=1} from state FOLLOWER
15:00:58.753 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Configuration response with different term.
15:00:58.754 [0-2] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 1
15:00:58.972 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Send join configuration request to node 1
15:00:58.973 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Configuration request was rejected in term 1
15:00:59.004 [0-3] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Received message with higher term 1 > 0
15:00:59.004 [0-3] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=1} from state FOLLOWER
15:00:59.004 [0-3] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 1
15:00:59.006 [0-1] [-zb-actors-1] DEBUG io.zeebe.raft - Raft event for term 1 was committed on position 4294967408
15:00:59.007 [0-3] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Configuration request was accepted in term 1
15:00:59.007 [0-3] [-zb-fs-workers-1] INFO  io.zeebe.raft - Joined raft in term 1
15:00:59.182 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Send join configuration request to node 1
15:00:59.182 [0-1] [-zb-actors-1] DEBUG io.zeebe.raft - New member 2 joining the cluster
15:00:59.184 [0-1] [-zb-actors-1] DEBUG io.zeebe.raft - Raft event for term 1 was committed on position 4294967544
15:00:59.185 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Configuration request was accepted in term 1
15:00:59.185 [0-2] [-zb-fs-workers-0] INFO  io.zeebe.raft - Joined raft in term 1
15:01:00.110 [] [main] DEBUG io.zeebe.raft - Interrupt connections for node 1
15:01:00.111 [] [main] INFO  io.zeebe.transport.endpoint - Deactivating endpoint for node '2' with address 'RemoteAddress{streamId=0, addr=localhost:25632}' on transport 'raft-1'
15:01:00.111 [] [main] INFO  io.zeebe.transport.endpoint - Deactivating endpoint for node '1' with address 'RemoteAddress{streamId=0, addr=localhost:25631}' on transport 'raft-2'
15:01:00.111 [] [main] INFO  io.zeebe.transport.endpoint - Deactivating endpoint for node '3' with address 'RemoteAddress{streamId=1, addr=localhost:25633}' on transport 'raft-1'
15:01:00.111 [] [main] INFO  io.zeebe.transport.endpoint - Deactivating endpoint for node '1' with address 'RemoteAddress{streamId=0, addr=localhost:25631}' on transport 'raft-3'
15:01:02.031 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - poll request send to 2 other members
15:01:02.069 [0-3] [-zb-fs-workers-1] DEBUG io.zeebe.raft - poll request send to 2 other members
15:01:02.284 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - accept poll request
15:01:02.284 [0-3] [-zb-fs-workers-1] DEBUG io.zeebe.raft - accept poll request
15:01:02.284 [0-3] [-zb-fs-workers-1] DEBUG io.zeebe.raft - poll request successful with 2 votes for a quorum of 2
15:01:02.284 [0-3] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_CANDIDATE, term=2} from state FOLLOWER
15:01:02.285 [0-2] [-zb-fs-workers-1] DEBUG io.zeebe.raft - poll request successful with 2 votes for a quorum of 2
15:01:02.285 [0-2] [-zb-fs-workers-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_CANDIDATE, term=2} from state FOLLOWER
15:01:02.285 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - vote request send to 2 other members
15:01:02.285 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - vote request send to 2 other members
15:01:02.285 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Transitioned to state CANDIDATE in term 2
15:01:02.286 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state CANDIDATE in term 2
15:01:08.465 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to receive poll response from 1
15:01:08.703 [0-2] [-zb-actors-0] DEBUG io.zeebe.raft - Failed to receive vote response from 1
15:01:08.704 [0-2] [-zb-actors-0] DEBUG io.zeebe.raft - vote request failed with 1 votes for a quorum of 2
15:01:08.704 [0-2] [-zb-actors-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state CANDIDATE
15:01:08.704 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 2
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Log entries for raft node 2
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967296, term: 1, type: NOOP, committed: true }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967408, term: 1, type: RAFT, committed: true }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967544, term: 1, type: RAFT, committed: true }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967688, term: 1, type: NULL_VAL, committed: true, message: foo }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967800, term: 1, type: NULL_VAL, committed: true, message: bar }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Log entries for raft node 3
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967296, term: 1, type: NOOP, committed: true }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967408, term: 1, type: RAFT, committed: true }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967544, term: 1, type: RAFT, committed: true }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967688, term: 1, type: NULL_VAL, committed: true, message: foo }
15:01:10.027 [] [main] ERROR io.zeebe.raft.test - Event { position: 4294967800, term: 1, type: NULL_VAL, committed: true, message: bar }
15:01:10.284 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Send leave configuration request to 2
15:01:10.284 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Configuration request was rejected in term 2
15:01:10.522 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - poll request send to 2 other members
15:01:10.556 [0-3] [-zb-actors-1] DEBUG io.zeebe.raft - Send leave configuration request to 1
15:01:14.439 [0-3] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to send configuration request to 1
15:01:14.703 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Send leave configuration request to 2
15:01:14.704 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Configuration request was rejected in term 2
15:01:15.028 [] [main] ERROR io.zeebe.raft - Timeout after: 5 SECONDS
java.util.concurrent.TimeoutException: Timeout after: 5 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145) ~[zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.raft.util.RaftRule.lambda$closeRaft$0(RaftRule.java:189) ~[test-classes/:?]
	at io.zeebe.util.LogUtil.catchAndLog(LogUtil.java:49) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.raft.util.RaftRule.closeRaft(RaftRule.java:187) [test-classes/:?]
	at io.zeebe.raft.util.RaftRule.after(RaftRule.java:170) [test-classes/:?]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386) [surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323) [surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143) [surefire-booter-2.20.jar:2.20]
15:01:15.284 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Failed to receive poll response from 1
15:01:15.284 [0-3] [-zb-actors-0] DEBUG io.zeebe.raft - Send leave configuration request to 1
15:01:15.428 [0-3] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to receive vote response from 1
15:01:15.428 [0-3] [-zb-actors-1] DEBUG io.zeebe.raft - vote request failed with 1 votes for a quorum of 2
15:01:15.428 [0-3] [-zb-actors-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=2} from state CANDIDATE
15:01:15.429 [service-container-main] [-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to remove service raft.candidate.0-3.2: java.lang.IllegalArgumentException: Cannot remove service with name 'raft.candidate.0-3.2': no such service registered.
15:01:20.423 [0-3] [-zb-actors-0] WARN  io.zeebe.raft - Timeout while leaving raft cluster.
15:01:20.429 [0-2] [-zb-fs-workers-0] DEBUG io.zeebe.raft - Send leave configuration request to 3
15:01:24.592 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to send configuration request to 3
15:01:24.592 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to receive poll response from 1
15:01:24.592 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - Failed to receive poll response from 3
15:01:24.592 [0-2] [-zb-actors-1] DEBUG io.zeebe.raft - poll request failed with 1 votes for a quorum of 2
15:01:25.283 [0-2] [-zb-actors-0] DEBUG io.zeebe.raft - Send leave configuration request to 1
15:01:25.429 [] [main] ERROR io.zeebe.raft - Timeout after: 5 SECONDS
java.util.concurrent.TimeoutException: Timeout after: 5 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145) ~[zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.raft.util.RaftRule.lambda$closeRaft$0(RaftRule.java:189) ~[test-classes/:?]
	at io.zeebe.util.LogUtil.catchAndLog(LogUtil.java:49) [zb-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at io.zeebe.raft.util.RaftRule.closeRaft(RaftRule.java:187) [test-classes/:?]
	at io.zeebe.raft.util.RaftRule.after(RaftRule.java:170) [test-classes/:?]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) [surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386) [surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323) [surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143) [surefire-booter-2.20.jar:2.20]
15:01:26.284 [0-2] [-zb-actors-0] DEBUG io.zeebe.raft - poll request send to 2 other members
15:01:30.435 [0-2] [-zb-actors-0] WARN  io.zeebe.raft - Timeout while leaving raft cluster.
15:01:30.450 [] [main] INFO  io.zeebe.test - Test finished: shouldRejoinCluster(io.zeebe.raft.RaftThreeNodesTest)

```

**Comment by Zelldon** [comment]
we removed our raft impl
