### ISSUE TITLE
Sequence of integration tests fails

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#135]
Execute two integration tests in order. Second one fails. Broker shutdown seems not to release socket binding properly.

There's two issues to this: 

* the actual issue that the broker does not come up a second time
* the issue that there can be exceptions during startup that let the broker hang infinitely (which required commits https://github.com/camunda-tngp/service-container/commit/de81887ddf7e142ad00dce005af08040b7b0c751 and https://github.com/camunda-tngp/camunda-tngp/commit/2c63d5027423d41b77e387ddb7070e2f1938eb1d to make the integration tests halt at all)

Build output:

```

16:44:17 Running org.camunda.bpm.broker.it.taskqueue.TaskQueueTest
16:44:17 No configuration provided, using default configuration.
16:44:17 Using /tmp/tngp-counters1808361842751672932.raw for counters.
16:44:17 Created temp directory for snapshots at location /tmp/tngp-snapshot-386238537563699001.
16:44:17 Bound clientApi to /0.0.0.0:51015.
16:44:17 Bound management to localhost/127.0.0.1:51016.
16:44:17 transition to state: FOLLOWER
16:44:18 transition to state: CANDIDATE
16:44:18 transition to state: LEADER
16:44:18 [LEADER] leader for 0
16:44:18 Closing...
16:44:18 Broker closed.
16:44:18 No configuration provided, using default configuration.
16:44:18 Using /tmp/tngp-counters4529166185023776775.raw for counters.
16:44:18 Created temp directory for snapshots at location /tmp/tngp-snapshot-5215797877713458531.
16:44:19 Bound management to localhost/127.0.0.1:51016.
16:44:19 java.util.concurrent.CompletionException: java.net.BindException: Address already in use
16:44:19 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
16:44:19 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
16:44:19 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
16:44:19 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
16:44:19 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
16:44:19 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doBindServerSocket(TransportConductor.java:236)
16:44:19 	at org.camunda.tngp.transport.ServerSocketBindingBuilder.lambda$bindAsync$0(ServerSocketBindingBuilder.java:53)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.accept(TransportConductor.java:82)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.accept(TransportConductor.java:26)
16:44:19 	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:108)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doWork(TransportConductor.java:62)
16:44:19 	at org.camunda.tngp.util.agent.AgentGroup.doWork(AgentGroup.java:40)
16:44:19 	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
16:44:19 	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
16:44:19 	at java.lang.Thread.run(Thread.java:745)
16:44:19 Caused by: java.net.BindException: Address already in use
16:44:19 	at sun.nio.ch.Net.bind0(Native Method)
16:44:19 	at sun.nio.ch.Net.bind(Net.java:433)
16:44:19 	at sun.nio.ch.Net.bind(Net.java:425)
16:44:19 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
16:44:19 	at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157)
16:44:19 	at org.camunda.tngp.transport.impl.ServerSocketBindingImpl.doBind(ServerSocketBindingImpl.java:66)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doBindServerSocket(TransportConductor.java:229)
16:44:19 	... 9 more
16:44:19 java.util.concurrent.CompletionException: java.net.BindException: Address already in use
16:44:19 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
16:44:19 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
16:44:19 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
16:44:19 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
16:44:19 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
16:44:19 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doBindServerSocket(TransportConductor.java:236)
16:44:19 	at org.camunda.tngp.transport.ServerSocketBindingBuilder.lambda$bindAsync$0(ServerSocketBindingBuilder.java:53)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.accept(TransportConductor.java:82)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.accept(TransportConductor.java:26)
16:44:19 	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:108)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doWork(TransportConductor.java:62)
16:44:19 	at org.camunda.tngp.util.agent.AgentGroup.doWork(AgentGroup.java:40)
16:44:19 	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
16:44:19 	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
16:44:19 	at java.lang.Thread.run(Thread.java:745)
16:44:19 Caused by: java.net.BindException: Address already in use
16:44:19 	at sun.nio.ch.Net.bind0(Native Method)
16:44:19 	at sun.nio.ch.Net.bind(Net.java:433)
16:44:19 	at sun.nio.ch.Net.bind(Net.java:425)
16:44:19 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
16:44:19 	at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157)
16:44:19 	at org.camunda.tngp.transport.impl.ServerSocketBindingImpl.doBind(ServerSocketBindingImpl.java:66)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doBindServerSocket(TransportConductor.java:229)
16:44:19 	... 9 more
16:44:19 Exception in thread "service-container-main" java.util.concurrent.CompletionException: java.net.BindException: Address already in use
16:44:19 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
16:44:19 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
16:44:19 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
16:44:19 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
16:44:19 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
16:44:19 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doBindServerSocket(TransportConductor.java:236)
16:44:19 	at org.camunda.tngp.transport.ServerSocketBindingBuilder.lambda$bindAsync$0(ServerSocketBindingBuilder.java:53)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.accept(TransportConductor.java:82)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.accept(TransportConductor.java:26)
16:44:19 	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:108)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doWork(TransportConductor.java:62)
16:44:19 	at org.camunda.tngp.util.agent.AgentGroup.doWork(AgentGroup.java:40)
16:44:19 	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
16:44:19 	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
16:44:19 	at java.lang.Thread.run(Thread.java:745)
16:44:19 Caused by: java.net.BindException: Address already in use
16:44:19 	at sun.nio.ch.Net.bind0(Native Method)
16:44:19 	at sun.nio.ch.Net.bind(Net.java:433)
16:44:19 	at sun.nio.ch.Net.bind(Net.java:425)
16:44:19 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
16:44:19 	at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157)
16:44:19 	at org.camunda.tngp.transport.impl.ServerSocketBindingImpl.doBind(ServerSocketBindingImpl.java:66)
16:44:19 	at org.camunda.tngp.transport.impl.agent.TransportConductor.doBindServerSocket(TransportConductor.java:229)
16:44:19 	... 9 more
16:44:28 Could not start broker: null
16:44:28 Closing...
16:44:38 Failed to close broker within 10 seconds.
16:44:38 Tests run: 7, Failures: 0, Errors: 1, Skipped: 5, Time elapsed: 21.552 sec <<< FAILURE!
16:44:38 shouldCreateTask(org.camunda.bpm.broker.it.taskqueue.TaskQueueTest)  Time elapsed: 20.006 sec  <<< ERROR!
16:44:38 java.util.concurrent.TimeoutException
16:44:38 	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
16:44:38 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
16:44:38 	at org.camunda.tngp.broker.system.SystemContext.init(SystemContext.java:76)
16:44:38 	at org.camunda.tngp.broker.Broker.start(Broker.java:38)
16:44:38 	at org.camunda.tngp.broker.Broker.<init>(Broker.java:26)
16:44:38 	at org.camunda.bpm.broker.it.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:51)
16:44:38 	at org.camunda.bpm.broker.it.EmbeddedBrokerRule.before(EmbeddedBrokerRule.java:29)
16:44:38 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
16:44:38 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
16:44:38 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
16:44:38 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
16:44:38 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
16:44:38 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
16:44:38 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
16:44:38 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
16:44:38 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
16:44:38 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
16:44:38 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
16:44:38 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
16:44:38 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
16:44:38 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
16:44:38 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
16:44:38 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:44:38 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:44:38 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:44:38 	at java.lang.reflect.Method.invoke(Method.java:498)
16:44:38 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
16:44:38 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
16:44:38 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
16:44:38 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
16:44:38 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
16:44:38 
16:44:38 Running org.camunda.bpm.broker.it.startup.BrokerRestartTest
16:44:38 Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
```

**Comment by meyerdan** [comment]
We should close this, it does not occur anymore
