### ISSUE TITLE
Unepxected output mapping exception

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1417]
According to the stacktrace, this occurs on running an output mapping of tasks. Not clear yet what triggers this. Possible explanations: a non-JSON structured document as input (e.g. due to a race condition with involved buffers); a bug in the msg pack handling itself;

Stack trace:

```
java.util.NoSuchElementException: null
 at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280) ~[?:1.8.0_131]
 at java.util.ArrayDeque.pop(ArrayDeque.java:517) ~[?:1.8.0_131]
 at io.zeebe.msgpack.mapping.MsgPackDocumentIndexer.processValueNode(MsgPackDocumentIndexer.java:257) ~[zb-msgpack-json-path-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.msgpack.mapping.MsgPackDocumentIndexer.visitElement(MsgPackDocumentIndexer.java:157) ~[zb-msgpack-json-path-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.msgpack.query.MsgPackTraverser.traverse(MsgPackTraverser.java:60) ~[zb-msgpack-json-path-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.msgpack.mapping.MsgPackDocumentIndexer.index(MsgPackDocumentIndexer.java:137) ~[zb-msgpack-json-path-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.msgpack.mapping.MappingProcessor.merge(MappingProcessor.java:152) ~[zb-msgpack-json-path-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.broker.workflow.processor.activity.OutputMappingHandler.handle(OutputMappingHandler.java:68) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.broker.workflow.processor.BpmnStepHandlers.handle(BpmnStepHandlers.java:102) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.broker.workflow.processor.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:83) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:187) ~[zeebe-broker-core-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:298) ~[zb-logstreams-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:281) ~[zb-logstreams-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
 at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.12.0-alpha4.jar:0.12.0-alpha4]
```

**Comment by menski** [comment]
We changed a lot of things and I'm don't know how to reproduce this. Closing until we see it again.
