### ISSUE TITLE
Exception when payload map/object contains NULL value

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#1441]
As discussed on Slack - when I have an object with null attributes and serialize that as JSON and send to Zeebe the exception below occurs every time.

Comment @menski "ist wohl nen bug in Zeebe json merge, wenn eine variable auf null gesetzt ist und dann später im merge nen wert bekommt. Mach mal an deine `OrderFlowContext` die annotation `@JsonInclude(Include.NON_NULL)` ran, dann hat deine initiale payload keine null werte und der smoke test läuft bis zum nächsten job"

```
22:36:52.021 [exporter] [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.RuntimeException: Failed to convert MessagePack to JSON
       at io.zeebe.gateway.impl.data.MsgPackConverter.convertToJsonBytes(MsgPackConverter.java:83) ~[zeebe-gateway-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.gateway.impl.data.MsgPackConverter.convertToJson(MsgPackConverter.java:63) ~[zeebe-gateway-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.broker.exporter.stream.ExporterRecordMapper.asJson(ExporterRecordMapper.java:319) ~[zeebe-broker-core-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.broker.exporter.stream.ExporterRecordMapper.ofJobRecord(ExporterRecordMapper.java:178) ~[zeebe-broker-core-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.broker.exporter.stream.ExporterRecordMapper.newRecord(ExporterRecordMapper.java:138) ~[zeebe-broker-core-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.broker.exporter.stream.ExporterRecordMapper.map(ExporterRecordMapper.java:122) ~[zeebe-broker-core-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.broker.exporter.stream.ExporterStreamProcessor$RecordExporter.wrap(ExporterStreamProcessor.java:223) ~[zeebe-broker-core-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.broker.exporter.stream.ExporterStreamProcessor.onEvent(ExporterStreamProcessor.java:98) ~[zeebe-broker-core-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:312) ~[zb-logstreams-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:301) ~[zb-logstreams-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.12.0-alpha3.jar:0.12.0-alpha3]
Caused by: java.lang.RuntimeException: Document has more content than a single object/array
       at io.zeebe.gateway.impl.data.MsgPackConverter.convert(MsgPackConverter.java:102) ~[zeebe-gateway-0.12.0-alpha3.jar:0.12.0-alpha3]
       at io.zeebe.gateway.impl.data.MsgPackConverter.convertToJsonBytes(MsgPackConverter.java:79) ~[zeebe-gateway-0.12.0-alpha3.jar:0.12.0-alpha3]
       ... 15 more
```

**Comment by Zelldon** [comment]
Hey @berndruecker ,

so something like the following should cause the problem right?

```java
    final WorkflowInstanceEvent workflowInstance =
        clientRule
            .getWorkflowClient()
            .newCreateInstanceCommand()
            .bpmnProcessId("anId")
            .latestVersion()
            .payload("{\"foo\":null}")
            .send()
            .join();
```

Would help if you post a snippet or example to reproduce this.

**Comment by Zelldon** [comment]
Seems to be fixed on develop
