### ISSUE TITLE
Workflow instance payload is missing on catch event

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1507]
To reproduce start 1000 Workflow instances two times, then you will see the following exception:

```java
07:42:53.647 [workflow-instance] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.logstreams - Stream processor 'workflow-instance' failed to process event. It stop processing further events.
java.lang.RuntimeException: Failed to extract correlation-key: no result
	at io.zeebe.broker.workflow.processor.catchevent.SubscribeMessageHandler.extractCorrelationKey(SubscribeMessageHandler.java:100) ~[classes/:?]
	at io.zeebe.broker.workflow.processor.catchevent.SubscribeMessageHandler.handle(SubscribeMessageHandler.java:61) ~[classes/:?]
	at io.zeebe.broker.workflow.processor.BpmnStepHandlers.handle(BpmnStepHandlers.java:103) ~[classes/:?]
	at io.zeebe.broker.workflow.processor.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:80) ~[classes/:?]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:187) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:298) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:281) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
```

If you change the log statement to:

```java
      // the exception will be replaces by an incident - #1018
      throw new RuntimeException(
          String.format(
              "Failed to extract correlation-key: no result. Payload %s, correlation key %s",
              BufferUtil.bufferAsString(workflowInstance.getPayload()),
              BufferUtil.bufferAsString(catchEvent.getCorrelationKey().getExpression())));
```

Then it states that the payload is empty or something else is wrong with the payload.

```
java.lang.RuntimeException: Failed to extract correlation-key: no result. Payload �, correlation key $.key
```

**Comment by Zelldon** [comment]
Awesome was a problem in the NonBlockingWorkflowInstanceCreator, on the last workflow creation there was no payload :see_no_evil: :man_facepalming:
