### ISSUE TITLE
Broker fails to start on older MacOS

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1517]
Broker cannot be started because of RocksDB on older MacOS versions:

```
11:22:50.990 [] [main] INFO  io.zeebe.gateway - Gateway started using grpc server: ServerImpl{logId=2, transportServer=NettyServer{logId=1, address=/0.0.0.0:26500}}
11:22:51.110 [partition-0] [0.0.0.0:26501-zb-actors-0] INFO  io.zeebe.raft - Joined raft in term 0
Exception in thread "0.0.0.0:26501-zb-actors-1" Exception in thread "0.0.0.0:26501-zb-actors-0" java.lang.UnsatisfiedLinkError: /private/var/folders/gj/9mxdcbrj05n8m3bvwfb4blcr0000gn/T/librocksdbjni8985386104048871252.jnilib: dlopen(/private/var/folders/gj/9mxdcbrj05n8m3bvwfb4blcr0000gn/T/librocksdbjni8985386104048871252.jnilib, 1): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /private/var/folders/gj/9mxdcbrj05n8m3bvwfb4blcr0000gn/T/librocksdbjni8985386104048871252.jnilib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/folders/gj/9mxdcbrj05n8m3bvwfb4blcr0000gn/T/librocksdbjni8985386104048871252.jnilib
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
    at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
    at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
    at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
    at io.zeebe.logstreams.state.StateController.<clinit>(StateController.java:84)
    at io.zeebe.broker.exporter.stream.ExporterStreamProcessor.<init>(ExporterStreamProcessor.java:58)
    at io.zeebe.broker.exporter.ExporterManagerService.startExporter(ExporterManagerService.java:81)
    at io.zeebe.servicecontainer.impl.ServiceController.invoke(ServiceController.java:602)
    at io.zeebe.servicecontainer.impl.ServiceController.lambda$addReferencedValue$1(ServiceController.java:589)
    at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:147)
    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76)
    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187)
    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154)
    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135)
    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112)
java.lang.NoClassDefFoundError: Could not initialize class io.zeebe.logstreams.state.StateController
    at io.zeebe.broker.subscription.message.processor.MessageStreamProcessor.<init>(MessageStreamProcessor.java:43)
    at io.zeebe.broker.subscription.message.MessageService.startStreamProcessors(MessageService.java:70)
    at io.zeebe.broker.subscription.message.MessageService.lambda$new$0(MessageService.java:49)
    at io.zeebe.servicecontainer.impl.ServiceController.invoke(ServiceController.java:602)
    at io.zeebe.servicecontainer.impl.ServiceController.lambda$addReferencedValue$1(ServiceController.java:589)
    at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:147)
    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76)
    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187)
    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154)
    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135)
    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112)
```

**Comment by Zelldon** [comment]
So Mac OS lower then 10.13.4  seems to be a problem, see https://forum.zeebe.io/t/zbctl-status-doesnt-indicate-leader/374/7?u=zelldon

**Comment by npepinpe** [comment]
I assume this isn't an issue in newer versions, since @korthout can run the broker? :)
