### ISSUE TITLE
Broker dies if job worker wants to activate to many jobs at once

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1578]
On JobWorker creation the user can specify how many jobs should be activated at once.

This could look like this:
```java

 final JobWorker subscription =
        client
            .jobClient()
            .newWorker()
            .jobType(JOB_TYPE)
            .handler(
                (c, t) -> {
                  reporter.increment();
                  c.newCompleteCommand(t.getKey()).payload("{}").send().join();
                })
            .timeout(10_000)
            .name("test")
            .bufferSize(1000)
            .open();
```
Apart from that the fact that name `bufferSize` is a bit misleading, the user can specify any `int` value.
This means the current JobProcessor implementation tries to create an batch with for example `1000` activate job events. 

This will cause following exception to be thrown:

```java
14:07:16.298 [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.logstreams - Stream processor 'job' failed to process event. It stop processing further events.
java.lang.RuntimeException: Cannot claim more than 174763 bytes.
	at io.zeebe.dispatcher.Dispatcher.claim(Dispatcher.java:294) ~[zb-dispatcher-0.13.0-20181028.182342-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:220) ~[zb-logstreams-0.13.0-20181028.182352-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:198) ~[zb-logstreams-0.13.0-20181028.182352-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.flush(TypedCommandWriterImpl.java:144) ~[zeebe-broker-core-0.13.0-20181028.182407-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.writeEvent(TypedStreamProcessor.java:201) ~[zeebe-broker-core-0.13.0-20181028.182407-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.writeEvent(StreamProcessorController.java:339) ~[zb-logstreams-0.13.0-20181028.182352-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
io.zeebe.client.cmd.ClientException: Failed to await termination of in-flight requests
	at io.zeebe.client.impl.ZeebeClientImpl.close(ZeebeClientImpl.java:125)
	at io.zeebe.AutoCloseables.close(AutoCloseables.java:41)
	at io.zeebe.cluster.ZeebeBrokerExtension.afterEach(ZeebeBrokerExtension.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:217)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:229)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:227)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:216)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:119)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Since the dispatcher explodes the broker also stops processing.

**Comment by huksley** [comment]
Having the same error event when bufferSize is rather small (`10`)
https://github.com/huksley/zeebe-kafka-camunda/blob/master/workers/src/main/kotlin/zeebe/workers/ZeebeProvider.kt#L39

I think it is more related to currently available activated jobs (i.e. if it is too much, Zeebe dies)

```bash
22:07:28.396 [zb-stream-processor] [172.24.0.10:26501-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.RuntimeException: Cannot claim more than 174763 bytes.
	at io.zeebe.dispatcher.Dispatcher.claim(Dispatcher.java:294) ~[zb-dispatcher-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:231) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:209) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.flush(TypedCommandWriterImpl.java:143) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.JobTimeoutTrigger.lambda$deactivateTimedOutJobs$1(JobTimeoutTrigger.java:65) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.JobState.lambda$forEachTimedOutEntry$0(JobState.java:251) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.rocksdb.ZbRocksDb.forEach(ZbRocksDb.java:294) ~[zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.JobState.forEachTimedOutEntry(JobState.java:238) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:60) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

**Comment by Zelldon** [comment]
Hey @huksley what kind of payload do you have on your workflow instance and how big are they?

@menski I assume this is also an problem if the workflow instance contains a larger payload where adding an maximum job limit will not solve this issue.

**Comment by huksley** [comment]
@Zelldon About 1k and I create 100 processes per second.
