### ISSUE TITLE
Possible NPE in partition install service

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1628]
On bootstrap and during a state transition `Raft.getState()` will return `null`
https://github.com/zeebe-io/zeebe/blob/0.12.1/raft/src/main/java/io/zeebe/raft/Raft.java#L454-L456

```
java.lang.NullPointerException: null
    at io.zeebe.broker.clustering.base.partitions.PartitionInstallService.onStateChange(PartitionInstallService.java:197) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.raft.Raft.lambda$null$1(Raft.java:379) [zb-raft-0.12.1.jar:0.12.1]
    at io.zeebe.util.LogUtil.catchAndLog(LogUtil.java:49) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.raft.Raft.lambda$notifyRaftStateListeners$2(Raft.java:379) [zb-raft-0.12.1.jar:0.12.1]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_121]
    at io.zeebe.raft.Raft.notifyRaftStateListeners(Raft.java:378) [zb-raft-0.12.1.jar:0.12.1]
    at io.zeebe.raft.controller.RaftJoinService.lambda$leave$2(RaftJoinService.java:107) ~[zb-raft-0.12.1.jar:0.12.1]
    at io.zeebe.raft.controller.RaftJoinService.sendConfigurationRequest(RaftJoinService.java:184) ~[zb-raft-0.12.1.jar:0.12.1]
    at io.zeebe.raft.controller.RaftJoinService.leave(RaftJoinService.java:112) ~[zb-raft-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:147) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) ~[zb-util-0.12.1.jar:0.12.1]
```

**Comment by menski** [comment]
we removed our custom raft implementation
