### ISSUE TITLE
Possible NPE in job stream processor

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1637]
Could be related that we think we have to timeout a job which is already completed or canceled.

```
11:46:46.524 [job] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.initMetadata(TypedCommandWriterImpl.java:69) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.writeRecord(TypedCommandWriterImpl.java:103) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.writeRecord(TypedCommandWriterImpl.java:82) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.writeFollowUpCommand(TypedCommandWriterImpl.java:130) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStreamProcessor.lambda$deactivateTimedOutJobs$1(JobStreamProcessor.java:130) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStateController.lambda$forEachTimedOutEntry$0(JobStateController.java:254) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.logstreams.rocksdb.ZbRocksDb.forEach(ZbRocksDb.java:287) ~[zb-logstreams-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStateController.forEachTimedOutEntry(JobStateController.java:248) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStreamProcessor.deactivateTimedOutJobs(JobStreamProcessor.java:127) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.12.1.jar:0.12.1]
11:47:15.969 [logstream.partition-0.blockIdx.writer] [0.0.0.0:26501-zb-fs-workers-0] INFO  io.zeebe.logstreams - Delete last snapshot file /home/beppo/.local/share/Trash/files/zeebe-broker-0.2.12.1/data/partition-0/snapshots/logstream.partition-0.blockIdx.writer-4294967296.snapshot.
11:47:16.552 [job] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.initMetadata(TypedCommandWriterImpl.java:69) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.writeRecord(TypedCommandWriterImpl.java:103) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.writeRecord(TypedCommandWriterImpl.java:82) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.writeFollowUpCommand(TypedCommandWriterImpl.java:130) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStreamProcessor.lambda$deactivateTimedOutJobs$1(JobStreamProcessor.java:130) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStateController.lambda$forEachTimedOutEntry$0(JobStateController.java:254) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.logstreams.rocksdb.ZbRocksDb.forEach(ZbRocksDb.java:287) ~[zb-logstreams-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStateController.forEachTimedOutEntry(JobStateController.java:248) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.broker.job.JobStreamProcessor.deactivateTimedOutJobs(JobStreamProcessor.java:127) ~[zeebe-broker-core-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.12.1.jar:0.12.1]
    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.12.1.jar:0.12.1]
```

**Comment by menski** [comment]
this was submitted by operate tests on 0.12.1 but is probably still the same on  0.13.0. We observed something similar with job activation. Maybe we don't clean the job state correctly. 

https://github.com/zeebe-io/zeebe/commit/10496ae7b32f89e50c43896039fdc74a0c3f8b4d
