### ISSUE TITLE
Stream processor 'workflow-instance' failed to process event

### ISSUE THREAD

**Issue by aleferov-v** [zeebe-io/zeebe#1747]
**Problem**:

Zeebe broker can't start and show me this error:

```java
10:01:12.719 [workflow-instance] [172.17.0.2:26501-zb-actors-1] ERROR io.zeebe.logstreams - Stream processor 'workflow-instance' failed to process event. It stop processing further events.
java.lang.NullPointerException: null
	at io.zeebe.broker.workflow.model.transformation.handler.MessageHandler.transform(MessageHandler.java:45) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.model.transformation.handler.MessageHandler.transform(MessageHandler.java:29) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:51) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zb-bpmn-model-0.13.1.jar:0.13.1]
	at io.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:60) ~[zb-bpmn-model-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:82) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.state.WorkflowPersistenceCache.updateInMemoryState(WorkflowPersistenceCache.java:143) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.state.WorkflowPersistenceCache.lookupWorkflowByIdAndPersistedVersion(WorkflowPersistenceCache.java:207) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.state.WorkflowPersistenceCache.getLatestWorkflowVersionByProcessId(WorkflowPersistenceCache.java:187) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.state.WorkflowState.getLatestWorkflowVersionByProcessId(WorkflowState.java:98) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.processor.instance.CreateWorkflowInstanceHandler.getWorkflowDefinition(CreateWorkflowInstanceHandler.java:82) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.processor.instance.CreateWorkflowInstanceHandler.handle(CreateWorkflowInstanceHandler.java:49) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.processor.WorkflowInstanceCommandHandlers.handle(WorkflowInstanceCommandHandlers.java:44) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.workflow.processor.WorkflowInstanceCommandProcessor.processRecord(WorkflowInstanceCommandProcessor.java:51) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:45) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:187) ~[zeebe-broker-core-0.13.1.jar:0.13.1]
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:298) ~[zb-logstreams-0.13.1.jar:0.13.1]
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:281) ~[zb-logstreams-0.13.1.jar:0.13.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.13.1.jar:0.13.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.13.1.jar:0.13.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.13.1.jar:0.13.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.13.1.jar:0.13.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.13.1.jar:0.13.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.13.1.jar:0.13.1]
```

And if I want do something with zeebe client I get this:
```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Request timed out after PT15S
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678) ~[grpc-core-1.16.1.jar:1.16.1]
```

If it's not a bug, how can I to fix this myself?

**Comment by saig0** [comment]
Hi @aleferov-v ,

Thank you for raising this up. Can you please share your BPMN?

**Comment by aleferov-v** [comment]
Here is
[documentProcess.bpmn.zip](https://github.com/zeebe-io/zeebe/files/2648461/documentProcess.bpmn.zip)

And now I can't even deploy this model

**Comment by saig0** [comment]
Currently, if the broker fails with an expected exception then it stops processing any new event. 

I can reproduce the problem with your BPMN. We need to fix it :)

**Comment by aleferov-v** [comment]
I see. 
Do you understand where is problem in my model?

**Comment by saig0** [comment]
Not yet. I need to look into it. I'll update the issue when I've some insides ;)

**Comment by menski** [comment]
@aleferov-v the problem is that your model contains a message element without a correlation key. If you open up your BPMN XML file in a text editor or the XML view of the modeler you will find this line

```
<bpmn:message id="Message_1ihreie" name="Message_2t6q6lt" />
```

This leads to the null pointer exception. If you remove the line the model should work again.

I will create the bug issue #1754 for this. Thanks for reporting.

**Comment by aleferov-v** [comment]
@saig0 @menski Thanks for the prompt response!
