### ISSUE TITLE
Inconsistent job state when canceling and activating at the same time

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1759]
It seems that there exists a race condition on our RocksDB state if a job is activated/complete at the same time as it is canceled.

#### Exception
```
java.lang.RuntimeException: deadline must be greater than 0
	at io.zeebe.util.EnsureUtil.ensureGreaterThan(EnsureUtil.java:37) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.JobState.getDeadlinesKey(JobState.java:361) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.JobState.delete(JobState.java:176) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.job.CancelProcessor.onCommand(CancelProcessor.java:40) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.logstreams.processor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:58) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:36) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:168) ~[zeebe-broker-core-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:296) [zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:279) [zb-logstreams-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) ~[zb-util-0.14.0.jar:0.14.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) ~[zb-util-0.14.0.jar:0.14.0]
```

#### Record Log

```
2018-12-05 16:59:56.831  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685253,"position":4295000400,"timestamp":1544029165885,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295000048,"metadata":{"partitionId":1,"intent":"CREATED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB"},"value":{"payload":"{\"foo\":\"b\"}","type":"taskA","worker":"","deadline":null,"headers":{"bpmnProcessId":"demoProcess","elementId":"taskA","elementInstanceKey":2251799813685252,"workflowInstanceKey":2251799813685249,"workflowKey":1,"workflowDefinitionVersion":1},"customHeaders":{},"retries":3,"errorMessage":""}}
2018-12-05 16:59:56.831  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685249,"position":4295000752,"timestamp":1544029165886,"raftTerm":1,"producerId":-1,"sourceRecordPosition":-1,"metadata":{"partitionId":1,"intent":"CANCEL","recordType":"COMMAND","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"WORKFLOW_INSTANCE"},"value":{"payload":"{}","bpmnProcessId":"","elementId":"","version":-1,"workflowKey":-1,"workflowInstanceKey":-1,"scopeInstanceKey":-1}}
2018-12-05 16:59:56.831  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685249,"position":4295000944,"timestamp":1544029165887,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295000752,"metadata":{"partitionId":1,"intent":"ELEMENT_TERMINATING","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"WORKFLOW_INSTANCE"},"value":{"payload":"{\"a\":\"b\"}","bpmnProcessId":"demoProcess","elementId":"demoProcess","version":1,"workflowKey":1,"workflowInstanceKey":2251799813685249,"scopeInstanceKey":-1}}
2018-12-05 16:59:56.831  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685252,"position":4295001184,"timestamp":1544029165887,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295000944,"metadata":{"partitionId":1,"intent":"ELEMENT_TERMINATING","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"WORKFLOW_INSTANCE"},"value":{"payload":"{\"foo\":\"b\"}","bpmnProcessId":"demoProcess","elementId":"taskA","version":1,"workflowKey":1,"workflowInstanceKey":2251799813685249,"scopeInstanceKey":2251799813685249}}
2018-12-05 16:59:56.832  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":-1,"position":4295001432,"timestamp":1544029165887,"raftTerm":1,"producerId":-1,"sourceRecordPosition":-1,"metadata":{"partitionId":1,"intent":"ACTIVATE","recordType":"COMMAND","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB_BATCH"},"value":{"type":"taskA","worker":"b4a16d92-9","timeout":2000,"amount":32,"jobKeys":[],"jobs":[]}}
2018-12-05 16:59:56.833  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685253,"position":4295001584,"timestamp":1544029165887,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295001184,"metadata":{"partitionId":1,"intent":"CANCEL","recordType":"COMMAND","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB"},"value":{"payload":"{\"foo\":\"b\"}","type":"taskA","worker":"","deadline":null,"headers":{"bpmnProcessId":"demoProcess","elementId":"taskA","elementInstanceKey":2251799813685252,"workflowInstanceKey":2251799813685249,"workflowKey":1,"workflowDefinitionVersion":1},"customHeaders":{},"retries":3,"errorMessage":""}}
2018-12-05 16:59:56.833  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685252,"position":4295001920,"timestamp":1544029165887,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295001184,"metadata":{"partitionId":1,"intent":"ELEMENT_TERMINATED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"WORKFLOW_INSTANCE"},"value":{"payload":"{\"foo\":\"b\"}","bpmnProcessId":"demoProcess","elementId":"taskA","version":1,"workflowKey":1,"workflowInstanceKey":2251799813685249,"scopeInstanceKey":2251799813685249}}
2018-12-05 16:59:56.833  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685253,"position":4295002168,"timestamp":1544029165888,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295001432,"metadata":{"partitionId":1,"intent":"ACTIVATED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB"},"value":{"payload":"{\"foo\":\"b\"}","type":"taskA","worker":"b4a16d92-9","deadline":1544029167888,"headers":{"bpmnProcessId":"demoProcess","elementId":"taskA","elementInstanceKey":2251799813685252,"workflowInstanceKey":2251799813685249,"workflowKey":1,"workflowDefinitionVersion":1},"customHeaders":{},"retries":3,"errorMessage":""}}
2018-12-05 16:59:56.833  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685254,"position":4295002512,"timestamp":1544029165888,"raftTerm":1,"producerId":1,"sourceRecordPosition":4295001432,"metadata":{"partitionId":1,"intent":"ACTIVATED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB_BATCH"},"value":{"type":"taskA","worker":"b4a16d92-9","timeout":2000,"amount":32,"jobKeys":[2251799813685253],"jobs":[{"payload":"{\"foo\":\"b\"}","type":"taskA","worker":"b4a16d92-9","deadline":1544029167888,"headers":{"bpmnProcessId":"demoProcess","elementId":"taskA","elementInstanceKey":2251799813685252,"workflowInstanceKey":2251799813685249,"workflowKey":1,"workflowDefinitionVersion":1},"customHeaders":{},"retries":3,"errorMessage":""}]}}
2018-12-05 16:59:56.833  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685253,"position":4295002944,"timestamp":1544029165893,"raftTerm":1,"producerId":-1,"sourceRecordPosition":-1,"metadata":{"partitionId":1,"intent":"COMPLETE","recordType":"COMMAND","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB"},"value":{"payload":"{\"a\":\"b\"}","type":"","worker":"","deadline":null,"headers":{"bpmnProcessId":"","elementId":"","elementInstanceKey":-1,"workflowInstanceKey":-1,"workflowKey":-1,"workflowDefinitionVersion":-1},"customHeaders":{},"retries":-1,"errorMessage":""}}
2018-12-05 16:59:56.833  INFO 1365 --- [           main] io.zeebe.test.records                    : {"key":2251799813685253,"position":4295003240,"timestamp":1544029181828,"raftTerm":1,"producerId":-1,"sourceRecordPosition":-1,"metadata":{"partitionId":1,"intent":"FAIL","recordType":"COMMAND","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"JOB"},"value":{"payload":"{}","type":"","worker":"","deadline":null,"headers":{"bpmnProcessId":"","elementId":"","elementInstanceKey":-1,"workflowInstanceKey":-1,"workflowKey":-1,"workflowDefinitionVersion":-1},"customHeaders":{},"retries":2,"errorMessage":""}}
```

**Comment by MiguelPires** [comment]
Fixed by https://github.com/zeebe-io/zeebe/pull/2569
