### ISSUE TITLE
Can't restart Broker on windows

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1810]
Currently it seems not possible to restart the Broker on a windows enviroment, see stacktrace below.

```bash 
org.rocksdb.RocksDBException: Directory exists
        at org.rocksdb.Checkpoint.createCheckpoint(Native Method) ~[rocksdbjni-5.17.2.jar:?]
        at org.rocksdb.Checkpoint.createCheckpoint(Checkpoint.java:51) ~[rocksdbjni-5.17.2.jar:?]
        at io.zeebe.logstreams.state.StateSnapshotController.copySnapshot(StateSnapshotController.java:108) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.state.StateSnapshotController.recover(StateSnapshotController.java:79) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.processor.StreamProcessorController.recoverFromSnapshot(StreamProcessorController.java:152) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.processor.StreamProcessorController.onActorStarting(StreamProcessorController.java:127) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
20:11:32.695 [service-controller] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.servicecontainer - Service failed to start while in AwaitStartState
org.rocksdb.RocksDBException: Directory exists
        at org.rocksdb.Checkpoint.createCheckpoint(Native Method) ~[rocksdbjni-5.17.2.jar:?]
        at org.rocksdb.Checkpoint.createCheckpoint(Checkpoint.java:51) ~[rocksdbjni-5.17.2.jar:?]
        at io.zeebe.logstreams.state.StateSnapshotController.copySnapshot(StateSnapshotController.java:108) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.state.StateSnapshotController.recover(StateSnapshotController.java:79) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.processor.StreamProcessorController.recoverFromSnapshot(StreamProcessorController.java:152) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.processor.StreamProcessorController.onActorStarting(StreamProcessorController.java:127) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
20:11:32.728 [service-container-main] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to build service
org.rocksdb.RocksDBException: Directory exists
        at org.rocksdb.Checkpoint.createCheckpoint(Native Method) ~[rocksdbjni-5.17.2.jar:?]
        at org.rocksdb.Checkpoint.createCheckpoint(Checkpoint.java:51) ~[rocksdbjni-5.17.2.jar:?]
        at io.zeebe.logstreams.state.StateSnapshotController.copySnapshot(StateSnapshotController.java:108) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.state.StateSnapshotController.recover(StateSnapshotController.java:79) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.processor.StreamProcessorController.recoverFromSnapshot(StreamProcessorController.java:152) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.logstreams.processor.StreamProcessorController.onActorStarting(StreamProcessorController.java:127) ~[zb-logstreams-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

**Comment by MiguelPires** [comment]
I was able to reproduce this error locally with the 0.14 release but not with the current develop which suggests that it was indeed solved by #1750

**Comment by Zelldon** [comment]
Could you check it again with develop after https://github.com/zeebe-io/zeebe/pull/1798 is merged? I changed a lot in the state management

**Comment by MiguelPires** [comment]
Sure. I just checked it again and it still seems to be fixed on develop

**Comment by Zelldon** [comment]
Thanks @MiguelPires then I will close this
