### ISSUE TITLE
Stream processor fails if user tries to create instance of workflow with only a timer start event

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1871]
If I deploy [timer.bpmn](https://github.com/zeebe-io/zeebe/files/2755306/timer.bpmn.txt) and try to start the process, i.e. using zbctl I get a successful response which is kind of unexpected? 

```
$ zbctl deploy /tmp/timer.bpmn 
{
  "key": 2,
  "workflows": [
    {
      "bpmnProcessId": "process",
      "version": 1,
      "workflowKey": 1,
      "resourceName": "/tmp/timer.bpmn"
    }
  ]
}
```

```
$ zbctl create instance process
{
  "workflowKey": 1,
  "bpmnProcessId": "process",
  "version": 1,
  "workflowInstanceKey": 9
}
```

But also the broker dies

```
14:29:07.278 [zb-stream-processor] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.logstreams - Stream processor 'zb-stream-processor' failed to process event. It stop processing further events.           
java.lang.RuntimeException: Workflow has multiple start events but no deferred record was found
        at io.zeebe.broker.workflow.processor.subprocess.TriggerStartEventHandler.handle(TriggerStartEventHandler.java:64) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                     
        at io.zeebe.broker.workflow.processor.BpmnStepHandlers.handle(BpmnStepHandlers.java:125) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                               
        at io.zeebe.broker.workflow.processor.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:80) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                       
        at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                               
        at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:168) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]      
        at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:304) ~[zb-logstreams-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                
        at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:287) ~[zb-logstreams-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                               
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                          
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                         
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                      
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                       
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
```

**Comment by menski** [comment]
The same is true for a process with a message start event.

**Comment by menski** [comment]
@MiguelPires and @deepthidevaki, if one of you is searching for work or something else to do, one can grab this issue and improve the user experience

**Comment by menski** [comment]
Expected behavior, the create workflow instance command is rejected with a useful error message. The workflow instance is not started, and the stream processor is not broken afterwards.
