### ISSUE TITLE
payload too big and no incident emit

### ISSUE THREAD

**Issue by aximo** [zeebe-io/zeebe#1875]
zeebe broker is 0.14.0

I meet an issue when put a big payload in job, and this exception is thrown in zeebe broker, but there are no incidents  in zeebe-simple-monitor, the monitor show that workflow instance is in Active state
```
22:42:17.129 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.IllegalStateException: length > maxValue for type: 115769
        at io.zeebe.protocol.clientapi.ExecuteCommandRequestEncoder.putValue(ExecuteCommandRequestEncoder.java:333) ~[zb-protocol-0.14.0.jar:0.14.0]
        at io.zeebe.protocol.impl.encoding.ExecuteCommandRequest.write(ExecuteCommandRequest.java:169) ~[zb-protocol-impl-0.14.0.jar:0.14.0]
        at io.zeebe.gateway.impl.broker.request.BrokerExecuteCommand.write(BrokerExecuteCommand.java:89) ~[zeebe-gateway-0.14.0.jar:0.14.0]
        at io.zeebe.transport.impl.sender.TransportHeaderWriter.wrapRequest(TransportHeaderWriter.java:74) ~[zb-transport-0.14.0.jar:0.14.0]
        at io.zeebe.transport.impl.ClientOutputImpl.sendRequestWithRetry(ClientOutputImpl.java:122) ~[zb-transport-0.14.0.jar:0.14.0]
        at io.zeebe.gateway.impl.broker.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:174) ~[zeebe-gateway-0.14.0.jar:0.14.0]
        at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$4(BrokerRequestManager.java:134) ~[zeebe-gateway-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]

```
so it is a normal behavior in zeebe? or  it is bug of zeebe broke or zeeber monitor?

**Comment by Zelldon** [comment]
Hey @aximo ,

thanks for reporting this. 

The request you have send does not reached the broker, it ends in the gateway and can't be send to the broker because of his size. How large is your payload exactly? Be aware that zeebe is not intended to handle large payloads.

 I think it makes sense to define a maximum size for some values (https://github.com/zeebe-io/zeebe/issues/1333) so this would make it also much clearer and can also be found in the docs.

We currently working on some issues to improve the error messages so the user understand better the problems (for example https://github.com/zeebe-io/zeebe/issues/1863 and https://github.com/zeebe-io/zeebe/issues/1862).

What is your current use case for this? What do you want to achieve?
Would it help if you can configure the maximum request buffer size in the gateway and broker?
I think it would be then also necessary to configure some sizes in the broker (dispatchers etc.).
Be aware that everything you send as payload is then stored in the log and and also in the state of the broker.

Greets
Chris
