### ISSUE TITLE
Null pointer exception if no message subscription correlation key is set

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1900]
If an user deploys an invalid BPMN model with an empty or non existing correlation key the broker throws a null pointer exception. Expected behavior is that the model is rejected, which I think is already the case,  but the broker should not throw a null pointer exception.

#### Message subscription in BPMN
```
<bpmn:message id="Message_0g2cah2" name="Message_24kqeof">
  <bpmn:extensionElements>
    <zeebe:subscription correlationKey="" />
  </bpmn:extensionElements>
</bpmn:message>
```

#### Stacktrace
```
09:46:25.137 [zb-stream-processor] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.broker.workflow - Unexpected error while processing resource 'foo.bpmn'                                                   
java.lang.NullPointerException: null
        at io.zeebe.msgpack.jsonpath.JsonPathQueryCompiler.compile(JsonPathQueryCompiler.java:52) ~[zb-msgpack-json-path-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                           
        at io.zeebe.broker.workflow.model.validation.ZeebeExpressionValidator.validateJsonPath(ZeebeExpressionValidator.java:43) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]               
        at io.zeebe.broker.workflow.model.validation.ZeebeSubscriptionValidator.validate(ZeebeSubscriptionValidator.java:40) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                   
        at io.zeebe.broker.workflow.model.validation.ZeebeSubscriptionValidator.validate(ZeebeSubscriptionValidator.java:24) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                   
        at io.zeebe.model.bpmn.validation.ValidationVisitor.visit(ValidationVisitor.java:47) ~[zb-bpmn-model-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                       
        at io.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zb-bpmn-model-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                  
        at io.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:60) ~[zb-bpmn-model-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                     
        at io.zeebe.broker.workflow.deployment.transform.BpmnValidator.validate(BpmnValidator.java:46) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                         
        at io.zeebe.broker.workflow.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:92) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                
        at io.zeebe.broker.workflow.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:71) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                        
        at io.zeebe.broker.workflow.processor.deployment.TransformingDeploymentCreateProcessor.processRecord(TransformingDeploymentCreateProcessor.java:64) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
        at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                               
        at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:170) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]      
        at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:304) ~[zb-logstreams-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                
        at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:287) ~[zb-logstreams-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                               
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                          
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                         
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                      
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                       
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]                                                                                   
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT] 
```

**Comment by saig0** [comment]
By what kind of message event does this error occur?

**Comment by menski** [comment]
I saw it for start and intermediate catch events, I guess it also happens for boundary events.
