### ISSUE TITLE
Deploying BPMN file with empty header kills broker

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#1902]
If you have this in a bpmn file and try to deploy it to the broker:

```
          <zeebe:header />
```

You get this error on the broker:

```
05:04:55.477 [zb-stream-processor] [172.30.0.3:26501-zb-actors-0] ERROR io.zeebe.logstreams - Stream processor 'zb-stream-processor' failed to process event. It stop processing further events.
java.lang.NullPointerException: null
	at io.zeebe.util.StringUtil.getBytes(StringUtil.java:31) ~[zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.StringUtil.getBytes(StringUtil.java:27) ~[zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.buffer.BufferUtil.wrapString(BufferUtil.java:51) ~[zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.model.transformation.transformer.ServiceTaskTransformer.lambda$encode$0(ServiceTaskTransformer.java:101) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_131]
	at io.zeebe.broker.workflow.model.transformation.transformer.ServiceTaskTransformer.encode(ServiceTaskTransformer.java:99) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.model.transformation.transformer.ServiceTaskTransformer.transformTaskHeaders(ServiceTaskTransformer.java:83) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.model.transformation.transformer.ServiceTaskTransformer.transform(ServiceTaskTransformer.java:59) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.model.transformation.transformer.ServiceTaskTransformer.transform(ServiceTaskTransformer.java:39) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:51) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zb-bpmn-model-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:60) ~[zb-bpmn-model-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:99) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.state.WorkflowPersistenceCache.updateInMemoryState(WorkflowPersistenceCache.java:129) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.state.WorkflowPersistenceCache.lookupPersistenceStateForWorkflowByKey(WorkflowPersistenceCache.java:246) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.state.WorkflowPersistenceCache.getWorkflowByKey(WorkflowPersistenceCache.java:237) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.state.WorkflowState.getWorkflowByKey(WorkflowState.java:54) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.deployment.TransformingDeploymentCreateProcessor.createTimerIfTimerStartEvent(TransformingDeploymentCreateProcessor.java:94) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.deployment.TransformingDeploymentCreateProcessor.processRecord(TransformingDeploymentCreateProcessor.java:71) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:170) ~[zeebe-broker-core-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:304) ~[zb-logstreams-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:287) ~[zb-logstreams-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.15.0-SNAPSHOT.jar:0.15.0-SNAPSHOT]
```

And the broker dies completely.

**Comment by jwulf** [comment]
You just need to have this somewhere in your process:

![empty_header](https://user-images.githubusercontent.com/406975/51584602-d33ec980-1f21-11e9-93f9-3ea88847d6aa.png)

**Comment by jwulf** [comment]
I would expect the broker to (a) ignore an empty header while parsing a BPMN file (maybe emit a warning?), and (b) to not die when passed a file that it can't parse.

**Comment by saig0** [comment]
@jwulf, thank you for pointing this out :beetle:
