### ISSUE TITLE
When deploying two YAML workflows I cannot create an instance of the second one

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1931]
Deploying two different YAML workflows is successful but afterwards it is not possible to start an instance of the second deployed workflow. Failing test case for example adding `deploy("workflows/workflow-with-mappings.yaml");` before deploying the test process (line 50) in
 https://github.com/zeebe-io/zeebe/blob/81afb84cf1703cf47cf7781e85fb7669cda0a66e/qa/integration-tests/src/test/java/io/zeebe/broker/it/workflow/YamlWorkflowTest.java#L47-L65 

Also I noticed when deploying the same YAML workflow twice, i.e. repeat `deploy(resource);` in the mentioned test case an NPE is throw, which could be related to this issue or not

```
11:47:19.079 [zb-stream-processor] [0.0.0.0:25601-zb-actors-1] ERROR io.zeebe.logstreams - Stream processor 'zb-stream-processor' failed to process event. It stop processing further events.
java.lang.NullPointerException: null
	at io.zeebe.broker.workflow.processor.deployment.TransformingDeploymentCreateProcessor.createTimerIfTimerStartEvent(TransformingDeploymentCreateProcessor.java:94) ~[classes/:?]
	at io.zeebe.broker.workflow.processor.deployment.TransformingDeploymentCreateProcessor.processRecord(TransformingDeploymentCreateProcessor.java:71) ~[classes/:?]
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[classes/:?]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:170) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:304) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:287) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
```

**Comment by menski** [comment]
It seems that on the second deployment the resource name points to the wrong offset in the deployment record, which then leads to the case that the resource lookup in the deployment fails:
https://github.com/zeebe-io/zeebe/blob/d62863e9573448ee0261800b6959ec87c819cd54/broker-core/src/main/java/io/zeebe/broker/workflow/state/WorkflowPersistenceCache.java#L94

It seems to point to a random offset inside the transformed XML :thinking:

**Comment by menski** [comment]
The problem seems to be related to the msgpack array value implementation. During the deployment we iterate over the resources using an iterator.
https://github.com/zeebe-io/zeebe/blob/d62863e9573448ee0261800b6959ec87c819cd54/broker-core/src/main/java/io/zeebe/broker/workflow/deployment/transform/DeploymentTransformer.java#L69-L72

If the resource is a YAML workflow we replace the `resource` value of the deployment resource with the XML representation, which is bigger then the YAML version, this then leads to a case where the following `resourceName` property becomes invalid.

https://github.com/zeebe-io/zeebe/blob/d62863e9573448ee0261800b6959ec87c819cd54/broker-core/src/main/java/io/zeebe/broker/workflow/deployment/transform/DeploymentTransformer.java#L160-L161

See https://github.com/zeebe-io/zeebe/commit/1344cd6300ceadddbb01ac173433301b488035f1 for a failing test case.

**Comment by Zelldon** [comment]
Nice catch :see_no_evil: I hope we can replace the UnpackedObjects at some point in the future I have always problems with them :sweat_smile: 

BTW.: I think there is also another bug in the line you posted. Say if you have two resources, the first invalid and second valid then the Deployment is accepted, because the `success` variable is overwritten right? I will try to reproduce this, tomorrow.

**Comment by Zelldon** [comment]
Btw to fix your symptom reorder the properties in `DeploymentResource` :sweat_smile:  

But I think the root cause for this is that the UnpackedObject only uses one Buffer, which is read once (as far I saw now). Each property holds a different view of the buffer. 
If a property has changed, like you described, then the other properties have to be invalided and read again, since the offset has changed. Since the properties aren't invalidated, they point to the same offset, which is then a wrong view at the changed buffer.
