### ISSUE TITLE
Reject timeDates too far into the future/past

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2108]
Starting a timer start event with a timeDate that is well-formed but too into the future/past will cause an overflow:

```
11:32:29.258 [exporter] [0.0.0.0:26501-zb-actors-0] DEBUG io.zeebe.broker.exporter.debug-log - {"key":-1,"position":4294971376,"timestamp":"2019-02-28T10:32:28.905Z","raftTerm":1,"producerId":0,"sourceRecordPosition":4294967392,"metadata":{"valueType":"TIMER","intent":"CREATE","recordType":"COMMAND","partitionId":0,"rejectionType":"NULL_VAL","rejectionReason":""},"value":{"elementInstanceKey":-1,"dueDate":-30605079600000,"handlerFlowNodeId":"StartEvent_1o2m7ya"}}
11:32:29.255 [zb-stream-processor] [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.logstreams - Stream processor 'zb-stream-processor' failed to process event. It stop processing further events.
java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892) ~[?:1.8.0_191]
	at java.time.Duration.toNanos(Duration.java:1186) ~[?:1.8.0_191]
	at io.zeebe.util.sched.ActorControl.scheduleTimer(ActorControl.java:288) ~[zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorControl.runDelayed(ActorControl.java:233) ~[zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.timer.DueDateTimerChecker.scheduleTimer(DueDateTimerChecker.java:63) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.timer.CreateTimerProcessor.scheduleTimer(CreateTimerProcessor.java:70) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.executeSideEffects(TypedStreamProcessor.java:180) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.executeSideEffects(StreamProcessorController.java:320) ~[zb-logstreams-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
```

This should be checked so the command can be canceled. Alternatively, we could also validate this in the BPMN validation which would let the user know of the problems immediately. However, this isn't a BPMN issue and introducing this verification in the DueDateTimerChecker involves less changes.

**Comment by MiguelPires** [comment]
Changing the time representation in the ActorControl from nanoseconds to milliseconds would prevent the overflow as long as the maximum time allowed by the format can be represented by a long. Spec for reference: http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm

**Comment by menski** [comment]
We will not limit this for now
