### ISSUE TITLE
Broker tries to claim more than 174763 bytes when timing out jobs

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2124]
I'm assuming this is related to the same issue we had with activating, e.g. something with batching jobs?

Activating a lot of jobs without completing/failing them, with no payload whatsoever, I eventually ran into the following:

```
java.lang.RuntimeException: Unexpected error occurred during RocksDB transaction.
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:169) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:153) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:289) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:76) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.broker.job.JobState.forEachTimedOutEntry(JobState.java:186) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.broker.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:60) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:108) [zb-util-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
Caused by: java.lang.RuntimeException: Cannot claim more than 174763 bytes.
        at io.zeebe.dispatcher.Dispatcher.claim(Dispatcher.java:294) ~[zb-dispatcher-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:233) ~[zb-logstreams-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:211) ~[zb-logstreams-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.flush(TypedCommandWriterImpl.java:143) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.broker.job.JobTimeoutTrigger.lambda$deactivateTimedOutJobs$1(JobTimeoutTrigger.java:65) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.broker.job.JobState.lambda$forEachTimedOutEntry$6(JobState.java:198) ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.visit(ZeebeTransactionDb.java:385) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$whileTrue$7(ZeebeTransactionDb.java:295) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.runInNewTransaction(ZeebeTransactionDb.java:177) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:166) ~[zb-db-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
```

Interesting lines are the following:

>at **io.zeebe.broker.job.JobTimeoutTrigger.lambda$deactivateTimedOutJobs$1(JobTimeoutTrigger.java:65)** ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
> at **io.zeebe.broker.job.JobState.lambda$forEachTimedOutEntry$6(JobState.java:198)** ~[zeebe-broker-core-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]

**Comment by npepinpe** [comment]
It happened to me two times in a row, but now I can't reproduce it anymore (i.e. tried writing a test case specifically for it). Not sure how it happened exactly, since we're flushing the writer after every job we time out, and all jobs had an empty payload. Either way, closing as not reproduceable.

**Comment by menski** [comment]
Happened to Bernd also, we should investigate the root cause

```
22:54:42.358 [zb-stream-processor] [10.244.0.170:26501-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.RuntimeException: Unexpected error occurred during RocksDB transaction.
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:169) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:153) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:289) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:76) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.broker.job.JobState.forEachTimedOutEntry(JobState.java:186) ~[zeebe-broker-core-0.16.1.jar:0.16.1]
	at io.zeebe.broker.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:60) ~[zeebe-broker-core-0.16.1.jar:0.16.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zb-util-0.16.1.jar:0.16.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.16.1.jar:0.16.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zb-util-0.16.1.jar:0.16.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.16.1.jar:0.16.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.16.1.jar:0.16.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.16.1.jar:0.16.1]
Caused by: java.lang.RuntimeException: Cannot claim more than 174763 bytes.
	at io.zeebe.dispatcher.Dispatcher.claim(Dispatcher.java:294) ~[zb-dispatcher-0.16.1.jar:0.16.1]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:233) ~[zb-logstreams-0.16.1.jar:0.16.1]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:211) ~[zb-logstreams-0.16.1.jar:0.16.1]
	at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.flush(TypedCommandWriterImpl.java:143) ~[zeebe-broker-core-0.16.1.jar:0.16.1]
	at io.zeebe.broker.job.JobTimeoutTrigger.lambda$deactivateTimedOutJobs$1(JobTimeoutTrigger.java:65) ~[zeebe-broker-core-0.16.1.jar:0.16.1]
	at io.zeebe.broker.job.JobState.lambda$forEachTimedOutEntry$6(JobState.java:198) ~[zeebe-broker-core-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.visit(ZeebeTransactionDb.java:385) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$whileTrue$7(ZeebeTransactionDb.java:295) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.runInNewTransaction(ZeebeTransactionDb.java:177) ~[zb-db-0.16.1.jar:0.16.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:166) ~[zb-db-0.16.1.jar:0.16.1]
	... 11 more
```

**Comment by berndruecker** [comment]
I can't reproduce on my GKE cluster under load - but I try to get information how to reproduce on AKS in the customer scenario
