### ISSUE TITLE
Nullpointer on AbstractHandler#isStateSameAsElementState

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2174]
The element instance in the context can be null.

```java
java.lang.RuntimeException: Unexpected error occurred during RocksDB transaction.
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:169) ~[zb-db-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.reprocessEvent(StreamProcessorController.java:248) ~[zb-logstreams-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.reprocessNextEvent(StreamProcessorController.java:229) ~[zb-logstreams-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
Caused by: java.lang.NullPointerException
	at io.zeebe.broker.workflow.processor.handlers.AbstractHandler.isStateSameAsElementState(AbstractHandler.java:80) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.handlers.element.ElementActivatingHandler.shouldHandleState(ElementActivatingHandler.java:53) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.handlers.AbstractHandler.handle(AbstractHandler.java:48) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.BpmnStepHandlers.handle(BpmnStepHandlers.java:152) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:76) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:179) ~[zeebe-broker-core-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.runInNewTransaction(ZeebeTransactionDb.java:177) ~[zb-db-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.transaction(ZeebeTransactionDb.java:166) ~[zb-db-0.17.0-SNAPSHOT.jar:0.17.0-SNAPSHOT]
	... 8 more
```

```java
  protected boolean isStateSameAsElementState(BpmnStepContext<T> context) {
    return context.getState() == context.getElementInstance().getState();
  }
```

**Comment by npepinpe** [comment]
We should fix the NPE, but not having an element instance in this case (e.g. `ELEMENT_ACTIVATING`) is probably related to #2176.
