### ISSUE TITLE
TimerStartEventTest shouldTriggerDifferentWorkflowsSeparately is unstable

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2222]
```
[ERROR] shouldTriggerDifferentWorkflowsSeparately(io.zeebe.broker.workflow.TimerStartEventTest)  Time elapsed: 5.411 s  <<< FAILURE!                                                                    
org.junit.ComparisonFailure: expected:<[2]L> but was:<[1]L>                          
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                                                        
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                         
        at io.zeebe.broker.workflow.TimerStartEventTest.shouldTriggerDifferentWorkflowsSeparately(TimerStartEventTest.java:355)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                        
        at java.lang.reflect.Method.invoke(Method.java:498)                                    
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)                                                                                                         
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)                                                                                                           
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)   
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)                                                                                                                
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)              
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)                                                                                                                                  
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)           
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)                                                                                                                                          
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)                      
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)                                                                                                            
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)                                                                                                                                  
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)     
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)                                                                                                                            
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)                    
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)                                                                                                                             
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)               
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)                                                                                                             
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)                                                                                                      
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by Zelldon** [comment]
Also `TimerStartEventTest.shouldCreateMultipleInstanceAtTheCorrectTimes`

```
15:47:19 [1 - Java Tests] [ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.297 s <<< FAILURE! - in io.zeebe.broker.workflow.TimerStartEventTest
15:47:19 [1 - Java Tests] [ERROR] shouldCreateMultipleInstanceAtTheCorrectTimes(io.zeebe.broker.workflow.TimerStartEventTest)  Time elapsed: 6.285 s  <<< FAILURE!
15:47:19 [1 - Java Tests] org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
15:47:19 [1 - Java Tests] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15:47:19 [1 - Java Tests] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
15:47:19 [1 - Java Tests] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
15:47:19 [1 - Java Tests] 	at io.zeebe.broker.workflow.TimerStartEventTest.shouldCreateMultipleInstanceAtTheCorrectTimes(TimerStartEventTest.java:383)
15:47:19 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:47:19 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:47:19 [1 - Java Tests] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:47:19 [1 - Java Tests] 	at java.lang.reflect.Method.invoke(Method.java:498)
15:47:19 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
15:47:19 [1 - Java Tests] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
15:47:19 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
15:47:19 [1 - Java Tests] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
15:47:19 [1 - Java Tests] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
15:47:19 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
15:47:19 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:47:19 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
15:47:19 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
15:47:19 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
15:47:19 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:47:19 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
15:47:19 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:47:19 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
15:47:19 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
