### ISSUE TITLE
Integration test ServiceTaskTest#shouldCompleteTasksFromMultipleProcesses is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2257]
```
15:23:59 [1 - Java Tests] [ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.792 s <<< FAILURE! - in io.zeebe.broker.it.workflow.ServiceTaskTest
15:23:59 [1 - Java Tests] [ERROR] shouldCompleteTasksFromMultipleProcesses(io.zeebe.broker.it.workflow.ServiceTaskTest)  Time elapsed: 0.873 s  <<< ERROR!
15:23:59 [1 - Java Tests] io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
15:23:59 [1 - Java Tests] 	at java.util.Optional.orElseThrow(Optional.java:290)
15:23:59 [1 - Java Tests] 	at io.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:80)
15:23:59 [1 - Java Tests] 	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertElementCompleted(ZeebeAssertHelper.java:161)
15:23:59 [1 - Java Tests] 	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertWorkflowInstanceCompleted(ZeebeAssertHelper.java:104)
15:23:59 [1 - Java Tests] 	at io.zeebe.broker.it.workflow.ServiceTaskTest.shouldCompleteTasksFromMultipleProcesses(ServiceTaskTest.java:389)
15:23:59 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:23:59 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:23:59 [1 - Java Tests] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:23:59 [1 - Java Tests] 	at java.lang.reflect.Method.invoke(Method.java:498)
15:23:59 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
15:23:59 [1 - Java Tests] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
15:23:59 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
15:23:59 [1 - Java Tests] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
15:23:59 [1 - Java Tests] 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
15:23:59 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
15:23:59 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:23:59 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
15:23:59 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
15:23:59 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
15:23:59 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:23:59 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
15:23:59 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:23:59 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
15:23:59 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by Zelldon** [comment]
Run it 350 times without an error :sweat_smile:

**Comment by Zelldon** [comment]
Can't reproduce it anymore. I assume it is fixed with fixing the race condition in the RecordingExporter https://github.com/zeebe-io/zeebe/commit/3bdf197996ca4c1455b043ffafbe070bb3ba27c9
