### ISSUE TITLE
MessageOutputMappingTest#shouldApplyOutputMappings is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2269]
```
15:52:22 [1 - Java Tests] [ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.335 s <<< FAILURE! - in io.zeebe.broker.workflow.variables.MessageOutputMappingTest
15:52:22 [1 - Java Tests] [ERROR] shouldApplyOutputMappings[from {'i': 2, 'x': 1} to activity: [("x", "0")] and scope: [("i", "2")]](io.zeebe.broker.workflow.variables.MessageOutputMappingTest)  Time elapsed: 0.046 s  <<< ERROR!
15:52:22 [1 - Java Tests] io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
15:52:22 [1 - Java Tests] 	at java.util.Optional.orElseThrow(Optional.java:290)
15:52:22 [1 - Java Tests] 	at io.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:80)
15:52:22 [1 - Java Tests] 	at io.zeebe.broker.workflow.variables.MessageOutputMappingTest.shouldApplyOutputMappings(MessageOutputMappingTest.java:186)
15:52:22 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:52:22 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:52:22 [1 - Java Tests] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:52:22 [1 - Java Tests] 	at java.lang.reflect.Method.invoke(Method.java:498)
15:52:22 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
15:52:22 [1 - Java Tests] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
15:52:22 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
15:52:22 [1 - Java Tests] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
15:52:22 [1 - Java Tests] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
15:52:22 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:52:22 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
15:52:22 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
15:52:22 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:52:22 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
15:52:22 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:52:22 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
15:52:22 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:52:22 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
15:52:22 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:52:22 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
15:52:22 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:52:22 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
15:52:22 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
15:52:22 [1 - Java Tests] 
```

**Comment by Zelldon** [comment]
Can't reproduce it locally, since the time elapse is `Time elapsed: 0.046 s ` I assume it is related to the concurrency problem which was fixed with https://github.com/zeebe-io/zeebe/commit/3bdf197996ca4c1455b043ffafbe070bb3ba27c9
