### ISSUE TITLE
SetVariablesTest.shouldFailSetVariablesIfWorkflowInstanceIsCompleted is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2271]
```
16:10:39 [1 - Java Tests] [ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.644 s <<< FAILURE! - in io.zeebe.broker.it.workflow.SetVariablesTest
16:10:39 [1 - Java Tests] [ERROR] shouldFailSetVariablesIfWorkflowInstanceIsCompleted(io.zeebe.broker.it.workflow.SetVariablesTest)  Time elapsed: 0.065 s  <<< FAILURE!
16:10:39 [1 - Java Tests] java.lang.AssertionError: Expected test to throw (an instance of io.zeebe.client.cmd.ClientStatusException and status code to be <NOT_FOUND>)
16:10:39 [1 - Java Tests] 	at org.junit.Assert.fail(Assert.java:88)
16:10:39 [1 - Java Tests] 	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
16:10:39 [1 - Java Tests] 	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
16:10:39 [1 - Java Tests] 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
16:10:39 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
16:10:39 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
16:10:39 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
16:10:39 [1 - Java Tests] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
16:10:39 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
16:10:39 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
16:10:39 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
16:10:39 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
16:10:39 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
16:10:39 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
16:10:39 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
16:10:39 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
16:10:39 [1 - Java Tests] 
```

**Comment by Zelldon** [comment]
Again related to class rule
