### ISSUE TITLE
io.zeebe.broker.it.job.ActivateJobsTest.shouldActivateJobsOnPartitionsRoundRobin is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2287]
```
Error Message
Expecting:
  <[0, 1, 0]>
to contain only:
  <[0, 1, 2]>
but could not find the following elements:
  <[2]>
Stacktrace
java.lang.AssertionError: 

Expecting:
  <[0, 1, 0]>
to contain only:
  <[0, 1, 2]>
but could not find the following elements:
  <[2]>

	at io.zeebe.broker.it.job.ActivateJobsTest.shouldActivateJobsOnPartitionsRoundRobin(ActivateJobsTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zelldon** [comment]
We need to wait here until all partitions are up
