### ISSUE TITLE
TimerCatchEventTest is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2293]
```
13:42:43 [1 - Java Tests] [ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.775 s <<< FAILURE! - in io.zeebe.broker.workflow.timer.TimerCatchEventTest
13:42:43 [1 - Java Tests] [ERROR] shouldTriggerMultipleTimers(io.zeebe.broker.workflow.timer.TimerCatchEventTest)  Time elapsed: 1.004 s  <<< FAILURE!
13:42:43 [1 - Java Tests] java.lang.AssertionError: 
13:42:43 [1 - Java Tests] 
13:42:43 [1 - Java Tests] Expecting:
13:42:43 [1 - Java Tests]  <1553863360737L>
13:42:43 [1 - Java Tests] to be less than:
13:42:43 [1 - Java Tests]  <1553863359837L> 
13:42:43 [1 - Java Tests] 	at io.zeebe.broker.workflow.timer.TimerCatchEventTest.shouldTriggerMultipleTimers(TimerCatchEventTest.java:285)
13:42:43 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:42:43 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:42:43 [1 - Java Tests] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:42:43 [1 - Java Tests] 	at java.lang.reflect.Method.invoke(Method.java:498)
13:42:43 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
13:42:43 [1 - Java Tests] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
13:42:43 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
13:42:43 [1 - Java Tests] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
13:42:43 [1 - Java Tests] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
13:42:43 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:42:43 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
13:42:43 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:42:43 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
13:42:43 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
13:42:43 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
13:42:43 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
13:42:43 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by Zelldon** [comment]
```java

2019-04-23T10:03:14.417Z] [ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.827 s <<< FAILURE! - in io.zeebe.broker.workflow.timer.TimerCatchEventTest

[2019-04-23T10:03:14.417Z] [ERROR] testLifeCycle(io.zeebe.broker.workflow.timer.TimerCatchEventTest)  Time elapsed: 5.068 s  <<< FAILURE!

[2019-04-23T10:03:14.417Z] org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>

[2019-04-23T10:03:14.417Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[2019-04-23T10:03:14.417Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

[2019-04-23T10:03:14.417Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[2019-04-23T10:03:14.417Z] 	at io.zeebe.broker.workflow.timer.TimerCatchEventTest.testLifeCycle(TimerCatchEventTest.java:123)

[2019-04-23T10:03:14.417Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2019-04-23T10:03:14.417Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2019-04-23T10:03:14.417Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-04-23T10:03:14.417Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

[2019-04-23T10:03:14.417Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

[2019-04-23T10:03:14.417Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2019-04-23T10:03:14.417Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

[2019-04-23T10:03:14.417Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)

[2019-04-23T10:03:14.417Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

[2019-04-23T10:03:14.417Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-04-23T10:03:14.417Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)

[2019-04-23T10:03:14.417Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-04-23T10:03:14.417Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

[2019-04-23T10:03:14.417Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

[2019-04-23T10:03:14.417Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by Zelldon** [comment]
```java

[2019-04-23T09:40:55.799Z] [ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.794 s <<< FAILURE! - in io.zeebe.broker.workflow.timer.TimerCatchEventTest
[2019-04-23T09:40:55.799Z] [ERROR] shouldTriggerHandlerNodeWhenAttachedToActivity(io.zeebe.broker.workflow.timer.TimerCatchEventTest)  Time elapsed: 5.088 s  <<< FAILURE!
[2019-04-23T09:40:55.799Z] org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
[2019-04-23T09:40:55.799Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2019-04-23T09:40:55.799Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2019-04-23T09:40:55.799Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2019-04-23T09:40:55.799Z] 	at io.zeebe.broker.workflow.timer.TimerCatchEventTest.shouldTriggerHandlerNodeWhenAttachedToActivity(TimerCatchEventTest.java:432)
[2019-04-23T09:40:55.799Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-04-23T09:40:55.799Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-04-23T09:40:55.799Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-04-23T09:40:55.799Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[2019-04-23T09:40:55.799Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[2019-04-23T09:40:55.799Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2019-04-23T09:40:55.799Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2019-04-23T09:40:55.799Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[2019-04-23T09:40:55.799Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2019-04-23T09:40:55.799Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[2019-04-23T09:40:55.799Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[2019-04-23T09:40:55.799Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[2019-04-23T09:40:55.799Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2019-04-23T09:40:55.799Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[2019-04-23T09:40:55.799Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
