### ISSUE TITLE
AssertionError in LockBlockIndex rollback transaction call

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2324]
In tests I sometimes see the following assertion error, which indicates that we try to rollback a transaction which does not own the rocksdb native handle. 

```
Exception in thread "0.0.0.0:25636-zb-actors-0" java.lang.AssertionError
	at org.rocksdb.Transaction.rollback(Transaction.java:215)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.rollbackInternal(ZeebeTransaction.java:107)
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:174)
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:143)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:266)
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:117)
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.lookupBlockPosition(LogBlockIndex.java:114)
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.lookupBlockAddress(LogBlockIndex.java:88)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.lookUpBlockAddressForPosition(BufferedLogStreamReader.java:327)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:111)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seekToFirstEvent(BufferedLogStreamReader.java:126)
	at io.zeebe.logstreams.processor.StreamProcessorController.recoverFromSnapshot(StreamProcessorController.java:167)
	at io.zeebe.logstreams.processor.StreamProcessorController.onActorStarting(StreamProcessorController.java:110)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112)
```

**Comment by Zelldon** [comment]
I saw this as well and it seems this happens only after the test is done and the broker tries to stop.
