### ISSUE TITLE
timeout at startup with default configuration on mac

### ISSUE THREAD

**Issue by aximo** [zeebe-io/zeebe#2480]
broker version: 0.17.0
os: macOS  10.14.3

When i startup broker in default configuration ,some error happen and broker exit finally:
```
18:32:00.714 [service-controller] [0.0.0.0:26501-zb-actors-0] INFO  io.zeebe.transport - Bound clientApi.server to /0.0.0.0:26501
18:32:00.714 [service-controller] [0.0.0.0:26501-zb-actors-0] INFO  io.zeebe.transport - Bound replicationApi.server to /0.0.0.0:26503
18:32:20.974 [] [main] ERROR io.zeebe.broker.system - Could not start broker
java.util.concurrent.TimeoutException: Timeout after: 20 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145) ~[zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.broker.system.SystemContext.init(SystemContext.java:205) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.start(Broker.java:76) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.lambda$new$0(Broker.java:61) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:29) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.<init>(Broker.java:61) [zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.<init>(Broker.java:48) [zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.StandaloneBroker.startBrokerFromConfiguration(StandaloneBroker.java:65) [zeebe-distribution-0.17.0.jar:0.17.0]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:36) [zeebe-distribution-0.17.0.jar:0.17.0]
18:32:20.979 [] [main] INFO  io.zeebe.broker.system - Closing...
18:32:30.790 [service-controller] [0.0.0.0:26501-zb-actors-0] INFO  io.zeebe.raft - Created raft partition-0 with configuration RaftConfiguration{heartbeatInterval='250ms', electionInterval='1s', leaveTimeout='1s'}
```

Any suggestion?

**Comment by aximo** [comment]
more detail,any help?
```
11:48:53.043 [] [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
11:49:13.055 [] [main] ERROR io.zeebe.broker.system - Could not start broker
java.util.concurrent.TimeoutException: Timeout after: 20 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145) ~[zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.broker.system.SystemContext.init(SystemContext.java:205) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.start(Broker.java:76) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.lambda$new$0(Broker.java:61) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:29) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.<init>(Broker.java:61) [zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.<init>(Broker.java:48) [zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.StandaloneBroker.startBrokerFromConfiguration(StandaloneBroker.java:65) [zeebe-distribution-0.17.0.jar:0.17.0]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:36) [zeebe-distribution-0.17.0.jar:0.17.0]
11:49:13.060 [] [main] INFO  io.zeebe.broker.system - Closing...
11:49:13.063 [] [main] DEBUG io.zeebe.gateway - Closing client ...
11:49:13.065 [] [main] DEBUG io.zeebe.gateway - topology manager closed
11:49:13.068 [] [main] DEBUG io.zeebe.gateway - transport closed
11:49:13.069 [] [main] DEBUG io.zeebe.gateway - internal transport closed
11:49:13.069 [] [main] DEBUG io.zeebe.gateway - data frame receive buffer closed
11:49:13.070 [] [main] DEBUG io.zeebe.gateway - Client closed.
11:49:22.964 [service-controller] [0.0.0.0:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Adding Node{nodeId=0, clientApi=0.0.0.0:26501, managementApi=0.0.0.0:26502, replicationApi=0.0.0.0:26503, subscriptionApi=0.0.0.0:26504} to list of known members
11:49:22.971 [service-container-main] [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.RuntimeException: Could not start service cluster.base.gossip.join removed while starting
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.onStarted(ServiceController.java:232) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:204) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:197) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceController.onServiceEvent(ServiceController.java:119) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.17.0.jar:0.17.0]
11:49:22.976 [service-container-main] [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.RuntimeException: Could not start service cluster.base.topologyManager removed while starting
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.onStarted(ServiceController.java:232) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:204) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:197) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceController.onServiceEvent(ServiceController.java:119) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.17.0.jar:0.17.0]
11:49:22.981 [io.zeebe.servicecontainer.CompositeServiceBuilder$CompositeInstallCompletion] [0.0.0.0:26501-zb-actors-1] DEBUG io.zeebe.util.actor - Continuing on future completion failed
java.lang.IllegalStateException: Cannot complete future, the future is already completed exceptionally with 'Could not complete installation of cluster.base.bootstrapped: Failed to install cluster.base.topologyManager'
	at io.zeebe.util.sched.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:194) ~[zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:201) ~[zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.CompositeServiceBuilder$CompositeInstallCompletion.lambda$null$0(CompositeServiceBuilder.java:103) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:35) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.17.0.jar:0.17.0]
11:49:23.076 [] [main] DEBUG io.zeebe.servicecontainer - Service container closing failed. Print dependencies.
11:49:23.077 [] [main] DEBUG io.zeebe.servicecontainer -
transport.clientApi.server.receive-buffer in AwaitDependentsStopped
	\
transport.clientApi.messageHandler in AwaitDependentsStopped
	\
 	-- transport.clientApi.server.receive-buffer in AwaitDependentsStopped
cluster.base.partition.install.partition-0 in AwaitDependenciesStartedState
	\
 	-- null
 	-- null
transport.clientApi.server.server in AwaitStopState
	\
 	-- transport.clientApi.messageHandler in AwaitDependentsStopped
11:49:23.077 [] [main] ERROR io.zeebe.broker.system - Failed to close broker within PT10S seconds.
java.util.concurrent.TimeoutException: Timeout after: 10000 MILLISECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145) ~[zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.close(ServiceContainerImpl.java:212) ~[zeebe-service-container-0.17.0.jar:0.17.0]
	at io.zeebe.broker.system.SystemContext.close(SystemContext.java:227) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.system.SystemContext.init(SystemContext.java:209) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.start(Broker.java:76) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.lambda$new$0(Broker.java:61) ~[zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:29) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.<init>(Broker.java:61) [zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.Broker.<init>(Broker.java:48) [zeebe-broker-core-0.17.0.jar:0.17.0]
	at io.zeebe.broker.StandaloneBroker.startBrokerFromConfiguration(StandaloneBroker.java:65) [zeebe-distribution-0.17.0.jar:0.17.0]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:36) [zeebe-distribution-0.17.0.jar:0.17.0]
11:49:52.831 [clientApi.server-receiver] [0.0.0.0:26501-zb-actors-1] DEBUG io.zeebe.transport - Failed to add channel java.nio.channels.SocketChannel[closed]
java.nio.channels.ClosedChannelException: null
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:197) ~[?:1.8.0_211]
	at java.nio.channels.SelectableChannel.register(SelectableChannel.java:280) ~[?:1.8.0_211]
	at io.zeebe.transport.impl.TransportChannel.registerSelector(TransportChannel.java:192) ~[zeebe-transport-0.17.0.jar:0.17.0]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.maintainChannels(ReadTransportPoller.java:92) ~[zeebe-transport-0.17.0.jar:0.17.0]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.pollBlockingEnded(ReadTransportPoller.java:57) ~[zeebe-transport-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.RunnableAdapter.lambda$wrapConsumer$2(RunnableAdapter.java:61) ~[zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.17.0.jar:0.17.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.17.0.jar:0.17.0]
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timeout after: 20 SECONDS
	at io.zeebe.broker.system.SystemContext.init(SystemContext.java:210)
	at io.zeebe.broker.Broker.start(Broker.java:76)
	at io.zeebe.broker.Broker.lambda$new$0(Broker.java:61)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:29)
	at io.zeebe.broker.Broker.<init>(Broker.java:61)
	at io.zeebe.broker.Broker.<init>(Broker.java:48)
	at io.zeebe.broker.StandaloneBroker.startBrokerFromConfiguration(StandaloneBroker.java:65)
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:36)
Caused by: java.util.concurrent.TimeoutException: Timeout after: 20 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145)
	at io.zeebe.broker.system.SystemContext.init(SystemContext.java:205)
	... 7 more
```

**Comment by menski** [comment]
In upcoming releases the service startup can be logged by enabling trace logging for the service container, see
https://github.com/zeebe-io/zeebe/blob/17fb1df1910876f53da36b604584c5e1bfdaacf4/service-container/src/test/resources/log4j2-test.xml#L11

Feel free to reopen this issue if you can provide more information.
