### ISSUE TITLE
Large JSONObjects can't be deserialized

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#250]
On writing test cases for #193 there occurred the following exception for larger json payload:

```java
The log stream processor failed to process event. It stop processing further events.
java.lang.RuntimeException: Could not deserialize object. Deserialization stuck at offset 110
	at org.camunda.tngp.broker.util.msgpack.UnpackedObject.wrap(UnpackedObject.java:30)
	at org.camunda.tngp.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:148)
	at org.camunda.tngp.broker.workflow.processor.WorkflowInstanceStreamProcessor.onTaskEvent(WorkflowInstanceStreamProcessor.java:289)
	at org.camunda.tngp.broker.workflow.processor.WorkflowInstanceStreamProcessor.onEvent(WorkflowInstanceStreamProcessor.java:213)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:320)
	at org.camunda.tngp.util.state.ComposedState.doWork(ComposedState.java:60)
	at org.camunda.tngp.util.state.StateMachine.doWork(StateMachine.java:107)
	at org.camunda.tngp.util.state.StateMachineAgent.doWork(StateMachineAgent.java:50)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:138)
	at org.camunda.tngp.util.agent.AgentGroup.doWork(AgentGroup.java:45)
	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: offset=161 length=-51 not valid for buffer.capacity()=410
	at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:240)
	at org.camunda.tngp.broker.util.msgpack.value.BinaryValue.wrap(BinaryValue.java:46)
	at org.camunda.tngp.broker.util.msgpack.value.BinaryValue.read(BinaryValue.java:87)
	at org.camunda.tngp.broker.util.msgpack.property.BaseProperty.read(BaseProperty.java:84)
	at org.camunda.tngp.broker.util.msgpack.value.ObjectValue.read(ObjectValue.java:121)
	at org.camunda.tngp.broker.util.msgpack.UnpackedObject.wrap(UnpackedObject.java:26)
	... 12 more
```

See as example the follwing test cases, which are currently ignored, `WorkflowTaskIOMappingTest#shouldUseOutputMappingToReplaceObjectWithComplexObjectInWorkflowPayload`

and 
`#shouldUseOutputMappingToReplaceObjectInComplexObjectWithValueInWorkflowPayload`.
If one jsonobject is uncommented/removed the test will run without an exception.

**Comment by Zelldon** [comment]
I think this is fixed with https://github.com/zeebe-io/zeebe/issues/582
