### ISSUE TITLE
DB transaction loops forever with an exception in new leader

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2515]
I have seen the following error a couple of times in docker-compose setup, after leadership change occurs. The transaction retries forever because there is an exception. It doesn't block the processor. It can still create workflows and activate jobs.
`Caused by: java.lang.IllegalStateException: Expected to find job with key 2251799813692390, but no job found`
I wonder if it is due to some inconsistent state.

```
java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:155) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:266) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:117) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:108) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:104) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.engine.state.instance.JobState.forEachTimedOutEntry(JobState.java:176) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.engine.processor.workflow.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:61) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | Caused by: java.lang.IllegalStateException: Expected to find job with key 2251799813692390, but no job found
broker-2_1  | 	at io.zeebe.engine.state.instance.JobState.visitJob(JobState.java:225) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.engine.state.instance.JobState.lambda$forEachTimedOutEntry$0(JobState.java:182) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.visit(ZeebeTransactionDb.java:365) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$whileTrue$8(ZeebeTransactionDb.java:273) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$ensureInOpenTransaction$1(ZeebeTransactionDb.java:155) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:171) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:143) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
```

**Comment by menski** [comment]
Assumption:
- activate job on old leader
- kill leader
- on recovery we either don't create the activated state correctly or handle timeouted jobs wrong

**Comment by npepinpe** [comment]
Quick question, since the exception is thrown, is it possible we never time out jobs after this? i.e. we iterate over jobs and fail early due to this exception, so we never iterate over the others?

**Comment by Zelldon** [comment]
@npepinpe I think you are right since the transaction is then aborted and rolled back

See also the following traces which we will print every 30 seconds the same key:

```
12:58:23.982 [stream-processor] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-actors-2] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.
        at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:155) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:266) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:117) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:108) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:104) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.engine.state.instance.JobState.forEachTimedOutEntry(JobState.java:198) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.engine.processor.workflow.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:61) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:88) ~[zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:51) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:177) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:142) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:126) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:104) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Expected to find job with key 9007199254773553, but no job found
        at io.zeebe.engine.state.instance.JobState.visitJob(JobState.java:247) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.engine.state.instance.JobState.lambda$forEachTimedOutEntry$0(JobState.java:204) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.visit(ZeebeTransactionDb.java:365) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$whileTrue$8(ZeebeTransactionDb.java:273) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$ensureInOpenTransaction$1(ZeebeTransactionDb.java:155) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:141) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        ... 13 more
12:58:53.990 [stream-processor] [zeebe-0.zeebe.default.svc.cluster.local:26501-zb-actors-2] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.
        at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:155) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:266) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:117) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:108) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:104) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.engine.state.instance.JobState.forEachTimedOutEntry(JobState.java:198) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.engine.processor.workflow.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:61) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:88) ~[zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:51) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:177) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:142) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:126) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:104) [zeebe-util-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Expected to find job with key 9007199254773553, but no job found
        at io.zeebe.engine.state.instance.JobState.visitJob(JobState.java:247) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.engine.state.instance.JobState.lambda$forEachTimedOutEntry$0(JobState.java:204) ~[zeebe-workflow-engine-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.visit(ZeebeTransactionDb.java:365) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$whileTrue$8(ZeebeTransactionDb.java:273) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$ensureInOpenTransaction$1(ZeebeTransactionDb.java:155) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:171) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:143) ~[zeebe-db-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
        ... 13 more
```

**Comment by npepinpe** [comment]
As it's not useful at the moment to fail while iterating, we will just log errors for now and remove the key from the deadline family, and keep iterating. We should leave the issue open after because this fixes the symptom and not the cause.
