### ISSUE TITLE
Exceptions in Elasticsearch Exporter on long running test

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2528]
We saw in the latest weekly run the following exceptions:

```
{
 insertId:  "tyw38hg25ee69d"  
 labels: {…}  
 logName:  "projects/zeebe-io/logs/zeebe"  
 receiveTimestamp:  "2019-05-26T02:07:57.767612101Z"  
 resource: {
  labels: {
   cluster_name:  "default"    
   container_name:  "zeebe"    
   instance_id:  "4962350218928084326"    
   namespace_id:  "default"    
   pod_id:  "zeebe-1"    
   project_id:  "zeebe-io"    
   zone:  "europe-west1-b"    
  }
  type:  "container"   
 }
 severity:  "INFO"  
 textPayload:  "02:07:52.420 [exporter] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-fs-workers-2] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush at least one bulk request ElasticsearchException[Elasticsearch exception [type=cluster_block_exception, reason=blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
"  
 timestamp:  "2019-05-26T02:07:52.420772187Z"  
}

{
 insertId:  "tyw38hg25ee69e"  
 labels: {…}  
 logName:  "projects/zeebe-io/logs/zeebe"  
 receiveTimestamp:  "2019-05-26T02:07:57.767612101Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "02:07:52.421 [exporter] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-fs-workers-2] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush bulk completely
"  
 timestamp:  "2019-05-26T02:07:52.421210868Z"  
}


```

We saw this on all nodes. In addition to that we saw later the following exception:

```
{
 insertId:  "wgpcldg2mnvyz6"  
 labels: {…}  
 logName:  "projects/zeebe-io/logs/zeebe"  
 receiveTimestamp:  "2019-05-26T23:25:52.686940016Z"  
 resource: {
  labels: {
   cluster_name:  "default"    
   container_name:  "zeebe"    
   instance_id:  "3948891464973361785"    
   namespace_id:  "default"    
   pod_id:  "zeebe-0"    
   project_id:  "zeebe-io"    
   zone:  "europe-west1-b"    
  }
  type:  "container"   
 }
 severity:  "INFO"  
 textPayload:  "java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:537) ~[elasticsearch-rest-client-6.7.2.jar:6.7.2]
	at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:520) ~[elasticsearch-rest-client-6.7.2.jar:6.7.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:232) ~[elasticsearch-rest-client-6.7.2.jar:6.7.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.7.2.jar:6.7.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.7.2.jar:6.7.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.7.2.jar:6.7.2]
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:472) ~[elasticsearch-rest-high-level-client-6.7.2.jar:6.7.2]
	at io.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:88) ~[zeebe-elasticsearch-exporter-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:101) ~[zeebe-elasticsearch-exporter-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:87) ~[zeebe-elasticsearch-exporter-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:456) ~[zeebe-broker-core-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:42) ~[zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:51) ~[zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
"  
 timestamp:  "2019-05-26T23:25:49.308793316Z"  
}

```

**Comment by Zelldon** [comment]
This was the first exception


```

{
 insertId:  "1sntympg23it76e"  
 labels: {…}  
 logName:  "projects/zeebe-io/logs/zeebe"  
 receiveTimestamp:  "2019-05-25T23:31:10.617667625Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "23:31:05.107 [exporter] [zeebe-3.zeebe.default.svc.cluster.local:26501-zb-fs-workers-2] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush at least one bulk request ElasticsearchException[Elasticsearch exception [type=cluster_block_exception, reason=blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
"  
 timestamp:  "2019-05-25T23:31:05.107805950Z"  
}

```

**Comment by Zelldon** [comment]
I think the reason is that on node `elasticsearch-master-2`  we used 75% disk space.

```
This happens when Elasticsearch thinks the disk is running low on space so it puts itself into read-only mode.

By default Elasticsearch's decision is based on the percentage of disk space that's free, so on big disks this can happen even if you have many gigabytes of free space.

The flood stage watermark is 95% by default, so on a 1TB drive you need at least 50GB of free space or Elasticsearch will put itself into read-only mode.
[...]
```
https://stackoverflow.com/questions/50609417/elasticsearch-error-cluster-block-exception-forbidden-12-index-read-only-all

I'm not sure what our current setting is.

**Comment by menski** [comment]
This is related to our benchmark setup and cannot be fixed in Zeebe itself. I created https://github.com/zeebe-io/zeebe-benchmark/issues/3 to setup ES Curator to get rid of indices.
