### ISSUE TITLE
Tests fail in before because of atomix supplier

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2534]
This exception happens a lot in the last days, it happens in different tests.

```
16:02:24  [ERROR] shouldCompleteWorkflow(io.zeebe.broker.engine.TimerStartEventTest)  Time elapsed: 3.361 s  <<< FAILURE!
16:02:24  java.lang.AssertionError: 
16:02:24  
16:02:24  Expecting actual not to be null
16:02:24  	at io.zeebe.test.broker.protocol.clientapi.ClientApiRule.fetchAtomix(ClientApiRule.java:129)
16:02:24  	at io.zeebe.test.broker.protocol.clientapi.ClientApiRule.before(ClientApiRule.java:99)
16:02:24  	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
16:02:24  	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
16:02:24  	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
16:02:24  	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
16:02:24  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
16:02:24  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
16:02:24  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
16:02:24  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
16:02:24  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
16:02:24  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
16:02:24  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
16:02:24  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
16:02:24  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
16:02:24  	at org.junit.runners.Suite.runChild(Suite.java:128)
16:02:24  	at org.junit.runners.Suite.runChild(Suite.java:27)
16:02:24  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
16:02:24  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
16:02:24  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
16:02:24  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
16:02:24  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
16:02:24  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
16:02:24  	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
16:02:24  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
16:02:24  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
16:02:24  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
16:02:24  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
16:02:24  	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
16:02:24  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
16:02:24  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
16:02:24  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
16:02:24  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by menski** [comment]
I added the following log statement to the `getService` method in the `EmbeddedBrokerRule` to debug this issue:
```
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: broker-core/src/test/java/io/zeebe/broker/test/EmbeddedBrokerRule.java
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ broker-core/src/test/java/io/zeebe/broker/test/EmbeddedBrokerRule.java:301 @ public class EmbeddedBrokerRule extends ExternalResource {
  public <S> S getService(final ServiceName<S> serviceName) {
    final ServiceContainer serviceContainer = broker.getBrokerContext().getServiceContainer();

    final Injector<S> injector = new Injector<>();
    final Injector<S> injector =
        new Injector<S>() {
          @Override
          public void inject(S service) {
            LOG.info(
                "Injected service {} for service name {} to accessor service",
                service,
                serviceName);
            super.inject(service);
          }
 
          @Override
          public S getValue() {
            final S service = super.getValue();
            LOG.info(
                "Returning service {} for service name {} to accessor service",
                service,
                serviceName);
            return service;
          }
        };

    final ServiceName<TestService> accessorServiceName =
        ServiceName.newServiceName("serviceAccess" + serviceName.getName(), TestService.class);
```

In case of this bug this leads to this log output which indicates that the injector does not return the injected service:

```
18:19:23.383 [service-controller] [0.0.0.0:27007-zb-actors-0] INFO  io.zeebe.broker.clustering - Returning atomix Atomix{partitions=io.atomix.primitive.partition.impl.DefaultPartitionService@2388ca52} from AtomixService
18:19:23.383 [service-controller] [0.0.0.0:27007-zb-actors-0] INFO  io.zeebe.broker.test - Injected service Atomix{partitions=io.atomix.primitive.partition.impl.DefaultPartitionService@2388ca52} for service name cluster.base.atomix to accessor service
18:19:23.384 [] [main] INFO  io.zeebe.broker.test - Returning service null for service name cluster.base.atomix to accessor service
```

**Comment by menski** [comment]
Okay I just understood that the value is uninjected in case the service is removed, which we trigger before returning the injected value. Which gives a small time frame for a race condition where the injector is already invalidated.

https://github.com/zeebe-io/zeebe/blob/391e9ce173d6c08551ced452a5c3796160729753/broker-core/src/test/java/io/zeebe/broker/test/EmbeddedBrokerRule.java#L315-L317
