### ISSUE TITLE
Concurrently complete and cancel can bring workflow in an undesired state 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2542]
The test `WorkflowInstanceStreamProcessorTest.shouldCancelAndCompleteJobConcurrentlyInSubProcess` tests the behavior of concurrently completed and canceled instance, but it seems that this does not always work as expected. The test is flaky and the corresponding instance ends sometimes in an undesired state, where it can't be completed nor terminated.

See the following log, where terminating and completing are skipped because the instance is not in an expected state.

```
13:13:41.405 [processor-snapshot-director] [-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - The position of the last valid snapshot is '-1'. Taking snapshots beyond this position.
13:13:41.516 [processor] [-zb-actors-0] DEBUG io.zeebe.broker.workflow - Skipping record TypedEventImpl{metadata=RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_TERMINATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}, value={"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}} due to step guard; in-memory element is ElementInstance{elementRecord=IndexedRecord{key=8, state=ELEMENT_COMPLETING, value={"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}}, parentKey=5, childCount=0, jobKey=-1, activeTokens=0}
13:13:41.517 [processor] [-zb-actors-0] DEBUG io.zeebe.broker.workflow - Skipping record TypedEventImpl{metadata=RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_COMPLETING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}, value={"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}} due to step guard; in-memory element is ElementInstance{elementRecord=IndexedRecord{key=8, state=ELEMENT_COMPLETING, value={"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}}, parentKey=5, childCount=0, jobKey=-1, activeTokens=0}

```

The following records are printed after the failed test:
```
13:13:51.559 [] [Time-limited test] INFO  io.zeebe.broker.test - Test failed, following records where exported:
13:13:51.564 [] [Time-limited test] INFO  io.zeebe.broker.test - Records on partition 0:
			Position: 4294967296 Key: -1
				RecordMetadata{recordType=COMMAND, intentValue=255, intent=CREATE, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE_CREATION, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","key":-1,"instanceKey":-1,"version":-1,"variables":"gA=="}
			Position: 4294967448 Key: 1
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS"}
			Position: 4294967656 Key: 2
				RecordMetadata{recordType=EVENT, intentValue=255, intent=CREATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE_CREATION, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","key":123,"instanceKey":1,"version":1,"variables":"gA=="}
			Position: 4294967832 Key: 1
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS"}
			Position: 4294968056 Key: 3
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_c8eed253-c50f-44db-ab1b-9fafc36ca412","flowScopeKey":1,"bpmnElementType":"START_EVENT"}
			Position: 4294968328 Key: 3
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_c8eed253-c50f-44db-ab1b-9fafc36ca412","flowScopeKey":1,"bpmnElementType":"START_EVENT"}
			Position: 4294968600 Key: 3
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_COMPLETING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_c8eed253-c50f-44db-ab1b-9fafc36ca412","flowScopeKey":1,"bpmnElementType":"START_EVENT"}
			Position: 4294968872 Key: 3
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_COMPLETED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_c8eed253-c50f-44db-ab1b-9fafc36ca412","flowScopeKey":1,"bpmnElementType":"START_EVENT"}
			Position: 4294969144 Key: 4
				RecordMetadata{recordType=EVENT, intentValue=255, intent=SEQUENCE_FLOW_TAKEN, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"sequenceFlow_a6f0871b-76da-4c4c-ba6d-f20f6d0da46d","flowScopeKey":1,"bpmnElementType":"SEQUENCE_FLOW"}
			Position: 4294969416 Key: 5
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"subProcess","flowScopeKey":1,"bpmnElementType":"SUB_PROCESS"}
			Position: 4294969648 Key: 5
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"subProcess","flowScopeKey":1,"bpmnElementType":"SUB_PROCESS"}
			Position: 4294969880 Key: 6
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_1407ac74-6827-4480-a953-56e09d99b1f1","flowScopeKey":5,"bpmnElementType":"START_EVENT"}
			Position: 4294970152 Key: 6
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_1407ac74-6827-4480-a953-56e09d99b1f1","flowScopeKey":5,"bpmnElementType":"START_EVENT"}
			Position: 4294970424 Key: 6
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_COMPLETING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_1407ac74-6827-4480-a953-56e09d99b1f1","flowScopeKey":5,"bpmnElementType":"START_EVENT"}
			Position: 4294970696 Key: 6
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_COMPLETED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"startEvent_1407ac74-6827-4480-a953-56e09d99b1f1","flowScopeKey":5,"bpmnElementType":"START_EVENT"}
			Position: 4294970968 Key: 7
				RecordMetadata{recordType=EVENT, intentValue=255, intent=SEQUENCE_FLOW_TAKEN, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"sequenceFlow_45d4cfa2-4c86-4df9-851e-621466371633","flowScopeKey":5,"bpmnElementType":"SEQUENCE_FLOW"}
			Position: 4294971240 Key: 8
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}
			Position: 4294971464 Key: 8
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}
			Position: 4294971688 Key: -1
				RecordMetadata{recordType=COMMAND, intentValue=255, intent=CREATE, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=JOB, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"deadline":-9223372036854775808,"worker":"","retries":3,"type":"taskType","headers":{"bpmnProcessId":"process","workflowDefinitionVersion":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","elementInstanceKey":8},"customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":""}
			Position: 4294972008 Key: 9
				RecordMetadata{recordType=EVENT, intentValue=255, intent=CREATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=JOB, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"deadline":-9223372036854775808,"worker":"","retries":3,"type":"taskType","headers":{"bpmnProcessId":"process","workflowDefinitionVersion":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","elementInstanceKey":8},"customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":""}
			Position: 4294972328 Key: 1
				RecordMetadata{recordType=COMMAND, intentValue=255, intent=CANCEL, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS"}
			Position: 4294972536 Key: 1
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_TERMINATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"process","flowScopeKey":-1,"bpmnElementType":"PROCESS"}
			Position: 4294972760 Key: -1
				RecordMetadata{recordType=EVENT, intentValue=255, intent=CREATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=JOB, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"deadline":-9223372036854775808,"worker":"","retries":3,"type":"taskType","headers":{"bpmnProcessId":"process","workflowDefinitionVersion":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","elementInstanceKey":8},"customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":""}
			Position: 4294973064 Key: 5
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_TERMINATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"subProcess","flowScopeKey":1,"bpmnElementType":"SUB_PROCESS"}
			Position: 4294973296 Key: 4294972760
				RecordMetadata{recordType=EVENT, intentValue=255, intent=COMPLETED, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=JOB, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"deadline":-9223372036854775808,"worker":"","retries":3,"type":"taskType","headers":{"bpmnProcessId":"process","workflowDefinitionVersion":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","elementInstanceKey":8},"customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":""}
			Position: 4294973600 Key: 8
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_TERMINATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}
			Position: 4294973824 Key: 8
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_COMPLETING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"process","version":1,"workflowKey":123,"workflowInstanceKey":1,"elementId":"task","flowScopeKey":5,"bpmnElementType":"SERVICE_TASK"}

13:13:51.568 [processor-snapshot-director] [-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Enforce snapshot creation. Last successful processed position is 4294973824.
13:13:51.588 [processor-snapshot-director] [-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Creation of snapshot for processor took 19 ms.
13:13:51.590 [processor] [-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/junit2291438789661476055/state/1_processor/runtime'.
13:13:51.590 [processor] [-zb-actors-1] DEBUG io.zeebe.logstreams - Closed stream processor controller processor.
13:13:51.599 [service-controller] [-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/junit2291438789661476055/index/runtime'.

org.junit.ComparisonFailure: 
Expected :true
Actual   :false
<Click to see difference>


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:96)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:69)
	at io.zeebe.engine.processor.workflow.WorkflowInstanceStreamProcessorRule.awaitElementInState(WorkflowInstanceStreamProcessorRule.java:268)
	at io.zeebe.engine.processor.workflow.WorkflowInstanceStreamProcessorTest.shouldCancelAndCompleteJobConcurrentlyInSubProcess(WorkflowInstanceStreamProcessorTest.java:201)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Zelldon** [comment]
I think the log statement should not be on debug level more a warning or error.

**Comment by menski** [comment]
I ignored the test case as it is constantly failing in CI caused by this bug. Please make sure to enable the test again when fixing the bug
https://github.com/zeebe-io/zeebe/commit/a5e123deb3b0e3f21e3c0a39d5f0eabf467e0db3
