### ISSUE TITLE
BrokerShutdownTest crashes JVM

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2568]
```
[...]
[2019-06-03T05:52:06.683Z] [INFO] Running io.zeebe.broker.it.shutdown.BrokerShutdownTest
[2019-06-03T05:52:07.257Z] [WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 4. See FAQ web page and the dump file /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire-reports/2019-06-03T05-47-15_261-jvmRun4.dumpstream

[...]

[2019-06-03T05:53:32.283Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project zeebe-qa-integration-tests: There are test failures.
[2019-06-03T05:53:32.283Z] [ERROR] 
[2019-06-03T05:53:32.283Z] [ERROR] Please refer to /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire-reports for the individual test results.
[2019-06-03T05:53:32.283Z] [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[2019-06-03T05:53:32.283Z] [ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2019-06-03T05:53:32.283Z] [ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx2048m -XX:MaxDirectMemorySize=4g -jar /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire/surefirebooter8305224814351261554.jar /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire 2019-06-03T05-47-15_261-jvmRun4 surefire5246893423464142267tmp surefire_17281588670180783787tmp
[2019-06-03T05:53:32.283Z] [ERROR] Error occurred in starting fork, check output in log
[2019-06-03T05:53:32.283Z] [ERROR] Process Exit Code: 134
[2019-06-03T05:53:32.283Z] [ERROR] Crashed tests:
[2019-06-03T05:53:32.283Z] [ERROR] io.zeebe.broker.it.shutdown.BrokerShutdownTest
[2019-06-03T05:53:32.283Z] [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2019-06-03T05:53:32.283Z] [ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx2048m -XX:MaxDirectMemorySize=4g -jar /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire/surefirebooter8305224814351261554.jar /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire 2019-06-03T05-47-15_261-jvmRun4 surefire5246893423464142267tmp surefire_17281588670180783787tmp
[2019-06-03T05:53:32.283Z] [ERROR] Error occurred in starting fork, check output in log
[2019-06-03T05:53:32.283Z] [ERROR] Process Exit Code: 134
[2019-06-03T05:53:32.283Z] [ERROR] Crashed tests:
[2019-06-03T05:53:32.283Z] [ERROR] io.zeebe.broker.it.shutdown.BrokerShutdownTest
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:511)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:383)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:298)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:247)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
[2019-06-03T05:53:32.283Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
[2019-06-03T05:53:32.283Z] [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2019-06-03T05:53:32.283Z] [ERROR] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2019-06-03T05:53:32.283Z] [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2019-06-03T05:53:32.283Z] [ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-03T05:53:32.283Z] [ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-03T05:53:32.283Z] [ERROR] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-03T05:53:32.283Z] [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2019-06-03T05:53:32.283Z] [ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx2048m -XX:MaxDirectMemorySize=4g -jar /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire/surefirebooter8305224814351261554.jar /home/jenkins/workspace/zeebe-io_zeebe_staging/qa/integration-tests/target/surefire 2019-06-03T05-47-15_261-jvmRun4 surefire5246893423464142267tmp surefire_17281588670180783787tmp
[2019-06-03T05:53:32.283Z] [ERROR] Error occurred in starting fork, check output in log
[2019-06-03T05:53:32.283Z] [ERROR] Process Exit Code: 134
[2019-06-03T05:53:32.283Z] [ERROR] Crashed tests:
[2019-06-03T05:53:32.283Z] [ERROR] io.zeebe.broker.it.shutdown.BrokerShutdownTest
[2019-06-03T05:53:32.284Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
[2019-06-03T05:53:32.284Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:116)
[2019-06-03T05:53:32.284Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:372)
[2019-06-03T05:53:32.284Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:348)
[2019-06-03T05:53:32.284Z] [ERROR] 	... 4 more
[2019-06-03T05:53:32.284Z] [ERROR] -> [Help 1]
[2019-06-03T05:53:32.284Z] [ERROR] 
[2019-06-03T05:53:32.284Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2019-06-03T05:53:32.284Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2019-06-03T05:53:32.284Z] [ERROR] 
[2019-06-03T05:53:32.284Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2019-06-03T05:53:32.284Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Unfortunately I had no access to the log.

**Comment by Zelldon** [comment]
I think this was related to the race condition and bug in the service container, see https://github.com/zeebe-io/zeebe/issues/2741
