### ISSUE TITLE
Closing of AsyncDirector and StreamProcessor seems not to work as expected

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2590]
This is easy to reproduce just run `RejectIncompleteCommandsTest`, then you see the following exception:

```
07:26:19.035 [exporter] [0.0.0.0:25602-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter'.
07:26:19.036 [zb-stream-processor-snapshot-director] [0.0.0.0:25602-zb-fs-workers-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
	at io.zeebe.engine.processor.StreamProcessor.getLastWrittenPositionAsync(StreamProcessor.java:279) ~[classes/:?]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$5(AsyncSnapshotDirector.java:222) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:147) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
```

I assume the tests are to fast and close during start up.

**Comment by Zelldon** [comment]
closed by https://github.com/zeebe-io/zeebe/pull/2748
