### ISSUE TITLE
Broker does not close dependencies in correct order

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2637]
With https://github.com/zeebe-io/zeebe/pull/2605 we wanted to fix a problem with the closing order. The problem was that the async director access a service which was not yet completely installed. 

I investigated this issue a bit further and it seems that on closing we also have the problem that the Partition (+StateSnapshotController) and Logblockindex is closed before the StreamProcessor, which is problematic. To reproduce this issue just run RejectIncompleteCommandsTest.

It seems that somehow the dependencies are not correctly handled? Please have a look at branch https://github.com/zeebe-io/zeebe/tree/2590-alternative-fix

**Be aware** That I added already a open and close future in the stream processor, which maybe causes this currently IDK.

I think this issue is not so urgent since this only happens if we close the broker during start up (when the stream processor is not completely opened).

**Comment by Zelldon** [comment]
```java

====
Broker startup time: 8188
====

10:57:55.982 [service-controller] [0.0.0.0:25602-zb-actors-1] ERROR io.zeebe.logstreams - start stream processor
10:57:55.982 [service-controller] [0.0.0.0:25602-zb-actors-1] ERROR io.zeebe.logstreams - OpenAsync
10:57:55.985 [zb-stream-processor] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.logstreams - Recovering state of partition 1 from snapshot
10:57:56.002 [topology] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition 1 on Node{nodeId=0, commandApi=0.0.0.0:25602} with state LEADER
10:57:56.016 [] [atomix-cluster-events] DEBUG io.zeebe.gateway - Got membership event BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, addresses={command=0.0.0.0:25602}, partitionRoles={1=true}}
10:57:56.016 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Member 0 received event ClusterMembershipEvent{type=METADATA_CHANGED, subject=Member{id=0, address=0.0.0.0:25603, properties={brokerInfo={"nodeId":0,"partitionsCount":1,"clusterSize":1,"replicationFactor":1,"addresses":{"command":"0.0.0.0:25602"},"partitionRoles":{"1":true}}}}, time=1560761876015}
10:57:56.018 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.gateway - Received membership event: ClusterMembershipEvent{type=METADATA_CHANGED, subject=Member{id=0, address=0.0.0.0:25603, properties={brokerInfo={"nodeId":0,"partitionsCount":1,"clusterSize":1,"replicationFactor":1,"addresses":{"command":"0.0.0.0:25602"},"partitionRoles":{"1":true}}}}, time=1560761876015}
10:57:56.033 [exporter] [0.0.0.0:25602-zb-fs-workers-0] INFO  io.zeebe.broker.exporter - Recovering exporter 'exporter' from snapshot
10:57:56.117 [exporter] [0.0.0.0:25602-zb-fs-workers-0] INFO  io.zeebe.broker.exporter - Recovered exporter 'exporter' from snapshot at lastExportedPosition -1
10:57:56.145 [exporter] [0.0.0.0:25602-zb-fs-workers-0] INFO  io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={NULL_VAL=true, COMMAND=true, EVENT=true, SBE_UNKNOWN=true, COMMAND_REJECTION=true}, acceptValueTypes={JOB_BATCH=true, DEPLOYMENT=true, WORKFLOW_INSTANCE_CREATION=true, NOOP=true, VARIABLE_DOCUMENT=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, ERROR=true, SBE_UNKNOWN=true, NULL_VAL=true, JOB=true, WORKFLOW_INSTANCE=true, VARIABLE=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, TIMER=true, MESSAGE_SUBSCRIPTION=true, EXPORTER=true, INCIDENT=true, MESSAGE=true}}
10:57:56.190 [zb-stream-processor] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
10:57:56.213 [] [main] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:25602' on transport 'gateway'
10:57:56.272 [commandApi.server-receiver] [0.0.0.0:25602-zb-actors-0] ERROR io.zeebe.broker.transport - Failed to deserialize message of type MESSAGE in client API
java.lang.RuntimeException: Could not deserialize object. Deserialization stuck at offset 40 of length 40
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:43) ~[classes/:?]
	at io.zeebe.broker.transport.commandapi.CommandApiMessageHandler.handleExecuteCommandRequest(CommandApiMessageHandler.java:127) ~[classes/:?]
	at io.zeebe.broker.transport.commandapi.CommandApiMessageHandler.onRequest(CommandApiMessageHandler.java:193) ~[classes/:?]
	at io.zeebe.transport.impl.ServerReceiveHandler.onFragment(ServerReceiveHandler.java:73) ~[classes/:?]
	at io.zeebe.transport.impl.TransportChannel.handleMessage(TransportChannel.java:153) ~[classes/:?]
	at io.zeebe.transport.impl.TransportChannel.receive(TransportChannel.java:129) ~[classes/:?]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.processKey(ReadTransportPoller.java:110) ~[classes/:?]
	at org.agrona.nio.NioSelectedKeySet.forEach(NioSelectedKeySet.java:141) ~[agrona-1.0.2.jar:1.0.2]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.processKeys(ReadTransportPoller.java:102) ~[classes/:?]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.pollBlockingEnded(ReadTransportPoller.java:58) ~[classes/:?]
	at io.zeebe.util.sched.RunnableAdapter.lambda$wrapConsumer$2(RunnableAdapter.java:61) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
Caused by: java.lang.RuntimeException: Property 'name' has no valid value
	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:128) ~[classes/:?]
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:39) ~[classes/:?]
	... 16 more
10:57:56.325 [commandApi.server-receiver] [0.0.0.0:25602-zb-actors-0] ERROR io.zeebe.broker.transport - Failed to deserialize message of type MESSAGE in client API
java.lang.RuntimeException: Could not deserialize object. Deserialization stuck at offset 35 of length 35
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:43) ~[classes/:?]
	at io.zeebe.broker.transport.commandapi.CommandApiMessageHandler.handleExecuteCommandRequest(CommandApiMessageHandler.java:127) ~[classes/:?]
	at io.zeebe.broker.transport.commandapi.CommandApiMessageHandler.onRequest(CommandApiMessageHandler.java:193) ~[classes/:?]
	at io.zeebe.transport.impl.ServerReceiveHandler.onFragment(ServerReceiveHandler.java:73) ~[classes/:?]
	at io.zeebe.transport.impl.TransportChannel.handleMessage(TransportChannel.java:153) ~[classes/:?]
	at io.zeebe.transport.impl.TransportChannel.receive(TransportChannel.java:129) ~[classes/:?]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.processKey(ReadTransportPoller.java:110) ~[classes/:?]
	at org.agrona.nio.NioSelectedKeySet.forEach(NioSelectedKeySet.java:141) ~[agrona-1.0.2.jar:1.0.2]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.processKeys(ReadTransportPoller.java:102) ~[classes/:?]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.pollBlockingEnded(ReadTransportPoller.java:58) ~[classes/:?]
	at io.zeebe.util.sched.RunnableAdapter.lambda$wrapConsumer$2(RunnableAdapter.java:61) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
Caused by: java.lang.RuntimeException: Property 'correlationKey' has no valid value
	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:128) ~[classes/:?]
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:39) ~[classes/:?]
	... 16 more
10:57:56.332 [commandApi.server-receiver] [0.0.0.0:25602-zb-actors-0] ERROR io.zeebe.broker.transport - Failed to deserialize message of type MESSAGE in client API
java.lang.RuntimeException: Could not deserialize object. Deserialization stuck at offset 46 of length 46
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:43) ~[classes/:?]
	at io.zeebe.broker.transport.commandapi.CommandApiMessageHandler.handleExecuteCommandRequest(CommandApiMessageHandler.java:127) ~[classes/:?]
	at io.zeebe.broker.transport.commandapi.CommandApiMessageHandler.onRequest(CommandApiMessageHandler.java:193) ~[classes/:?]
	at io.zeebe.transport.impl.ServerReceiveHandler.onFragment(ServerReceiveHandler.java:73) ~[classes/:?]
	at io.zeebe.transport.impl.TransportChannel.handleMessage(TransportChannel.java:153) ~[classes/:?]
	at io.zeebe.transport.impl.TransportChannel.receive(TransportChannel.java:129) ~[classes/:?]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.processKey(ReadTransportPoller.java:110) ~[classes/:?]
	at org.agrona.nio.NioSelectedKeySet.forEach(NioSelectedKeySet.java:141) ~[agrona-1.0.2.jar:1.0.2]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.processKeys(ReadTransportPoller.java:102) ~[classes/:?]
	at io.zeebe.transport.impl.selector.ReadTransportPoller.pollBlockingEnded(ReadTransportPoller.java:58) ~[classes/:?]
	at io.zeebe.util.sched.RunnableAdapter.lambda$wrapConsumer$2(RunnableAdapter.java:61) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
Caused by: java.lang.RuntimeException: Property 'timeToLive' has no valid value
	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:128) ~[classes/:?]
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:39) ~[classes/:?]
	... 16 more
10:57:56.376 [] [main] INFO  io.zeebe.broker.test - Test execution time: 504
10:57:56.377 [] [main] INFO  io.zeebe.broker.system - Closing...
10:57:56.381 [exporter] [0.0.0.0:25602-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter'.
10:57:56.393 [] [zb-blocking-task-runner-3-0.0.0.0:25602] DEBUG io.zeebe.gateway - Closing gateway broker client ...
10:57:56.430 [] [zb-blocking-task-runner-3-0.0.0.0:25602] DEBUG io.zeebe.gateway - topology manager closed
10:57:56.430 [service-controller] [0.0.0.0:25602-zb-actors-0] ERROR io.zeebe.broker.clustering - Stop partition
10:57:56.431 [service-controller] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
10:57:56.462 [service-controller] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/13b1c650-ff23-426c-96d0-f70d02460e24/data/partition-1/state/1_zb-stream-processor/runtime'.
10:57:56.464 [] [zb-blocking-task-runner-3-0.0.0.0:25602] DEBUG io.zeebe.gateway - transport closed
10:57:56.465 [] [zb-blocking-task-runner-3-0.0.0.0:25602] DEBUG io.zeebe.gateway - data frame receive buffer closed
10:57:56.465 [] [zb-blocking-task-runner-3-0.0.0.0:25602] DEBUG io.zeebe.gateway - Gateway broker client closed.
10:57:56.503 [zb-stream-processor] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.processor - Start scanning the log for error events.
10:57:56.503 [zb-stream-processor] [0.0.0.0:25602-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.AssertionError: null
	at org.rocksdb.Transaction.rollback(Transaction.java:215) ~[rocksdbjni-6.0.1.jar:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.rollbackInternal(ZeebeTransaction.java:107) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:174) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:143) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:266) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:117) ~[classes/:?]
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.lookupBlockPosition(LogBlockIndex.java:114) ~[classes/:?]
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.lookupBlockAddress(LogBlockIndex.java:88) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.lookUpBlockAddressForPosition(BufferedLogStreamReader.java:341) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:126) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seekToFirstEvent(BufferedLogStreamReader.java:141) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:194) ~[classes/:?]
	at io.zeebe.engine.processor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:173) ~[classes/:?]
	at io.zeebe.engine.processor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:154) ~[classes/:?]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:165) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
10:57:56.515 [service-controller] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/13b1c650-ff23-426c-96d0-f70d02460e24/data/partition-1/index/runtime'.
10:57:56.518 [zb-stream-processor] [0.0.0.0:25602-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.AssertionError: null
	at org.rocksdb.Transaction.rollback(Transaction.java:215) ~[rocksdbjni-6.0.1.jar:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.rollbackInternal(ZeebeTransaction.java:107) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:174) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:143) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.foreach(ZeebeTransactionDb.java:246) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.foreach(ZeebeTransactionDb.java:232) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEach(TransactionalColumnFamily.java:99) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEach(TransactionalColumnFamily.java:95) ~[classes/:?]
	at io.zeebe.engine.state.deployment.DeploymentsState.foreachPending(DeploymentsState.java:73) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.deployment.distribute.DeploymentDistributeProcessor.reprocessPendingDeployments(DeploymentDistributeProcessor.java:67) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
10:57:56.548 [] [raft-partition-group-system-0] INFO  io.atomix.core.impl.CorePrimitivesService - Stopped
10:57:56.579 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to INACTIVE

```
