### ISSUE TITLE
Cannot create workers on OpenLiberty due to RejectedExecutionException

### ISSUE THREAD

**Issue by lostiniceland** [zeebe-io/zeebe#2719]
Creating a worker instance in OpenLiberty 19.0.0.5 fails with the following exception

```
[err] [grpc-default-executor-0] WARN io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type test
[err] io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
[err] 	at io.grpc.Status.asRuntimeException(Status.java:533)
[err] 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
[err] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
[err] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[err] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[err] 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
[err] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
[err] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[err] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[err] 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
[err] 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
[err] 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
[err] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
[err] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
[err] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:575)
[err] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[err] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[err] 	at java.base/java.lang.Thread.run(Thread.java:835)
[err] Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@575a4f1e[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4e8f82fa[Wrapped task = io.zeebe.client.impl.subscription.JobRunnableFactory$$Lambda$358/0x0000000801cadc40@2c28f6ce]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@19e743aa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
[err] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
[err] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
[err] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705)
[err] 	at io.zeebe.client.impl.subscription.JobWorkerImpl.submitJob(JobWorkerImpl.java:121)
[err] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[err] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[err] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
[err] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[err] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[err] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[err] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[err] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[err] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[err] 	at io.zeebe.client.impl.subscription.JobPoller.onNext(JobPoller.java:77)
[err] 	at io.zeebe.client.impl.subscription.JobPoller.onNext(JobPoller.java:29)
[err] 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:429)
[err] 	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
[err] 	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
[err] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:563)
[err] 	... 5 more
```

Code causing this
```
@ApplicationScoped
public class ZeebeStartup {

	@Inject
	ZeebeClientBuilder clientBuilder;

	@Inject
	SomeService someService;

	private List<JobWorker> registeredWorkers = new ArrayList<>(4);

	@Dependent
	@Produces
	ZeebeClientBuilder produceZeebeClientBuilder(){
		final String broker = "localhost:26500";
		return ZeebeClient.newClientBuilder().brokerContactPoint(broker);
	}

	public void init(@Observes @Initialized(ApplicationScoped.class) Object init) {
		try (ZeebeClient client = clientBuilder.build()) {
			// FIXME only deploy when not already deployed
			DeploymentEvent deploymentEvent = client.newDeployCommand()
					.addResourceFromClasspath("test.bpmn")
					.send().join(20, TimeUnit.SECONDS);
			System.out.println("Deployment created with key: " + deploymentEvent.getKey());
			registeredWorkers.add(client.newWorker().jobType("test").handler(new ZeebeStartup.Test()).timeout(Duration.ofSeconds(10)).open());
		} catch (Exception e){
			e.printStackTrace();
		}
	}

	public void destroy(@Observes @Destroyed(ApplicationScoped.class) Object init) {
		registeredWorkers.forEach(JobWorker::close);
	}

	private final class Test implements JobHandler {

		@Override
		public void handle(JobClient client, ActivatedJob job) {
			someService.do()
			client.newCompleteCommand(job.getKey());
		}
	}
}
```

**Comment by Zelldon** [comment]
Hey @lostiniceland,

thanks for trying out Zeebe.
I think the problem is that you're using try-with-resource, which closes the ZeebeClient directly after you opened the worker. Closing the ZeebeClient means that it will closes all other resources as well like open workers for example.

I don't know how OpenLiberty works, but you need to make sure that you keep the client and worker open as long you want to handle jobs with your worker

Hope that helps.

Greets
Chris.

**Comment by lostiniceland** [comment]
I was just following the getting started guide (https://docs.zeebe.io/java-client-examples/job-worker-open.html), and expected the returned worker to keep the connection. Maybe you could update the documentation about this.

I will update my sample later today and see if it solves the issue.

**Comment by lostiniceland** [comment]
Yes, keeping the client open solves the issue. Please update the docs
