### ISSUE TITLE
Actor failed in phase 'STARTED'

### ISSUE THREAD

**Issue by michalmoravek** [zeebe-io/zeebe#2747]
The first run of broker produce this error. Zeebe installed on Windows 10 Pro system.

```08:12:57.703 [] [main] INFO  io.zeebe.util.config - Reading configuration for class class io.zeebe.broker.system.configuration.BrokerCfg from file c:\apps\zeebe-broker-0.18.0\conf\zeebe.cfg.toml
08:12:58.029 [] [main] INFO  io.zeebe.broker.system - Scheduler configuration: Threads{cpu-bound: 2, io-bound: 2}.
08:12:58.114 [] [main] INFO  io.zeebe.broker.system - Version: 0.18.0
08:12:58.120 [] [main] INFO  io.zeebe.broker.system - Starting broker with configuration {
  "network": {
    "host": "0.0.0.0",
    "portOffset": 0,
    "commandApi": {
      "host": "0.0.0.0",
      "port": 26501,
      "sendBufferSize": "16M"
    },
    "internalApi": {
      "host": "0.0.0.0",
      "port": 26502,
      "sendBufferSize": "16M"
    }
  },
  "cluster": {
    "initialContactPoints": [],
    "partitionIds": [
      1
    ],
    "nodeId": 0,
    "partitionsCount": 1,
    "replicationFactor": 1,
    "clusterSize": 1,
    "clusterName": "zeebe-cluster"
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "metrics": {
    "reportingInterval": "5s",
    "file": "c:\\apps\\zeebe-broker-0.18.0\\metrics\\zeebe.prom",
    "enableHttpServer": false,
    "host": "0.0.0.0",
    "port": 9600
  },
  "data": {
    "directories": [
      "c:\\apps\\zeebe-broker-0.18.0\\data"
    ],
    "logSegmentSize": "512M",
    "indexBlockSize": "4M",
    "snapshotPeriod": "15m",
    "snapshotReplicationPeriod": "5m",
    "maxSnapshots": 1
  },
  "exporters": [],
  "gateway": {
    "enable": true,
    "network": {
      "host": "0.0.0.0",
      "port": 26500
    },
    "cluster": {
      "contactPoint": "0.0.0.0:26502",
      "transportBuffer": "128M",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 26502
    },
    "threads": {
      "managementThreads": 1
    }
  }
}
08:13:00.095 [service-controller] [0.0.0.0:26501-zb-actors-1] INFO  io.zeebe.transport - Bound commandApi.server to /0.0.0.0:26501
08:13:00.917 [] [zb-blocking-task-runner-3-0.0.0.0:26501] INFO  io.zeebe.gateway - Version: 0.18.0
08:13:00.926 [] [zb-blocking-task-runner-3-0.0.0.0:26501] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "enable": true,
  "network": {
    "host": "0.0.0.0",
    "port": 26500
  },
  "cluster": {
    "contactPoint": "0.0.0.0:26502",
    "transportBuffer": "128M",
    "requestTimeout": "15s",
    "clusterName": "zeebe-cluster",
    "memberId": "gateway",
    "host": "0.0.0.0",
    "port": 26502
  },
  "threads": {
    "managementThreads": 1
  }
}
08:13:01.414 [service-controller] [0.0.0.0:26501-zb-actors-1] INFO  io.atomix.core.Atomix - 3.2.0-alpha1 (revision 44a5f9 built on 2019-06-06 16:37:07)

08:13:02.566 [] [netty-messaging-event-nio-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:26502
08:13:02.592 [] [netty-messaging-event-nio-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
08:13:02.655 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:26502
08:13:02.657 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
08:13:02.663 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member activated: Member{id=0, address=0.0.0.0:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":1,"clusterSize":1,"replicationFactor":1,"addresses":{"command":"0.0.0.0:26501"},"partitionRoles":{}}}}
08:13:02.674 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
08:13:02.679 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
08:13:02.682 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
08:13:02.686 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
08:13:02.716 [] [atomix-0] INFO  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Started
08:13:02.751 [] [atomix-0] INFO  io.atomix.primitive.partition.impl.HashBasedPrimaryElectionService - Started
08:13:02.775 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [0.0.0.0:26501-zb-actors-0] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:26501' on transport 'gateway-broker-client'
08:13:02.832 [] [atomix-0] INFO  io.atomix.protocols.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=system}
08:13:03.009 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to FOLLOWER
08:13:03.022 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to CANDIDATE
08:13:03.023 [] [raft-server-system-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.protocols.raft.roles.FollowerRole$$Lambda$302/368185691@1db9eed9 not registered
08:13:03.035 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Transitioning to LEADER
08:13:03.050 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{system-partition-1} - Found leader 0
08:13:03.115 [] [raft-server-system-partition-1] INFO  io.atomix.protocols.raft.partition.RaftPartitionGroup - Started
08:13:03.328 [] [raft-partition-group-system-1] INFO  io.atomix.protocols.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-atomix}
08:13:03.391 [] [raft-server-raft-atomix-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-atomix-partition-1} - Transitioning to FOLLOWER
08:13:03.392 [] [raft-server-raft-atomix-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-atomix-partition-1} - Transitioning to CANDIDATE
08:13:03.396 [] [raft-server-raft-atomix-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.protocols.raft.roles.FollowerRole$$Lambda$302/368185691@20bfc1e7 not registered
08:13:03.409 [] [raft-server-raft-atomix-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-atomix-partition-1} - Transitioning to LEADER
08:13:03.411 [] [raft-server-raft-atomix-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-atomix-partition-1} - Found leader 0
08:13:03.424 [] [raft-partition-group-raft-atomix-0] INFO  io.atomix.protocols.raft.partition.RaftPartitionGroup - Started
08:13:03.426 [] [raft-partition-group-raft-atomix-0] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Started
08:13:03.666 [] [raft-partition-group-system-15] INFO  io.atomix.core.impl.CoreTransactionService - Started
08:13:03.668 [] [raft-partition-group-system-15] INFO  io.atomix.core.impl.CorePrimitivesService - Started
08:13:03.697 [service-controller] [0.0.0.0:26501-zb-actors-1] INFO  io.zeebe.broker.clustering - Creating leader election for partition 1 in node 0
08:13:03.714 [] [raft-server-raft-atomix-partition-1-state] INFO  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Configuring distributed-log on node 0 with logName raft-atomix-partition-1
08:13:05.151 [service-controller] [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.UnsatisfiedLinkError: C:\Users\morav\AppData\Local\Temp\librocksdbjni8060841947975998070.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_211]
        at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_211]
        at java.lang.System.load(Unknown Source) ~[?:1.8.0_211]
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78) ~[rocksdbjni-6.0.1.jar:?]
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56) ~[rocksdbjni-6.0.1.jar:?]
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:63) ~[rocksdbjni-6.0.1.jar:?]
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:34) ~[rocksdbjni-6.0.1.jar:?]
        at io.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.<clinit>(ZeebeRocksDbFactory.java:36) ~[zeebe-db-0.18.0.jar:0.18.0]
        at io.zeebe.logstreams.impl.service.LogBlockIndexService.start(LogBlockIndexService.java:44) ~[zeebe-logstreams-0.18.0.jar:0.18.0]
        at io.zeebe.servicecontainer.impl.ServiceController$AwaitDependenciesStartedState.onDependenciesAvailable(ServiceController.java:182) ~[zeebe-service-container-0.18.0.jar:0.18.0]
        at io.zeebe.servicecontainer.impl.ServiceController$AwaitDependenciesStartedState.accept(ServiceController.java:135) ~[zeebe-service-container-0.18.0.jar:0.18.0]
        at io.zeebe.servicecontainer.impl.ServiceController$AwaitDependenciesStartedState.accept(ServiceController.java:129) ~[zeebe-service-container-0.18.0.jar:0.18.0]
        at io.zeebe.servicecontainer.impl.ServiceController.onServiceEvent(ServiceController.java:119) ~[zeebe-service-container-0.18.0.jar:0.18.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zeebe-util-0.18.0.jar:0.18.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.18.0.jar:0.18.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.18.0.jar:0.18.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.18.0.jar:0.18.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.18.0.jar:0.18.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.18.0.jar:0.18.0]```

**Comment by menski** [comment]
Seems to be an open issue on RockDB https://github.com/facebook/rocksdb/issues/5177

**Comment by 862618936** [comment]
I have the same situation. Have you solved this problem?

**Comment by Zelldon** [comment]
Due to inactivity I will close this. Feel free to reopen it if this issue still exist.
