### ISSUE TITLE
Nullpointer on installing RAFT snapshot

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2766]
On restarting nodes I saw in the logs the following error:

```
12:30:35.013 [] [raft-server-raft-atomix-partition-4-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-4} - Failed to install snapshot for service distributed-log
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_212]
        at io.atomix.primitive.impl.DefaultPrimitiveTypeRegistry.getPrimitiveType(DefaultPrimitiveTypeRegistry.java:43) ~[atomix-primitive-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.service.RaftServiceContext.installSnapshot(RaftServiceContext.java:241) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.installService(RaftServiceManager.java:540) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:504) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:422) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
12:30:35.022 [] [raft-server-raft-atomix-partition-4-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-4} - Expected to read snapshot, but caught a non recoverable error; blocking thread to avoid applying further entries and creating inconsistencies
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_212]
        at io.atomix.primitive.impl.DefaultPrimitiveTypeRegistry.getPrimitiveType(DefaultPrimitiveTypeRegistry.java:43) ~[atomix-primitive-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.service.RaftServiceContext.installSnapshot(RaftServiceContext.java:241) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.installService(RaftServiceManager.java:540) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:504) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:422) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by npepinpe** [comment]
When restoring a snapshot for a service, Atomix reads the type name and tries to resolve the type from it. Here, the type name was `null`, so when it tried to get its hash code it exploded.

The type is null if when reading the name `readString` returns null; Atomix encodes null strings in its buffers by encoding all strings as: boolean - length - data, where the boolean is a single byte to denote whether or not the string is null. If it's false, then length and data are omitted, and it doesn't read further. In our case this is what happened. So either we had a corrupted snapshot (i.e. the data is not what we expected) or we wrote a null string when we wrote the snapshot.

When writing a service snapshot, it first writes metadata, then the snapshot data:

```java
private void snapshotService(SnapshotWriter writer, RaftServiceContext service) {
    writer.writeLong(service.serviceId().id());
    writer.writeString(service.serviceType().name());
    writer.writeString(service.serviceName());
    byte[] config = Serializer.using(service.serviceType().namespace()).encode(service.serviceConfig());
    writer.writeInt(config.length).writeBytes(config);
    try {
      service.takeSnapshot(writer);
    } catch (Exception e) {
      logger.error("Failed to take snapshot of service {}", service.serviceId(), e);
    }
  }
```

`service.serviceType()` is pretty much guaranteed not to be null, as when constructing the service context it checks if it is null and fails if it is, and it is a final field (called `primitiveType`, because idk). And our type returns a literal string on `name()`. So it seems unlikely we wrote null when we wrote the snapshot, and more the snapshot had unexpected data.

**Comment by npepinpe** [comment]
I added checksums to snapshots, and managed to prove that sometimes we write the wrong thing and the checksums don't match. However, weirdly enough, we do get the correct bytes from the server: the checksum of the request's bytes matches the expected snapshot checksum, but when we write the snapshot to disk we end up with a different checksum...except not always! If the checksums don't match, it now fails the install request, and tries again...and it works! Fun... :hankey: !

While I'd like to continue figuring out why we write the wrong snapshot, I think checksums should anyway probably be implemented as a separate issue.

**Comment by npepinpe** [comment]
Moving work to [zeebe-io/atomix#20](https://github.com/zeebe-io/atomix/issues/20)

**Comment by npepinpe** [comment]
Closed by https://github.com/zeebe-io/atomix/pull/21
