### ISSUE TITLE
NPE in DeploymentDistributorImpl when restarting nodes

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2793]
I got the following error while testing something else; with our standard benchmark setup, I killed the leader of 5 partitions (possibly unrelated, but that's how it happened this time anyway). The following error popped up:

```
14:03:33.949 [stream-processor] [zeebe-2.zeebe.npepinpe.svc.cluster.local:26501-zb-actors-4] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.handlePushResponse(DeploymentDistributorImpl.java:290) ~[zeebe-broker-core-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.handleResponse(DeploymentDistributorImpl.java:243) ~[zeebe-broker-core-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.lambda$null$4(DeploymentDistributorImpl.java:228) ~[zeebe-broker-core-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:74) ~[zeebe-util-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:51) [zeebe-util-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:177) [zeebe-util-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:142) [zeebe-util-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:126) [zeebe-util-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:104) [zeebe-util-0.20.0-SNAPSHOT.jar:0.20.0-SNAPSHOT]
```

That was in the node I killed, right before it closed.

**Comment by Zelldon** [comment]
Duplicate of #2781

**Comment by npepinpe** [comment]
Closing in favor of #2781
