### ISSUE TITLE
Null pointer exception in atomix after restarting with existing data

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2835]
We saw this in a operate benchmark

```
08:04:03.407 [] [raft-server-raft-atomix-partition-1-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-1} - Expected to read snapshot, but caught a non recoverable error; blocking thread to avoid applying further entries and creating inconsistencies
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_212]
        at io.atomix.primitive.impl.DefaultPrimitiveTypeRegistry.getPrimitiveType(DefaultPrimitiveTypeRegistry.java:43) ~[atomix-primitive-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.service.RaftServiceContext.installSnapshot(RaftServiceContext.java:241) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.installService(RaftServiceManager.java:540) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:504) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:422) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by npepinpe** [comment]
That's fixed with the latest Atomix released, see #2766
