### ISSUE TITLE
Error when deploying process exceeding 65534 bytes in size

### ISSUE THREAD

**Issue by iamtakingiteasy** [zeebe-io/zeebe#2851]
**Describe the bug**
Deploying a process file that exceeds 65534 bytes in size is meeting limitation on SBE side.

**To Reproduce**
Make an XML of any valid process that exceeds 65534 bytes in size and attempt to deploy it to zeebe either via simple-exporter app, or gRPC API.

No code is required, only size matters and example process may be generated with simple shellscript producing 64KiB long comment in basic process:

```sh
#!/bin/sh

cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_0j0uq4u" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="3.0.0-dev">
  <bpmn:process id="Process_1yj0j7l" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
<!--
$(yes | tr -d '\n' | head -c 65536 | sed 's/.\{1024\}/&\n/g')
-->
</bpmn:definitions>
EOF
```

**Expected behavior**
Actual deployment to succeed

**Log/Stacktrace**
```
java.lang.IllegalStateException: length > maxValue for type: 68461
	at io.zeebe.protocol.record.ExecuteCommandRequestEncoder.putValue(ExecuteCommandRequestEncoder.java:333) ~[zeebe-protocol-0.19.0.jar:0.19.0]
	at io.zeebe.protocol.impl.encoding.ExecuteCommandRequest.write(ExecuteCommandRequest.java:169) ~[zeebe-protocol-impl-0.19.0.jar:0.19.0]
	at io.zeebe.gateway.impl.broker.request.BrokerExecuteCommand.write(BrokerExecuteCommand.java:87) ~[zeebe-gateway-0.19.0.jar:0.19.0]
	at io.zeebe.transport.impl.sender.TransportHeaderWriter.wrapRequest(TransportHeaderWriter.java:74) ~[zeebe-transport-0.19.0.jar:0.19.0]
	at io.zeebe.transport.impl.ClientOutputImpl.sendRequestWithRetry(ClientOutputImpl.java:122) ~[zeebe-transport-0.19.0.jar:0.19.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:157) ~[zeebe-gateway-0.19.0.jar:0.19.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$4(BrokerRequestManager.java:149) ~[zeebe-gateway-0.19.0.jar:0.19.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:85) ~[zeebe-util-0.19.0.jar:0.19.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:51) [zeebe-util-0.19.0.jar:0.19.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:177) [zeebe-util-0.19.0.jar:0.19.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:142) [zeebe-util-0.19.0.jar:0.19.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:126) [zeebe-util-0.19.0.jar:0.19.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:104) [zeebe-util-0.19.0.jar:0.19.0]
17:04:04.659 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [10.52.1.168:26501-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
```

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.19.0 from docker, as well as master builds
 - Configuration: hazelcast-exporter, latest simple-exporter app, single-node zeebe deployment

**Comment by npepinpe** [comment]
Hi @iamtakingiteasy, thanks for opening the issue.

This is a known limitation in our system at the moment; we use SBE to (de)serialize the records we write to our event log, so any command is limited to a little less than 64Kb. So far it was never an issue,  but we are always open to revise our assumptions.

Is this something that is blocking you? Would it be possible for you to share the actual workflows you're trying to deploy, so we have some idea of what kind of workflows are over 64Kb in size?

Thanks!

**Comment by iamtakingiteasy** [comment]
Currently i have work-arounded the issue by stripping whitespace from my actual workflow and i still have margin of removing visual elements and shortening ids, but process can be minified only so much.

Current unminified version: https://static.eientei.org/data/property-offer.bpmn

Note: `$.body` syntax is what my json deserializer uses to merge header values with input fields on resulting structure.

Probably, splitting it in few smaller processes would help too and in this specific case might even be viable, but I doubt it always would be so.

**Comment by npepinpe** [comment]
This seems to me like a legitimate use case. As you mentioned, there are workarounds applicable (splitting into smaller processes and using message correlation to coordinate them), but they are just that, workarounds. I think increasing the size makes sense, and we should discuss if it makes sense to have size limits at all.

Thanks for reporting this!

**Comment by iamtakingiteasy** [comment]
A bit of sidenote: API for deploying workflows then might benefit from using gRPC streams.
