### ISSUE TITLE
Broker keeps throwing exception when deploying a large BPMN file

### ISSUE THREAD

**Issue by echou** [zeebe-io/zeebe#2917]
**Describe the bug**

When I deploy a 60KB BPMN file, the broker keeps logging IllegalStateException very rapidly.

**To Reproduce**
Deploy a large BPMN file (base64 encoded > 64KB)

If possible add a minimal reproducer code sample
 - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java

**Expected behavior**

**Log/Stacktrace**

15:16:43.026 [stream-processor] [10.123.96.200:26501-zb-actors-0] ERROR io.zeebe.processor - Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=DISTRIBUTE, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=DEPLOYMENT, rejectionType=NULL_VAL, rejectionReason=}, value={  .... }
java.lang.IllegalStateException: length > maxValue for type: 75830
	at io.zeebe.protocol.record.RecordMetadataEncoder.putRejectionReason(RecordMetadataEncoder.java:469) ~[zeebe-protocol-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.protocol.impl.record.RecordMetadata.write(RecordMetadata.java:110) ~[zeebe-protocol-impl-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.copyExistingEventToBuffer(LogStreamBatchWriterImpl.java:179) ~[zeebe-logstreams-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.done(LogStreamBatchWriterImpl.java:151) ~[zeebe-logstreams-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:94) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedStreamWriterImpl.appendRejection(TypedStreamWriterImpl.java:29) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.writeRejectionOnCommand(ProcessingStateMachine.java:312) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$errorHandlingInTransaction$4(ProcessingStateMachine.java:296) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:69) ~[zeebe-db-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.errorHandlingInTransaction(ProcessingStateMachine.java:291) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$onError$3(ProcessingStateMachine.java:279) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:27) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:128) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:108) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:92) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:196) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.21.0-SNAPSHOT (from docker camunda/zeebe:SNAPSHOT)
 - Configuration: [e.g. exporters etc.]

[cluster]
nodeId = 0
replicationFactor = 2
partitionsCount = 2
clusterSize = 2
clusterName = "zeebe-cluster-0"

[data]
directories = [ "data" ]
snapshotPeriod = "15m"
maxSnapshots = "3"

[[exporters]]
id = "elasticsearch"
className = "io.zeebe.exporter.ElasticsearchExporter"
  [exporters.args]
  url = "..."
  [exporters.args.bulk]
  delay = 5
  size = 1000
  [exporters.args.index]
  prefix = "zeebe-record-0"
  createTemplate = true
  command = false
  event = true
  rejection = false
  deployment = true
  error = true
  incident = true
  job = true
  jobBatch = false
  message = true
  messageSubscription = true
  variable = true
  variableDocument = false
  workflowInstance = true
  workflowInstanceCreation = false
  workflowInstanceSubscription = true

**Comment by echou** [comment]
this issue is not the same as #2851. In my case, the error is thrown repeatedly and the logfile grows very fast.  It seems to be related to cluster sync (intent = "DISTRIBUTE")?

**Comment by npepinpe** [comment]
Distribution is retried until it succeeds, so that explains why it keeps happening. In this case the issue is that we try to dump the whole record when writing the rejection reason, but that record is already close to the max size, so it's too large for the field anyway.

But this means the initial DEPLOY command was successfully written, so my guess is that workflow is extremely close to the max record size, and when in DISTRIBUTE it tips over and passes it. I could be wrong though, @Zelldon ?

**Comment by Zelldon** [comment]
Not sure here. There has been an error before that, as you can see in the stacktrace we are currently in the `onError` state. Which then tries to write a rejection, which again fails where we then loop endless. 

The best way to reproduce this would be that you share your deployment @echou .
Can you take a look at the logs, which exception was printed as first?

**Comment by echou** [comment]
Indeed the deployment was successful, then the exceptions started. the log rolled so fast. I finally captured the first exception as follows:

11:24:02.913 [stream-processor] [10.123.96.200:26551-zb-actors-0] ERROR io.zeebe.processor - Expected to successfully process event 'LoggedEvent [type=0, version=0, streamId=1, position=4295089632, key=2251799813685250, timestamp=1565148242899, sourceEventPosition=4295028400]' with processor, but caught an exception. Skip this event.
java.lang.IllegalStateException: length > maxValue for type: 84060
	at io.zeebe.clustering.management.PushDeploymentRequestEncoder.putDeployment(PushDeploymentRequestEncoder.java:239) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.system.management.deployment.PushDeploymentRequest.write(PushDeploymentRequest.java:87) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.util.SbeBufferWriterReader.toBytes(SbeBufferWriterReader.java:80) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.pushDeploymentToPartition(DeploymentDistributorImpl.java:182) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.distributeDeploymentToPartitions(DeploymentDistributorImpl.java:173) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.distributeDeployment(DeploymentDistributorImpl.java:152) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.prepareToDistribute(DeploymentDistributorImpl.java:146) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.deployOnMultiplePartitions(DeploymentDistributorImpl.java:125) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.pushDeploymentToPartitions(DeploymentDistributorImpl.java:105) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.pushDeployment(DeploymentDistributorImpl.java:93) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.deployment.distribute.DeploymentDistributeProcessor.distributeDeployment(DeploymentDistributeProcessor.java:81) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.deployment.distribute.DeploymentDistributeProcessor.processRecord(DeploymentDistributeProcessor.java:75) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$processInTransaction$1(ProcessingStateMachine.java:241) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:69) ~[zeebe-db-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:232) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:201) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:175) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:128) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:108) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:92) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:196) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]

the second and rest exceptions are:

11:24:03.029 [stream-processor] [10.123.96.200:26551-zb-actors-0] ERROR io.zeebe.processor - Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=DISTRIBUTE, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=DEPLOYMENT, rejectionType=NULL_VAL, rejectionReason=}, value={... xml body ...} }' without errors, but exception occurred with message 'length > maxValue for type: 84060' .
java.lang.IllegalStateException: length > maxValue for type: 84060
	at io.zeebe.clustering.management.PushDeploymentRequestEncoder.putDeployment(PushDeploymentRequestEncoder.java:239) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.system.management.deployment.PushDeploymentRequest.write(PushDeploymentRequest.java:87) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.util.SbeBufferWriterReader.toBytes(SbeBufferWriterReader.java:80) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.pushDeploymentToPartition(DeploymentDistributorImpl.java:182) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.distributeDeploymentToPartitions(DeploymentDistributorImpl.java:173) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.distributeDeployment(DeploymentDistributorImpl.java:152) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.prepareToDistribute(DeploymentDistributorImpl.java:146) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.deployOnMultiplePartitions(DeploymentDistributorImpl.java:125) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.pushDeploymentToPartitions(DeploymentDistributorImpl.java:105) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.pushDeployment(DeploymentDistributorImpl.java:93) ~[zeebe-broker-core-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.deployment.distribute.DeploymentDistributeProcessor.distributeDeployment(DeploymentDistributeProcessor.java:81) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.deployment.distribute.DeploymentDistributeProcessor.processRecord(DeploymentDistributeProcessor.java:75) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$processInTransaction$1(ProcessingStateMachine.java:241) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:69) ~[zeebe-db-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:232) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:201) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.engine.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:175) ~[zeebe-workflow-engine-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:128) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:108) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:92) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:196) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
