### ISSUE TITLE
Transport failed exception

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2922]
**Describe the bug**
In chaos meeting I saw the following exception in the log: 

```java
Aug 05, 2019 12:20:20 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 16030100c7010000c30303e37ee1f86e6858870b31906b18
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:306)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

**To Reproduce**
I think it is related to use zbctl without `--insecure` flag

**Expected behavior**
A clear and concise exception what went wrong. For me it was not clear.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: develop
 - Configuration: [e.g. exporters etc.]

**Comment by MiguelPires** [comment]
Yes, this happens because the client is sending a request with TLS enabled and the gateway isn't expecting it. However, this isn't a Zeebe exception so I can't do anything about it except hiding it.

**Comment by npepinpe** [comment]
This is logged on the gateway when the client sends a request with TLS enabled?

**Comment by Zelldon** [comment]
> Yes, this happens because the client is sending a request with TLS enabled and the gateway isn't expecting it. However, this isn't a Zeebe exception so I can't do anything about it except hiding it.

If you can hide it then you have access right ? :sweat_smile: So just wrap it with a new Exception with a descriptive message.

**Comment by MiguelPires** [comment]
I meant hide it as in change the log level. The prefix doesn't match our format, it's not logged by us.

**Comment by npepinpe** [comment]
Would it make sense to set the root log level to WARN and only lower it for `io.zeebe`?

**Comment by MiguelPires** [comment]
Netty uses java.util.logging and I think we'd have to do some work to remove this single log. Personally, I think it's better to have it than omitting it completely. In addition, the docs have a security troubleshooting section where the user can see why this happens if he happened to miss the client error which contains a better error message. Is that ok with everyone?

**Comment by npepinpe** [comment]
Personally I don't think it's super important, so as you guys want. I do like the part though that you added in the docs common errors and their meaning/solution :+1:
