### ISSUE TITLE
Stream processor tries to read non existing log entry

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#293]
I saw the following exception multiple times while running a 3 node broker cluster with the NonBlockingTaskCreator and 1.000.000 tasks to create:

```
ava.util.NoSuchElementException: Api protocol violation: No next log entry available; You need to probe with hasNext() first.
	at org.camunda.tngp.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:421)
	at org.camunda.tngp.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:16)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:285)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:272)
	at org.camunda.tngp.util.state.StateMachine.doWork(StateMachine.java:107)
	at org.camunda.tngp.util.state.StateMachineAgent.doWork(StateMachineAgent.java:50)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:138)
	at org.camunda.tngp.util.agent.AgentGroup.doWork(AgentGroup.java:45)
	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:140)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by menski** [comment]
I cannot reproduce this anymore
