### ISSUE TITLE
Workflow instance is not canceled

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2935]
**Describe the bug**
In some cases, it is not possible to cancel a workflow instance. The cancel command is applied but not all instances get terminated. 

The problem is that the flow scope is not terminated because an element instance is not removed from the state and it not removed from the flow scope (i.e. active token count + child count).

**To Reproduce**
This can happen when the termination overlap with an element instance completion. 

1. element: `ELEMENT_COMPLETING` 
2. flow scope: `ELEMENT_TERMINATING` 
3. element: `ELEMENT_COMPLETED` 

The `ELEMENT_COMPLETED` is not applied because the flow scope is not active anymore. The following statement is logged:

```
Skipping record [key: 2251799813685257, intent: ELEMENT_COMPLETED, value: {"bpmnProcessId":"process","version":1,"workflowKey":2251799813685249,"workflowInstanceKey":2251799813685251,"elementId":"task","flowScopeKey":2251799813685256,"bpmnElementType":"SERVICE_TASK"}] due to step guard; in-memory element is ElementInstance{elementRecord=IndexedRecord{key=2251799813685257, state=ELEMENT_COMPLETED, value={"bpmnProcessId":"process","version":1,"workflowKey":2251799813685249,"workflowInstanceKey":2251799813685251,"elementId":"task","flowScopeKey":2251799813685256,"bpmnElementType":"SERVICE_TASK"}}, parentKey=2251799813685256, childCount=0, jobKey=-1, activeTokens=0, multiInstanceLoopCounter=0}
``` 
**Log/Stacktrace**

Discovered by flaky test case:

```[ERROR] shouldCancelJobsOnTermination[parallel multi-instance](io.zeebe.engine.processor.workflow.multiinstance.MultiInstanceActivityTest)  Time elapsed: 5.102 s  <<< ERROR!```

<details><summary>Full Stacktrace</summary>
 <p>

```
[2019-08-06T11:12:06.326Z] [ERROR] shouldCancelJobsOnTermination[parallel multi-instance](io.zeebe.engine.processor.workflow.multiinstance.MultiInstanceActivityTest)  Time elapsed: 5.102 s  <<< ERROR!

[2019-08-06T11:12:06.326Z] io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria

[2019-08-06T11:12:06.326Z] 	at java.util.Optional.orElseThrow(Optional.java:290)

[2019-08-06T11:12:06.326Z] 	at io.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:72)

[2019-08-06T11:12:06.326Z] 	at io.zeebe.engine.util.client.WorkflowInstanceClient$ExistingInstanceClient.lambda$static$0(WorkflowInstanceClient.java:87)

[2019-08-06T11:12:06.326Z] 	at io.zeebe.engine.util.client.WorkflowInstanceClient$ExistingInstanceClient.cancel(WorkflowInstanceClient.java:135)

[2019-08-06T11:12:06.326Z] 	at io.zeebe.engine.processor.workflow.multiinstance.MultiInstanceActivityTest.shouldCancelJobsOnTermination(MultiInstanceActivityTest.java:357)

[2019-08-06T11:12:06.326Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2019-08-06T11:12:06.326Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2019-08-06T11:12:06.326Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-08-06T11:12:06.326Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

[2019-08-06T11:12:06.326Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

[2019-08-06T11:12:06.326Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

[2019-08-06T11:12:06.326Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

[2019-08-06T11:12:06.326Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

[2019-08-06T11:12:06.326Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

</p>
</details>

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.20.0
 - Configuration: [e.g. exporters etc.]

**Comment by saig0** [comment]
The test is flaky because of an actual bug :bug: 

When we have the following situation:

1. element: `ELEMENT_COMPLETING` 
2. flow scope: `ELEMENT_TERMINATING` 
3. element: `ELEMENT_COMPLETED` 

Then the `ELEMENT_COMPLETED` is not applied because the flow scope is not active anymore. We see the following log statement:

```
Skipping record [key: 2251799813685257, intent: ELEMENT_COMPLETED, value: {"bpmnProcessId":"process","version":1,"workflowKey":2251799813685249,"workflowInstanceKey":2251799813685251,"elementId":"task","flowScopeKey":2251799813685256,"bpmnElementType":"SERVICE_TASK"}] due to step guard; in-memory element is ElementInstance{elementRecord=IndexedRecord{key=2251799813685257, state=ELEMENT_COMPLETED, value={"bpmnProcessId":"process","version":1,"workflowKey":2251799813685249,"workflowInstanceKey":2251799813685251,"elementId":"task","flowScopeKey":2251799813685256,"bpmnElementType":"SERVICE_TASK"}}, parentKey=2251799813685256, childCount=0, jobKey=-1, activeTokens=0, multiInstanceLoopCounter=0}
``` 

Problem: the element is not removed from the state and it not removed from the flow scope (i.e. active token count + child count). As result, the flow scope is not terminated because of an active token.

I guess that we have the same problem for (sub-)processes.
