### ISSUE TITLE
Flaky test in LongPollingActivateJobsTest

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#2936]
**Describe the bug**
Flaky test in LongPollingActivateJobsTest

**Log/Stacktrace**
```
[2019-08-06T09:50:51.024Z] [ERROR]   LongPollingActivateJobsTest.shouldUnblockAllRequestsWhenJobsAvailable:126 

[2019-08-06T09:50:51.024Z] activateJobsStub.handle(<any>);

[2019-08-06T09:50:51.024Z] Wanted 48 times:

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockAllRequestsWhenJobsAvailable(LongPollingActivateJobsTest.java:126)

[2019-08-06T09:50:51.024Z] But was 24 times:

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.024Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)

[2019-08-06T09:50:51.025Z] -> at io.zeebe.gateway.api.util.StubbedGateway$StubbedBrokerClient.sendRequest(StubbedGateway.java:121)
```
**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

**Comment by Zelldon** [comment]
Saw this again on the CI
