### ISSUE TITLE
Atomix: Failed to snapshot services

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2999]
Saw the following exception during chaos testing in one of our nodes.

```
06:48:15.909 [] [raft-server-raft-atomix-partition-4-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-4} - Failed to snapshot services
java.lang.IllegalStateException: cannot write to completed snapshot
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-28.0-jre.jar:?]
        at io.atomix.protocols.raft.storage.snapshot.FileSnapshot.openWriter(FileSnapshot.java:47) ~[atomix-raft-3.2.0-alpha4.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.snapshot(RaftServiceManager.java:470) ~[atomix-raft-3.2.0-alpha4.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$takeSnapshots$4(RaftServiceManager.java:240) ~[atomix-raft-3.2.0-alpha4.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha4.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Zelldon** [comment]
related to #3319

**Comment by Zelldon** [comment]
This should no longer happen since we using our own snapshotting
