### ISSUE TITLE
SIGSEG on beginning a transaction

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3029]
**Describe the bug**
I had run the cluster with the latest snapshot of develop.

```
Cluster size: 3
Partitions count: 1
Replication factor: 3
Brokers:
  Broker 0 - zeebe-0.zeebe.default.svc.cluster.local:26501
    Partition 1 : Leader
  Broker 1 - zeebe-1.zeebe.default.svc.cluster.local:26501
    Partition 1 : Follower
  Broker 2 - zeebe-2.zeebe.default.svc.cluster.local:26501
    Partition 1 : Follower
```

I had run the chaos follower restart test, where broker 1 was restarted.
I investigated #3028 and had all logs open to see what happens on the nodes. After I while we had a leader change because probably zeebe-0 was not able to append/heartbeat in time.. Broker 2 become leader and after that an SIGSEG happened. See details below:

<details>
<pre>
09:44:52.525 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Member 2 received event ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=0, address=zeebe-0.zeebe.default.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAMAAAADAAAAAAABCgBjb21tYW5kQXBpLQB6ZWViZS0wLnplZWJlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAA=}, version=3.2.0-alpha4, timestamp=1567069834453, state=SUSPECT, incarnationNumber=1567071887440}, time=1567071892525} with BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={}}
09:44:52.526 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.gateway - Received membership event: ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=0, address=zeebe-0.zeebe.default.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAMAAAADAAAAAAABCgBjb21tYW5kQXBpLQB6ZWViZS0wLnplZWJlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAA=}, version=3.2.0-alpha4, timestamp=1567069834453, state=SUSPECT, incarnationNumber=1567071887440}, time=1567071892525} with BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={}} 
09:44:56.531 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Member 2 received event ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=0, address=zeebe-0.zeebe.default.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAMAAAADAAAAAAABCgBjb21tYW5kQXBpLQB6ZWViZS0wLnplZWJlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAA=}, version=3.2.0-alpha4, timestamp=1567069834453, state=ALIVE, incarnationNumber=1567071887441}, time=1567071896530} with BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={}}
09:44:56.531 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.gateway - Received membership event: ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=0, address=zeebe-0.zeebe.default.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAMAAAADAAAAAAABCgBjb21tYW5kQXBpLQB6ZWViZS0wLnplZWJlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAA=}, version=3.2.0-alpha4, timestamp=1567069834453, state=ALIVE, incarnationNumber=1567071887441}, time=1567071896530} with BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={}} 
09:45:05.618 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@707380c0
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.23.0.jar:1.23.0]
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.23.0.jar:1.23.0]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:65) ~[zeebe-gateway-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:87) ~[zeebe-gateway-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:169) ~[zeebe-gateway-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
09:45:24.533 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] WARN  io.zeebe.gateway - Failed to activate jobs for type benchmark-task from partition 1
io.zeebe.transport.RequestTimeoutException: Request timed out after PT1M
        at io.zeebe.transport.impl.sender.OutgoingRequest.timeout(OutgoingRequest.java:143) ~[zeebe-transport-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.transport.impl.sender.Sender.onTimerExpiry(Sender.java:291) ~[zeebe-transport-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at org.agrona.DeadlineTimerWheel.poll(DeadlineTimerWheel.java:344) ~[agrona-1.0.7.jar:1.0.7]
        at io.zeebe.transport.impl.sender.Sender.processTimeouts(Sender.java:100) ~[zeebe-transport-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
09:45:25.705 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Node 2 claiming leadership for LogStream partition 1 at term 2.
09:45:25.706 [] [raft-partition-group-raft-atomix-0] DEBUG io.zeebe.distributedlog.impl.DistributedLogstreamPartition - Partition 1 for node 2 claimed leadership
09:45:25.869 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: [/usr/local/zeebe/data/partition-1/state/snapshots/19761146305880, /usr/local/zeebe/data/partition-1/state/snapshots/19752555353592, /usr/local/zeebe/data/partition-1/state/snapshots/19378894469592]
09:45:26.035 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/usr/local/zeebe/data/partition-1/state/runtime'.
09:45:26.035 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Recovered state from snapshot '/usr/local/zeebe/data/partition-1/state/snapshots/19761146305880'
09:45:26.047 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Started restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
09:45:26.049 [io.zeebe.broker.clustering.base.partitions.PartitionInstallService] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Removing leader partition services for partition 1
09:45:26.051 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
09:45:26.051 [] [netty-messaging-event-epoll-client-3] WARN  io.atomix.cluster.messaging.impl.NettyMessagingService - Unable to dispatch message due to Task io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$$Lambda$389/0x00000008004b3040@59e4d734 rejected from java.util.concurrent.ThreadPoolExecutor@2a6861b6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
09:45:26.058 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/usr/local/zeebe/data/partition-1/state/runtime'.
09:45:26.063 [io.zeebe.broker.clustering.base.partitions.PartitionInstallService] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Installing follower partition service for partition 1
09:45:26.078 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Started restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
09:45:26.078 [io.zeebe.broker.clustering.base.partitions.PartitionInstallService] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Removing follower partition service for partition 1
09:45:26.078 [topology] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Updating partition information for partition 1 on Node{nodeId=2, commandApi=zeebe-2.zeebe.default.svc.cluster.local:26501} with state LEADER
09:45:26.079 [topology] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Updating partition information for partition 1 on Node{nodeId=2, commandApi=zeebe-2.zeebe.default.svc.cluster.local:26501} with state FOLLOWER
09:45:26.083 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
09:45:26.083 [io.zeebe.broker.clustering.base.partitions.PartitionInstallService] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.clustering - Installing leader partition service for partition 1
09:45:26.110 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Node 2 claiming leadership for LogStream partition 1 at term 3.
09:45:26.111 [] [raft-partition-group-raft-atomix-2] DEBUG io.zeebe.distributedlog.impl.DistributedLogstreamPartition - Partition 1 for node 2 claimed leadership
09:45:26.271 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: [/usr/local/zeebe/data/partition-1/state/snapshots/19761146305880, /usr/local/zeebe/data/partition-1/state/snapshots/19752555353592, /usr/local/zeebe/data/partition-1/state/snapshots/19378894469592]
09:45:26.430 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/usr/local/zeebe/data/partition-1/state/runtime'.
09:45:26.430 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Recovered state from snapshot '/usr/local/zeebe/data/partition-1/state/snapshots/19761146305880'
09:45:26.449 [service-controller] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Started restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
09:45:26.450 [exporter] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
09:45:26.451 [topology] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition 1 on Node{nodeId=2, commandApi=zeebe-2.zeebe.default.svc.cluster.local:26501} with state LEADER
09:45:26.451 [stream-processor] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
09:45:26.451 [service-container-main] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.IllegalStateException: Cannot install service with name 'logstream.raft-atomix-partition-1.stream-processor'. Service with same name already exists
        at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$11(ServiceContainerImpl.java:220) ~[zeebe-service-container-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
[thread 37 also had an error]
09:45:26.451 [service-container-main] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.IllegalStateException: Cannot install service with name 'io.zeebe.broker.exporter.1'. Service with same name already exists
        at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$11(ServiceContainerImpl.java:220) ~[zeebe-service-container-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
09:45:26.452 [service-container-main] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.IllegalStateException: Cannot install service with name 'logstream.raft-atomix-partition-1.snapshot-director'. Service with same name already exists
        at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$11(ServiceContainerImpl.java:220) ~[zeebe-service-container-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.0-SNAPSHOT.jar:0.21.0-SNAPSHOT]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6b7cada852, pid=14, tid=39
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni4558060246451924827.so+0x195852]  Java_org_rocksdb_OptimisticTransactionDB_beginTransaction__JJ+0x22
#
# Core dump will be written. Default location: /usr/local/zeebe/core.%e.%p.%t
#
# An error report file with more information is saved as:
# /usr/local/zeebe/hs_err_pid14.log
09:45:26.521 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Member 2 received event ClusterMembershipEvent{type=METADATA_CHANGED, subject=Member{id=2, address=zeebe-2.zeebe.default.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAQACAAAAAQAAAAMAAAADAAAAAAABCgBjb21tYW5kQXBpLQB6ZWViZS0yLnplZWJlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAEBAAAAAA==}}, time=1567071926521} with BrokerInfo{nodeId=2, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={1=LEADER}}
09:45:26.522 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [zeebe-2.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.gateway - Received membership event: ClusterMembershipEvent{type=METADATA_CHANGED, subject=Member{id=2, address=zeebe-2.zeebe.default.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAQACAAAAAQAAAAMAAAADAAAAAAABCgBjb21tYW5kQXBpLQB6ZWViZS0yLnplZWJlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAEBAAAAAA==}}, time=1567071926521} with BrokerInfo{nodeId=2, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={1=LEADER}} 
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
</pre>
</details>

The pod is recreated after this signal.
Watch on cluster status:
```
zeebe-1   1/1   Terminating   0     26m
zeebe-1   0/1   Terminating   0     26m
zeebe-1   0/1   Terminating   0     26m
zeebe-1   0/1   Terminating   0     26m
zeebe-1   0/1   Pending   0     0s
zeebe-1   0/1   Pending   0     0s
zeebe-1   0/1   ContainerCreating   0     0s
zeebe-1   0/1   Running   0     5s
zeebe-0   0/1   Running   1     34m
zeebe-2   0/1   Running   0     35m
zeebe-2   0/1   Error   0     36m
zeebe-2   0/1   Running   1     36m
zeebe-2   1/1   Running   1     37m
zeebe-1   1/1   Running   0     11m
zeebe-0   1/1   Running   1     41m
```

**To Reproduce**
IDK yet, just run it and see what happens

**Expected behavior**
Clearly no SIGSEG

**Comment by Zelldon** [comment]
Saw this today again. I assume it happens when the leader often changed and then there exist probably a race condition.

```
2019-10-18T08:43:20.109201143Z 2019-10-18 08:43:20.108 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Node 1 claiming leadership for LogStream partition 1 at term 136.
 I 
2019-10-18T08:43:20.110476273Z 2019-10-18 08:43:20.109 [] [raft-partition-group-raft-atomix-7] DEBUG io.zeebe.distributedlog.impl.DistributedLogstreamPartition - Partition 1 for node 1 claimed leadership
 I 
2019-10-18T08:43:20.357152550Z 2019-10-18 08:43:20.356 [service-controller] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
 I 
2019-10-18T08:43:21.134485358Z 2019-10-18 08:43:21.134 [service-controller] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/usr/local/zeebe/data/partition-1/state/runtime'.
 I 
2019-10-18T08:43:21.152163781Z 2019-10-18 08:43:21.151 [service-controller] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Started restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
 I 
2019-10-18T08:43:21.156861517Z 2019-10-18 08:43:21.152 [topology] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition 1 on Node{nodeId=1, commandApi=zeebe-1.zeebe.default.svc.cluster.local:26501} with state LEADER
 I 
2019-10-18T08:43:21.156904818Z 2019-10-18 08:43:21.153 [partition-1-processor] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
 I 
2019-10-18T08:43:21.156911641Z 2019-10-18 08:43:21.153 [exporter] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
 I 
2019-10-18T08:43:21.156916889Z [thread 48 also had an error]
 I 
2019-10-18T08:43:21.160455765Z 2019-10-18 08:43:21.154 [service-container-main] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-6] ERROR io.zeebe.servicecontainer - Failed to build service
 I 
2019-10-18T08:43:21.160519025Z java.lang.IllegalStateException: Cannot install service with name 'io.zeebe.broker.exporter.1'. Service with same name already exists
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$11(ServiceContainerImpl.java:220) ~[zeebe-service-container-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 I 
2019-10-18T08:43:21.160904304Z 2019-10-18 08:43:21.160 [service-container-main] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-6] ERROR io.zeebe.servicecontainer - Failed to build service
 I 
2019-10-18T08:43:21.160926681Z java.lang.IllegalStateException: Cannot install service with name 'logstream.raft-atomix-partition-1.stream-processor'. Service with same name already exists
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$11(ServiceContainerImpl.java:220) ~[zeebe-service-container-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 I 
2019-10-18T08:43:21.161227325Z 2019-10-18 08:43:21.160 [service-container-main] [zeebe-1.zeebe.default.svc.cluster.local:26501-zb-actors-6] ERROR io.zeebe.servicecontainer - Failed to build service
 I 
2019-10-18T08:43:21.161246384Z java.lang.IllegalStateException: Cannot install service with name 'logstream.raft-atomix-partition-1.snapshot-director'. Service with same name already exists
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$11(ServiceContainerImpl.java:220) ~[zeebe-service-container-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
 I 
2019-10-18T08:43:21.171896185Z #
 I 
2019-10-18T08:43:21.171940101Z # A fatal error has been detected by the Java Runtime Environment:
 I 
2019-10-18T08:43:21.171946406Z #
 I 
2019-10-18T08:43:21.171951317Z #  SIGSEGV (0xb) at pc=0x00007fb50619b852, pid=16, tid=40
 I 
2019-10-18T08:43:21.171956197Z #
 I 
2019-10-18T08:43:21.171960698Z # JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
 I 
2019-10-18T08:43:21.171965522Z # Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 I 
2019-10-18T08:43:21.171970683Z # Problematic frame:
 I 
2019-10-18T08:43:21.172265426Z # C  [librocksdbjni17336979893757113488.so+0x195852]  Java_org_rocksdb_OptimisticTransactionDB_beginTransaction__JJ+0x22
 I 
2019-10-18T08:43:21.172308007Z #
 I 
2019-10-18T08:43:21.172312218Z # Core dump will be written. Default location: /usr/local/zeebe/core.%e.%p.%t
 I 
2019-10-18T08:43:21.172315691Z #
 I 
2019-10-18T08:43:21.172513790Z # An error report file with more information is saved as:
 I 
2019-10-18T08:43:21.172524523Z # /usr/local/zeebe/hs_err_pid16.log
 I 
2019-10-18T08:43:21.224430533Z #
 I 
2019-10-18T08:43:21.224462176Z # If you would like to submit a bug report, please visit:
 I 
2019-10-18T08:43:21.224467017Z #   http://bugreport.java.com/bugreport/crash.jsp
 I 
2019-10-18T08:43:21.224471340Z # The crash happened outside the Java Virtual Machine in native code.
 I 
2019-10-18T08:43:21.224475680Z # See problematic frame for where to report the bug.
 I 
2019-10-18T08:43:21.224480211Z #
 I 
```

**Comment by Zelldon** [comment]
Could be fixed with https://github.com/zeebe-io/zeebe/pull/3303
