### ISSUE TITLE
Null Pointer Exception during Topic Subscription handling

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#313]
While starting 3 Brokers and opening and closing Topic Subscriptions I sometimes see a NPE with following stacktrace in [TopicSubscriptionManagementProcessor](https://github.com/camunda-tngp/camunda-tngp/blob/1382336d9beffffb2e1d51a7d754ac6a26ce2315/broker-core/src/main/java/org/camunda/tngp/broker/event/processor/TopicSubscriptionManagementProcessor.java#L370):

```
he log stream processor 'log.default-topic.0.subscription.management' failed to process event. It stop processing further events.
java.lang.NullPointerException
	at org.camunda.tngp.broker.event.processor.TopicSubscriptionManagementProcessor$SubscribedProcessor.executeSideEffects(TopicSubscriptionManagementProcessor.java:370)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$1(StreamProcessorController.java:325)
	at org.camunda.tngp.util.state.ComposedState.doWork(ComposedState.java:60)
	at org.camunda.tngp.util.state.StateMachine.doWork(StateMachine.java:107)
	at org.camunda.tngp.util.state.StateMachineAgent.doWork(StateMachineAgent.java:50)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:126)
	at org.camunda.tngp.util.actor.ActorRunner.tryRunActor(ActorRunner.java:125)
	at org.camunda.tngp.util.actor.ActorRunner.runActor(ActorRunner.java:95)
	at org.camunda.tngp.util.actor.ActorRunner.doWork(ActorRunner.java:78)
	at org.camunda.tngp.util.actor.ActorRunner.run(ActorRunner.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

I'm not sure if this happens while the topic subscription is open or when it is closed.

**Comment by menski** [comment]
I cannot reproduce this anymore
