### ISSUE TITLE
Topic Subscription Management Process fails to read property of subscription event

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#314]
While starting 3 Brokers and opening and closing Topic Subscriptions I sometimes see the following stacktrace in [TopicSubscriptionManagementProcessor](https://github.com/camunda-tngp/camunda-tngp/blob/1382336d9beffffb2e1d51a7d754ac6a26ce2315/broker-core/src/main/java/org/camunda/tngp/broker/event/processor/TopicSubscriptionManagementProcessor.java#L317):

```
The log stream processor 'log.default-topic.0.subscription.management' failed to process event. It stop processing further events.
java.lang.RuntimeException: Property 'name' has no valid value
	at org.camunda.tngp.broker.util.msgpack.property.BaseProperty.resolveValue(BaseProperty.java:73)
	at org.camunda.tngp.broker.util.msgpack.property.StringProperty.getValue(StringProperty.java:24)
	at org.camunda.tngp.broker.event.processor.TopicSubscriptionEvent.getName(TopicSubscriptionEvent.java:30)
	at org.camunda.tngp.broker.event.processor.TopicSubscriptionManagementProcessor$AckProcessor.executeSideEffects(TopicSubscriptionManagementProcessor.java:317)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$1(StreamProcessorController.java:325)
	at org.camunda.tngp.util.state.ComposedState.doWork(ComposedState.java:60)
	at org.camunda.tngp.util.state.StateMachine.doWork(StateMachine.java:107)
	at org.camunda.tngp.util.state.StateMachineAgent.doWork(StateMachineAgent.java:50)
	at org.camunda.tngp.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:126)
	at org.camunda.tngp.util.actor.ActorRunner.tryRunActor(ActorRunner.java:125)
	at org.camunda.tngp.util.actor.ActorRunner.runActor(ActorRunner.java:102)
	at org.camunda.tngp.util.actor.ActorRunner.doWork(ActorRunner.java:78)
	at org.camunda.tngp.util.actor.ActorRunner.run(ActorRunner.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
I cannot reproduce this anymore
