### ISSUE TITLE
Failed to process deployment response with multiple partitions

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3152]
**Describe the bug**
From time to time, the broker fails to process the response of a deployment request. After the timeout (15 seconds), the broker sends the request again and the deployment is successful eventually.

It seems that the response is sent correctly via Atomix but the receiver gets only a part of it. At least, the byte array of the response has the correct length.  

**To Reproduce**
Run a cluster QA test case (e.g. `JobWorkerWithMultiplePartitionsTest`) multiple times.

**Expected behavior**
The response is processed without retry.

**Log/Stacktrace**

Failure in the log: `Actor failed in phase 'STARTED'. Continue with next job`

<details><summary>Full Stacktrace</summary>
 <p>

```
10:38:40.753 [management-request-handler] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Handling deployment 2251799813685258 for partition 2 as leader
10:38:40.754 [management-request-handler] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment CREATE command for deployment 2251799813685258 was written on partition 2
10:38:40.754 [management-request-handler] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Handling deployment 2251799813685258 for partition 3 as leader
10:38:40.754 [management-request-handler] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment CREATE command for deployment 2251799813685258 was written on partition 3
10:38:40.761 [partition-1-processor] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813685258
10:38:40.763 [partition-1-processor] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813685258
10:38:40.768 [partition-1-processor] [0.0.0.0:25602-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.AssertionError: Decoder read only to position 13 but expected 18 as final position
	at io.zeebe.protocol.impl.encoding.ErrorResponse.wrap(ErrorResponse.java:97) ~[classes/:?]
	at io.zeebe.broker.engine.impl.DeploymentDistributorImpl.handleResponse(DeploymentDistributorImpl.java:262) ~[classes/:?]
```

</p>
</details>

**Environment:**
 - Zeebe Version: 0.20.0, 0.21.0
 - Configuration: one broker with partition count > 1

**Comment by saig0** [comment]
Fixed by #3168.
