### ISSUE TITLE
NPE in ExporterDirector

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3240]
**Describe the bug**
On chaos tests I saw the following exception, with the latest snapshot and the logstream concurrency fix.

Probably related to exporter concurrency fix.

```
java.lang.NullPointerException: null
	at io.zeebe.broker.exporter.stream.ExporterDirector.getLowestExporterPosition(ExporterDirector.java:183) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.exporter.ExporterManagerService.getLowestExporterPosition(ExporterManagerService.java:108) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.delete.LeaderLogStreamDeletionService.getMinimumExportedPosition(LeaderLogStreamDeletionService.java:47) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.delete.LeaderLogStreamDeletionService.delete(LeaderLogStreamDeletionService.java:42) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.onNewValidSnapshot(StateSnapshotController.java:263) ~[zeebe-logstreams-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.moveValidSnapshot(StateSnapshotController.java:114) ~[zeebe-logstreams-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.onCommitCheck(AsyncSnapshotDirector.java:157) ~[zeebe-workflow-engine-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$takeSnapshot$1(AsyncSnapshotDirector.java:131) ~[zeebe-workflow-engine-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:27) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
```

**Comment by Zelldon** [comment]
OK the log was from an old build. `io.zeebe.broker.logstreams.delete.LeaderLogStreamDeletionService.getMinimumExportedPosition` was removed in #3225 and rewritten so probably fixed.
