### ISSUE TITLE
Facing StatusRuntimeException: CANCELLED exception and also client taking longer to listen new job

### ISSUE THREAD

**Issue by regojoyson** [zeebe-io/zeebe#3264]
**Describe the bug**
   I am using zeebe 0.21.1 and using java client with spring boot.  after 1 week of upgrading, I am getting this exception.

more info : https://forum.zeebe.io/t/sometime-getting-exception-in-zeebe-broker-and-also-zeebe-client-taking-long-time-to-complete-it/734

**To Reproduce**
   I tried to reproduce but it will come occasionally, so I couldn't figure out.

**Expected behavior**
  it should run without any error and without taking long time to receive jobs by java client

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
10/16/2019 12:15:26 PM2019-10-16 06:45:26.930 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-0] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@1fc07628
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
10/16/2019 12:15:26 PM	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:72) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:94) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:176) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.931 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-0] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@50203f27
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
10/16/2019 12:15:26 PM	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:72) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:94) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:176) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.940 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@5ced0b18
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
10/16/2019 12:15:26 PM	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:72) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:94) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:176) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.941 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@69745aaa
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
10/16/2019 12:15:26 PM	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:72) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:94) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:176) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.947 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@217c706c
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
```

</p>
</details>

**Environment:**
 - OS: [docker ]
 - Zeebe Version: [e.g. 0.21.1]
 - Configuration: [elastic exporter]

**Comment by jwulf** [comment]
```
io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.940 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@5ced0b18
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
10/16/2019 12:15:26 PM	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:72) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:94) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:176) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.941 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@69745aaa
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
10/16/2019 12:15:26 PM	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.24.0.jar:1.24.0]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:72) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:94) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:176) ~[zeebe-gateway-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.21.1.jar:0.21.1]
10/16/2019 12:15:26 PM2019-10-16 06:45:26.947 [io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler] [10.42.37.204:26501-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete io.zeebe.gateway.impl.broker.request.BrokerActivateJobsRequest@217c706c
10/16/2019 12:15:26 PMio.grpc.StatusRuntimeException: CANCELLED: call already cancelled
```

**Comment by jwulf** [comment]
This is the gateway reporting that the client cancelled the gRPC call and closed the response channel?

**Comment by jwulf** [comment]
@regojoyson it looks to me that the client has cancelled the connection. I saw this with the Node client when I was managing a client-side timeout. If the client had timed out the call and the broker tried to respond to it, it would throw this error. 

Take a look at what your client is doing. What I would do is debug logging in the client - the gRPC command that it is sending, and what it is doing after that.

Where is the source code that gets executed on the client? If you are using the Spring Boot client, please find the source code for the release you are using on Git Hub (the right version), and point me to it. We can debug exactly what is going on. I've traced down several bugs like this in the Node client previously.

**Comment by regojoyson** [comment]
@jwulf, I figured out the issue here,

Whenever  I stopping my client at that time the zeebe gives the above error. but these logs are not coming previously on zeebe 0.20.1. 
Are there any specific reasons it came in a newer version..?

**Comment by imsuperman0920** [comment]
@jwulf 
I got the same exception. any idea?

**Comment by RedUno** [comment]
Hi,
I have same problem on Zeebe 0.20.0, 98% of my zeebe clients (Go) timeout.
```
│ 2019/12/04 13:40:16 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ 2019/12/04 13:40:31 Failed to activate jobs for worker http-go rpc error: code = Canceled desc = stream terminated by RST_STREAM with error code: CANCEL                                       │
│ 2019/12/04 13:40:46 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ 2019/12/04 13:41:01 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ 2019/12/04 13:41:16 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ 2019/12/04 13:41:31 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ 2019/12/04 13:41:46 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ Completed job with key 4503599854487730                                                                                                                                                        │
│ 2019/12/04 13:42:01 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ Completed job with key 6755399668181348                                                                                                                                                        │
│ 2019/12/04 13:42:16 Failed to activate jobs for worker http-go rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                             │
│ Completed job with key 6755399668181364  
```

**Comment by Zelldon** [comment]
> Whenever I stopping my client at that time the zeebe gives the above error. but these logs are not coming previously on zeebe 0.20.1.
Are there any specific reasons it came in a newer version..?

This is not really an issue it just logs that the connection was canceled. You see this now because we introduced long polling in the latest versions.

**Comment by Zelldon** [comment]
As I wrote I see no issue here which is why I will close this issue. If you disagree feel free to reopen it.

**Comment by eapenjohn** [comment]
i dont know is bit late to report . but we being seeing this for a long time and it almost flooding the console , not able  to see any real meaningful errors. Can we able to disable this kind of logs 

Current settings : everything running from local console
Zeebe version used . 22.1 
Zeebe client used : .net nuget ze-client by Christopher Zell


snippet of error
2020-05-25 19:55:27.596 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete BrokerActivateJobsRequest{requestDto={"type":"KKRDeviceGatewayAllocator.GetFreeGateway","worker":"WKRR","timeout":60000,"maxJobsToActivate":50,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}}
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.26.0.jar:1.26.0]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:73) ~[zeebe-gateway-0.22.1.jar:0.22.1]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:95) ~[zeebe-gateway-0.22.1.jar:0.22.1]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:191) ~[zeebe-gateway-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-05-25 19:55:27.916 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] WARN  io.zeebe.gateway - Failed to complete BrokerActivateJobsRequest{requestDto={"type":"KKRDeviceGatewayAllocator.GetUnallocatedDevices","worker":"WKRR","timeout":60000,"maxJobsToActivate":50,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}}
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.26.0.jar:1.26.0]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:73) ~[zeebe-gateway-0.22.1.jar:0.22.1]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:95) ~[zeebe-gateway-0.22.1.jar:0.22.1]
        at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:191) ~[zeebe-gateway-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]

**Comment by npepinpe** [comment]
It was disabled in 0.23.
