### ISSUE TITLE
FlakyTest: shouldReclaimOnMessageSend – io.zeebe.transport.ClientTransportMemoryTest

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3273]
```
Error
expected:<[tru]e> but was:<[fals]e>
Stacktrace
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:91)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at io.zeebe.transport.ClientTransportMemoryTest.shouldReclaimOnMessageSend(ClientTransportMemoryTest.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Standard Output
12:17:07.568 [main] [] INFO  io.zeebe.test - Test finished: shouldReclaimRequestMemoryOnRequestTimeout(io.zeebe.transport.ClientTransportMemoryTest)
12:17:07.568 [main] [] INFO  io.zeebe.test - Test started: shouldReclaimOnMessageSend(io.zeebe.transport.ClientTransportMemoryTest)
12:17:07.588 [main] [] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '1' with address 'localhost:35701' on transport 'test'

```

**Comment by Zelldon** [comment]
Run it around 1k times also the all transport test together but can't reproduce it locally. I assume the problem is that dispatcher and some transport components are scheduled, but might not ready yet when the message is publish in that case maybe the message is lost.

**Comment by npepinpe** [comment]
I think you might be right, it seems we silently fail if we don't have enough memory to send the request, for example; I can imagine in other places we also fail silently :disappointed: 

I can try to make the test a little more robust, then we can hopefully get more info, as I had the same where I ran it > 10k times and nothing.

**Comment by Zelldon** [comment]
> fail if we don't have enough memory to send the request, for example; I can imagine in other places we also fail silently 

I hope not :sweat_smile:

**Comment by npepinpe** [comment]
tbh I hope to remove the transport this quarter so maybe its not worth spending much more time on this than adding some logging

**Comment by Zelldon** [comment]
This would be awesome :heart_eyes:
