### ISSUE TITLE
ServiceContainer sometimes can't remove services

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3316]
**Description**
I run some tests locally in a loop and sometimes they took really long on cleanUp phase. The issue seems that the service container is sometimes not able to remove all services

```
14:18:03.567 [service-container-main] [0.0.0.0:25612-zb-actors-0] DEBUG io.zeebe.servicecontainer - Removed service broker.httpServer
14:18:23.533 [] [Time-limited test] DEBUG io.zeebe.servicecontainer - Service container closing failed. Print dependencies.
14:18:23.534 [] [Time-limited test] DEBUG io.zeebe.servicecontainer - 
logstream.raft-atomix-partition-1.service in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- logstream.raft-atomix-partition-1.storage in AwaitDependentsStopped
transport.commandApi.server.server in AwaitDependentsStopped
	\
cluster.base.bootstrapped in AwaitDependentsStopped
	\
cluster.base.atomix.join in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.topologyManager in AwaitDependentsStopped
cluster.base.partition.raft-atomix-partition-1.leader in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1.service in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- raft.leader.raft-atomix-partition-1.openLogStream in AwaitDependentsStopped
broker.system.management.requestHandler in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
cluster.base.atomix in AwaitDependentsStopped
	\
 	-- cluster.base.bootstrapped in AwaitDependentsStopped
 	-- cluster.base.raft.configurationManager in AwaitDependentsStopped
cluster.base.topologyManager in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.bootstrapped in AwaitDependentsStopped
cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
	\
 	-- cluster.base.partition.install.raft-atomix-partition-1 in AwaitDependentsStopped
cluster.base.partitions.bootstrap in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.raft.configurationManager in AwaitDependentsStopped
 	-- cluster.base.atomix.join in AwaitDependentsStopped
cluster.base.raft.configurationManager in AwaitDependentsStopped
	\
 	-- cluster.base.bootstrapped in AwaitDependentsStopped
logstream.raft-atomix-partition-1 in AwaitDependentsStopped
	\
raft.leader.raft-atomix-partition-1.openLogStream in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1.distributed.log in AwaitDependentsStopped
 	-- logstream.raft-atomix-partition-1.service in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
logstream.raft-atomix-partition-1.storage in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1 in AwaitDependentsStopped
cluster.base.partition.install.raft-atomix-partition-1 in AwaitDependentsStopped
	\
 	-- cluster.base.partitions.bootstrap in AwaitDependentsStopped
logstream.raft-atomix-partition-1.distributed.log in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
logstream.raft-atomix-partition-1.stream-processor in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.topologyManager in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- transport.commandApi.messageHandler in AwaitDependentsStopped
 	-- cluster.base.partition.raft-atomix-partition-1.leader in AwaitDependentsStopped
 	-- broker.system.management.requestHandler in AwaitDependentsStopped
transport.commandApi.messageHandler in AwaitDependentsStopped
	\
 	-- transport.commandApi.server.server in AwaitDependentsStopped
logstream.raft-atomix-partition-1.snapshot-director in AwaitStopState
	\
 	-- logstream.raft-atomix-partition-1.stream-processor in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- cluster.base.partition.raft-atomix-partition-1.leader in AwaitDependentsStopped
14:18:23.534 [] [Time-limited test] ERROR io.zeebe.broker.system - Failed to close broker within PT20S seconds.
java.util.concurrent.TimeoutException: Timeout after: 20000 MILLISECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[classes/:?]
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.close(ServiceContainerImpl.java:117) ~[classes/:?]
	at io.zeebe.broker.system.SystemContext.close(SystemContext.java:175) ~[classes/:?]
	at io.zeebe.broker.Broker.lambda$close$1(Broker.java:71) ~[classes/:?]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [classes/:?]
	at io.zeebe.broker.Broker.close(Broker.java:67) [classes/:?]
	at io.zeebe.broker.test.EmbeddedBrokerRule.stopBroker(EmbeddedBrokerRule.java:196) [test-classes/:?]
	at io.zeebe.broker.test.EmbeddedBrokerRule.after(EmbeddedBrokerRule.java:145) [test-classes/:?]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292) [junit-4.12.jar:4.12]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
14:18:23.548 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shut down.
14:18:23.586 [] [Time-limited test] INFO  io.zeebe.broker.test - Broker closing time: 20054
14:18:23.586 [] [Time-limited test] WARN  io.zeebe.broker.test - There are still allocated direct buffers of a total size of 16992kB.

```

**Comment by Zelldon** [comment]
Fixed with https://github.com/zeebe-io/zeebe/pull/3362
