### ISSUE TITLE
NPE in FsLogStorage#getSize

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3343]
**Describe the bug**

Saw the following error in our long running tests.

```
I 2019-11-09T13:57:54.969602984Z zeebe-1 2019-11-09 13:57:54.955 [] [raft-server-1-raft-atomix-partition-7-state] ERROR io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService - Expected to append new buffer, but caught an non recoverable exception. Will block the primitive.
  zeebe-1
I 2019-11-09T13:57:54.969628532Z zeebe-1 java.lang.NullPointerException: null
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSize(FsLogSegment.java:113) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.append(FsLogStorage.java:62) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.logstreams.impl.service.LogStreamService.append(LogStreamService.java:131) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService.append(DefaultDistributedLogstreamService.java:214) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService.append(DefaultDistributedLogstreamService.java:178) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.atomix.primitive.service.AbstractPrimitiveService.lambda$configure$4(AbstractPrimitiveService.java:167) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.primitive.service.impl.DefaultServiceExecutor.lambda$register$2(DefaultServiceExecutor.java:163) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.primitive.service.impl.DefaultServiceExecutor.apply(DefaultServiceExecutor.java:182) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.primitive.service.AbstractPrimitiveService.apply(AbstractPrimitiveService.java:113) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.service.RaftServiceContext.applyCommand(RaftServiceContext.java:542) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.service.RaftServiceContext.executeCommand(RaftServiceContext.java:514) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.applyCommand(RaftServiceManager.java:853) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:462) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha8.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
  zeebe-1
  undefined

```

**Comment by Zelldon** [comment]
More context, seems to happen on Broker shutdown

```
I 2019-11-09T13:57:54.629970296Z zeebe-1 2019-11-09 13:57:54.628 [] [Broker close Thread] INFO  io.zeebe.broker.system - Broker shutting down...
  zeebe-1
I 2019-11-09T13:57:54.656872409Z zeebe-1 2019-11-09 13:57:54.653 [partition-5-processor-snapshot-director] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Enforce snapshot creation. Last successful processed position is 56465941049512.
  zeebe-1
I 2019-11-09T13:57:54.656932958Z zeebe-1 2019-11-09 13:57:54.656 [service-container-main] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-6] DEBUG io.zeebe.servicecontainer - Removed service broker.httpServer
  zeebe-1
I 2019-11-09T13:57:54.669791485Z zeebe-1 2019-11-09 13:57:54.659 [partition-1-processor] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-7] DEBUG io.zeebe.logstreams - Closed stream processor controller partition-1-processor.
  zeebe-1
I 2019-11-09T13:57:54.669828042Z zeebe-1 2019-11-09 13:57:54.660 [partition-7-processor] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-6] DEBUG io.zeebe.logstreams - Closed stream processor controller partition-7-processor.
  zeebe-1
I 2019-11-09T13:57:54.669834297Z zeebe-1 2019-11-09 13:57:54.660 [partition-2-processor] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-6] DEBUG io.zeebe.logstreams - Closed stream processor controller partition-2-processor.
  zeebe-1
I 2019-11-09T13:57:54.725808023Z zeebe-1 2019-11-09 13:57:54.725 [exporter-1] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-4] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
  zeebe-1
I 2019-11-09T13:57:54.725840516Z zeebe-1 2019-11-09 13:57:54.725 [exporter-1] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-4] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-1'.
  zeebe-1
I 2019-11-09T13:57:54.726167690Z zeebe-1 2019-11-09 13:57:54.726 [service-controller] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-4] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
  zeebe-1
I 2019-11-09T13:57:54.825543387Z zeebe-1 2019-11-09 13:57:54.825 [exporter-5] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-3] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
  zeebe-1
I 2019-11-09T13:57:54.825998452Z zeebe-1 2019-11-09 13:57:54.825 [exporter-5] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-3] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-5'.
  zeebe-1
I 2019-11-09T13:57:54.848256242Z zeebe-1 2019-11-09 13:57:54.848 [exporter-6] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-6] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
  zeebe-1
I 2019-11-09T13:57:54.848613726Z zeebe-1 2019-11-09 13:57:54.848 [exporter-6] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-6] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-6'.
  zeebe-1
I 2019-11-09T13:57:54.859159227Z zeebe-1 2019-11-09 13:57:54.858 [exporter-2] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-5] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
  zeebe-1
I 2019-11-09T13:57:54.859681399Z zeebe-1 2019-11-09 13:57:54.859 [exporter-2] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-5] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-2'.
  zeebe-1
I 2019-11-09T13:57:54.860297942Z zeebe-1 2019-11-09 13:57:54.860 [service-controller] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-6] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-2, restore-info-2, snapshot-request-2, snapshot-info-request-2
  zeebe-1
I 2019-11-09T13:57:54.893294442Z zeebe-1 2019-11-09 13:57:54.893 [exporter-7] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-2] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
  zeebe-1
I 2019-11-09T13:57:54.893531412Z zeebe-1 2019-11-09 13:57:54.893 [exporter-7] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-2] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-7'.
  zeebe-1
I 2019-11-09T13:57:54.898641048Z zeebe-1 2019-11-09 13:57:54.898 [service-controller] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-3] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-7, restore-info-7, snapshot-request-7, snapshot-info-request-7
  zeebe-1
I 2019-11-09T13:57:54.903992824Z zeebe-1 2019-11-09 13:57:54.903 [service-controller] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-4] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/usr/local/zeebe/data/partition-1/state/runtime'.
  zeebe-1
I 2019-11-09T13:57:54.916416246Z zeebe-1 2019-11-09 13:57:54.916 [service-controller] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-6] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/usr/local/zeebe/data/partition-2/state/runtime'.
  zeebe-1
I 2019-11-09T13:57:54.919589045Z zeebe-1 2019-11-09 13:57:54.919 [service-controller] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-3] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/usr/local/zeebe/data/partition-7/state/runtime'.
  zeebe-1
I 2019-11-09T13:57:54.927411395Z zeebe-1 2019-11-09 13:57:54.927 [service-container-main] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-5] DEBUG io.zeebe.servicecontainer - Removed service logstream.raft-atomix-partition-2
  zeebe-1
I 2019-11-09T13:57:54.927483054Z zeebe-1 2019-11-09 13:57:54.927 [service-container-main] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-5] DEBUG io.zeebe.servicecontainer - Removed service logstream.raft-atomix-partition-1
  zeebe-1
I 2019-11-09T13:57:54.930960511Z zeebe-1 2019-11-09 13:57:54.930 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962502160. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.931400275Z zeebe-1 2019-11-09 13:57:54.931 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962502464. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.932011201Z zeebe-1 2019-11-09 13:57:54.931 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962502768. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.932468955Z zeebe-1 2019-11-09 13:57:54.932 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962503072. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.932954516Z zeebe-1 2019-11-09 13:57:54.932 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962503376. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.933263761Z zeebe-1 2019-11-09 13:57:54.933 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962503680. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.943202261Z zeebe-1 2019-11-09 13:57:54.942 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962503984. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.943685779Z zeebe-1 2019-11-09 13:57:54.943 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962504288. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.944078386Z zeebe-1 2019-11-09 13:57:54.943 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962504592. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.944392636Z zeebe-1 2019-11-09 13:57:54.944 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962504896. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.944715326Z zeebe-1 2019-11-09 13:57:54.944 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962505200. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.945038445Z zeebe-1 2019-11-09 13:57:54.944 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962520272. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.945389335Z zeebe-1 2019-11-09 13:57:54.945 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962534344. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.945698065Z zeebe-1 2019-11-09 13:57:54.945 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962534648. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.945981698Z zeebe-1 2019-11-09 13:57:54.945 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962534984. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.946234558Z zeebe-1 2019-11-09 13:57:54.946 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962535288. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.946519003Z zeebe-1 2019-11-09 13:57:54.946 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962535592. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.946808147Z zeebe-1 2019-11-09 13:57:54.946 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962535896. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.951155293Z zeebe-1 2019-11-09 13:57:54.950 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962536232. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.962152611Z zeebe-1 2019-11-09 13:57:54.961 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962536536. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.967974555Z zeebe-1 2019-11-09 13:57:54.950 [] [raft-server-1-raft-atomix-partition-2-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-2 - Rejecting append request at position 57307756383800. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.968753685Z zeebe-1 2019-11-09 13:57:54.968 [] [raft-server-1-raft-atomix-partition-2-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-2 - Rejecting append request at position 57307756384104. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.969158209Z zeebe-1 2019-11-09 13:57:54.969 [] [raft-server-1-raft-atomix-partition-2-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-2 - Rejecting append request at position 57307756384408. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.969298869Z zeebe-1 2019-11-09 13:57:54.964 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962536856. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.969442850Z zeebe-1 2019-11-09 13:57:54.962 [service-container-main] [zeebe-1.zeebe.long-running.svc.cluster.local:26501-zb-actors-6] DEBUG io.zeebe.servicecontainer - Removed service logstream.raft-atomix-partition-7
  zeebe-1
I 2019-11-09T13:57:54.969602984Z zeebe-1 2019-11-09 13:57:54.955 [] [raft-server-1-raft-atomix-partition-7-state] ERROR io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService - Expected to append new buffer, but caught an non recoverable exception. Will block the primitive.
  zeebe-1
I 2019-11-09T13:57:54.969628532Z zeebe-1 java.lang.NullPointerException: null
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSize(FsLogSegment.java:113) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.append(FsLogStorage.java:62) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.logstreams.impl.service.LogStreamService.append(LogStreamService.java:131) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService.append(DefaultDistributedLogstreamService.java:214) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService.append(DefaultDistributedLogstreamService.java:178) ~[zeebe-logstreams-0.22.0-alpha1.jar:0.22.0-alpha1]
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.atomix.primitive.service.AbstractPrimitiveService.lambda$configure$4(AbstractPrimitiveService.java:167) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.primitive.service.impl.DefaultServiceExecutor.lambda$register$2(DefaultServiceExecutor.java:163) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.primitive.service.impl.DefaultServiceExecutor.apply(DefaultServiceExecutor.java:182) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.primitive.service.AbstractPrimitiveService.apply(AbstractPrimitiveService.java:113) ~[atomix-primitive-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.service.RaftServiceContext.applyCommand(RaftServiceContext.java:542) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.service.RaftServiceContext.executeCommand(RaftServiceContext.java:514) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.applyCommand(RaftServiceManager.java:853) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:462) ~[atomix-raft-3.2.0-alpha8.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha8.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
  zeebe-1
I 2019-11-09T13:57:54.973540035Z zeebe-1 2019-11-09 13:57:54.973 [] [raft-server-1-raft-atomix-partition-1-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Rejecting append request at position 56873962537160. Log storage is closed.
  zeebe-1
I 2019-11-09T13:57:54.973579629Z zeebe-1 2019-11-09 13:57:54.973 [] [raft-server-1-raft-atomix-partition-2-state] WARN  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-2 - Rejecting append request at position 57307756384728. Log storage is closed.
  zeebe-1
```

**Comment by Zelldon** [comment]
We replaced our log with atomix
