### ISSUE TITLE
Docs build fail due to request timeouts

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3404]
**Describe the bug**
It happens from time to time that the builds fail because the link checker got an timeout. This is kind of annoying, because we have to run the complete test suite again. Maybe we can do it in a earlier state and also increase the timeout. Or simple force to fail the pipeline. Currently we have to wait until the test suite is done and even if the test are green then the pipeline will fail because of this timeout.

```

+ .ci/scripts/docs/build.sh

+ export MDBOOK_OUTPUT__LINKCHECK__FOLLOW_WEB_LINKS=true

+ cd docs/

+ mdbook build

2019-11-21 08:01:02 [INFO] (mdbook::book): Book building has started

Replacing commit template {{commit}} with hash aa2ea4c5c83015899d66901ab2fc2984eb273736

2019-11-21 08:01:03 [INFO] (mdbook::book): Running the html backend

Replacing commit template {{commit}} with hash aa2ea4c5c83015899d66901ab2fc2984eb273736

2019-11-21 08:01:08 [INFO] (mdbook::book): Running the linkcheck backend

2019-11-21 08:01:08 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer

error: Unable to retrieve "https://maven.apache.org/": https://maven.apache.org/: timed out



    ┌── java-client/get-started.md:21:3 ───

    │

 21 │ * [Apache Maven](https://maven.apache.org/)

    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ https://maven.apache.org/: timed out

    │



Error: ErrorMessage { msg: "One or more incorrect links" }

2019-11-21 08:01:41 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.

2019-11-21 08:01:41 [ERROR] (mdbook::utils): Error: Rendering failed

2019-11-21 08:01:41 [ERROR] (mdbook::utils): 	Caused By: The "linkcheck" renderer failed

script returned exit code 101
```

or 

```

+ .ci/scripts/docs/build.sh

+ export MDBOOK_OUTPUT__LINKCHECK__FOLLOW_WEB_LINKS=true

+ cd docs/

+ mdbook build

2019-11-21 07:09:08 [INFO] (mdbook::book): Book building has started

Replacing commit template {{commit}} with hash 777c0da3827690eb847d5bccdf0d69294adfa142

2019-11-21 07:09:09 [INFO] (mdbook::book): Running the html backend

Replacing commit template {{commit}} with hash 777c0da3827690eb847d5bccdf0d69294adfa142

2019-11-21 07:09:14 [INFO] (mdbook::book): Running the linkcheck backend

2019-11-21 07:09:14 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer

error: Unable to retrieve "http://www.bpmn.org/": http://www.bpmn.org/: error trying to connect: failed to lookup address information: Name or service not known



    ┌── basics/workflows.md:51:12 ───

    │

 51 │ Zeebe uses [BPMN 2.0](http://www.bpmn.org/) for representing workflows. BPMN is an industry standard which is widely supported by different vendors and implementations. Using BPMN ensures that workflows can be interchanged between Zeebe and other workflow systems.

    │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ http://www.bpmn.org/: error trying to connect: failed to lookup address information: Name or service not known

    │



Error: ErrorMessage { msg: "One or more incorrect links" }

2019-11-21 07:09:19 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.

2019-11-21 07:09:19 [ERROR] (mdbook::utils): Error: Rendering failed

2019-11-21 07:09:19 [ERROR] (mdbook::utils): 	Caused By: The "linkcheck" renderer failed

script returned exit code 101
```

**Comment by Zelldon** [comment]
Lately I have the following error on docs building

```

java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'

	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)

	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)

	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)

	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

io.fabric8.kubernetes.client.KubernetesClientException: error dialing backend: EOF
```

:man_shrugging:

**Comment by menski** [comment]
This is a k8s issue and not related with the docs build as far as I can say

**Comment by pihme** [comment]
@menski @Zelldon: This issue is done already via the commit by menski. However, I would like to reenable the link check. Unless there are objections and maybe if someone could tell me how to increase the timeout. 

What is different now from November, when the issue was created, is that this stage will be repeated three times. This solved the issue of the kubernetes connection errors and it might also help with the other timeouts. This is speculation, through, as the link checking has been disabled for some time. 

Please let me know if you have objections to reenabling the link checker

**Comment by menski** [comment]
I would like to get the link checker back

**Comment by pihme** [comment]
Re-enabled link checker for the monitor branch (which runs every hour) for observation.

**Comment by pihme** [comment]
Adding a retry didn't help much.

**Comment by pihme** [comment]
Waiting on https://github.com/Michael-F-Bryan/mdbook-linkcheck/pull/35

**Comment by npepinpe** [comment]
As we're dropping the docs, I'm closing this. Docs are moved to a new system and managed in a separate repo.
