### ISSUE TITLE
Expected to execute side effects for event successfully, but exception was thrown

### ISSUE THREAD

**Issue by RedUno** [zeebe-io/zeebe#3463]
**Describe the bug**

`Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103495829491608, key=-1, timestamp=1574238760521, sourceEventPosition=-1]' successfully, but exception was thrown.`

Error raised every 10s with a different position.

If I restart the node, the error will just switch to another node.

It doesn't seem (I hope so) that the error affects the running instances for now.

**To Reproduce**
Cluster size: 3
Partitions count: 4
Replication factor: 3
If it's help, we had network high latency problem the night before the first time the error appeared.

**Log/Stacktrace**
```
2019-11-19T20:30:25.000Z	20:30:25.081 [raft-server-raft-atomix-partition-2-state] INFO  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-2 - Backup log raft-atomix-partition-2 at position 102825812959888
2019-11-19T20:32:23.000Z	20:32:23.962 [raft-server-raft-atomix-partition-4-state] INFO  io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-4 - Backup log raft-atomix-partition-4 at position 102812929858360
2019-11-20T08:32:40.000Z	08:32:40.537 [corecloud-zeebe-sbg3-0.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103495829491608, key=-1, timestamp=1574238760521, sourceEventPosition=-1]' successfully, but exception was thrown.
2019-11-20T08:32:40.000Z	java.lang.NullPointerException: null
2019-11-20T08:32:40.000Z	08:32:40.536 [corecloud-zeebe-sbg3-0.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103495829491344, key=-1, timestamp=1574238760521, sourceEventPosition=-1]' successfully, but exception was thrown.
2019-11-20T08:32:40.000Z	java.lang.NullPointerException: null
2019-11-20T08:33:10.000Z	java.lang.NullPointerException: null
2019-11-20T08:33:10.000Z	08:33:10.544 [corecloud-zeebe-sbg3-0.svc.cluster.local:26501-zb-actors-0] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103500122120216, key=-1, timestamp=1574238790527, sourceEventPosition=-1]' successfully, but exception was thrown.
2019-11-20T08:33:10.000Z	08:33:10.543 [corecloud-zeebe-sbg3-0.svc.cluster.local:26501-zb-actors-0] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103500122119952, key=-1, timestamp=1574238790527, sourceEventPosition=-1]' successfully, but exception was thrown.
2019-11-20T08:33:10.000Z	java.lang.NullPointerException: null
2019-11-20T08:33:40.000Z	08:33:40.552 [corecloud-zeebe-sbg3-0.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103500122570456, key=-1, timestamp=1574238820539, sourceEventPosition=-1]' successfully, but exception was thrown.
2019-11-20T08:33:40.000Z	08:33:40.551 [corecloud-zeebe-sbg3-0.svc.cluster.local:26501-zb-actors-1] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=103500122570192, key=-1, timestamp=1574238820539, sourceEventPosition=-1]' successfully, but exception was thrown.
2019-11-20T08:33:40.000Z	java.lang.NullPointerException: null
2019-11-20T08:33:40.000Z	java.lang.NullPointerException: null
```
</p>
</details>

**Environment:**
 - OS:4.19.78-coreos
 - Zeebe Version: 0.20.0
 - Configuration: elasticsearch exporter, cluster size: 3, partition count: 4, replication factor: 3

**Comment by saig0** [comment]
Hi @RedUno,

thank you for raising this up! In order to analyze this issue, we need more information.

Can you reproduce this issue on a clean Zeebe installation?
Does it occur with the latest Zeebe version (0.21.1)?
Can you share your workflows? 
Do you see any stacktrace from the NPE?

**Comment by RedUno** [comment]
Hi, thanks @saig0 

I didn't find a way to reproduce this issue on a clean installation, to test locally i had to copy data from our servers and mount it on a zeebe node.

Yes, upgrading to version 0.21.1 seems to hide the issue. when rolling back to 0.20.0 the exception appear again. 

Do you think this issue affect the running instances? are we losing data ?

NPE stacktrace
```
zeebe_broker      | 14:16:46.078 [stream-processor] [172.18.0.4:26501-zb-actors-0] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=130322192662528, key=-1, timestamp=1575382606068, sourceEventPosition=-1]' successfully, but exception was thrown.
zeebe_broker      | java.lang.NullPointerException: null
zeebe_broker      |     at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:249) ~[agrona-1.0.3.jar:1.0.3]
zeebe_broker      |     at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandSender.rejectCorrelateMessageSubscription(SubscriptionCommandSender.java:181) ~[zeebe-workflow-engine-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.engine.processor.workflow.message.CorrelateWorkflowInstanceSubscription.sendRejectionCommand(CorrelateWorkflowInstanceSubscription.java:164) ~[zeebe-workflow-engine-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:34) ~[zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:43) ~[zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:77) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:43) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:169) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:134) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:118) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorThread.run(ActorThread.java:96) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      | 14:16:46.084 [stream-processor] [172.18.0.4:26501-zb-actors-0] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=3, position=130322192662792, key=-1, timestamp=1575382606068, sourceEventPosition=-1]' successfully, but exception was thrown.
zeebe_broker      | java.lang.NullPointerException: null
zeebe_broker      |     at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:249) ~[agrona-1.0.3.jar:1.0.3]
zeebe_broker      |     at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandSender.rejectCorrelateMessageSubscription(SubscriptionCommandSender.java:181) ~[zeebe-workflow-engine-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.engine.processor.workflow.message.CorrelateWorkflowInstanceSubscription.sendRejectionCommand(CorrelateWorkflowInstanceSubscription.java:164) ~[zeebe-workflow-engine-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:34) ~[zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:43) ~[zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:77) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:43) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:169) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:134) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:118) [zeebe-util-0.20.0.jar:0.20.0]
zeebe_broker      |     at io.zeebe.util.sched.ActorThread.run(ActorThread.java:96) [zeebe-util-0.20.0.jar:0.20.0]```

**Comment by saig0** [comment]
:+1: Thank you for the details.

I ran into the same problem. It seems that it still exists with the latest version. Currently, I don't see any negative effects of it. 

Closing this issue in preference of #3466
