### ISSUE TITLE
NPE while rejecting a correlate workflow instance subscription command

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#3466]
**Describe the bug**
When the correlation of a message is rejected (e.g. the message catch event is left in between) then an NPE is written to the log. 

It seems that the message is not lost and can be correlated afterward. So, maybe no negative effect.

**To Reproduce**

![image](https://user-images.githubusercontent.com/4305769/69968035-e2b37980-1519-11ea-8b29-613c96b0f7bc.png)

* deploy a workflow with an event-based gateway and two message catch events
* publish one message for each message catch event with TTL > 0
* create a new instance of this workflow
* verify that the NPE is written to the log

**Expected behavior**
No error is written to the log.

**Log/Stacktrace**

```
ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=1, position=4295278864, key=-1, timestamp=1575296948148, sourceEventPosition=-1]' successfully, but exception was thrown.
java.lang.NullPointerException: null
```

<details><summary>Full Stacktrace</summary>
 <p>

```
2019-12-02 15:29:08.166 [partition-1-processor] [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=1, position=4295278864, key=-1, timestamp=1575296948148, sourceEventPosition=-1]' successfully, but exception was thrown.
java.lang.NullPointerException: null
	at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:249) ~[agrona-1.1.0.jar:1.1.0]
	at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandSender.rejectCorrelateMessageSubscription(SubscriptionCommandSender.java:188) ~[zeebe-workflow-engine-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.message.CorrelateWorkflowInstanceSubscription.sendRejectionCommand(CorrelateWorkflowInstanceSubscription.java:204) ~[zeebe-workflow-engine-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:34) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:43) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.22.0-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

**Comment by deepthidevaki** [comment]
Could not reproduce it. But from the stack trace, I think NPE is due to [this](https://github.com/zeebe-io/zeebe/blob/95a8130a22f6000a521c0ee38319c02dcae155b4/engine/src/main/java/io/zeebe/engine/processor/workflow/message/CorrelateWorkflowInstanceSubscription.java#L108). When the subscription does not exists, it tries to send a rejection message with correlation key = null.
