### ISSUE TITLE
Cannot cancel recursive calling process

### ISSUE THREAD

**Issue by mschoe** [zeebe-io/zeebe#3505]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior
- deploy attached process and create an instance
--> the call activity starts it's own parent process
- cancel the root instance via zbctl in order to stop recursive calling of the process
--> canceling the root instance works, but the process continues to call itself
- try to cancel the instances in operate
--> does not work, cancel operation failed

If possible add a minimal reproducer code sample
 - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java

**Expected behavior**
when I cancel the root instance all other instances should be canceled too

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
2019-12-09 11:52:10.093 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.gateway - Error handling gRPC request
io.grpc.StatusRuntimeException: NOT_FOUND: Command rejected with code 'CANCEL': Expected to cancel a workflow instance with key '4503599627395878', but no such workflow was found
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.25.0.jar:1.25.0]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:352) ~[zeebe-gateway-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:281) ~[zeebe-gateway-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$1(BrokerRequestManager.java:115) ~[zeebe-gateway-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:137) ~[zeebe-gateway-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:180) ~[zeebe-gateway-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:27) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:127) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.0-alpha2.jar:0.22.0-alpha2]
Caused by: io.zeebe.gateway.cmd.BrokerRejectionException: Command (CANCEL) rejected (NOT_FOUND): Expected to cancel a workflow instance with key '4503599627395878', but no such workflow was found
	... 10 more

```

</p>
</details>

**Environment:**
 - OS: linux
 - Zeebe Version:latest alpha
 - Configuration: [e.g. exporters etc.]

[calling_process.bpmn.txt](https://github.com/zeebe-io/zeebe/files/3939271/calling_process.bpmn.txt)

**Comment by saig0** [comment]
@mschoe, thank you for raising this up :balloon: 

I can't reproduce the behavior. It should be possible to cancel the root instance. All other child instances should be canceled **eventually**. 

Please note that the cancelation is propagated from the parent to the child (all way down). When the child is terminated (and it has no active child anymore) then the parent gets terminated (all the way up again). This all happens on the stream as separate events.

Since the workflow is very short, it spawns a big hierarchy in a short time. So, it may take a while until the cancel command catches up. 

Don't expect the broker to **immediately** stop spawning new instances after you send the command. Again, it might happen that the command times out (i.e. don't get a response) because canceling all instances takes more than 15 seconds (default timeout).

Does this make sense for you?

**Comment by mschoe** [comment]
Hi @saig0, thank you for having a look at this issue. After retesting the scenario I can confirm that the cancelation works as expected. Let's close this issue.
