### ISSUE TITLE
SnasphotReplicationTest#shouldReplicateSnapshot is unstable

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3534]
**Description**

Failed located due to running with mvn clean install and saw this also on the CI at some point.

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.579 s <<< FAILURE! - in io.zeebe.broker.it.clustering.SnapshotReplicationTest
[ERROR] io.zeebe.broker.it.clustering.SnapshotReplicationTest.shouldReplicateSnapshots  Time elapsed: 8.576 s  <<< ERROR!
java.lang.RuntimeException: java.nio.file.DirectoryNotEmptyException: /tmp/51192a68-1466-426b-918c-b157291fbce3/data/raft-partition/partitions/1
	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:36)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/51192a68-1466-426b-918c-b157291fbce3/data/raft-partition/partitions/1
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:247)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1141)
	at io.zeebe.util.FileUtil$1.postVisitDirectory(FileUtil.java:54)
	at io.zeebe.util.FileUtil$1.postVisitDirectory(FileUtil.java:43)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2742)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:41)
	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:37)
	at io.zeebe.broker.it.clustering.ClusteringRule.lambda$createBrokerBase$3(ClusteringRule.java:281)
	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:34)
	... 20 more
```

**Comment by npepinpe** [comment]
Strange, this is in the post-step of the tests, right? And we are already recursively deleting the folder...I guess it means we are concurrently writing new files during the deletion? Are we deleting too early before the broker has shut down? :thinking:

**Comment by Zelldon** [comment]
[io.zeebe.broker.it.clustering.SnapshotReplicationTest.txt](https://github.com/zeebe-io/zeebe/files/3955677/io.zeebe.broker.it.clustering.SnapshotReplicationTest.txt)
[io.zeebe.broker.it.clustering.SnapshotReplicationTest-output.txt](https://github.com/zeebe-io/zeebe/files/3955678/io.zeebe.broker.it.clustering.SnapshotReplicationTest-output.txt)
Test outputs

**Comment by Zelldon** [comment]
It seems to be the same issue like https://github.com/zeebe-io/zeebe/issues/3612

**Comment by npepinpe** [comment]
Should've been fixed by correctly chaining the rules in `ClusteringRule` (see #3696)
