### ISSUE TITLE
BrokerReprocessingTest is flaky due to not able to start broker.

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3609]
**Description**

Qa tests are sometimes failing because the brokers cannot be started.

```
11:46:42.070 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/11]: leader management request handler
11:46:42.074 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/11]: leader management request handler started in 3 ms
11:46:42.074 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/11]: zeebe partitions
11:46:42.078 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
11:46:42.263 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
11:46:42.373 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
11:46:42.479 [io.zeebe.logstreams.impl.log.LogStreamImpl] [Broker-0-zb-actors-1] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
11:46:42.971 [io.zeebe.logstreams.impl.log.LogStreamImpl] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 0 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
11:46:42.984 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
11:46:42.985 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
11:46:43.059 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
11:46:43.780 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
11:47:12.181 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 failed with unexpected exception.
java.util.concurrent.TimeoutException: Timeout after: 30 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.scheduleActor(Broker.java:234) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$partitionsStep$14(Broker.java:299) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.partitionsStep(Broker.java:303) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$initStart$9(Broker.java:179) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.internalStart(Broker.java:129) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.start(Broker.java:119) [zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:209) [zeebe-broker-0.22.0-SNAPSHOT-tests.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.before(EmbeddedBrokerRule.java:124) [zeebe-broker-0.22.0-SNAPSHOT-tests.jar:0.22.0-SNAPSHOT]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50) [junit-4.13.jar:4.13]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282) [junit-4.13.jar:4.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by csabaujvari** [comment]
Hi there,

We are having the same issue with 0.22.1. Should it be fixed?
