### ISSUE TITLE
BrokerLeaderChangeTest flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3612]
**Description**

```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 47.085 s <<< FAILURE! - in io.zeebe.broker.it.clustering.BrokerLeaderChangeTest

[ERROR] io.zeebe.broker.it.clustering.BrokerLeaderChangeTest.shouldBecomeFollowerAfterRestartLeaderChange  Time elapsed: 27.966 s  <<< ERROR!

java.lang.RuntimeException: java.nio.file.DirectoryNotEmptyException: /tmp/a110578c-b07a-4b70-a93d-fac340a290ec/data/raft-partition/partitions/1/runtime

	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:36)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)

	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/a110578c-b07a-4b70-a93d-fac340a290ec/data/raft-partition/partitions/1/runtime

	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:243)

	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)

	at java.base/java.nio.file.Files.delete(Files.java:1141)

	at io.zeebe.util.FileUtil$1.postVisitDirectory(FileUtil.java:54)

	at io.zeebe.util.FileUtil$1.postVisitDirectory(FileUtil.java:43)

	at java.base/java.nio.file.Files.walkFileTree(Files.java:2742)

	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)

	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:41)

	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:37)

	at io.zeebe.broker.it.clustering.ClusteringRule.lambda$createBrokerBase$3(ClusteringRule.java:281)

	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:34)

	... 6 more

```

**Comment by npepinpe** [comment]
Should be fixed by #3696
