### ISSUE TITLE
shouldCorrelateMessageOnDifferentPartitions test is unstable

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#3639]
**Description**

io.zeebe.engine.processor.workflow.message.MessageCorrelationMultiplePartitionsTest.shouldCorrelateMessageOnDifferentPartitions is unstable.

```
Error
No event found matching the criteria
```

**Comment by deepthidevaki** [comment]
Found this in the logs:

```
08:20:40.848 [partition-2-processor] ERROR io.zeebe.processor - Expected to execute side effects for event 'LoggedEvent [type=0, version=0, streamId=2, position=4294974240, key=-1, timestamp=1578903640816, sourceEventPosition=-1]' successfully, but exception was thrown.
java.lang.IndexOutOfBoundsException: index=6 length=4 capacity=0
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1706) ~[agrona-1.1.0.jar:1.1.0]
	at org.agrona.concurrent.UnsafeBuffer.putInt(UnsafeBuffer.java:547) ~[agrona-1.1.0.jar:1.1.0]
	at io.zeebe.dispatcher.ClaimedFragment.abort(ClaimedFragment.java:69) ~[zeebe-dispatcher-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamWriterImpl.tryWrite(LogStreamWriterImpl.java:149) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandMessageHandler.writeCommand(SubscriptionCommandMessageHandler.java:292) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandMessageHandler.onCorrelateWorkflowInstanceSubscription(SubscriptionCommandMessageHandler.java:180) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandMessageHandler.lambda$apply$0(SubscriptionCommandMessageHandler.java:93) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandMessageHandler.apply(SubscriptionCommandMessageHandler.java:76) ~[classes/:?]
	at io.zeebe.engine.util.EngineRule$PartitionCommandSenderImpl.sendCommand(EngineRule.java:358) ~[test-classes/:?]
	at io.zeebe.engine.processor.workflow.message.command.SubscriptionCommandSender.correlateWorkflowInstanceSubscription(SubscriptionCommandSender.java:124) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.message.MessageCorrelator.sendCorrelateCommand(MessageCorrelator.java:78) ~[classes/:?]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:44) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
```
```
