### ISSUE TITLE
NullPointerException in BufferedLogStreamReader.getCommitPosition

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#364]
Hey guys.

I play around with alpha6. I just deployed a workflow definition, now I just want to log all events from the topic and start to see this on the broker:

```
java.lang.NullPointerException
        at io.zeebe.logstreams.log.BufferedLogStreamReader.getCommitPosition(BufferedLogStreamReader.java:403)
        at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:147)
        at io.zeebe.broker.workflow.index.WorkflowDeploymentCache.lookupWorkflow(WorkflowDeploymentCache.java:119)
        at org.agrona.collections.LongLruCache.lookup(LongLruCache.java:89)
        at io.zeebe.broker.workflow.index.WorkflowDeploymentCache.getWorkflow(WorkflowDeploymentCache.java:104)
        at io.zeebe.broker.workflow.processor.WorkflowInstanceStreamProcessor$WorkflowInstanceCreatedEventProcessor.processEvent(WorkflowInstanceStreamProcessor.java:429)
        at io.zeebe.logstreams.processor.StreamProcessorController$ReprocessingState.processEvent(StreamProcessorController.java:568)
        at io.zeebe.logstreams.processor.StreamProcessorController$ReprocessingState.doWork(StreamProcessorController.java:528)
        at io.zeebe.logstreams.processor.StreamProcessorController$ReprocessingState.doWork(StreamProcessorController.java:518)
        at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:107)
        at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:50)
        at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:126)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:125)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:95)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:78)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by menski** [comment]
I cannot reproduce this and at least the second stacktrace was related to old raft implementation
