### ISSUE TITLE
SkipFailingEventsTest.shouldNotBlacklistInstanceOnCommand unstable

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3676]
It seems that it can happen that transaction commit fails and the test fails.

```
ERROR] io.zeebe.engine.processor.SkipFailingEventsTest.shouldNotBlacklistInstanceOnCommand Time elapsed: 2.496 s <<< ERROR! 

io.zeebe.db.ZeebeDbException: Unexpected error occurred during RocksDB transaction. 

	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:142) 

	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:171) 

	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.exists(ZeebeTransactionDb.java:205) 

	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.exists(TransactionalColumnFamily.java:165) 

	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.exists(TransactionalColumnFamily.java:120) 

	at io.zeebe.engine.state.BlackList.isOnBlacklist(BlackList.java:35) 

	at io.zeebe.engine.state.ZeebeState.isOnBlacklist(ZeebeState.java:124) 

	at io.zeebe.engine.processor.SkipFailingEventsTest.shouldNotBlacklistInstanceOnCommand(SkipFailingEventsTest.java:367) 

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 

	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) 

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) 

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) 

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54) 

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54) 

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54) 

	at org.junit.rules.RunRules.evaluate(RunRules.java:20) 

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 

	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) 

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) 

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) 

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) 

	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 

	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 

	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 

	at org.junit.runners.Suite.runChild(Suite.java:128) 

	at org.junit.runners.Suite.runChild(Suite.java:27) 

	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 

	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 

	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 

	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55) 

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137) 

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119) 

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87) 

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) 

	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158) 

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377) 

	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138) 

	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465) 

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451) 

Caused by: org.rocksdb.RocksDBException: Busy 

	at org.rocksdb.Transaction.commit(Native Method) 

	at org.rocksdb.Transaction.commit(Transaction.java:206) 

	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal(ZeebeTransaction.java:117) 

	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:164) 

	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:135) 

	... 51 more 


```

**Comment by npepinpe** [comment]
From reading the RocksDB unit tests (lol), it seems expected to get a `Busy` error when two conflicting transactions are trying to commit - that is, if two transactions are on-going, and one updates and commits, the second one to commit will fail and return a `Busy` error. See the [OptimisticTransactionTest](https://github.com/facebook/rocksdb/blob/master/java/src/test/java/org/rocksdb/OptimisticTransactionTest.java)

**Comment by Zelldon** [comment]
Never saw this again. Also not reproducible locally. 

![skiptest](https://user-images.githubusercontent.com/2758593/79227320-ff64a400-7e5f-11ea-9edb-f6fa2e1afc5f.png)
