### ISSUE TITLE
Remove client #connect API

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#372]
Instead of having two methods `#connect` and `#disconnect`, remove `#connect` and reporpuse `#disconnect` such that it properly closes all open connections.

This simplifies using the client. As soon as a `ZeebeClient` object is created, it can be used for making requests. Users do not have to worry about client state and lifecycle.

**Comment by menski** [comment]
Is there a reason why the `close` method does not call `disconnect` anymore?

When I run the `ZeebeClientTest` method `shouldEstablishNewConnectionsAfterDisconnect` in IntelliJ it fails most of the times in [line 100](https://github.com/zeebe-io/zeebe/blob/de1071e7d8e99af8e8ac59236782bfd7afa51e33/client-java/src/test/java/io/zeebe/client/ZeebeClientTest.java#L100). And there is also a `NullPointerException` which also is thrown if the test passes. It seems that the `eventSource` of a subscription [sometimes is null](https://github.com/zeebe-io/zeebe/blob/de1071e7d8e99af8e8ac59236782bfd7afa51e33/client-java/src/main/java/io/zeebe/client/task/impl/subscription/EventSubscriptions.java#L93). Not sure if this is expected or a problem of the test suite.

```
java.lang.NullPointerException
	at io.zeebe.client.task.impl.subscription.EventSubscriptions.lambda$reopenSubscriptionsForRemote$0(EventSubscriptions.java:93)
	at io.zeebe.client.task.impl.subscription.EventSubscriptions.forAllDoConsume(EventSubscriptions.java:198)
	at io.zeebe.client.task.impl.subscription.EventSubscriptions.reopenSubscriptionsForRemote(EventSubscriptions.java:91)
	at io.zeebe.client.task.impl.subscription.SubscriptionManager.onConnectionClosed(SubscriptionManager.java:191)
	at io.zeebe.transport.impl.actor.Conductor.lambda$null$5(Conductor.java:141)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.zeebe.transport.impl.actor.Conductor.lambda$onChannelDisconnected$6(Conductor.java:137)
	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:113)
	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:88)
	at io.zeebe.util.DeferredCommandContext.doWork(DeferredCommandContext.java:66)
	at io.zeebe.transport.impl.actor.Conductor.doWork(Conductor.java:67)
	at io.zeebe.transport.impl.actor.ClientConductor.doWork(ClientConductor.java:41)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
	at java.lang.Thread.run(Thread.java:748)

org.junit.ComparisonFailure: 
Expected :true
Actual   :false
 <Click to see difference>


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:89)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:67)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:38)
	at io.zeebe.client.ZeebeClientTest.shouldEstablishNewConnectionsAfterDisconnect(ZeebeClientTest.java:100)
```
