### ISSUE TITLE
KryoException happening randomly during broker restart

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#3721]
After deploying the latest version of zeebe-**0.22.1**, I am observing `com.esotericsoftware.kryo.KryoException: Buffer underflow` popping up while the broker is getting restarted (specifically on the 7th step of Broker Bootstrap). This is not happening during all restarts, but is happening quite often.

**Expected behavior**
Broker bootstrapping should pass all the `cluster services` steps (I guess there are 11 steps in total).

**Log/Stacktrace**
I have attached the log files from my Alpha and Beta environments. Both environments have exact same configs, but it happened only on Beta.

<details><summary>Errortrace in beta</summary>
 <p>

```
2020-01-21 14:48:51.576 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/11]: embedded gateway started in 121 ms
2020-01-21 14:48:51.576 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services
2020-01-21 14:48:56.648 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.FollowerRole - RaftServer{system-partition-1}{role=FOLLOWER} - java.net.ConnectException
2020-01-21 14:48:56.663 [] [raft-server-0-system-partition-1] WARN  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{system-partition-1}{role=CANDIDATE} - java.net.ConnectException
2020-01-21 14:48:57.066 [] [raft-server-0-system-partition-1-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{system-partition-1} - Expected to read snapshot, but caught a non recoverable error; blocking thread to avoid applying further entries and creating inconsistencies
com.esotericsoftware.kryo.KryoException: Buffer underflow.
	at com.esotericsoftware.kryo.io.Input.require(Input.java:199) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.io.Input.readBoolean(Input.java:801) ~[kryo-4.0.2.jar:?]
	at io.atomix.utils.serializer.serializers.ByteBufferSerializer.read(ByteBufferSerializer.java:39) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at io.atomix.utils.serializer.serializers.ByteBufferSerializer.read(ByteBufferSerializer.java:25) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-4.0.2.jar:?]
	at io.atomix.utils.serializer.Namespace.lambda$null$2(Namespace.java:411) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:58) ~[kryo-4.0.2.jar:?]
	at io.atomix.utils.serializer.Namespace.lambda$deserialize$3(Namespace.java:409) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at io.atomix.utils.serializer.KryoIOPool.run(KryoIOPool.java:45) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:407) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at io.atomix.utils.serializer.Serializer$1.decode(Serializer.java:76) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.initializeService(RaftServiceManager.java:304) ~[atomix-raft-3.2.0-alpha10.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.installService(RaftServiceManager.java:287) ~[atomix-raft-3.2.0-alpha10.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:253) ~[atomix-raft-3.2.0-alpha10.jar:?]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$2(RaftServiceManager.java:207) ~[atomix-raft-3.2.0-alpha10.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha10.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Attached logs**
[logs-from-zeebe-in-beta-zeebe-zeebe-0.txt](https://github.com/zeebe-io/zeebe/files/4091781/logs-from-zeebe-in-beta-zeebe-zeebe-0.txt) - Failed at 7th step
[logs-from-zeebe-in-alpha-zeebe-zeebe-1.txt](https://github.com/zeebe-io/zeebe/files/4091782/logs-from-zeebe-in-alpha-zeebe-zeebe-1.txt) - Successfully executed 11 steps

**Environment:**
 - OS: Linux Docker
 - Zeebe Version: 0.22.1
 - ZEEBE_PARTITIONS_COUNT: 3
 - ZEEBE_CLUSTER_SIZE: 3
 - ZEEBE_REPLICATION_FACTOR: 3
 - JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -Xms2048m -Xmx2048m

**Comment by Zelldon** [comment]
Hey, 

thanks for your report!

Are you running a fresh installation? Or do you tried to migrate from a older version?

Greets
Chris

**Comment by strawhat5** [comment]
Hi Chris, thanks for your quick reply. I am migrating from `0.21.1` release.  I did not face this issue at all while I was using the previous version. Could this have anything to do with the Raft changes in the latest release?

**Comment by Zelldon** [comment]
Exactly, if you have old data this will not work. Please see the release notes where it states that we did some **Breaking changes** and that it is not possible to migrate data.

There was the same question in our slack channel https://zeebe-io.slack.com/archives/C6WGNHV2A/p1579584125056200

>**Samuel**  06:22
>  Is there any problem if we migrate from zeebe 0.21.1 to 0.22.1?
>**menski**:
> Please see the important notice at the beginning of the release notes https://github.com/zeebe-io/zeebe/releases
It is not possible to upgrade data from 0.21.1 to 0.22.1 as we changed the internal way how we store our event log on disk. Which was in important step to improve Zeebe so we decided to go with this breaking change. We recommend to finish running Instances on the old Zeebe version and start new ones on an updated cluster. Sorry for any inconveniences. Let us know if you have any other questions.

Hope that helps.

Greets
Chris

**Comment by strawhat5** [comment]
Oh I see. I read that earlier, but I was of the understanding that it affects only "in-flight" logs, as mentioned by Bernd [here](https://github.com/zeebe-io/zeebe/issues/3169#issuecomment-541586274).

So to sum it up, we cannot "upgrade to `0.22.x`", even if there are no running instances of workflows. And, the only way to move to `0.22.x` is to delete the whole cluster ("including persistent volume"), and do a fresh install. Is this understanding correct?

**Comment by Zelldon** [comment]
Yes that is correct.

**Comment by strawhat5** [comment]
Alright, got it. Thanks for your inputs Chris!

**Just an update**: After tearing down the cluster (along with data), fresh install of `0.22.1` worked.

**Comment by Zelldon** [comment]
You're welcome🙂

Thanks for the update👍

Greets
Chris
