### ISSUE TITLE
Allow to read payload from TopicEvents

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#376]
Currently it is not easily possible to read the payload from TopicEvents (use case: run some monitor aside ZeeBe to visualize what is happening), as this seems to be still MsgPack encoded when reading the event as JSON. There is no totally easy way of converting the payload, also this should be hidden for the user of the Java client API.

At the moment I could do something like:

`
client.topics()
        .newSubscription(Constants.DEFAULT_TOPIC)
        .startAtHeadOfTopic().forcedStart()
        .name("zeebe-simple-monitor")
        .handler((event) ->
        {
            JsonReader jsonReader = Json.createReader(new StringReader(event.getJson()));
           String eventState = eventJson.getString("state", null);            
            
            if (TopicEventType.WORKFLOW_INSTANCE.equals(event.getMetadata().getType())) {   
              if ("WORKFLOW_INSTANCE_CREATED".equals(eventState)) { //event.getState() not possible yet
                final WorkflowInstanceEventImpl workflowInstanceEvent = msgPackMapper.convert(((TopicEventImpl)event).getAsMsgPack(), WorkflowInstanceEventImpl.class);
                workflowInstanceEvent.updateMetadata(event.getMetadata());
                workflowInstanceEvent.getPayload();

`

Which even fails without me having any idea why:

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ((CTRL-CHAR, code 135)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@44581de9; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689) ~[jackson-core-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[jackson-core-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[jackson-databind-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.9.jar:2.8.9]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2945) ~[jackson-databind-2.8.9.jar:2.8.9]
	at io.zeebe.client.impl.data.MsgPackMapper.convert(MsgPackMapper.java:34) ~[zeebe-client-java-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	... 19 common frames omitted
```

Please provide a proper way of accessing payload (applicable to at least WorkflowDefinitions (BPMN XML) and WorkflowInstances (JSON Payload).

**Comment by saig0** [comment]
@berndruecker , you can use a workflowInstanceEventHandler instead of a generic handler. The workflow instance event has a get to retrieve the JSON payload.

```java
final TopicSubscription topicSubscription = client.topics().newSubscription(TOPIC)
            .name("app-monitoring")
            .startAtHeadOfTopic()
            .workflowInstanceEventHandler(event ->
            {
                String payload = event.getPayload();
                // ....
            })
            .open();
```

**Comment by berndruecker** [comment]
But I also want to read "WORKFLOW_DEFINITION_DEPLOYED", that's not on the WorkflowInstanceEvent handler - isn't it? That would be totally confusing ;-)

Also I thought that the generic handler serves the use case to inspect everything going on in the broker - to e.g. build a monitoring. So I see it as a valid use case

**Comment by saig0** [comment]
In case of the "WORKFLOW_DEFINITION_DEPLOYED", you can use a `workflowEventHandler`.

**Comment by berndruecker** [comment]
So I have to open 2 different streams to get the information together? What is the use case for the TopicEventHandler then?

**Comment by saig0** [comment]
You can register multiple handlers for different event types on one subscription, e.g. open a subscription with a worklowInstance + workflow handler.

I'm not sure about the use case, but you can use the TopicEventHandler for simple logging or working with JSON object. Your example may work if you've a topic event and a (Jackson) JSON mapper:  `new ObjectMapper().readValue(event.getJson(), WorkflowInstanceEventImpl.class`. The payload needs to converted via `MsgPackConverter`.

**Comment by berndruecker** [comment]
I still struggle with the best practice for this use case - but I can move along for the moment. It does work using Jackson, but you have to inject the MsgPackConverter:

```
                    final ObjectMapper objectMapper = new ObjectMapper();
                    objectMapper.setInjectableValues(new InjectableValues.Std().addValue(MsgPackConverter.class, new MsgPackConverter()));
                    final WorkflowInstanceEventImpl workflowInstanceEvent = objectMapper.readValue(event.getJson(), WorkflowInstanceEventImpl.class);
```

Thanks!
We can close the issue for now - let's see what other users make out of it :-)
