### ISSUE TITLE
Investigate call already canceled exception

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3767]
**Description**

We see often reports from users, which say they see these exceptions quite often.
In our benchmark we also saw these exception quite often but we expected this is related to pod restarts etc. But this seem not to be the case

```
I 2020-01-30T03:17:21.480895200Z io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:73) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:95) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:191) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-01-30T03:21:04.785733744Z io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:73) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:95) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:191) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-01-30T03:27:43.325894914Z io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:341) ~[grpc-stub-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.onResponse(LongPollingActivateJobsRequest.java:87) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onResponse$5(LongPollingActivateJobsHandler.java:124) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-01-30T03:27:43.326134392Z io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:73) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 

```

These logs were printed without any pod restart. I would like to understand why this happens.

**Comment by npepinpe** [comment]
Hm, could it be something to do with keep alive? What if your requests gets killed by a middleware component (e.g. nginx ingress controller, a reverse proxy, etc.)? From the Gateway pov, would that be an already cancelled request?

**Comment by Zelldon** [comment]
Probably but in our benchmarks we have no proxy nor nginx :thinking:

**Comment by npepinpe** [comment]
I was referring to our users complaining about this; for our benchmark I'm not sure, tbh. What's the behaviour if the client times out, from the gateway pov? Does it seem like the request is cancelled?

**Comment by Zelldon** [comment]
> I was referring to our users complaining about this; for our benchmark I'm not sure, tbh. What's the behaviour if the client times out, from the gateway pov? Does it seem like the request is cancelled?

Ah ok. Yes actually on the long polling for example we check whether this connection was already canceled or not.

**Comment by strawhat5** [comment]
Hi @Zelldon ,

We have been using Zeebe for more than a month now, and this error is really becoming annoying now. Just the sheer amount of logs that it generates is ridiculous, and that too in `WARN` level. We have been running Zeebe at `LOG_LEVEL: DEBUG` with low load, and this warning is generating almost 50% of the logs.

Since this is a harmless warning, and is being generated for all Long Polling workers (attached my logs), could you suppress it in the next sub-release (maybe, 0.22.2)? 🤔 Or, it would be even better if there is any way to suppress it right now (other than setting log level to ERROR).

<details><summary>Stacktrace</summary>
 <p>

```
zeebe_broker | 2020-02-01 14:55:38.252 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"payment-service","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type payment-service after timeout of PT20S
zeebe_broker | 2020-02-01 14:55:38.256 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-0] WARN  io.zeebe.gateway - Failed to complete BrokerActivateJobsRequest{requestDto={"type":"payment-service","worker":"default","timeout":300000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}}
zeebe_broker | io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
zeebe_broker | 	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
zeebe_broker | 	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368) ~[grpc-stub-1.26.0.jar:1.26.0]
zeebe_broker | 	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.complete(LongPollingActivateJobsRequest.java:73) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.timeout(LongPollingActivateJobsRequest.java:95) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$addTimeOut$9(LongPollingActivateJobsHandler.java:191) ~[zeebe-gateway-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
```

</p>
</details>

**Comment by npepinpe** [comment]
So the fix seems relatively easy, we can check before completing a request if it has been cancelled, completed, or timed out already (I imagine there is a possibility of race conditions but it should already mitigate it a lot). But I'm wondering, how helpful it is to even log this exception at all - let's say we downgrade this to trace, what information do we lose, really? From the gRPC docs, CANCELLED is mostly used to indicate a client has cancelled the request (I don't think it's possible for the server side to actually cancel calls without shutting down), which is a valid possibility - not sure it warrants logging it. It seems the gRPC Java team is aware of this (https://github.com/grpc/grpc-java/issues/5061) and they've added a work-around - setting a callback to be executed on cancellation (instead of throwing an exception). This however requires us, on every call, to cast the stream observer, add a callback, and...do nothing? I'm not sure what I prefer :thinking:

**Comment by Zelldon** [comment]
I thought that I added something like that already on the long polling to check whether the connection is already cancelled or not.😅🤔 Maybe for sending the activate response idk 🤷‍♂️ yes i think we can also remove the log

**Comment by npepinpe** [comment]
For the long polling, we have a check if it's already completed, but not cancelled or timed out (though the methods are there, so it looks like we were going to?). 

Adding a check in the `LongPollingActivateJobsRequest` is not enough anyway, as we sometimes also complete other requests after they've been cancelled, so we basically have three choices:

1. Cast the `streamObserver` to `ServerCallStreamObserver<GrpcResponseT>` (which, tbh, I'm not sure why we don't **already** get a `ServerCallStreamObserver` :thinking:), then add a cancellation listener, as described in https://github.com/grpc/grpc-java/issues/5061, or
2. We can also check ourselves for every call before responding if it has already been cancelled - I'm not sure if there'd be any race condition with this though, e.g. `isCancelled()` returns false but then it gets cancelled in between the branch and the `onComplete(...)` call, or...
3. We handle the exception and simply suppress it if it is a `CANCELLED` status

I would go with either 1 or 3 - probably 1. I'm not a fan of the extra cast on every request, but at the same time I'd rather that than us throwing a useless exception we end up suppressing.
