### ISSUE TITLE
NPE on client command if lost leader role

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#379]
When a broker loses the leadership of a raft cluster it triggers a NPE on receiving a client request. This may be caused by raft not stopping the log stream service fast enough.

```
java.lang.NullPointerException                                                                                                      
        at io.zeebe.logstreams.log.LogStreamWriterImpl.claimLogEntry(LogStreamWriterImpl.java:229)                                  
        at io.zeebe.logstreams.log.LogStreamWriterImpl.tryWrite(LogStreamWriterImpl.java:171)                                       
        at io.zeebe.broker.transport.clientapi.ClientApiMessageHandler.handleExecuteCommandRequest(ClientApiMessageHandler.java:175)
        at io.zeebe.broker.transport.clientapi.ClientApiMessageHandler.onRequest(ClientApiMessageHandler.java:307)                  
        at io.zeebe.transport.impl.ServerReceiveHandler.onFragment(ServerReceiveHandler.java:75)                                    
        at io.zeebe.transport.impl.TransportChannel.handleMessage(TransportChannel.java:151)                                        
        at io.zeebe.transport.impl.TransportChannel.receive(TransportChannel.java:123)                                              
        at io.zeebe.transport.impl.selector.ReadTransportPoller.pollNow(ReadTransportPoller.java:44)
        at io.zeebe.transport.impl.actor.Receiver.doWork(Receiver.java:43)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:747)

```

**Comment by meyerdan** [comment]
Let's cose and see if it reappears.
