### ISSUE TITLE
Unexpected performance drop after elastic and worker restart

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3866]
**Describe the bug**

On investigating snapshot configurations https://github.com/zeebe-io/zeebe/issues/3760 I run several benchmarks one of them (the steady state) had a complete processing stop after elastic was shutdown and restarted by k8's. At the same time also 2 workers have been restarted.

![run](https://user-images.githubusercontent.com/2758593/74722779-caf6b200-5239-11ea-9011-a9b550f7c7e4.png)

Only after a leader change at 2 am the processing seem to start again, but still quite low.
![raft-leader](https://user-images.githubusercontent.com/2758593/74723103-4f493500-523a-11ea-9f51-303548fdbaee.png)

In the metrics we can see that we only receive requests on partition one. In the logs we have endless deadline exceed exceptions. 

The topology on broker 2 is also not correct.

```[zell ~/ ns:zell-snapshot-steady-state]$ k exec -it zell-snapshot-steady-state-zeebe-1 -- zbctl --insecure status
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.23.0-SNAPSHOT
Brokers:
  Broker 0 - zell-snapshot-steady-state-zeebe-0.zell-snapshot-steady-state-zeebe.zell-snapshot-steady-state.svc.cluster.local:26501
    Version: 0.23.0-SNAPSHOT
    Partition 1 : Leader
    Partition 2 : Leader
    Partition 3 : Leader
  Broker 1 - zell-snapshot-steady-state-zeebe-1.zell-snapshot-steady-state-zeebe.zell-snapshot-steady-state.svc.cluster.local:26501
    Version: 0.23.0-SNAPSHOT
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 2 - zell-snapshot-steady-state-zeebe-2.zell-snapshot-steady-state-zeebe.zell-snapshot-steady-state.svc.cluster.local:26501
    Version: 0.23.0-SNAPSHOT
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
[zell ~/ ns:zell-snapshot-steady-state]$ k exec -it zell-snapshot-steady-state-zeebe-2 -- zbctl --insecure status
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.23.0-SNAPSHOT
Brokers:
  Broker 0 - zell-snapshot-steady-state-zeebe-0.zell-snapshot-steady-state-zeebe.zell-snapshot-steady-state.svc.cluster.local:26501
    Version: 0.23.0-SNAPSHOT
    Partition 1 : Leader
    Partition 2 : Leader
  Broker 1 - zell-snapshot-steady-state-zeebe-1.zell-snapshot-steady-state-zeebe.zell-snapshot-steady-state.svc.cluster.local:26501
    Version: 0.23.0-SNAPSHOT
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 2 - zell-snapshot-steady-state-zeebe-2.zell-snapshot-steady-state-zeebe.zell-snapshot-steady-state.svc.cluster.local:26501
    Version: 0.23.0-SNAPSHOT
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
```

Configuration - default:

* 3 partitions
* 3 nodes
 * 3 repl. factor
 * 300 wfi/s
 * 12 workers
 * elastic exporter

**Comment by Zelldon** [comment]
I think the problem are the workers, which seem not be able to handle restarts. 

On another benchmark only workers are restarted by k8s and the same happend. The newly created worker pod was also never able to activate any jobs it always gets DEADLINE_EXCEEDED exception.

```
I 2020-02-17T17:02:46.201714229Z 17:02:46.192 [grpc-default-executor-1] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker benchmark-worker and job type benchmark-task
 
I 2020-02-17T17:02:46.201767635Z io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 71.998352542s. [remote_addr=zell-other-max-1-zeebe/10.0.15.4:26500]
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:?]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449) [app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [app.jar:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) [app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [app.jar:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) [app.jar:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:521) [app.jar:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) [app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:641) [app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:529) [app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:703) [app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:692) [app.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [app.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [app.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
 
I 2020-02-17T17:03:59.223065312Z 17:03:59.221 [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker benchmark-worker and job type benchmark-task
 ```

**Comment by Zelldon** [comment]
I think here the issue was more the worker and this issue is also a bit outdated
