### ISSUE TITLE
Leader is not able to replicate all snapshot chunks

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3887]
**Describe the bug**

Happend on Benchmark https://github.com/zeebe-io/zeebe/issues/3760#issuecomment-589020702

It seems that the leader is sometimes not able to read all chunks, which means it is not able to publish all chunks. 

```
I 2020-02-20T04:36:02.189023635Z 2020-02-20 04:36:02.188 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] ERROR io.zeebe.logstreams.snapshot - Unexpected error on reading snapshot chunk from file '/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004951.log'.
 
I 2020-02-20T04:36:02.189049029Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004951.log
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:?]
	at io.zeebe.logstreams.state.SnapshotChunkUtil.createSnapshotChunkFromFile(SnapshotChunkUtil.java:27) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.ReplicationController.replicate(ReplicationController.java:38) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.lambda$replicateLatestSnapshot$0(StateSnapshotController.java:83) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-20T04:36:02.189130793Z 2020-02-20 04:36:02.188 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004627.sst
 
I 2020-02-20T04:36:02.225991643Z 2020-02-20 04:36:02.225 [] [Broker-0-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 004464.sst of snapshot 51438185-6-1582173336362-121727963829496
 
I 2020-02-20T04:36:02.401261049Z 2020-02-20 04:36:02.400 [] [Broker-0-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 57/110
 
I 2020-02-20T04:36:02.905183001Z 2020-02-20 04:36:02.904 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004373.sst
 
I 2020-02-20T04:36:02.906476585Z 2020-02-20 04:36:02.906 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004857.sst
 
I 2020-02-20T04:36:02.918344811Z 2020-02-20 04:36:02.918 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004928.sst
 
I 2020-02-20T04:36:02.928218651Z 2020-02-20 04:36:02.927 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004599.sst
 
I 2020-02-20T04:36:03.078784998Z 2020-02-20 04:36:03.078 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/003878.sst
 
I 2020-02-20T04:36:03.078843920Z 2020-02-20 04:36:03.078 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004861.sst
 
I 2020-02-20T04:36:03.089334251Z 2020-02-20 04:36:03.089 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004854.sst
 
I 2020-02-20T04:36:03.182399454Z 2020-02-20 04:36:03.182 [] [Broker-0-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 004574.sst of snapshot 51438185-6-1582173336362-121727963829496
 
I 2020-02-20T04:36:03.262597282Z 2020-02-20 04:36:03.262 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004655.sst
 
I 2020-02-20T04:36:03.338229127Z 2020-02-20 04:36:03.337 [] [Broker-0-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 58/110
 
I 2020-02-20T04:36:03.541923590Z 2020-02-20 04:36:03.541 [] [Broker-0-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 004825.sst of snapshot 51438185-6-1582173336362-121727963829496
 
I 2020-02-20T04:36:03.643502865Z 2020-02-20 04:36:03.643 [] [Broker-0-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 59/110
 
I 2020-02-20T04:36:03.725007989Z 2020-02-20 04:36:03.724 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/MANIFEST-004359
 
I 2020-02-20T04:36:03.725608492Z 2020-02-20 04:36:03.725 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] ERROR io.zeebe.logstreams.snapshot - Unexpected error on reading snapshot chunk from file '/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/MANIFEST-004359'.
 
I 2020-02-20T04:36:03.725632146Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/MANIFEST-004359
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:?]
	at io.zeebe.logstreams.state.SnapshotChunkUtil.createSnapshotChunkFromFile(SnapshotChunkUtil.java:27) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.ReplicationController.replicate(ReplicationController.java:38) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.lambda$replicateLatestSnapshot$0(StateSnapshotController.java:83) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-20T04:36:03.725760797Z 2020-02-20 04:36:03.725 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004832.sst
 
I 2020-02-20T04:36:04.100359538Z 2020-02-20 04:36:04.100 [Broker-2-SnapshotDirector-1] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/51438185-6-1582173336362-121727963829496/004517.sst
 
```

I think this would mean that at the end the follower cant mark the snapshot as valid, since not all chunks have been received.

**Comment by npepinpe** [comment]
Is it possible we're trying to replicate snapshots while deleting them? Was that with max snapshot count 1?

**Comment by Zelldon** [comment]
Yes with count 1. Could be. But this would mean we need more then 15 min to replicate it?

**Comment by Zelldon** [comment]
Furthermore I would expect that all others after the first one which failed are also missing :man_shrugging:

**Comment by npepinpe** [comment]
True, if your interval is 15 minutes this seems strange. 

The other possibility is that we open the snapshot when it's committed to read the latest position, which results in some temporary files and may result in some clean up being done (I think they compact the MANIFEST? not 100% sure). There was already an issue with the LOCK file, so could be related?

**Comment by Zelldon** [comment]
would make sense we should investigate that

**Comment by Zelldon** [comment]
Actually I see this really often in the referenced benchmark.

**Comment by Zelldon** [comment]
It seems to happen also for sst files so I assume it is unrelated to RocksDB clean up ? @npepinpe 

```
I 2020-02-18T21:59:52.817199512Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003353.sst
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:?]
	at io.zeebe.logstreams.state.SnapshotChunkUtil.createSnapshotChunkFromFile(SnapshotChunkUtil.java:27) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.ReplicationController.replicate(ReplicationController.java:38) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.lambda$replicateLatestSnapshot$0(StateSnapshotController.java:83) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-18T21:59:52.817322515Z 2020-02-18 21:59:52.816 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003374.sst
 
I 2020-02-18T21:59:52.817327815Z 2020-02-18 21:59:52.816 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003377.log
 
I 2020-02-18T21:59:52.817411729Z 2020-02-18 21:59:52.816 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] ERROR io.zeebe.logstreams.snapshot - Unexpected error on reading snapshot chunk from file '/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003377.log'.
 
I 2020-02-18T21:59:52.817419185Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003377.log
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:?]
	at io.zeebe.logstreams.state.SnapshotChunkUtil.createSnapshotChunkFromFile(SnapshotChunkUtil.java:27) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.ReplicationController.replicate(ReplicationController.java:38) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.lambda$replicateLatestSnapshot$0(StateSnapshotController.java:83) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-18T21:59:52.817502726Z 2020-02-18 21:59:52.817 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003260.sst
 
I 2020-02-18T21:59:52.817734969Z 2020-02-18 21:59:52.817 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] ERROR io.zeebe.logstreams.snapshot - Unexpected error on reading snapshot chunk from file '/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003260.sst'.
 
I 2020-02-18T21:59:52.817793065Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003260.sst
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:?]
	at io.zeebe.logstreams.state.SnapshotChunkUtil.createSnapshotChunkFromFile(SnapshotChunkUtil.java:27) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.ReplicationController.replicate(ReplicationController.java:38) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.lambda$replicateLatestSnapshot$0(StateSnapshotController.java:83) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-18T21:59:52.817925094Z 2020-02-18 21:59:52.817 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003375.log
 
I 2020-02-18T21:59:52.818095733Z 2020-02-18 21:59:52.817 [Broker-0-SnapshotDirector-2] [Broker-0-zb-fs-workers-3] ERROR io.zeebe.logstreams.snapshot - Unexpected error on reading snapshot chunk from file '/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003375.log'.
 
I 2020-02-18T21:59:52.818113526Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/37797229-5-1582063190352-88721147752472/003375.log
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:?]
	at io.zeebe.logstreams.state.SnapshotChunkUtil.createSnapshotChunkFromFile(SnapshotChunkUtil.java:27) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.ReplicationController.replicate(ReplicationController.java:38) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.lambda$replicateLatestSnapshot$0(StateSnapshotController.java:83) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
```

**Comment by npepinpe** [comment]
Hm, yeah if it happens for SST files then those are immutable - they are only deleted once we delete the snapshot. I suppose if the snapshot is very large it might take a long time to replicate? :sa: 

Although from looking at the metrics you posted, replication time was well under 15 minutes, so we shouldn't be deleting a snapshot until we create the next one :thinking:

**Comment by Zelldon** [comment]
I had hoped that. This scares me a bit :sweat_smile:

**Comment by npepinpe** [comment]
So I was wrong, and RocksDB will compact SST files together, so no it's possible a background job removes an SST file while we're working with it - but now that we don't open snapshots anymore, this should be a non-issue. Should we tentatively close this?

**Comment by npepinpe** [comment]
The `AsyncSnapshotDirector` would commit the snapshot at index X + 1, which would delete the snapshot at index X, but the `LeaderRole` was in the middle of replicating X, hence the error. And as we now cause a shutdown of the partition on uncaught exception, this was causing a hard fail. So with https://github.com/zeebe-io/atomix/pull/197 we somewhat fixed this by preventing a hard failure to occur when we have expected issues (e.g. I/O).

I think we could still improve it to avoid having an error logged at all, but I'm not sure what is the best way, and the blast radius has been considerably reduced. @Zelldon @deepthidevaki any ideas?

**Comment by npepinpe** [comment]
After discussion, we can catch `NoSuchFileException` and log a warning, as opposed to an error on normal `IOExceptions`.

**Comment by npepinpe** [comment]
After discussing it with others, I think there is actually more work to be done here in a follow up issue where we properly deal with deleting snapshots that could be replicated by different components (e.g. `LeaderAppender` and `ReplicationController`). We could also simply delay this until we build state on the followers, at which point we will have a single replication mechanism again.

So for now I would mark this as closed.
