### ISSUE TITLE
Moving valid snapshot fails with zero maxSnapshotCount

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3889]
**Describe the bug**

With using max snapshot count zero I seeing exceptions on moving valid snapshots.

```
I 2020-02-20T14:23:10.262324650Z 2020-02-20 14:23:10.262 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 17785461840704 is committed, current commit position is 17785461848800. After that snapshot can be marked as valid.
 
I 2020-02-20T14:23:10.384128523Z 2020-02-20 14:23:10.382 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-3] ERROR io.zeebe.logstreams.snapshot - Unexpected exception occurred on moving valid snapshot.
 
I 2020-02-20T14:23:10.384162668Z java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.skip(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:160) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$0(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:222) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:130) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.commitSnapshot(AtomixSnapshotStorage.java:95) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.SnapshotStorage.commitSnapshot(SnapshotStorage.java:48) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.commitSnapshot(StateSnapshotController.java:67) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$onCommitCheck$4(AsyncSnapshotDirector.java:177) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-20T14:23:10.968051307Z 2020-02-20 14:23:10.967 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Created snapshot for Broker-2-StreamProcessor-3
 
I 2020-02-20T14:23:10.968227659Z 2020-02-20 14:23:10.967 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 14675905108864 is committed, current commit position is 14675905108864. After that snapshot can be marked as valid.
 
I 2020-02-20T14:23:11.133494304Z 2020-02-20 14:23:11.132 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-2] ERROR io.zeebe.logstreams.snapshot - Unexpected exception occurred on moving valid snapshot.
 
I 2020-02-20T14:23:11.133525097Z java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.skip(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:160) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$0(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:222) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:130) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.commitSnapshot(AtomixSnapshotStorage.java:95) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.SnapshotStorage.commitSnapshot(SnapshotStorage.java:48) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.commitSnapshot(StateSnapshotController.java:67) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$onCommitCheck$4(AsyncSnapshotDirector.java:177) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-20T14:23:12.222074479Z 2020-02-20 14:23:12.221 [] [raft-server-2-raft-partition-partition-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@156a2374)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@69c9fc23]
 
I 2020-02-20T14:23:12.222905305Z 2020-02-20 14:23:12.222 [] [raft-server-2-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The last processed position for snapshot /usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431 is 17828415826080
 
I 2020-02-20T14:23:12.239152342Z 2020-02-20 14:23:12.237 [] [raft-server-2-raft-partition-partition-1] ERROR io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Failed to commit pending snapshot DbPendingSnapshot{index=7581936, term=1, timestamp=2020-02-20 02:23:09,431, directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431}, rolling back
 
I 2020-02-20T14:23:12.239220211Z java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.skip(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:160) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$0(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:222) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:143) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot.commit(DbPendingSnapshot.java:114) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.atomix.protocols.raft.roles.PassiveRole.onInstall(PassiveRole.java:306) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.roles.FollowerRole.onInstall(FollowerRole.java:81) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$null$10(RaftContext.java:218) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:255) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200214.153010-125.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-02-20T14:23:12.247462006Z 2020-02-20 14:23:12.239 [] [raft-server-2-raft-partition-partition-1] WARN  io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot - Failed to delete pending snapshot DbPendingSnapshot{index=7581936, term=1, timestamp=2020-02-20 02:23:09,431, directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431}
 
I 2020-02-20T14:23:12.247505472Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:41) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot.abort(DbPendingSnapshot.java:120) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.atomix.protocols.raft.roles.PassiveRole.abortPendingSnapshot(PassiveRole.java:521) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.roles.PassiveRole.onInstall(PassiveRole.java:314) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.roles.FollowerRole.onInstall(FollowerRole.java:81) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$null$10(RaftContext.java:218) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:255) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200214.153010-125.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-02-20T14:23:12.248386380Z 2020-02-20 14:23:12.247 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - Failed to install 2
 
I 2020-02-20T14:23:12.684790704Z 2020-02-20 14:23:12.684 [] [raft-server-0-raft-partition-partition-3] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@5be3bbf8)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@4b1d46bc]
 

```

Actually I'm not 100% sure what I would expect by this setting. Probably that it is either not allowed to set it to zero **OR** it does not create any snapshots. But currently it takes snapshots and fails on moving them, which is not nice and unexpected.

**Comment by npepinpe** [comment]
Seems like I simple fix - we just need to decide what is the expected behavior: allow users to set 0 (meaning don't take snapshots - can be useful when testing), or enforce having a positive number of snapshots always.

Personally I would lean towards the latter, but let's hear some opinions.

**Comment by Zelldon** [comment]
> Seems like I simple fix - we just need to decide what is the expected behavior:

Correct.

> allow users to set 0 (meaning don't take snapshots - can be useful when testing),

Then we probably need to rename the property, because it is called maxSnapshotCount. Which somehow means this is the limit you have to reach until we start to compact. :man_shrugging: :sweat_smile: 

I would also vote for not permitting zero.

**Comment by jwulf** [comment]
If you disallow zero, the best UX would be to document that (including in comments in the config file), and set it to 1 if they provide anything less than 1 as a setting.

**Comment by menski** [comment]
The decision, we will remove the configuration of setting the number of snapshots and will always have a single snapshot, not configurable.

**Comment by jwulf** [comment]
Good, I like it. Sensible defaults and it just works out of the box.

**Comment by korthout** [comment]
The code needs to deal with multiple snapshots in multiple places, but it seems that it is no problem to keep that code for now. Currently, the code always carefully goes through the snapshots in reversed chronological order. Having only one snapshot does not change that. However, that code can be simplified.

This issue will thus only be used to remove the configuration setting and I'll add additional issues to simplify code (assumes only 1 snapshot) for the places I encounter.
