### ISSUE TITLE
Compaction is really IO intense and takes a long time in finding the right position

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3918]
**Description**
On investigating https://github.com/zeebe-io/zeebe/issues/3893 I found out that this patterns was related to our back pressure algorithm, which reacts on the processing latency. This latency is affected on higher IO, which is caused by snapshoting.

Further investigations showed me that the snapshot replication and removing pending snapshots is not the problematic part. It is more the compacting log, which is caused by taking snapshots.

We can also see this based on our metrics.

![run](https://user-images.githubusercontent.com/2758593/75167129-39011480-5725-11ea-8b7f-d5fec5d52cf7.png)
![io](https://user-images.githubusercontent.com/2758593/75167135-3999ab00-5725-11ea-9163-f1210623d97f.png)

In the panels above we can see that the processing degrades, this is because of the vegas limiter algorithm and it drops significantly from time to time (every 15 min ~ snapshot interval).
We see also that the read bytes per second spikes every 15 min. After we reached our max count we also spike really high - up to 100 Mb/s. The only thing what happens after reaching max count - is the log compaction, every thing else is the same as before. 

I added some log statements to see how long the deletion and seek takes. We can see that for example finding the corresponding index for a given position takes up to 15 seconds!

**Example benchmark**
Reached max count 3:

```
I 2020-02-24T15:18:26.350079529Z 2020-02-24 15:18:26.349 [Broker-0-LogStream-2] [Broker-1-zb-actors-3] INFO  io.zeebe.logstreams - Seek to position 2933468337552 took 7688 ms
 
I 2020-02-24T15:18:26.350115069Z 2020-02-24 15:18:26.349 [Broker-0-LogStream-2] [Broker-1-zb-actors-3] DEBUG io.zeebe.logstreams - Delete data from log stream until position '2933468337552' (address: '1263294').
 
I 2020-02-24T15:18:26.350835389Z 2020-02-24 15:18:26.350 [Broker-0-LogStream-2] [Broker-1-zb-actors-3] INFO  io.zeebe.logstreams - Deletion up to 1263294 took 1 ms
 
I 2020-02-24T15:18:26.351437752Z 2020-02-24 15:18:26.350 [] [raft-server-1-raft-partition-partition-2] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1 up to 1183302
 
I 2020-02-24T15:18:26.352655191Z 2020-02-24 15:18:26.352 [] [raft-partition-group-raft-partition-0] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 1183302
 
I 2020-02-24T15:18:27.344981201Z 2020-02-24 15:18:27.344 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 2937759615464 took 6253 ms
 
I 2020-02-24T15:18:27.345009142Z 2020-02-24 15:18:27.344 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.logstreams - Delete data from log stream until position '2937759615464' (address: '1264401').
 
I 2020-02-24T15:18:27.345014143Z 2020-02-24 15:18:27.344 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Deletion up to 1264401 took 0 ms
 
I 2020-02-24T15:18:27.345555299Z 2020-02-24 15:18:27.345 [] [raft-server-1-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1 up to 1183373
 
I 2020-02-24T15:18:27.346374583Z 2020-02-24 15:18:27.345 [] [raft-partition-group-raft-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 1183373
 
I 2020-02-24T15:18:32.284897548Z 2020-02-24 15:18:32.284 [Broker-0-LogStream-3] [Broker-1-zb-actors-2] INFO  io.zeebe.logstreams - Seek to position 3075203967000 took 8487 ms
 
I 2020-02-24T15:18:32.284929336Z 2020-02-24 15:18:32.284 [Broker-0-LogStream-3] [Broker-1-zb-actors-2] DEBUG io.zeebe.logstreams - Delete data from log stream until position '3075203967000' (address: '1316732').
 
I 2020-02-24T15:18:32.284933844Z 2020-02-24 15:18:32.284 [Broker-0-LogStream-3] [Broker-1-zb-actors-2] INFO  io.zeebe.logstreams - Deletion up to 1316732 took 0 ms
 
```

next snapshot:
```
I 2020-02-24T15:33:26.666018222Z 2020-02-24 15:33:26.665 [Broker-0-LogStream-3] [Broker-1-zb-actors-3] DEBUG io.zeebe.logstreams - Delete data from log stream until position '5600645394064' (address: '2397183').
 
I 2020-02-24T15:33:26.666025470Z 2020-02-24 15:33:26.665 [Broker-0-LogStream-3] [Broker-1-zb-actors-3] INFO  io.zeebe.logstreams - Deletion up to 2397183 took 0 ms
 
I 2020-02-24T15:33:26.666296081Z 2020-02-24 15:33:26.666 [] [raft-server-1-raft-partition-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1295563 up to 2352554
 
I 2020-02-24T15:33:26.667620488Z 2020-02-24 15:33:26.666 [] [raft-partition-group-raft-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 2352554
 
I 2020-02-24T15:33:28.095583659Z 2020-02-24 15:33:28.095 [Broker-0-LogStream-2] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 5652184469112 took 8174 ms
 
I 2020-02-24T15:33:28.095617855Z 2020-02-24 15:33:28.095 [Broker-0-LogStream-2] [Broker-1-zb-actors-1] DEBUG io.zeebe.logstreams - Delete data from log stream until position '5652184469112' (address: '2434578').
 
I 2020-02-24T15:33:28.095625016Z 2020-02-24 15:33:28.095 [Broker-0-LogStream-2] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Deletion up to 2434578 took 0 ms
 
I 2020-02-24T15:33:28.095726711Z 2020-02-24 15:33:28.095 [] [raft-server-1-raft-partition-partition-2] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1183302 up to 2366614
 
I 2020-02-24T15:33:28.096260972Z 2020-02-24 15:33:28.096 [] [raft-partition-group-raft-partition-0] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 2366614
 
I 2020-02-24T15:33:30.786885198Z 2020-02-24 15:33:30.786 [Broker-0-LogStream-1] [Broker-1-zb-actors-2] INFO  io.zeebe.logstreams - Seek to position 5347238841808 took 7229 ms
 
I 2020-02-24T15:33:30.787972369Z 2020-02-24 15:33:30.786 [Broker-0-LogStream-1] [Broker-1-zb-actors-2] DEBUG io.zeebe.logstreams - Delete data from log stream until position '5347238841808' (address: '2300317').
 
I 2020-02-24T15:33:30.788039488Z 2020-02-24 15:33:30.787 [Broker-0-LogStream-1] [Broker-1-zb-actors-2] INFO  io.zeebe.logstreams - Deletion up to 2300317 took 0 ms
 
I 2020-02-24T15:33:30.788101493Z 2020-02-24 15:33:30.788 [] [raft-server-1-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1183373 up to 2245584
 
I 2020-02-24T15:33:30.789191552Z 2020-02-24 15:33:30.788 [] [raft-partition-group-raft-partition-4] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 2245584
 
I 2020-02-24T15:33:33.812166458Z 2020-02-24 15:33:33.806 [Broker-0-LogStream-3] [Broker-2-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 5600645394064 took 13617 ms
 
I 2020-02-24T15:33:33.812200492Z 2020-02-24 15:33:33.812 [Broker-0-LogStream-3] [Broker-2-zb-actors-1] DEBUG io.zeebe.logstreams - Delete data from log stream until position '5600645394064' (address: '2397183').
 
I 2020-02-24T15:33:33.812486584Z 2020-02-24 15:33:33.812 [Broker-0-LogStream-3] [Broker-2-zb-actors-1] INFO  io.zeebe.logstreams - Deletion up to 2397183 took 0 ms
 
I 2020-02-24T15:33:33.817448266Z 2020-02-24 15:33:33.817 [] [raft-server-2-raft-partition-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1295563 up to 2352554
 
I 2020-02-24T15:33:33.818754995Z 2020-02-24 15:33:33.817 [] [raft-partition-group-raft-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 2352554
 
I 2020-02-24T15:33:35.373560626Z 2020-02-24 15:33:35.365 [Broker-0-LogStream-3] [Broker-0-zb-actors-3] INFO  io.zeebe.logstreams - Seek to position 5600645394064 took 14851 ms
 
I 2020-02-24T15:33:35.373605257Z 2020-02-24 15:33:35.373 [Broker-0-LogStream-3] [Broker-0-zb-actors-3] DEBUG io.zeebe.logstreams - Delete data from log stream until position '5600645394064' (address: '2397183').
 
I 2020-02-24T15:33:35.373654383Z 2020-02-24 15:33:35.373 [Broker-0-LogStream-3] [Broker-0-zb-actors-3] INFO  io.zeebe.logstreams - Deletion up to 2397183 took 0 ms
 
I 2020-02-24T15:33:35.373790367Z 2020-02-24 15:33:35.373 [] [raft-server-0-raft-partition-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1295563 up to 2352554
 
I 2020-02-24T15:33:35.374861155Z 2020-02-24 15:33:35.374 [] [raft-partition-group-raft-partition-3] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 2352554
 
I 2020-02-24T15:33:38.375265395Z 2020-02-24 15:33:38.369 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-1-zb-actors-3] ERROR io.zeebe.gateway - Error handling gRPC request
 
I 2020-02-24T15:33:38.375290926Z io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request type command-api-1 timed out in 15000 milliseconds
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.27.1.jar:1.27.1]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:383) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:308) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:147) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:183) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
Caused by: java.util.concurrent.TimeoutException: Request type command-api-1 timed out in 15000 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:159) ~[atomix-cluster-3.2.0-20200214.153025-125.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-02-24T15:33:38.378032662Z 2020-02-24 15:33:38.377 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-1-zb-actors-3] ERROR io.zeebe.gateway - Error handling gRPC request
 

```

This also explains why we see directly after that deadline exceeded exceptions.

**Comment by Zelldon** [comment]
These seek times increase over time:

```
I 2020-02-24T15:33:33.812166458Z 2020-02-24 15:33:33.806 [Broker-0-LogStream-3] [Broker-2-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 5600645394064 took 13617 ms
 
I 2020-02-24T15:33:35.373560626Z 2020-02-24 15:33:35.365 [Broker-0-LogStream-3] [Broker-0-zb-actors-3] INFO  io.zeebe.logstreams - Seek to position 5600645394064 took 14851 ms
 
I 2020-02-24T15:33:39.158839570Z 2020-02-24 15:33:39.158 [Broker-0-LogStream-2] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - Seek to position 5652184469112 took 19005 ms
 
I 2020-02-24T15:33:39.213599857Z 2020-02-24 15:33:39.213 [Broker-0-LogStream-2] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 5652184469112 took 18862 ms
 
I 2020-02-24T15:33:39.532266621Z 2020-02-24 15:33:39.531 [Broker-0-LogStream-1] [Broker-0-zb-actors-2] INFO  io.zeebe.logstreams - Seek to position 5347238841808 took 16079 ms
 
I 2020-02-24T15:33:40.429668431Z 2020-02-24 15:33:40.429 [Broker-0-LogStream-1] [Broker-2-zb-actors-2] INFO  io.zeebe.logstreams - Seek to position 5347238841808 took 16638 ms
 
I 2020-02-24T15:48:26.346056413Z 2020-02-24 15:48:26.340 [Broker-0-LogStream-3] [Broker-1-zb-actors-3] INFO  io.zeebe.logstreams - Seek to position 8104609533592 took 9115 ms
 
I 2020-02-24T15:48:27.173227656Z 2020-02-24 15:48:27.172 [Broker-0-LogStream-2] [Broker-1-zb-actors-2] INFO  io.zeebe.logstreams - Seek to position 8495449716368 took 8451 ms
 
I 2020-02-24T15:48:27.755073788Z 2020-02-24 15:48:27.754 [Broker-0-LogStream-1] [Broker-1-zb-actors-0] INFO  io.zeebe.logstreams - Seek to position 7816840760616 took 8493 ms
 
I 2020-02-24T15:48:35.510217116Z 2020-02-24 15:48:35.504 [Broker-0-LogStream-3] [Broker-2-zb-actors-2] INFO  io.zeebe.logstreams - Seek to position 8104609533592 took 18614 ms
 
I 2020-02-24T15:48:37.965513617Z 2020-02-24 15:48:37.964 [Broker-0-LogStream-3] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Seek to position 8104609533592 took 20804 ms
 
I 2020-02-24T15:48:39.348515937Z 2020-02-24 15:48:39.348 [Broker-0-LogStream-2] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - Seek to position 8495449716368 took 20510 ms
 
I 2020-02-24T15:48:39.422918787Z 2020-02-24 15:48:39.422 [Broker-0-LogStream-1] [Broker-0-zb-actors-3] INFO  io.zeebe.logstreams - Seek to position 7816840760616 took 20372 ms
 
I 2020-02-24T15:48:39.448928783Z 2020-02-24 15:48:39.448 [Broker-0-LogStream-2] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 8495449716368 took 20497 ms
 
I 2020-02-24T15:48:40.009872505Z 2020-02-24 15:48:40.009 [Broker-0-LogStream-1] [Broker-2-zb-actors-3] INFO  io.zeebe.logstreams - Seek to position 7816840760616 took 20532 ms
 
```

**Comment by Zelldon** [comment]
We already described this issue here as well https://github.com/zeebe-io/zeebe/issues/3623

**Comment by Zelldon** [comment]
I added more log statements to see what takes so long. Interesting is that on followers it takes longer then on a leader. I assume because the internal index is not created?

**Broker 0 - Partition 1 Leader:**


```
I 2020-02-24T21:12:01.249224055Z 2020-02-24 21:12:01.249 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Invalidate buffer took: 0 ms
 
I 2020-02-24T21:12:01.249372444Z 2020-02-24 21:12:01.249 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Seek from 1265953 to pos 2933466957312 took: 0 ms
 
I 2020-02-24T21:12:01.249396856Z 2020-02-24 21:12:01.249 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 2933466957312 took 8233 ms
 
I 2020-02-24T21:12:01.249404337Z 2020-02-24 21:12:01.249 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Delete data from log stream until position '2933466957312' (address: '1265953').
 
I 2020-02-24T21:12:01.250823794Z 2020-02-24 21:12:01.250 [] [raft-server-0-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1 up to 1186284
 
I 2020-02-24T21:12:01.254367153Z 2020-02-24 21:12:01.252 [] [raft-partition-group-raft-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 1186284
 
I 2020-02-24T21:12:01.254712937Z 2020-02-24 21:12:01.254 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Deletion up to 1265953 took 5 ms
 
```
**Broker 1 - Partition 1 Follower:**
```
I 2020-02-24T21:12:07.247356067Z 2020-02-24 21:12:07.246 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Lookup for pos 2933466957312 took: 13444 ms
 
I 2020-02-24T21:12:07.247388631Z 2020-02-24 21:12:07.247 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Invalidate buffer took: 0 ms
 
I 2020-02-24T21:12:07.247521318Z 2020-02-24 21:12:07.247 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Seek from 1265953 to pos 2933466957312 took: 0 ms
 
I 2020-02-24T21:12:07.247825392Z 2020-02-24 21:12:07.247 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Seek to position 2933466957312 took 13445 ms
 
I 2020-02-24T21:12:07.247890402Z 2020-02-24 21:12:07.247 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.logstreams - Delete data from log stream until position '2933466957312' (address: '1265953').
 
I 2020-02-24T21:12:07.253914033Z 2020-02-24 21:12:07.252 [] [raft-server-1-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting log up from 1 up to 1186284
 
I 2020-02-24T21:12:07.254734708Z 2020-02-24 21:12:07.254 [Broker-0-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Deletion up to 1265953 took 7 ms
 
I 2020-02-24T21:12:07.256343602Z 2020-02-24 21:12:07.255 [] [raft-partition-group-raft-partition-0] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - Compacting up to index 1186284
 
I 2020-02-24T21:12:08.624682957Z 2020-02-24 21:12:08.624 [] [raft-partition-group-raft-partition-0] INFO  io.zeebe.logstreams - Compaction for index 1265953 took 1377 ms
 
```

**Comment by npepinpe** [comment]
I was thinking, regarding compaction, we currently receive the snapshot and do a lookup of the position -> index so we know where to compact - but part of the snapshot metadata already carries a lower bound index for compaction we could use. The problem right now is that our abstraction was built such that the log stream is in charge of deletion, which I'm starting to think is the wrong idea.

We could remove this, as our log storage is really just an adapter for the underlying Raft log, and we could delegate the compaction directly to the `RaftPartitionServer` from the `DeletionService` without going through the log stream. We could then use the index only without even opening the snapshot or performing a lookup.
