### ISSUE TITLE
Race condition when closing the broker

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#398]
I sometimes see this error which could be cause by closing the log stream before closing the stream processors.

```
14:28:56.398 [actor-runner-broker-2] ERROR io.zeebe.logstreams - Stream processor 'log.default-topic.0.subscription.management' failed.
java.lang.IllegalStateException: log storage is already closed
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.ensureOpenedStorage(FsLogStorage.java:505) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:228) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:222) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readMore(BufferedLogStreamReader.java:314) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:397) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:292) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:283) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:131) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [zb-util-0.1.0.jar:0.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
14:28:56.398 [actor-runner-broker-1] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.0.processor.instance' failed.
java.lang.NullPointerException: null
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:135) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:254) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:239) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:222) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readMore(BufferedLogStreamReader.java:314) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:397) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:292) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:283) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:131) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:145) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [zb-util-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [zb-util-0.1.0.jar:0.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by ThorbenLindhauer** [comment]
I believe this issue can be solved by introducing a service dependency from the log stream service to the raft service. Reasoning: The raft service manages the log stream (i.e. on close, it closes the log stream which in turn closes the log storage and invalidates the log segments), but without the dependency the log stream service and any dependent stream processors may still be running.

**Comment by menski** [comment]
Thanks for fixing :cookie:
