### ISSUE TITLE
Benchmark starter is not able to handle broker restarts

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4023]
It seems that after a broker restart it can happen that the starter still sends to the same gateway and is not able to start new instances until it also restarted.

it happened in one of our long running tests.

![processing](https://user-images.githubusercontent.com/2758593/73545411-9910dd80-443b-11ea-888c-65576d9c6102.png)

We can see that at ~13 o'clock one broker was restarted. The processing went down completely. 
The starter starts to log 

```
I 2020-01-29T12:02:32.143883351Z 12:02:32.142 [Thread-1] WARN  io.zeebe.ResponseChecker - Request failed
 
I 2020-01-29T12:02:32.143913255Z java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 61.999986716s. [remote_addr=long-running-zeebe/10.0.4.16:26500]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_212]
	at io.zeebe.ResponseChecker.run(ResponseChecker.java:41) [app.jar:?]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 61.999986716s. [remote_addr=long-running-zeebe/10.0.4.16:26500]
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:?]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449) ~[app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[app.jar:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[app.jar:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:521) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:641) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:529) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:703) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:692) ~[app.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[app.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[app.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
 
I 2020-01-29T12:02:32.144760986Z 12:02:32.143 [Thread-1] WARN  io.zeebe.ResponseChecker - Request failed
 
I 2020-01-29T12:02:32.144805624Z java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 61.999987226s. [remote_addr=long-running-zeebe/10.0.4.16:26500]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_212]
	at io.zeebe.ResponseChecker.run(ResponseChecker.java:41) [app.jar:?]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 61.999987226s. [remote_addr=long-running-zeebe/10.0.4.16:26500]
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:?]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449) ~[app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[app.jar:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[app.jar:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:521) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:641) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:529) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:703) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:692) ~[app.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[app.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[app.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
 
I 2020-01-29T12:02:32.156105383Z 12:02:32.154 [Thread-1] WARN  io.zeebe.ResponseChecker - Request failed
 
I 2020-01-29T12:02:32.156138419Z java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 61.999984593s. [remote_addr=long-running-zeebe/10.0.4.16:26500]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_212]
	at io.zeebe.ResponseChecker.run(ResponseChecker.java:41) [app.jar:?]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 61.999984593s. [remote_addr=long-running-zeebe/10.0.4.16:26500]
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:?]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449) ~[app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[app.jar:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[app.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[app.jar:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:521) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:641) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:529) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:703) ~[app.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:692) ~[app.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[app.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[app.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
 
```

It went out of memory at some time but is was not directly restarted :thinking: 
```
I 2020-01-26T02:51:58.926137780Z java.lang.OutOfMemoryError: GC overhead limit exceeded
 
I 2020-01-29T12:03:58.617398980Z java.lang.OutOfMemoryError: GC overhead limit exceeded
 
E 2020-01-29T12:05:06.523995521Z Exception in thread "grpc-default-executor-30" java.lang.OutOfMemoryError: GC overhead limit exceeded
 
E 2020-01-29T12:05:22.036516158Z Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "grpc-nio-worker-ELG-1-2"
 
E 2020-01-29T12:12:34.222714095Z Exception in thread "grpc-nio-worker-ELG-1-1" java.lang.OutOfMemoryError: Java heap space
 
```

K8s restarted the pod after some time then processing started again.

**Comment by npepinpe** [comment]
Please verify if this is still the case, then we can reassess.

**Comment by Zelldon** [comment]
I think this no longer happens.

 * I haven't seen this for a while
 *  We now use standalone gw in our benchmarks 
 * we have several chaos tests were we restart or disconnect the gateway and this haven't been reproduced

For these reason I will close this for now. Feel free to reopen it.
