### ISSUE TITLE
java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by danielccyr** [zeebe-io/zeebe#403]
I'm following the instructions [here](https://docs.zeebe.io/java-client/get-started.html) and I get:

```
Connected.
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.zeebe.transport.impl.TransportChannel.finishConnect(TransportChannel.java:261)
	at io.zeebe.transport.impl.selector.ConnectTransportPoller.processKey(ConnectTransportPoller.java:128)
	at org.agrona.nio.NioSelectedKeySet.forEach(NioSelectedKeySet.java:136)
	at io.zeebe.transport.impl.selector.ConnectTransportPoller.pollNow(ConnectTransportPoller.java:111)
	at io.zeebe.transport.impl.selector.ConnectTransportPoller.doWork(ConnectTransportPoller.java:52)
	at io.zeebe.transport.impl.actor.ClientConductor.doWork(ClientConductor.java:43)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
	at java.lang.Thread.run(Thread.java:745)
Closed.
```

**Comment by menski** [comment]
How did you started the broker?

**Comment by menski** [comment]
I will close this as we didn't get any response
