### ISSUE TITLE
Nullpointer on enforcing snapshot

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4085]
**Describe the bug**

```
I 2020-03-20T02:49:13.242334839Z 2020-03-20 02:49:13.242 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Enforce snapshot creation. Last successful processed position is -1.
 
I 2020-03-20T02:49:13.251094391Z 2020-03-20 02:49:13.250 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - No previous entry found for position -1, cannot take snapshot
 
I 2020-03-20T02:49:13.251162808Z 2020-03-20 02:49:13.250 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] ERROR io.zeebe.logstreams.snapshot - Unexpected exception occurred on creating snapshot, was enforced to do so.
 
I 2020-03-20T02:49:13.251168072Z java.lang.NullPointerException: null
	at io.zeebe.logstreams.state.StateSnapshotController.takeSnapshot(StateSnapshotController.java:52) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.enforceSnapshotCreation(AsyncSnapshotDirector.java:234) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$0(AsyncSnapshotDirector.java:106) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-03-20T02:49:13.251504295Z 2020-03-20 02:49:13.251 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-SnapshotDirector-1 successfully
 

```

**Comment by npepinpe** [comment]
Looks like we tried to take a snapshot for a position that we couldn't find on the log. We can easily handle the NPE (and we should), but is this a valid case? Attempting to take a snapshot for a position that is not found in the log? Seems to indicate a bigger problem :thinking:
