### ISSUE TITLE
Workers print warning that sun.reflect.Reflection.getCallerClass is not supported

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4106]
**Description**

```
I 2020-03-22T16:32:52.377033650Z java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request type command-api-1 timed out in 15000 milliseconds
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at io.zeebe.ResponseChecker.run(ResponseChecker.java:41) [app.jar:0.23.0-SNAPSHOT]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request type command-api-1 timed out in 15000 milliseconds
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:0.23.0-SNAPSHOT]
	at me.dinowernli.grpc.prometheus.MonitoringClientCallListener.onClose(MonitoringClientCallListener.java:50) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[app.jar:0.23.0-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[app.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2020-03-22T16:55:33.441768023Z WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
 ```

This problem seems that we build with the shade plugin a multi release jar, but don't mark it as such, https://github.com/zeebe-io/zeebe/blob/develop/benchmarks/project/pom.xml#L123

Related bug issue:
https://issues.apache.org/jira/browse/LOG4J2-2537

**Comment by npepinpe** [comment]
Closing, feel free to fix it separately or if you're refactoring the worker already, but no need to dedicate time specifically for this.
