### ISSUE TITLE
io.zeebe.transport.impl.AtomixTransportTest#shouldRetryOnInvalidResponse[use different messaging service]

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4124]
**Describe the bug**

The following test `io.zeebe.transport.impl.AtomixTransportTest#shouldRetryOnInvalidResponse[use different messaging service]` some times fails on CI (but running it locally 4737 times it was always green). 

**Failure**

```
Error
expected:<[tru]e> but was:<[fals]e>
Stacktrace
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.transport.impl.AtomixTransportTest.shouldRetryOnInvalidResponse(AtomixTransportTest.java:185)
```

**Log**

<details><summary>Full Stacktrace</summary>
 <p>

```
Standard Output
09:16:17.090 [-zb-actors-5] ERROR io.zeebe.transport - Unexpected exception on handling request for partition 0.
java.lang.IllegalStateException: expected
	at io.zeebe.transport.impl.AtomixTransportTest.lambda$shouldFailResponseWhenRequestHandlerThrowsException$8(AtomixTransportTest.java:197) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixTransportTest$DirectlyResponder.onRequest(AtomixTransportTest.java:372) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixServerTransport.lambda$handleAtomixRequest$4(AtomixServerTransport.java:107) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:150) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
09:16:20.384 [-zb-actors-2] ERROR io.zeebe.transport - Unexpected exception on handling request for partition 0.
java.lang.IllegalStateException: expected
	at io.zeebe.transport.impl.AtomixTransportTest.lambda$shouldFailResponseWhenRequestHandlerThrowsException$8(AtomixTransportTest.java:197) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixTransportTest$DirectlyResponder.onRequest(AtomixTransportTest.java:372) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixServerTransport.lambda$handleAtomixRequest$4(AtomixServerTransport.java:107) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:150) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
```

</p>
</details>

**Comment by pihme** [comment]
Was in Top 3 flaky tests in CW 26

**Comment by Zelldon** [comment]
I'm not able to reproduce this.

**Comment by pihme** [comment]
New occurrence:

```
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.transport.impl.AtomixTransportTest.shouldRetryOnInvalidResponse(AtomixTransportTest.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

System out:
```
07:43:14.459 [-zb-actors-0] ERROR io.zeebe.transport - Unexpected exception on handling request for partition 0.
java.lang.IllegalStateException: expected
	at io.zeebe.transport.impl.AtomixTransportTest.lambda$shouldFailResponseWhenRequestHandlerThrowsException$8(AtomixTransportTest.java:198) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixTransportTest$DirectlyResponder.onRequest(AtomixTransportTest.java:387) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixServerTransport.lambda$handleAtomixRequest$4(AtomixServerTransport.java:107) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:151) ~[zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
07:43:17.959 [-zb-actors-5] ERROR io.zeebe.transport - Unexpected exception on handling request for partition 0.
java.lang.IllegalStateException: expected
	at io.zeebe.transport.impl.AtomixTransportTest.lambda$shouldFailResponseWhenRequestHandlerThrowsException$8(AtomixTransportTest.java:198) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixTransportTest$DirectlyResponder.onRequest(AtomixTransportTest.java:387) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixServerTransport.lambda$handleAtomixRequest$4(AtomixServerTransport.java:107) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:151) ~[zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
```

**Comment by pihme** [comment]
New occurrece:
```
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.transport.impl.AtomixTransportTest.shouldRetryOnInvalidResponse(AtomixTransportTest.java:186)
```

System out:
```
12:44:32.387 [-zb-actors-3] ERROR io.zeebe.transport - Unexpected exception on handling request for partition 0.
java.lang.IllegalStateException: expected
	at io.zeebe.transport.impl.AtomixTransportTest.lambda$shouldFailResponseWhenRequestHandlerThrowsException$8(AtomixTransportTest.java:198) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixTransportTest$DirectlyResponder.onRequest(AtomixTransportTest.java:387) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixServerTransport.lambda$handleAtomixRequest$4(AtomixServerTransport.java:107) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:151) ~[zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
12:44:36.076 [-zb-actors-0] ERROR io.zeebe.transport - Unexpected exception on handling request for partition 0.
java.lang.IllegalStateException: expected
	at io.zeebe.transport.impl.AtomixTransportTest.lambda$shouldFailResponseWhenRequestHandlerThrowsException$8(AtomixTransportTest.java:198) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixTransportTest$DirectlyResponder.onRequest(AtomixTransportTest.java:387) ~[test-classes/:?]
	at io.zeebe.transport.impl.AtomixServerTransport.lambda$handleAtomixRequest$4(AtomixServerTransport.java:107) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:151) ~[zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
```

**Comment by Zelldon** [comment]
I will take a look again

**Comment by Zelldon** [comment]
I added trace logging and run the branch in the CI several times https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/zell-atomix-transport/changes without luck 🙈😅

**Comment by Zelldon** [comment]
@pihme can you ping me if you see that again?

**Comment by pihme** [comment]
Sure

**Comment by pihme** [comment]
@Zelldon 
Happened again: https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/develop/1729/

I pressed the "Keep this build forever" button so that the link will remain valid. Once you are done, please tell INFRA to delete the build (they have the privileges to do so )

**Comment by Zelldon** [comment]
Thanks peter will take a look soon.

**Comment by pihme** [comment]
Further occurrences:
https://github.com/zeebe-io/zeebe/issues/4124

**Comment by deepthidevaki** [comment]
Following is the log from a failing build.

```
10:18:23.814 [] [main] INFO  io.zeebe.test - Test started: shouldRetryOnInvalidResponse[use different messaging service](io.zeebe.transport.impl.AtomixTransportTest)
10:18:23.817 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 31701 for test fork 6 with range PortRange{host='localhost', basePort=31700, maxOffset=100, currentOffset=2}
10:18:23.922 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:31701
10:18:23.924 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
10:18:23.926 [Broker-0-ServerTransport] [-zb-actors-4] TRACE io.zeebe.transport - Subscribe for topic command-api-0
10:18:23.928 [io.zeebe.transport.impl.AtomixClientTransportAdapter] [-zb-actors-4] TRACE io.zeebe.transport.impl.AtomixClientTransportAdapter - Send request 1260548796 to localhost:31701 with topic command-api-0
10:18:24.829 [Broker-0-ServerTransport] [-zb-actors-2] TRACE io.zeebe.transport - Handled request 0 for topic command-api-0
10:18:24.830 [Broker-0-ServerTransport] [-zb-actors-2] TRACE io.zeebe.transport - Send response to request 0 for topic command-api-0
10:18:24.841 [io.zeebe.transport.impl.AtomixClientTransportAdapter] [-zb-actors-0] TRACE io.zeebe.transport.impl.AtomixClientTransportAdapter - Got invalid response for request 1260548796, retry in PT0.01S.
10:18:24.931 [io.zeebe.transport.impl.AtomixClientTransportAdapter] [-zb-actors-0] TRACE io.zeebe.transport.impl.AtomixClientTransportAdapter - Send request 1260548796 to localhost:31701 with topic command-api-0
10:18:25.006 [Broker-0-ServerTransport] [-zb-actors-1] TRACE io.zeebe.transport - Handled request 1 for topic command-api-0
10:18:25.007 [Broker-0-ServerTransport] [-zb-actors-1] TRACE io.zeebe.transport - Send response to request 1 for topic command-api-0
10:18:25.020 [Broker-0-ServerTransport] [-zb-actors-4] TRACE io.zeebe.transport - Unsubscribe from topic command-api-0
10:18:25.022 [io.zeebe.transport.impl.AtomixClientTransportAdapter] [-zb-actors-4] TRACE io.zeebe.transport.impl.AtomixClientTransportAdapter - Got invalid response for request 1260548796, retry in PT0.01S.
10:18:25.146 [] [main] INFO  io.zeebe.test - Test finished: shouldRetryOnInvalidResponse[use different messaging service](io.zeebe.transport.impl.AtomixTransportTest)
```

It is retrying the request as expected. But it takes more than 1 second between the first attempt and second attempt. We only wait for 1 sec, so the test fails.

**Comment by npepinpe** [comment]
We could increase the time out, as it seems the test is correct, but would it make more sense here to avoid waiting on timing and use a controllable actor scheduler to control the execution?

**Comment by saig0** [comment]
To be more precise, not the retrying took longer than one second but the first response was sent with a delay of almost one second.

```
10:18:23.928 [io.zeebe.transport.impl.AtomixClientTransportAdapter] [-zb-actors-4] TRACE io.zeebe.transport.impl.AtomixClientTransportAdapter - Send request 1260548796 to localhost:31701 with topic command-api-0
10:18:24.829 [Broker-0-ServerTransport] [-zb-actors-2] TRACE io.zeebe.transport - Handled request 0 for topic command-api-0
```

**Comment by Zelldon** [comment]
Interesting. GC pauses?

Yes I think we can also try to control the time might be more predictable.

**Comment by saig0** [comment]
I could be GC or something in the actor scheduler. Hard to say.

Using `ControlledActorScheduler` is not easy. I tried but there is too much background work going on. The easiest fix would be to increase the timeout.

**Comment by Zelldon** [comment]
Then lets go with it
