### ISSUE TITLE
RaftTest#testCorrectTermInSnapshot is flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4176]
**Description**

```
java.lang.AssertionError: 
Expected :27
Actual   :23
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.atomix.raft.RaftTest.testCorrectTermInSnapshot(RaftTest.java:1526)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:53)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

<details>
<summary>log output</summary>
<pre>
21:18:19.645 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
21:18:19.647 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
21:18:19.649 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
21:18:19.658 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
21:18:19.688 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to FOLLOWER
21:18:20.454 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - No heartbeat from null in the last PT0.794S (calculated from last 794 ms), sending poll requests
21:18:20.455 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to CANDIDATE
21:18:20.455 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{2}{role=CANDIDATE} - Starting election
21:18:20.456 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to LEADER
21:18:20.456 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 2
21:18:20.472 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 2
21:18:20.480 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 2
21:18:20.724 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE
21:18:20.827 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - AppendRequest{term=1, leader=2, prevLogIndex=1, prevLogTerm=1, entries=1, commitIndex=1} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
21:18:20.835 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - AppendRequest{term=1, leader=2, prevLogIndex=2, prevLogTerm=1, entries=0, commitIndex=2} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
21:18:20.855 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - AppendRequest{term=1, leader=2, prevLogIndex=2, prevLogTerm=1, entries=0, commitIndex=3} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
21:18:20.887 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
21:18:20.887 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
21:18:20.887 [] INFO  io.atomix.raft.roles.LeaderRole - RaftServer{2}{role=LEADER} - Received greater term from 1
21:18:20.888 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
21:18:20.888 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
21:18:21.941 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{3}{role=FOLLOWER} - No heartbeat from null in the last PT1.068S (calculated from last 1068 ms), sending poll requests
21:18:21.942 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Accepted PollRequest{term=2, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
21:18:21.943 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to CANDIDATE
21:18:21.943 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{3}{role=CANDIDATE} - Starting election
21:18:21.945 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Accepted VoteRequest{term=3, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
21:18:21.945 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to LEADER
21:18:21.946 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 3
21:18:21.954 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - Accepted PollRequest{term=2, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
21:18:21.955 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 3
21:18:21.955 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - Accepted VoteRequest{term=3, candidate=3, lastLogIndex=23, lastLogTerm=1}: candidate's log is up-to-date
21:18:21.956 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 3
21:18:29.791 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to INACTIVE
21:18:29.795 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to INACTIVE
21:18:29.799 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE

java.lang.AssertionError: 
Expected :27
Actual   :23
<Click to see difference>

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.atomix.raft.RaftTest.testCorrectTermInSnapshot(RaftTest.java:1526)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:53)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

</pre>
</details>

A clear and concise description of what this issue is about.

**Comment by Zelldon** [comment]
superseded by #4258
