### ISSUE TITLE
Java Client implementation of OAuthCredentialsProvider OAuth spec complaint

### ISSUE THREAD

**Issue by nitindileep** [zeebe-io/zeebe#4215]
**Describe the bug**
The OAuth spec states that the Access token request must be made with Content-Type as "application/x-www-form-urlencoded" ([OAuth spec](https://tools.ietf.org/html/rfc6749#section-4.1.3)). However, the Java client implementation sends it in "application/json" format ([OAuthCredentialsProvider.java#L151](https://github.com/zeebe-io/zeebe/blob/90785d179e8e4c28e6a942eca69643716f7a3373/clients/java/src/main/java/io/zeebe/client/impl/oauth/OAuthCredentialsProvider.java#L151))
Due to this the access token request to a KeyCloak server is failing with the error 400: Bad Request

**To Reproduce**
1. Run KeyCloak in a docker container:
`docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:9.0.2`
2. Create a new client and copy the client credentials. Follow steps 2-5 from [Keycloak Camunda Identity Provider prerequisites](https://github.com/camunda/camunda-bpm-identity-keycloak#prerequisites-in-your-keycloak-realm)
3. Use the implementation of `OAuthCredentialsProvider` to build a ZeebeClient - [Official Documentation](https://docs.zeebe.io/operations/authorization.html#oauthcredentialsprovider)

If possible add a minimal reproducer code sample
 The same code available in the official Zeebe documentation for Authorization from Section [OAuthCredentialsProvider](https://docs.zeebe.io/operations/authorization.html#oauthcredentialsprovider) can be used

**Expected behavior**
The token request should be sent with the provided client_id and client_secret and the access_token should be added to the gRPC request header

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
14:38:26.674 [main] WARN io.zeebe.client.impl.oauth.OAuthCredentialsProvider - Failed while fetching credentials, will not add credentials to rpc: 
java.io.IOException: Failed while requesting access token with status code 400 and message Bad Request.
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:162)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:121)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.loadCredentials(OAuthCredentialsProvider.java:110)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:69)
	at io.zeebe.client.impl.ZeebeCallCredentials.applyRequestMetadata(ZeebeCallCredentials.java:44)
	at io.grpc.internal.CallCredentialsApplyingTransportFactory$CallCredentialsApplyingTransport.newStream(CallCredentialsApplyingTransportFactory.java:108)
	at io.grpc.internal.ForwardingConnectionClientTransport.newStream(ForwardingConnectionClientTransport.java:49)
	at io.grpc.internal.InternalSubchannel$CallTracingTransport.newStream(InternalSubchannel.java:635)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:261)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:190)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1.start(CensusTracingModule.java:394)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1.start(CensusStatsModule.java:695)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:315)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:287)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:272)
	at io.grpc.stub.ClientCalls.asyncUnaryCall(ClientCalls.java:65)
	at io.zeebe.gateway.protocol.GatewayGrpc$GatewayStub.topology(GatewayGrpc.java:996)
	at io.zeebe.client.impl.command.TopologyRequestImpl.send(TopologyRequestImpl.java:70)
	at io.zeebe.client.impl.command.TopologyRequestImpl.send(TopologyRequestImpl.java:61)
	at org.test.ZeebeWorkerApp$.delayedEndpoint$org$test$ZeebeWorkerApp$1(ZeebeWorkerApp.scala:39)
	at org.test.ZeebeWorkerApp$delayedInit$body.apply(ZeebeWorkerApp.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at org.test.ZeebeWorkerApp$.main(ZeebeWorkerApp.scala:9)
	at org.test.ZeebeWorkerApp.main(ZeebeWorkerApp.scala)
```

</p>
</details>

**Environment:**
 - OS: Mac
 - Zeebe Version: 0.22.0
 - Configuration: default

**Comment by npepinpe** [comment]
Hi @nitindileep, I believe this PR https://github.com/zeebe-io/zeebe/pull/4125 fixes those issues - it's not yet release but should be in the next stable release, next week (or, should any issues arise, the week after). With this PR we tested the client with both keycloak and hydra. Please let us know after the release if it does not work!

**Comment by nitindileep** [comment]
Hello @npepinpe, PR #4125 indeed seems to fix this issue. Is there perhaps an alpha build available to the general public which can be used to test the functionality?
