### ISSUE TITLE
TaskSubscriptionTest#shouldFetchAndHandleTasks fails

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#422]
```
java.lang.IllegalArgumentException: Can't access 133257786 max bucket buffer length is: 73348
	at io.zeebe.map.BucketBufferArray.getRealAddress(BucketBufferArray.java:115) ~[classes/:?]
	at io.zeebe.map.BucketBufferArray.getRealAddress(BucketBufferArray.java:108) ~[classes/:?]
	at io.zeebe.map.BucketBufferArray.getBucketDepth(BucketBufferArray.java:502) ~[classes/:?]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeSplitBucket(ZbMapBucketMergeHelper.java:386) ~[classes/:?]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMerging(ZbMapBucketMergeHelper.java:236) ~[classes/:?]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergingBuckets(ZbMapBucketMergeHelper.java:208) ~[classes/:?]
	at io.zeebe.map.ZbMap.remove(ZbMap.java:336) ~[classes/:?]
	at io.zeebe.map.Long2BytesZbMap.remove(Long2BytesZbMap.java:68) ~[classes/:?]
	at io.zeebe.broker.task.map.TaskInstanceMap.remove(TaskInstanceMap.java:75) ~[classes/:?]
	at io.zeebe.broker.task.processor.TaskInstanceStreamProcessor$CompleteTaskProcessor.updateState(TaskInstanceStreamProcessor.java:360) ~[classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$3(StreamProcessorController.java:363) ~[zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState$$Lambda$146/1291239341.work(Unknown Source) ~[?:?]
	at io.zeebe.util.state.ComposedState$FailSafeStep.doWork(ComposedState.java:41) ~[classes/:?]
	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[classes/:?]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [classes/:?]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [classes/:?]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:131) [zb-logstreams-0.1.0.jar:0.1.0]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:145) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

**Comment by ThorbenLindhauer** [comment]
Cannot reproduce. The root cause has probably been fixed in the meantime.
