### ISSUE TITLE
io.atomix.raft.RaftTest.testSnapshotSentOnDataLoss is flaky

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4302]
**Summary**

- How often does the test fail?  - Top3 flaky tests for CW 19
 
- Does it block your work? 
Not really, as it doesn't happen often
- Do we suspect that it is a real failure? 
I don't think so; could be related to the issues we have with bootstrap roles? Didn't really dig into it.

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error
Test timed out while waiting for an expected result, expectedResumes: 1, actualResumes: 0
Stacktrace
java.util.concurrent.TimeoutException: Test timed out while waiting for an expected result, expectedResumes: 1, actualResumes: 0
	at net.jodah.concurrentunit.Waiter.await(Waiter.java:184)
	at net.jodah.concurrentunit.Waiter.await(Waiter.java:128)
	at net.jodah.concurrentunit.ConcurrentTestCase.await(ConcurrentTestCase.java:103)
	at io.atomix.raft.RaftTest.recreateServerWithDataLoss(RaftTest.java:1613)
	at io.atomix.raft.RaftTest.testSnapshotSentOnDataLoss(RaftTest.java:1466)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
23:03:32.204 [] INFO  io.zeebe.test - Test finished: shouldFailOverOnLeaderDisconnect(io.atomix.raft.RaftTest)
23:03:32.204 [] INFO  io.zeebe.test - Test started: testSnapshotSentOnDataLoss(io.atomix.raft.RaftTest)
23:03:32.231 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
23:03:32.231 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
23:03:32.234 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
23:03:32.237 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to FOLLOWER
23:03:32.244 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to LEADER
23:03:32.245 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 1
23:03:32.249 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 1
23:03:32.249 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 1
23:03:42.606 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to INACTIVE
23:03:42.608 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to INACTIVE
23:03:42.609 [] WARN  io.atomix.utils.concurrent.SingleThreadContext - Execution of io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@38d1fe1b was rejected!
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7022af01[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@88b1d22[Wrapped task = io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@38d1fe1b]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@69bdedc4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 318]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.execute(SingleThreadContext.java:56) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext.execute(SingleThreadContext.java:150) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftServiceManager.compactLogs(RaftServiceManager.java:868) ~[classes/:?]
	at io.atomix.raft.impl.RaftServiceManager.tryToCompleteSnapshot(RaftServiceManager.java:838) ~[classes/:?]
	at io.atomix.raft.impl.RaftServiceManager.lambda$takeSnapshots$7(RaftServiceManager.java:770) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at io.atomix.raft.impl.RaftServiceManager.lambda$takeSnapshots$9(RaftServiceManager.java:800) ~[classes/:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
23:03:42.609 [] WARN  io.atomix.utils.concurrent.SingleThreadContext - Execution of io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@7a84c788 was rejected!
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4bb84c8e[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@33d3bb56[Wrapped task = io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@7a84c788]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2b2a91b4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 276]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.execute(SingleThreadContext.java:56) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext.execute(SingleThreadContext.java:150) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftServiceManager.compactLogs(RaftServiceManager.java:868) ~[classes/:?]
	at io.atomix.raft.impl.RaftServiceManager.tryToCompleteSnapshot(RaftServiceManager.java:838) ~[classes/:?]
	at io.atomix.raft.impl.RaftServiceManager.lambda$takeSnapshots$7(RaftServiceManager.java:770) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at io.atomix.raft.impl.RaftServiceManager.lambda$takeSnapshots$9(RaftServiceManager.java:800) ~[classes/:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
23:03:42.616 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
23:03:42.749 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=38, prevLogTerm=1, entries=0, commitIndex=38} to 3 failed: java.util.concurrent.CompletionException: java.net.ConnectException
23:03:42.754 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 1
23:03:42.757 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=38, prevLogTerm=1, entries=0, commitIndex=38} to 3 failed: java.util.concurrent.CompletionException: java.net.ConnectException
23:03:42.760 [] ERROR io.atomix.raft.impl.RaftContext - RaftServer{2} - An uncaught exception occurred, transition to inactive role
java.lang.IllegalStateException: Log writer inconsistent with next append entry index 38
	at io.atomix.raft.roles.PassiveRole.appendEntry(PassiveRole.java:881) ~[classes/:?]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:864) ~[classes/:?]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:813) ~[classes/:?]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:667) ~[classes/:?]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[classes/:?]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:197) ~[classes/:?]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$20(RaftContext.java:248) ~[classes/:?]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$31(RaftContext.java:278) ~[classes/:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
23:03:42.761 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to INACTIVE
23:03:42.999 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=38, prevLogTerm=1, entries=0, commitIndex=38} to 3 failed: java.util.concurrent.CompletionException: java.net.ConnectException
23:03:43.758 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=36, prevLogTerm=1, entries=2, commitIndex=38} to 2 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
23:03:44.000 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=38, prevLogTerm=1, entries=0, commitIndex=38} to 2 failed: RaftError{type=UNAVAILABLE, message=null}
23:03:44.000 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=38, prevLogTerm=1, entries=0, commitIndex=38} to 2 failed: RaftError{type=UNAVAILABLE, message=null}
23:03:51.000 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Suspected network partition after 6 failures from 3 over a period of time 6749 > 1500, stepping down
23:03:51.002 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
23:03:51.757 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.754S (calculated from last 754 ms), sending poll requests
23:03:51.758 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:52.742 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.984S (calculated from last 984 ms), sending poll requests
23:03:52.743 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:53.669 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.926S (calculated from last 926 ms), sending poll requests
23:03:53.669 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:54.826 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.156S (calculated from last 1156 ms), sending poll requests
23:03:54.826 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:55.733 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.906S (calculated from last 907 ms), sending poll requests
23:03:55.733 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:56.789 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.055S (calculated from last 1056 ms), sending poll requests
23:03:56.789 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:57.599 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.809S (calculated from last 810 ms), sending poll requests
23:03:57.599 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:58.446 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.846S (calculated from last 846 ms), sending poll requests
23:03:58.446 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:03:59.376 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.93S (calculated from last 930 ms), sending poll requests
23:03:59.377 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:00.486 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.109S (calculated from last 1109 ms), sending poll requests
23:04:00.487 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:01.855 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.368S (calculated from last 1368 ms), sending poll requests
23:04:01.856 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:02.739 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.883S (calculated from last 883 ms), sending poll requests
23:04:02.740 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:03.755 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.015S (calculated from last 1015 ms), sending poll requests
23:04:03.756 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:04.815 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.059S (calculated from last 1059 ms), sending poll requests
23:04:04.816 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:05.710 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.894S (calculated from last 894 ms), sending poll requests
23:04:05.711 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:06.534 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.823S (calculated from last 823 ms), sending poll requests
23:04:06.535 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:07.693 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.158S (calculated from last 1158 ms), sending poll requests
23:04:07.694 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:09.070 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.376S (calculated from last 1376 ms), sending poll requests
23:04:09.071 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:10.408 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT1.337S (calculated from last 1337 ms), sending poll requests
23:04:10.409 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:11.363 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.954S (calculated from last 954 ms), sending poll requests
23:04:11.364 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:12.226 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.862S (calculated from last 862 ms), sending poll requests
23:04:12.227 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - java.net.ConnectException
23:04:12.617 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE
</pre>
</details>

**Comment by pihme** [comment]
Test method no longer exists
