### ISSUE TITLE
Snapshot storage fails to delete push pending snapshot

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#4351]
**Describe the bug**

A single broker with a single partition and no replication factor, ends in a situation where a unparsable snapshot exists in the push pending section. It cannot be deleted and generates an exception and maybe affects other snapshot deletion.

**To Reproduce**

I don't know how this happend.

**Expected behavior**

Snapshot storage can always delete snapshots if required and does not fail with an inparsable name. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2020-04-22 12:00:18.846 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/1/pushed-pending/10709299-13-1587556818845.
2020-04-22 12:00:18.919 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Created snapshot for Broker-0-StreamProcessor-1
2020-04-22 12:00:18.921 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 3242700310344 is committed, current commit position is 3242700310344. After that snapshot can be marked as valid.
2020-04-22 12:00:18.922 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Current commit position 3242700310344 is greater then 3242700310344, snapshot is valid.
2020-04-22 12:00:18.949 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/10709299-13-1587556818845, metadata=DbSnapshotMetadata{index=10709299, term=13, timestamp=2020-04-22 12:00:18,845}}
2020-04-22 12:00:18.951 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/10709299-13-1587556339600, metadata=DbSnapshotMetadata{index=10709299, term=13, timestamp=2020-04-22 11:52:19,600}}
2020-04-22 12:00:19.057 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/10709299-13-1587556339600, metadata=DbSnapshotMetadata{index=10709299, term=13, timestamp=2020-04-22 11:52:19,600}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@1bfa70bc
2020-04-22 12:00:19.058 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Search for orphaned snapshots below oldest valid snapshot with index 10709299 in /usr/local/zeebe/data/raft-partition/partitions/1/pushed-pending
2020-04-22 12:00:19.059 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotMetadata - Failed to parse part of snapshot metadata
java.lang.NumberFormatException: For input string: "1587520597532.tmp"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Long.parseLong(Unknown Source) ~[?:?]
	at java.lang.Long.parseLong(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotMetadata.ofFileName(DbSnapshotMetadata.java:43) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotMetadata.ofPath(DbSnapshotMetadata.java:32) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.purgePendingSnapshot(AtomixSnapshotStorage.java:230) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.purgePendingSnapshots(AtomixSnapshotStorage.java:220) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:132) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$1(DbSnapshotStore.java:189) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:189) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:215) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:126) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.createNewCommittedSnapshot(AtomixSnapshotStorage.java:152) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.lambda$commitSnapshot$0(AtomixSnapshotStorage.java:75) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at java.util.Optional.flatMap(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.commitSnapshot(AtomixSnapshotStorage.java:75) ~[zeebe-broker-0.23.0.jar:0.23.0]
	at io.zeebe.logstreams.state.SnapshotStorage.commitSnapshot(SnapshotStorage.java:49) ~[zeebe-logstreams-0.23.0.jar:0.23.0]
	at io.zeebe.logstreams.state.StateSnapshotController.commitSnapshot(StateSnapshotController.java:64) ~[zeebe-logstreams-0.23.0.jar:0.23.0]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$onCommitCheck$7(AsyncSnapshotDirector.java:237) ~[zeebe-workflow-engine-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0.jar:0.23.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0.jar:0.23.0]
2020-04-22 12:00:19.062 [Broker-0-DeletionService-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 10709299
2020-04-22 12:00:19.063 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/10709299-13-1587556818845, metadata=DbSnapshotMetadata{index=10709299, term=13, timestamp=2020-04-22 12:00:18,845}}
```

</p>
</details>

Full Log: https://drive.google.com/open?id=1WDohRb8nDSCyJe2AN8w2OF4eMWQ1Wgj8
Data Dir: https://drive.google.com/open?id=1DNherx6unn7tPL8LfC9VyIt8UB52S8LG

**Environment:**
 - OS: Linux on k8s (Camunda Cloud)
 - Zeebe Version: 0.23.0

<details>
<summary>Configuration</summary>
<p>

```
{
  "network" : {
    "host" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
    "commandApi" : {
      "host" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "port" : 26501,
      "advertisedHost" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "advertisedPort" : 26501,
      "address" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:26501",
      "advertisedAddress" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:26501"
    },
    "internalApi" : {
      "host" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "port" : 26502,
      "advertisedHost" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "advertisedPort" : 26502,
      "address" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:26502",
      "advertisedAddress" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:26502"
    },
    "monitoringApi" : {
      "host" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "port" : 9600,
      "advertisedHost" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "advertisedPort" : 9600,
      "address" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:9600",
      "advertisedAddress" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:26502" ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 1,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://elasticsearch:9200",
        "bulk" : {
          "delay" : 5,
          "size" : 1000
        },
        "index" : {
          "prefix" : "zeebe-record",
          "createTemplate" : true,
          "command" : false,
          "event" : true,
          "rejection" : false,
          "deployment" : true,
          "incident" : true,
          "job" : true,
          "message" : false,
          "messageSubscription" : false,
          "raft" : false,
          "workflowInstance" : true,
          "workflowInstanceSubscription" : false
        }
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : true,
      "host" : "zeebe-0.zeebe-broker-service.26727dd0-f1b5-42d6-a550-ded95824e0e4-zeebe.svc.cluster.local",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}
```

</p>
</details>

**Comment by menski** [comment]
Another example:

Log: https://drive.google.com/open?id=1QiW66AN4jzVumXAXSYVwLpMf5iM7x49E
Data: https://drive.google.com/open?id=1qG3EgLuGYH_D7S8mQlMYwSVBsLM87ovB

**Comment by npepinpe** [comment]
For now prioritized as mid as we expect the impact to be low, but we should collect more data from running clusters in the cloud to have some idea of how many users are impacted, at which point we can re-prioritize it if need be.

**Comment by Zelldon** [comment]
With https://github.com/zeebe-io/zeebe/pull/4641 we rewrote the snapshotting and I can imagine that this will not appear anymore, which is the reason I will close this for now. If you see that again please reopen it.
