### ISSUE TITLE
Out of memory during release process

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#436]
During the 0.2.0 release of the zeebe repository the test suite runs out of memory, using the 4GB memory given to the docker container.

We either should increase the memory cap for the zeebe job docker container or reduce the memory consumption. First approach should be an easy fix. Later approach would be good in the long run.

#### Example log output

```
16:51:14 [ERROR] shouldCreateTopic(io.zeebe.broker.it.clustering.CreateTopicClusteredTest)  Time elapsed: 0.544 s  <<< ERROR!
16:51:14 java.lang.OutOfMemoryError: Direct buffer memory
16:51:14 	at java.nio.Bits.reserveMemory(Bits.java:693)
16:51:14 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
16:51:14 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
16:51:14 	at io.zeebe.util.allocation.DirectBufferAllocator.allocate(DirectBufferAllocator.java:28)
16:51:14 	at io.zeebe.util.allocation.BufferAllocators.allocateDirect(BufferAllocators.java:26)
16:51:14 	at io.zeebe.dispatcher.DispatcherBuilder.initAllocatedBuffer(DispatcherBuilder.java:266)
16:51:14 	at io.zeebe.dispatcher.DispatcherBuilder.build(DispatcherBuilder.java:198)
16:51:14 	at io.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:98)
16:51:14 	at io.zeebe.client.ZeebeClient.create(ZeebeClient.java:62)
16:51:14 	at io.zeebe.broker.it.ClientRule.before(ClientRule.java:52)
16:51:14 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
16:51:14 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
16:51:14 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
16:51:14 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
16:51:14 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:51:14 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
I temporally manually increased the memory limit of the ubuntu docker container to 6GB for the Zeebe Jenkins. Let's see if the test suite will stabilize with this change.

**Comment by menski** [comment]
I just monitored two runs of the zeebe distro jenkins job with a 6GB container memory limit. Both spiked at around 5.5GB memory usage during the test `io.zeebe.broker.it.clustering.CreateTopicClusteredTest`, which starts 3 brokers. It seems that the test timeout failures in the IT test suite are mainly triggered by out of memory issues as shown above.

To keep the test suite stable I will deploy a jenkins configured to provide the zeebe distro job a container with a 8GB memory limit. Nevertheless we may have another look if we can get the memory usage on broker startup down.
