### ISSUE TITLE
RaftTest.shouldFailOverOnLeaderDisconnect is flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4365]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? seen once so far
- Does it block your work? yes
- Do we suspect that it is a real failure? unknown

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Stacktrace

java.lang.NullPointerException
	at io.atomix.raft.RaftTest.shouldFailOverOnLeaderDisconnect(RaftTest.java:1823)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
01:15:16.195 [] INFO  io.zeebe.test - Test finished: testOneNodeCloseEvent(io.atomix.raft.RaftTest)
01:15:16.195 [] INFO  io.zeebe.test - Test started: shouldFailOverOnLeaderDisconnect(io.atomix.raft.RaftTest)
01:15:16.208 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
01:15:16.219 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
01:15:16.258 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to FOLLOWER
01:15:17.054 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.82S (calculated from last 845 ms), sending poll requests
01:15:17.055 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
01:15:17.055 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
01:15:17.068 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to LEADER
01:15:17.068 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 1
01:15:17.074 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 1
01:15:17.074 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 1
01:15:17.575 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 2 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:17.575 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 3 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:17.824 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 2 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:17.825 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 3 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:18.075 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 2 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:18.075 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - AppendRequest{term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 3 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:18.352 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{3}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=1, type=ACTIVE, updated=2020-04-24T01:15:16.253Z} in the last PT1.024S (calculated from last 1025 ms), sending poll requests
01:15:18.355 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Accepted PollRequest{term=1, candidate=3, lastLogIndex=1, lastLogTerm=1}: candidate's log is up-to-date
01:15:18.355 [] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{3}{role=FOLLOWER} - java.net.ConnectException
01:15:18.356 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to CANDIDATE
01:15:18.356 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{3}{role=CANDIDATE} - Starting election
01:15:18.364 [] WARN  io.atomix.raft.roles.CandidateRole - RaftServer{3}{role=CANDIDATE} - java.net.ConnectException
01:15:18.368 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Accepted VoteRequest{term=2, candidate=3, lastLogIndex=1, lastLogTerm=1}: candidate's log is up-to-date
01:15:18.371 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to LEADER
01:15:18.371 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 3
01:15:18.377 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 3
01:15:18.377 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{3} - ConfigureRequest{term=2, leader=3, index=0, timestamp=1587690916253, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}, DefaultRaftMember{id=3, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}]} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:18.378 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{3} - ConfigureRequest{term=2, leader=3, index=0, timestamp=1587690916253, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}, DefaultRaftMember{id=3, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}]} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:18.381 [] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{3} - ConfigureRequest{term=2, leader=3, index=0, timestamp=1587690916253, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}, DefaultRaftMember{id=3, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-04-24T01:15:16.253817Z}]} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException
01:15:18.384 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE
01:15:18.394 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to INACTIVE
01:15:18.396 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to INACTIVE
</pre>
</details>

**Comment by deepthidevaki** [comment]
Looks like this is fixed by https://github.com/zeebe-io/zeebe/commit/eeb0980056cf4880562d356b0f637edf5c32d895
Please reopen if the test fails again.
