### ISSUE TITLE
Verify snapshot after taking one

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4423]
**Description**

In order to avoid corrupted snapshots in the first place, we want to avoid that the Leader has taken a corrupted snapshot, which would be later then replicated.

To achieve this we want use the functionality of RocksDB's integrity check on opening a database. This means after taking the snapshot we want to open the DB in read-only mode to verify the integrity.

* When the snapshot is valid we should generate checksum's for each chunk and and for the complete snapshot. We could investigate, whether RocksDB can also generate checksum's for each file etc.
 * When the snapshot is invalid we could take a new one or just remove this one and wait for the next interval.

**Note** _it is intended that we don't expect malicious users or corrupted hard disk for now, since it is less likely and it makes it more complex_

**Comment by Zelldon** [comment]
RocksDB uses hard links for check pointing there database. It is not necessary to open the snapshot after taking one, since if the snapshot is corrupted this means the running database is also corrupted. We would detect that on the next access anyway. 


Example unit test which verifies that:

```
```java
  @Test
  public void shouldReplaceLastCorruptedSnapshot() throws Exception {
    // given two snapshots
    final RocksDBWrapper wrapper = new RocksDBWrapper();
    wrapper.wrap(snapshotController.openDb());
    wrapper.putInt("x", 1);
    takeSnapshot(1);
    corruptLatestSnapshot();

    // when
    assertThat(wrapper.getInt("x")).isEqualTo(1); // fails here since snapshot is corrupted which means runtime test is corrupted
    wrapper.putInt("x", 2);
    takeSnapshot(2);
    snapshotController.close();

    // when
    snapshotController.recover();
    wrapper.wrap(snapshotController.openDb());

    // then
    assertThat(wrapper.getInt("x")).isEqualTo(2);
  }
```

Exception we get with this test:

```

java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.

    at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:147)
    at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:172)
    at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.getValue(ZeebeTransactionDb.java:185)
    at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.get(ZeebeTransactionDb.java:180)
    at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(TransactionalColumnFamily.java:63)
    at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(TransactionalColumnFamily.java:134)
    at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(TransactionalColumnFamily.java:58)
    at io.zeebe.logstreams.util.RocksDBWrapper.getInt(RocksDBWrapper.java:31)
    at io.zeebe.broker.system.partitions.impl.StateSnapshotControllerTest.shouldReplaceLastCorruptedSnapshot(StateSnapshotControllerTest.java:207)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.get(ZeebeTransaction.java:54)
    at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$getValue$2(ZeebeTransactionDb.java:189)
    at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$ensureInOpenTransaction$1(ZeebeTransactionDb.java:173)
    at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:163)
    at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:135)
    ... 36 more
Caused by: org.rocksdb.RocksDBException: truncated block read from /tmp/junit2605796451576486742/state/runtime/000007.sst offset 0, expected 31 bytes, got 15
    at org.rocksdb.Transaction.get(Native Method)
    ... 45 more
```

**Comment by Zelldon** [comment]
Currently it is not clear what value we gain with this issue. With #4641 we introduced checksum's on snapshot level, but also on snapshot chunk level for all snapshot replications. Furthermore as written above if the snapshot on the Leader is corrupted this also means the runtime is corrupted due to the used hard links. 

If the Leader sends an snapshot to a follower, via any snapshot replication, we now can be sure that this is the same snapshot as he currently has, because of the checksum's. 

We are currently not preparing for disk rot nor malicious users, since we don't expect them in the cloud. This means it is currently not our focus to handle this failure cases/possibilities. This is the reason why we close this issue for now.
