### ISSUE TITLE
DefaultClusterEventServiceTest.shouldBroadcastAfterRestart flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4436]
**Summary**

- How often does the test fail? - Top3 of flaky tests in CW 21
- Does it block your work? - not really
- Do we suspect that it is a real failure? - unknown

**Failures**
<details><summary>Example assertion failure</summary>
<pre>
Error Message

expected:<[tru]e> but was:<[fals]e>

Stacktrace

org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:91)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at io.atomix.cluster.messaging.impl.DefaultClusterEventServiceTest.shouldBroadcastAfterRestart(DefaultClusterEventServiceTest.java:371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output

11:12:36.430 [] INFO  io.zeebe.test - Test finished: shouldBroadcastToMultipleLocalSubscriptionsForSameTopic(io.atomix.cluster.messaging.impl.DefaultClusterEventServiceTest)
11:12:36.431 [] INFO  io.zeebe.test - Test started: shouldBroadcastAfterRestart(io.atomix.cluster.messaging.impl.DefaultClusterEventServiceTest)
11:12:36.435 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
11:12:36.436 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Member activated: Member{id=1, address=localhost:1, host=localhost, properties={}}
11:12:36.444 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
11:12:36.444 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
11:12:36.445 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
11:12:36.447 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
11:12:36.448 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Member activated: Member{id=2, address=localhost:2, host=localhost, properties={}}
11:12:36.522 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
11:12:36.523 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
11:12:36.523 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
11:12:37.521 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Member deactivated: Member{id=2, address=localhost:2, host=localhost, properties={}}
11:12:37.521 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Stopped
11:12:37.521 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
11:12:37.522 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
11:12:37.522 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
11:12:37.524 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
11:12:37.525 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Member activated: Member{id=2, address=localhost:2, host=localhost, properties={}}
11:12:37.527 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
11:12:37.527 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
11:12:37.531 [] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
</pre>
</details>

**Comment by npepinpe** [comment]
Assigned to Deepthi as she's rewriting the cluster event service, so most likely has part of it she'll close this
