### ISSUE TITLE
BrokerHttpServerTest "flaky"

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4492]
**Summary**

- How often does the test fail? once so far
- Does it block your work? - not really 
- Do we suspect that it is a real failure? - no

**Failures**

https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/4340-do-not-merge-monitor-build-health-branch/502/

<details><summary>Example assertion failure</summary>
<pre>
Error Message

Failed to start broker

Stacktrace

io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
	at io.zeebe.broker.Broker.internalStart(Broker.java:142)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21)
	at io.zeebe.broker.Broker.start(Broker.java:115)
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:215)
	at io.zeebe.broker.test.EmbeddedBrokerRule.before(EmbeddedBrokerRule.java:128)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:461)
	at java.base/sun.nio.ch.Net.bind(Net.java:453)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output

03:19:56.469 [] [main] INFO  io.zeebe.test.util.SocketUtil - Starting socket assignment with testForkNumber 9 and testMavenId 1
03:19:56.551 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 34700 for test fork 9 with range PortRange{host='localhost', basePort=34700, maxOffset=100, currentOffset=1}
03:19:56.552 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 34701 for test fork 9 with range PortRange{host='localhost', basePort=34700, maxOffset=100, currentOffset=2}
03:19:56.553 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 34702 for test fork 9 with range PortRange{host='localhost', basePort=34700, maxOffset=100, currentOffset=3}
03:19:56.554 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 34703 for test fork 9 with range PortRange{host='localhost', basePort=34700, maxOffset=100, currentOffset=4}
03:19:56.555 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 34704 for test fork 9 with range PortRange{host='localhost', basePort=34700, maxOffset=100, currentOffset=5}
03:19:56.663 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/23097048-1b19-4967-88e2-403d4d8a79fd
03:19:56.760 [] [main] INFO  io.zeebe.broker.system - Version: 0.24.0-SNAPSHOT
03:19:58.467 [] [main] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 34702,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 34702,
      "address" : "0.0.0.0:34702",
      "advertisedAddress" : "0.0.0.0:34702"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 34703,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 34703,
      "address" : "0.0.0.0:34703",
      "advertisedAddress" : "0.0.0.0:34703"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 34704,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 34704,
      "address" : "0.0.0.0:34704",
      "advertisedAddress" : "0.0.0.0:34704"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/tmp/23097048-1b19-4967-88e2-403d4d8a79fd/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK"
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 34700,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:34703",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 34701
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
03:19:58.577 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/11]: actor scheduler
03:19:58.660 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/11]: actor scheduler started in 10 ms
03:19:58.664 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/11]: membership and replication protocol
03:20:03.002 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/11]: membership and replication protocol started in 4335 ms
03:20:03.002 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/11]: command api transport
03:20:03.214 [] [main] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:34702 
03:20:03.223 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/11]: command api transport started in 220 ms
03:20:03.223 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/11]: command api handler
03:20:03.271 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/11]: command api handler started in 48 ms
03:20:03.271 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/11]: subscription api
03:20:03.300 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/11]: subscription api started in 28 ms
03:20:03.301 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/11]: embedded gateway
03:20:03.307 [] [main] INFO  io.zeebe.gateway - Version: 0.24.0-SNAPSHOT
03:20:03.307 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 34700,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:34703",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 34701
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "enable" : true
}
03:20:03.442 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/11]: embedded gateway started in 140 ms
03:20:03.442 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services
03:20:03.683 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$452/0x00000008404d7c40@51a60dba not registered
03:20:03.742 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services started in 300 ms
03:20:03.742 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/11]: topology manager
03:20:03.743 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/11]: topology manager started in 1 ms
03:20:03.743 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/11]: metric's server
03:20:03.763 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
03:20:03.757 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/11]: metric's server failed with unexpected exception.
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:461) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:453) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
03:20:03.764 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/8]: topology manager
03:20:03.766 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/8]: topology manager closed in 2 ms
03:20:03.766 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/8]: cluster services
03:20:03.767 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/8]: cluster services closed in 0 ms
03:20:03.767 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/8]: embedded gateway
03:20:03.771 [] [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
03:20:03.772 [] [main] DEBUG io.zeebe.gateway - topology manager closed
03:20:03.775 [] [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
03:20:03.775 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/8]: embedded gateway closed in 8 ms
03:20:03.775 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/8]: subscription api
03:20:03.775 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/8]: subscription api closed in 0 ms
03:20:03.775 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/8]: command api handler
03:20:03.776 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/8]: command api handler closed in 1 ms
03:20:03.776 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/8]: command api transport
03:20:06.000 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/8]: command api transport closed in 2224 ms
03:20:06.000 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [7/8]: membership and replication protocol
03:20:08.224 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/8]: membership and replication protocol closed in 2223 ms
03:20:08.224 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [8/8]: actor scheduler
03:20:08.226 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/8]: actor scheduler closed in 2 ms
03:20:08.226 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 8 steps in 4462 ms.
03:20:08.226 [] [main] ERROR io.zeebe.broker.system - Failed to start broker 0!
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:461) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:453) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
</pre>
</details>

**Comment by Zelldon** [comment]
Seems that the metrics port was not free?

**Comment by pihme** [comment]
Looks like it.
This can happen because tests run in parallel, so it collides either with another tests that uses this port, or it could collide with something like https://github.com/zeebe-io/zeebe/issues/4366 which looks for any open port.

**Comment by pihme** [comment]
Will be fixed as part of #4547
