### ISSUE TITLE
Raft partition failure after several days of standby

### ISSUE THREAD

**Issue by ezolnbl** [zeebe-io/zeebe#4498]
**Describe the bug**
After a week of running zeebe environment without doing anything, I got these from the logs: (and the broker stopped working - processes and workers are throwing exceptions, can not get jobs). This error log is repeating every 5 seconds in 1 (fix, not randomly changing, so 1 node of the cluster is failing and the cluster can not failover) of the 3 node. There is plenty of hard disk under the environment.

**Expected behavior**
The cluster should run without error for long time without the need to restart pods/services and the cluster should handle failover.

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
2020-05-11 12:30:50.379 [] [raft-server-0-raft-partition-partition-3] ERROR io.atomix.utils.concurrent.SingleThreadContext - An uncaught exception occurred
java.lang.IndexOutOfBoundsException: Cannot truncate committed index: 2149083
        at io.atomix.storage.journal.SegmentedJournalWriter.truncate(SegmentedJournalWriter.java:116) ~[atomix-storage-3.2.0-alpha12.jar:?]
        at io.atomix.storage.journal.DelegatingJournalWriter.truncate(DelegatingJournalWriter.java:67) ~[atomix-storage-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.roles.PassiveRole.replaceExistingEntry(PassiveRole.java:879) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:818) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.roles.PassiveRole.appendEntries(PassiveRole.java:779) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.roles.PassiveRole.handleAppend(PassiveRole.java:635) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.roles.FollowerRole.onAppend(FollowerRole.java:196) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.impl.RaftContext.lambda$null$20(RaftContext.java:223) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:255) ~[atomix-raft-3.2.0-alpha12.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:182) ~[atomix-utils-3.2.0-alpha12.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:55) ~[atomix-utils-3.2.0-alpha12.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
 - OS: Azure k8s cluster with 3 node, each:
<pre>
Limits:
  cpu:     2
  memory:  2Gi
Requests:
  cpu:      500m
  memory:   2Gi
Environment:
  ZEEBE_LOG_LEVEL:           debug
  ZEEBE_PARTITIONS_COUNT:    1
  ZEEBE_CLUSTER_SIZE:        1
  ZEEBE_REPLICATION_FACTOR:  1
  JAVA_TOOL_OPTIONS:         -XX:+UseParallelGC
                             -XX:MinHeapFreeRatio=5
                             -XX:MaxHeapFreeRatio=10
                             -XX:MaxRAMPercentage=25.0
                             -XX:GCTimeRatio=4
                             -XX:AdaptiveSizePolicyWeight=90
                             -XX:+PrintFlagsFinal
                             -Xmx4g
                             -Xms4g
                             -XX:+HeapDumpOnOutOfMemoryError
                             -XX:HeapDumpPath=/usr/local/zeebe/data
                             -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
</pre>
 - Zeebe Version: 0.23.0-SNAPSHOT
 - Configuration: kafka exporter

**Comment by Zelldon** [comment]
seems to be related with https://github.com/zeebe-io/zeebe/issues/4467

**Comment by Zelldon** [comment]
Hey @ezolnbl 

thanks for reporting this.

In order to continue with this please answer some questions:

 * You wrote that you have a three node cluster, but your environment variables indicate that you're using a single node cluster? Could you please give us the complete configuration. Maybe the log output which is printed on bootstrap the node.
 * I would like to understand what the impact of this is. You wrote that the clients responding with exceptions. Could you please add these to the issue. Furthermore is this only a temporary issue and does it resolve it after some time?
 * Do you know whether there were some node restarts before this error?

Greets
Chris

**Comment by ezolnbl** [comment]
Sorry i was checking the wrong cluster on azure, the numbers are:
ZEEBE_PARTITIONS_COUNT:    3
ZEEBE_CLUSTER_SIZE:        3
ZEEBE_REPLICATION_FACTOR:  3

- sadly i can not tell exactly what was happened with the clients, they either did not do anything or they timed out but ic could not start a process:
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29.999987600s. [remote_add
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$1CloseInContext.runInContext(ClientCallImpl.java:416)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

- there were no node restarts(as far as I know), all of the pods were running with the same age and we did not initialize any restart

**Comment by Zelldon** [comment]
Hey @ezolnbl ,

sorry but I can't reproduce your issue.
I used the latest snapshot, a three node cluster. three partitions and replication factor three. After setting up the cluster I had a small load and then for several days no load. Today I started the load again and everything works as expected and I see no similar log statement. 

Do you have any idea how to reproduce that? Do you have seen that again?

Greets
Chris

**Comment by ezolnbl** [comment]
sadly I can not tell how to repro this, it just happened after unusing the env for a while, maybe it is possible that in a real environment this won't happen because there is no downtime in production other then a weekend or something...if you can afford to run the env for let's say 10 days and after that run something, maybe it would appear again

**Comment by Zelldon** [comment]
Sorry but can't reproduce this. I had a setup which I run for 10 days without any load. Yesterday I started to create and complete 100 workflows per s and everything works fine.

![noloadrestart](https://user-images.githubusercontent.com/2758593/85674648-4e7f4e80-b6c5-11ea-912b-fab58cabd178.png)


\cc @npepinpe should we close this for now?

**Comment by ezolnbl** [comment]
let's hope with new versions this won't rise again
