### ISSUE TITLE
On client channel close exceeds command queue 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#451]
I open a task subscription with zbctl and create tasks until it runs out of credits and then restart it. If I repeat this multiple times I can fairly consistently reproduce an error where the command queue of the `LockTaskStreamProcessor` exceeds its limit. I think this can lead to a problem where closed subscriptions are not removed correctly and still considered during task locking. But not absolutely sure if this can be a problem.

Also I'm not sure if this problem is triggered by the zbctl implementation or if there is a general problem here.

```
java.lang.IllegalStateException: Queue is full
        at org.agrona.concurrent.AbstractConcurrentArrayQueue.add(AbstractConcurrentArrayQueue.java:142)
        at io.zeebe.util.DeferredCommandContext.runAsync(DeferredCommandContext.java:42)
        at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onClientChannelCloseAsync(LockTaskStreamProcessor.java:168)
        at io.zeebe.broker.task.TaskSubscriptionManager.lambda$onClientChannelCloseAsync$14(TaskSubscriptionManager.java:356)
        at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:113)
        at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:88)
        at io.zeebe.util.DeferredCommandContext.doWork(DeferredCommandContext.java:66)
        at io.zeebe.broker.task.TaskSubscriptionManager.doWork(TaskSubscriptionManager.java:117)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by meyerdan** [comment]
Should be fine now, queues were removed during actor scheduler refactoring
