### ISSUE TITLE
Race condition on logstream truncate

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#452]
When [FsLogStorage#truncate](https://github.com/zeebe-io/zb-logstreams/blob/b87bb29f9e91b5c0edb689f3bf85b0c0cf2d797f/src/main/java/io/zeebe/logstreams/impl/log/fs/FsLogStorage.java#L158) is called the truncated segments are closed, which [unmaps the underlying buffer](https://github.com/zeebe-io/zb-logstreams/blob/b87bb29f9e91b5c0edb689f3bf85b0c0cf2d797f/src/main/java/io/zeebe/logstreams/impl/log/fs/FsLogSegment.java#L93). In parallel the LogBlockIndexController still tires to access these log segments and fails with NullPointerExceptions or invalid read address errors.

This does not seem to have a huge impact at the moment but maybe it's better to fix it, not sure yet.

This can be reproduced with the [LogStreamTest#shouldTruncateLogStorage](https://github.com/zeebe-io/zb-logstreams/blob/b87bb29f9e91b5c0edb689f3bf85b0c0cf2d797f/src/test/java/io/zeebe/logstreams/log/LogStreamTest.java#L406).

```
java.lang.NullPointerException
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:135)
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:254)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:239)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
	at java.lang.Thread.run(Thread.java:748)
```

```
10:28:24.350 [actor-runner-default] ERROR io.zeebe.logstreams - Can't read from illegal address: 4224
```

**Comment by ThorbenLindhauer** [comment]
zb-raft build failed locally for me with this exception:

```
-------------------------------------------------------------------------------
Test set: io.zeebe.raft.RaftThreeNodesTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.85 s <<< FAILURE! - in io.zeebe.raft.RaftThreeNodesTest
shouldTruncateLog(io.zeebe.raft.RaftThreeNodesTest)  Time elapsed: 3.88 s  <<< ERROR!
java.lang.NullPointerException
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:135)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.getFirstBlockAddress(FsLogStorage.java:487)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:199)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seekToFirstEvent(BufferedLogStreamReader.java:280)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(BufferedLogStreamReader.java:135)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.<init>(BufferedLogStreamReader.java:111)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.<init>(BufferedLogStreamReader.java:121)
	at io.zeebe.raft.util.RaftClusterRule.printLogEntries(RaftClusterRule.java:185)
	at io.zeebe.raft.util.RaftClusterRule.lambda$printLogEntries$14(RaftClusterRule.java:176)
	at io.zeebe.raft.util.RaftClusterRule$$Lambda$134/1030684756.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.zeebe.raft.util.RaftClusterRule.printLogEntries(RaftClusterRule.java:176)
	at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:224)
	at io.zeebe.raft.util.RaftClusterRule.awaitInitialEventCommittedOnAll(RaftClusterRule.java:153)
	at io.zeebe.raft.RaftThreeNodesTest.shouldTruncateLog(RaftThreeNodesTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

**Comment by menski** [comment]
Hopefully fixed with the latest orchestration service dependency refactoring. Will close for now. If we see this again we can reopen this issue or create a new one.
