### ISSUE TITLE
StreamProcessorTest.shouldInvokeOnProcessedListener flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4544]
**Summary**

- How often does the test fail? - at least once
- Does it block your work? - no 
- Do we suspect that it is a real failure? - unknown

**Failures**

https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/4340-do-not-merge-monitor-build-health-branch/677

<details><summary>Example assertion failure</summary>
<pre>
Stacktrace

java.lang.NullPointerException
	at io.zeebe.broker.system.partitions.StreamProcessorTest.shouldInvokeOnProcessedListener(StreamProcessorTest.java:692)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output

18:18:27.370 [] [main] INFO  io.zeebe.test - Test started: shouldInvokeOnProcessedListener(io.zeebe.broker.system.partitions.StreamProcessorTest)
18:18:28.556 [Broker-0-LogStream-0] [-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 0 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
18:18:28.713 [] [main] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
18:18:29.377 [] [main] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/junit1308636197042840184/stream-0/state/runtime'.
18:18:29.411 [Broker-0-StreamProcessor-0] [-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 0 from snapshot
18:18:29.562 [Broker-0-StreamProcessor-0] [-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@bd1e1c4)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@347fdfb2, configuration: Configuration(false)]
18:18:29.675 [Broker-0-StreamProcessor-0] [-zb-actors-0] INFO  io.zeebe.logstreams - Recovered state of partition 0 from snapshot at position -1
18:18:29.739 [] [main] INFO  io.zeebe.broker.test - Test failed, following records where exported:
18:18:29.779 [] [main] INFO  io.zeebe.broker.test - Records on partition 0:
			Position: 4294967296 Key: -1
				RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_ACTIVATING, requestStreamId=-2147483648, requestId=-1, protocolVersion=1, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=}
				Value:
{"bpmnProcessId":"","version":-1,"workflowKey":-1,"workflowInstanceKey":1,"elementId":"","flowScopeKey":-1,"bpmnElementType":"UNSPECIFIED","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1}

18:18:29.784 [] [main] DEBUG io.zeebe.util.buffer - Close stream processor
18:18:29.786 [Broker-0-StreamProcessor-0] [-zb-actors-2] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-0.
18:18:29.827 [Broker-0-LogStream-0] [-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream stream-0
18:18:29.830 [stream-0-write-buffer] [-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
18:18:29.831 [Broker-0-LogStream-0] [-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream stream-0 close 3 readers
18:18:29.831 [Broker-0-LogStream-0] [-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name stream-0
18:18:29.832 [] [main] DEBUG io.zeebe.broker.test - Clean up test files on path /tmp/junit1308636197042840184
</pre>
</details>

**Comment by Zelldon** [comment]
Had this locally today with running mvn in parallel
