### ISSUE TITLE
Recursive merging of buffers leads to invalid bucket buffer id

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#466]
The ZbMap tries to [merge bucket recursively](https://github.com/zeebe-io/zb-util/blob/33a93b2af2dc3189f17ea89b65942edacae59e22/zb-map/src/main/java/io/zeebe/map/ZbMapBucketMergeHelper.java#L239), which can lead to a `StackOverflowError` if the a big map (~1.000.000 entries) is emptied. Or to a to `ArrayIndexOutOfBoundsException` if the recursion ends, see following shorten stacktrace:

```
java.lang.ArrayIndexOutOfBoundsException: 1026

	at io.zeebe.map.BucketBufferArray.removeBucket(BucketBufferArray.java:405)
	at io.zeebe.map.ZbMapBucketMergeHelper.tryToMergeSplitBucketWithParent(ZbMapBucketMergeHelper.java:417)
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeSplitBucket(ZbMapBucketMergeHelper.java:383)
[...]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergingBuckets(ZbMapBucketMergeHelper.java:239)
	at io.zeebe.map.ZbMap.remove(ZbMap.java:331)
	at io.zeebe.map.ZbMapTest.removeValue(ZbMapTest.java:82)
	at io.zeebe.map.ZbMapTest.shouldPutAndRemoveRandomValues(ZbMapTest.java:1504)
```

**Comment by saig0** [comment]
Hint: the ArrayIndexOutOfBoundsException occurs when the buffer is shrunk. In this case, the 'nextBucketBufferId' is not updated depending on the current bucket buffer count:
https://github.com/zeebe-io/zb-util/blob/33a93b2af2dc3189f17ea89b65942edacae59e22/zb-map/src/main/java/io/zeebe/map/BucketBufferArray.java#L404
