### ISSUE TITLE
NullPointerException in EventHandle.java

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4663]
**Describe the bug**

This occurred in production 266 times in the last week - a NullPointerException is thrown in `io.zeebe.engine.processor.workflow.EventHandle` on line 42. You can see the stack trace below. Here is the offending block of code:

https://github.com/zeebe-io/zeebe/blob/29a31b6dab5acd28631598a0529c902921c9f30e/engine/src/main/java/io/zeebe/engine/processor/workflow/EventHandle.java#L39-L42

As this is an unexpected exception, I think it will blacklist the workflow instance, which is pretty bad, meaning that instance can never recover.

**To Reproduce**

As another user triggered this, I can't really say how to reproduce it unfortunately.

**Expected behavior**

NullPointerException are very rarely expected :slightly_smiling_face: 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.zeebe.engine.processor.workflow.EventHandle.triggerEvent(EventHandle.java:42) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.workflow.timer.TriggerTimerProcessor.triggerEvent(TriggerTimerProcessor.java:116) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.workflow.timer.TriggerTimerProcessor.processTimerTrigger(TriggerTimerProcessor.java:88) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.workflow.timer.TriggerTimerProcessor.processRecord(TriggerTimerProcessor.java:73) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:28) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:265) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:256) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:225) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:201) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:192) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.2.jar:0.23.2]
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.23.2
 - Configuration: can't tell yet the cluster type, we'll have to look at logs

**Comment by npepinpe** [comment]
Please investigate and we can reassess priority based on findings (e.g. number of users affected, how likely this is to happen, etc.)

**Comment by saig0** [comment]
The NPE occurs when a timer is triggered and the related element (e.g. the intermediate catch event) is left concurrently (i.e. before the timer is canceled).
