### ISSUE TITLE
0.23.2 Broker fails to start on Mac 10.14 + AdoptOpenJDK 11.0.4

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe#4679]
**Describe the bug**
Broker fails to start on Mac OS 10.14 with OpenJDK Java 11

**To Reproduce**

- Download 0.23.3 released
- Unzip
- Run `bin/broker`
- Wait
- Run `bin/zbctl status` in another terminal

**Expected behavior**
Broker starts, and `zbctl status` reports topology.

**Actual behavior**

During broker startup, this happens:

```
2020-06-08 20:19:35.002 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler
2020-06-08 20:19:35.005 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 10 steps in 4343 ms.
2020-06-08 20:19:35.005 [] [main] ERROR io.zeebe.broker.system - Failed to start broker 0!
java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.scheduleActor(Broker.java:269) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.lambda$partitionsStep$17(Broker.java:340) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.partitionsStep(Broker.java:346) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.lambda$initStart$9(Broker.java:183) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.internalStart(Broker.java:135) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.start(Broker.java:115) [zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:59) [zeebe-distribution-0.23.2.jar:0.23.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:46) [zeebe-distribution-0.23.2.jar:0.23.2]
2020-06-08 20:19:35.010 [] [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-06-08 20:19:35.013 [] [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:46) [zeebe-distribution-0.23.2.jar:0.23.2]
Caused by: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
	at io.zeebe.broker.Broker.internalStart(Broker.java:142) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.start(Broker.java:115) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:59) ~[zeebe-distribution-0.23.2.jar:0.23.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	... 5 more
Caused by: java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.scheduleActor(Broker.java:269) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.lambda$partitionsStep$17(Broker.java:340) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.partitionsStep(Broker.java:346) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.lambda$initStart$9(Broker.java:183) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.internalStart(Broker.java:135) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.broker.Broker.start(Broker.java:115) ~[zeebe-broker-0.23.2.jar:0.23.2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:59) ~[zeebe-distribution-0.23.2.jar:0.23.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	... 5 more
```

`zbctl status` reports:

```
bin/zbctl.darwin status
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:26500: connect: connection refused"
```

**Environment:**
 - OS: Darwin - Mac OS 10.14
 - Zeebe Version: 0.23.2
 - Configuration: Vanilla

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

**Comment by menski** [comment]
@korthout as you are our mac user can you try to reproduce this on your machine? Thanks

**Comment by korthout** [comment]
Quick try, but unable to reproduce. 

```
$ bin/broker
...
2020-06-08 11:28:03.979 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 837 ms.
2020-06-08 11:28:03.979 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 11 steps in 2588 ms.
```

```
$ bin/zbctl.darwin status --insecure
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 0.23.2
Brokers:
  Broker 0 - 0.0.0.0:26501
    Version: 0.23.2
    Partition 1 : Leader
```

However this was on macOS `10.15.5` with java version
```
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

This evening I have access to a machine running macOS `10.14`. I can give that a try.

**Comment by Zelldon** [comment]
I think it might again be related to AdoptOpenJDK, we had already previous some issues with this vendor.

**Comment by korthout** [comment]
@Zelldon interesting. I'll see if I can easily switch my jre to something else

**Comment by korthout** [comment]
Also unable to reproduce with AdoptOpenJDK 11. Might just be a problem on macOS `10.14`, or with a specific version of AdoptOpenJDK 11, since I used the latest build.

```
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

```
2020-06-08 12:03:14.643 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 920 ms.
2020-06-08 12:03:14.643 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 11 steps in 2510 ms.
```

@jwulf just to be sure, which version of macOS `10.14` are you on? You may also try to upgrade to the latest AdoptOpenJDK 11 (i.e. `11.0.7+10`)

**Comment by jwulf** [comment]
I installed this one and it works:

openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
