### ISSUE TITLE
StackdriverLayoutTest.shouldContainTime() is flaky

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#4770]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? sometimes
- Does it block your work? no
- Do we suspect that it is a real failure? no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Assertion failure</summary>
<pre>

```
The end value <51697000> must not be less than the start value <976231000>!
```

</pre>
</details>

<details><summary>Stacktrace</summary>
<pre>

```
java.lang.IllegalArgumentException: The end value <51697000> must not be less than the start value <976231000>!
	at org.assertj.core.util.Preconditions.checkArgument(Preconditions.java:129)
	at org.assertj.core.internal.Comparables.checkBoundsValidity(Comparables.java:369)
	at org.assertj.core.internal.Comparables.assertIsBetween(Comparables.java:352)
	at org.assertj.core.internal.Numbers.assertIsBetween(Numbers.java:152)
	at org.assertj.core.api.AbstractLongAssert.isBetween(AbstractLongAssert.java:246)
	at org.assertj.core.api.LongAssert$ByteBuddy$xNt8Z6pm.isBetween$accessor$NTzq4wdX(Unknown Source)
	at org.assertj.core.api.LongAssert$ByteBuddy$xNt8Z6pm$AssertJ$SoftProxies$2ktxCOkM.call(Unknown Source)
	at org.assertj.core.api.ErrorCollector.intercept(ErrorCollector.java:58)
	at org.assertj.core.api.LongAssert$ByteBuddy$xNt8Z6pm.isBetween(Unknown Source)
	at org.assertj.core.api.LongAssert$ByteBuddy$xNt8Z6pm.isBetween(Unknown Source)
	at io.zeebe.util.logging.StackdriverLayoutTest.shouldContainTime(StackdriverLayoutTest.java:229)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.assertj.core.api.SoftAssertionsStatement$1.evaluate(SoftAssertionsStatement.java:41)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

Failure in the test assertion when comparing the nanos of the timestamp.

```
public int getNano()

  Gets the number of nanoseconds, later along the time-line, from the start of the second.
  The nanosecond-of-second value measures the total number of nanoseconds from the second returned by getEpochSecond().
```

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>

```
06:09:05.974 [] [main] INFO  io.zeebe.test - Test finished: shouldTerminateAllEntriesWithALineSeparator(io.zeebe.util.logging.StackdriverLayoutTest)
06:09:05.974 [] [main] INFO  io.zeebe.test - Test started: shouldContainTime(io.zeebe.util.logging.StackdriverLayoutTest)
06:09:05.978 [] [main] INFO  io.zeebe.util.logging.StackdriverLayoutTest - This is a message
```

</pre>
</details>

**Comment by npepinpe** [comment]
Ah, makes total sense! My bad :see_no_evil:
