### ISSUE TITLE
RaftRolesTest. testAtomixBootstrapPartitionsAndRestartingNode flaky

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4798]
**Summary**

- How often does the test fail? I've only seen it once
- Does it block your work? not really
- Do we suspect that it is a real failure? unknown

**Failures**

https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/4723-failed-stream-processing-backport-0.23/2/

<details><summary>Example assertion failure</summary>
<pre>
[2020-06-23T08:32:16.163Z] [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 128.523 s <<< FAILURE! - in io.atomix.core.RaftRolesTest
[2020-06-23T08:32:16.163Z] [ERROR] io.atomix.core.RaftRolesTest.testAtomixBootstrapPartitionsAndRestartingNode  Time elapsed: 32.927 s  <<< FAILURE!
[2020-06-23T08:32:16.163Z] java.lang.AssertionError
[2020-06-23T08:32:16.163Z] 	at org.junit.Assert.fail(Assert.java:87)
[2020-06-23T08:32:16.163Z] 	at org.junit.Assert.assertTrue(Assert.java:42)
[2020-06-23T08:32:16.163Z] 	at org.junit.Assert.assertTrue(Assert.java:53)
[2020-06-23T08:32:16.163Z] 	at io.atomix.core.RaftRolesTest.testAtomixBootstrapPartitionsAndRestartingNode(RaftRolesTest.java:364)
[2020-06-23T08:32:16.163Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-06-23T08:32:16.163Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-06-23T08:32:16.163Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-06-23T08:32:16.163Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-06-23T08:32:16.163Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[2020-06-23T08:32:16.163Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2020-06-23T08:32:16.163Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[2020-06-23T08:32:16.163Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2020-06-23T08:32:16.163Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2020-06-23T08:32:16.164Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2020-06-23T08:32:16.164Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2020-06-23T08:32:16.164Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2020-06-23T08:32:16.164Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2020-06-23T08:32:16.164Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
[2020-06-23T08:32:16.164Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
[2020-06-23T08:32:16.164Z] 
[2020-06-23T08:32:16.738Z] [INFO] 
[2020-06-23T08:32:16.738Z] [INFO] Results:
[2020-06-23T08:32:16.738Z] [INFO] 
[2020-06-23T08:32:16.738Z] [ERROR] Failures: 
[2020-06-23T08:32:16.738Z] [ERROR]   RaftRolesTest.testAtomixBootstrapPartitionsAndRestartingNode:364
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by deepthidevaki** [comment]
This test and behavior is removed in 0.24

**Comment by Zelldon** [comment]
We will remove this test then. I will check whether I can backport some changes we made on 0.24

**Comment by npepinpe** [comment]
Closing as this hasn't happened in a while, and the CI pipeline is a lot more stable now. Please re-open if you see this occur again.
