### ISSUE TITLE
GossipClusteringTest.shouldRemoveLeaderFromCluster flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4939]
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: Lambda expression in io.zeebe.broker.it.clustering.ClusteringRule: expected the predicate to return <true> but it returned <false> for input of <[BrokerInfoImpl{nodeId=2, host='0.0.0.0', port=30841, version=0.25.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER}]}, BrokerInfoImpl{nodeId=1, host='0.0.0.0', port=30836, version=0.25.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER}]}]> within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:601)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:618)
	at io.zeebe.broker.it.clustering.ClusteringRule.waitForTopology(ClusteringRule.java:609)
	at io.zeebe.broker.it.clustering.ClusteringRule.waitForNewLeaderOfPartitions(ClusteringRule.java:590)
	at io.zeebe.broker.it.clustering.ClusteringRule.stopBrokerAndAwaitNewLeader(ClusteringRule.java:564)
	at io.zeebe.broker.it.clustering.GossipClusteringTest.shouldRemoveLeaderFromCluster(GossipClusteringTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)
	... 25 more
</pre>
</details>

**Hypotheses**

**Logs**

>23 MB https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/develop/1473/artifact/test-reports.zip

**Comment by Zelldon** [comment]
I think next time we need to attach the log results directly to the issue :sweat_smile:

**Comment by npepinpe** [comment]
Closing as this hasn't happened in a while, and the CI pipeline is a lot more stable now. Please re-open if you see this occur again.
