### ISSUE TITLE
Elastic exporter get broken pipe with big records

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4951]
**Describe the bug**

It seems we can easily break the connection to our elastic cluster if we have bigger messages.
I wanted to replay a scenario we observed during the Gameday on 10.07.2020, where elastic went oom and crash looped.
Furthermore Zeebe crashed due to big messages and went out of disk space.

In our benchmarks it seems it wents out of disk space because it is not able to export, since elastic connections are broken.

**To Reproduce**

Setup:

 * 3 partitions, 3 nodes, replication factor 3
 * load 100 wfi/s
 * variable size ~ 1 MB

It happens on different benchmarks that the exporter was not able to export the data, which means the broker went out of disk space.

**Expected behavior**

We can export and process the record without issues.

**Log/Stacktrace**

We see continuously the following messages:
```
Expand all | Collapse all{
 insertId: "sjoehgj2yh7gqhpu6"  
 jsonPayload: {
  @type: "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"   
  context: {…}   
  exception: "io.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk
	at io.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:151) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:116) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.flushAndReschedule(ElasticsearchExporter.java:103) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
Caused by: java.io.IOException: Broken pipe
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:964) ~[elasticsearch-rest-client-6.8.10.jar:6.8.10]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233) ~[elasticsearch-rest-client-6.8.10.jar:6.8.10]
	at io.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:189) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:148) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	... 8 more
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:?]
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.doWriteChunk(AbstractContentEncoder.java:171) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.doWriteChunk(AbstractContentEncoder.java:164) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.writeToChannel(AbstractContentEncoder.java:138) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.codecs.LengthDelimitedEncoder.write(LengthDelimitedEncoder.java:130) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.entity.NStringEntity.produceContent(NStringEntity.java:175) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.protocol.BasicAsyncRequestProducer.produceContent(BasicAsyncRequestProducer.java:125) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.client.MainClientExec.produceContent(MainClientExec.java:262) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.produceContent(DefaultClientExchangeHandlerImpl.java:140) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.outputReady(HttpAsyncRequestExecutor.java:249) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.produceOutput(DefaultNHttpClientConnection.java:290) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.client.InternalIODispatch.onOutputReady(InternalIODispatch.java:86) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onOutputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:145) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-07-13T12:58:29.015000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-test%22%0Alabels.k8s-pod%2Fapp%3D%22zell-test-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-test%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22&scrollTimestamp=2020-07-13T12:58:16.058549000Z&pinnedLogId=wmfgkvw4gzmjced5f&pinnedLogTimestamp=2020-07-13T12:57:50.182212Z

or different benchmark

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-07-13T13:20:56.077000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-chaos-large%22%0Alabels.k8s-pod%2Fapp%3D%22zell-chaos-large-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-chaos-large%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22&scrollTimestamp=2020-07-13T13:20:45.942604000Z&pinnedLogId=sjoehgj2yh7gqhpu6&pinnedLogTimestamp=2020-07-13T13:20:44.402767Z

<details><summary>Full Stacktrace</summary>
 <p>

```
E 2020-07-13T13:20:31.688372Z Error on exporting record with key 2251799813702286 
E 2020-07-13T13:20:34.432168Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
E 2020-07-13T13:20:39.380522Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
E 2020-07-13T13:20:41.727210Z Error on exporting record with key 2251799813702286 
E 2020-07-13T13:20:44.402767Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
E 2020-07-13T13:20:50.039588Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
E 2020-07-13T13:20:51.744128Z Error on exporting record with key 2251799813702286 
E 2020-07-13T13:20:54.443096Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
E 2020-07-13T13:20:59.437443Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
E 2020-07-13T13:21:02.193694Z Error on exporting record with key 2251799813702286 
E 2020-07-13T13:21:04.478565Z Unexpected exception occurred on periodically flushing bulk, will retry later. 
```

</p>
</details>

**Environment:**
 - OS: k8s
 - Zeebe Version: SNAPSHOT
 - Configuration: elastic

**Comment by Zelldon** [comment]
Sidenote: Elastic seems to spent long time in GC 
```
2020-07-13 15:16:57.329 CEST
[2020-07-13T13:16:57,328][INFO ][o.e.m.j.JvmGcMonitorService] [elasticsearch-master-0] [gc][2708] overhead, spent [448ms] collecting in the last [1s]
```

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-07-13T13:20:56.589000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-chaos-large%22%0Alabels.k8s-pod%2Fapp%3D%22elasticsearch-master%22&scrollTimestamp=2020-07-13T13:23:44.778882517Z&pinnedLogId=e02pw6zdiqhcxxzxo&pinnedLogTimestamp=2020-07-13T13:15:09.055908045Z

**Comment by Zelldon** [comment]
BTW I think in the cloud it went out of memory because they limit elastic to [2 gig](https://github.com/camunda-cloud/zeebe-controller-k8s/blob/master/templates/elasticsearch_statefulset.yaml#L35-L36), we give it [8 gig](https://github.com/zeebe-io/zeebe/blob/develop/benchmarks/setup/default/zeebe-values.yaml#L106). I think because we already experienced these issues once.

**Comment by npepinpe** [comment]
Is it the exporter that breaks or is it Elastic?

**Comment by Zelldon** [comment]
the exporter is the guy who has the issues and will not get a new connection. Elastic doesn't see that there are any issues at all.

**Comment by Zelldon** [comment]
We see that pvc of elastic is not growing, but because of https://github.com/zeebe-io/zeebe/issues/4830 we still think we are exporting 
![elastic](https://user-images.githubusercontent.com/2758593/87312794-55a9b780-c521-11ea-8164-e840d193eae1.png)

We see that zeebe PVC's are growing
![pvc](https://user-images.githubusercontent.com/2758593/87312797-56424e00-c521-11ea-96af-e77675b14974.png)

**Comment by npepinpe** [comment]
https://github.com/elastic/elasticsearch/issues/24038 ?

**Comment by Zelldon** [comment]
I wonder why we haven't seen that before when this is the issue?

**Comment by Zelldon** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html#_how_big_is_too_big

**Comment by Zelldon** [comment]
BTW: This is totally easy to reproduce

**Comment by Zelldon** [comment]
[i have seen this now with our normal benchmarks:](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-08-11T10%3A02%3A25.151000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22zeebe-chaos%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.pod_name%3D%22zeebe-chaos-zeebe-1%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Atimestamp%3D%222020-08-11T10%3A02%3A18.699405000Z%22%0AinsertId%3D%22iqme9mng62l9ro8xt%22&scrollTimestamp=2020-08-11T10%3A02%3A58.837601000Z)

```

2020-08-11 12:02:18.699 CEST
Error on exporting record with key 4503599627373489
 
Expand all | Collapse all{
 insertId: "iqme9mng62l9ro8xt"  
 jsonPayload: {
  @type: "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"   
  context: {…}   
  exception: "io.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk
	at io.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:148) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:116) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:84) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:354) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
Caused by: java.io.IOException: Broken pipe
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:964) ~[elasticsearch-rest-client-6.8.11.jar:6.8.11]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233) ~[elasticsearch-rest-client-6.8.11.jar:6.8.11]
	at io.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:184) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:145) ~[zeebe-elasticsearch-exporter-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	... 10 more
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:?]
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.doWriteChunk(AbstractContentEncoder.java:171) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.doWriteChunk(AbstractContentEncoder.java:164) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.writeToChannel(AbstractContentEncoder.java:138) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.codecs.LengthDelimitedEncoder.write(LengthDelimitedEncoder.java:130) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.entity.NStringEntity.produceContent(NStringEntity.java:175) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.protocol.BasicAsyncRequestProducer.produceContent(BasicAsyncRequestProducer.java:125) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.client.MainClientExec.produceContent(MainClientExec.java:262) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.produceContent(DefaultClientExchangeHandlerImpl.java:140) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.outputReady(HttpAsyncRequestExecutor.java:249) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.produceOutput(DefaultNHttpClientConnection.java:290) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.client.InternalIODispatch.onOutputReady(InternalIODispatch.java:86) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onOutputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:145) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
