### ISSUE TITLE
RaftFailOverTest.shouldReplicateSnapshotMultipleTimesAfterMultipleDataLoss flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#4953]
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at io.atomix.raft.RaftRule$TestAppendListener.awaitCommit(RaftRule.java:638)
	at io.atomix.raft.RaftRule.appendEntry(RaftRule.java:537)
	at io.atomix.raft.RaftRule.appendEntry(RaftRule.java:530)
	at io.atomix.raft.RaftRule.appendEntries(RaftRule.java:524)
	at io.atomix.raft.RaftFailOverTest.shouldReplicateSnapshotMultipleTimesAfterMultipleDataLoss(RaftFailOverTest.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
</pre>
</details>

**Hypotheses**

**Logs**
230 MB of output https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/develop/1519/artifact/test-reports.zip

**Comment by deepthidevaki** [comment]
For reference, logs from failing test : [RaftFailoverTest.shouldReplicateSnapshotMultipleTimesAfterMultipleDataLoss.txt](https://github.com/zeebe-io/zeebe/files/4948085/RaftFailoverTest.shouldReplicateSnapshotMultipleTimesAfterMultipleDataLoss.txt)

**Comment by pihme** [comment]
@deepthidevaki How did you attach the file?

**Comment by deepthidevaki** [comment]
It is not straight forward. I had to manually scan the output for this test (from test-report.zip) and copy relevant logs from it. I saw that this test was repeated twice. So I assume the first attempt was a failure and copied those logs.

**Comment by deepthidevaki** [comment]
Reasons for test failure: There is a leader change while we are writing 128 events to the first leader. All events are written to the old leader, while the new leader has only received a few of them. After writing the last event, the test wait for the event to be committed. But it can never be committed because the new leader does not have that event. 

Problems in the test:
* Currently we are writing too many events. We can reduce them. Or use sync-append i.e write an event and wait until it is committed before the next one is written.
* Test is not capable of handling leader change.

Problems in the code:
The reason for new election is that Leader thread was not able to handle the response from followers and send the next heartbeat on time because we were writing too many events. The task to handle the response was scheduled after all the appendEntries task. Only after the response is received leader sends the next heartbeat or AppendRequests (it only allows max of 2 AppendRequest inflight). In the test, election timeout is too small, so this causes the followers to miss heartbeat and starts a new election.

**Comment by pihme** [comment]
@deepthidevaki I am amazed how you can reproduce this detailed and logical timeline from the logs. I bow to you!

**Comment by deepthidevaki** [comment]
Thanks @pihme 

I created an issue to handle such cases in the Raft. But I don't think it is a critical issue and it is not very relevant for these tests. So I would suggest that we can improve this test without that fix - by either reducing the number of events to write or by using sync write. That way we do not encounter this situation that leads to flaky test.

**Comment by pihme** [comment]
off the top of my head I would vote for the synced writes
