### ISSUE TITLE
Broker can't rejoin the cluster

### ISSUE THREAD

**Issue by TangJiong** [zeebe-io/zeebe#4988]
**Describe the bug**
In a 1-gateway-4-broker cluster, we delete a broker and then add a new broker to the cluster, the new broker can't join the cluster.

**To Reproduce**
1. Set up a cluster with 1 gateway and for brokers.
2. Delete a broker and wait for 30 minutes.
3. Start a new broker having same configuration as the closed broker but empty disk.

**Expected behavior**
The new broker join the cluster successfuly and the partions re-distribute in the cluster.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
2020-07-15 12:19:53.660 [] [raft-server-3-raft-partition-partition-22] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-22} - AppendRequest{term=2, leader=3, prevLogIndex=2, prevLogTerm=2, entries=0, commitIndex=2} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /x.x.x.x:26502
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /x.x.x.x:26502
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$19(NettyMessagingService.java:486) ~[atomix-cluster-0.23.3.jar:0.23.3]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-28.2-jre.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$20(NettyMessagingService.java:486) ~[atomix-cluster-0.23.3.jar:0.23.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.ChannelPool.lambda$getChannel$4(ChannelPool.java:142) ~[atomix-cluster-0.23.3.jar:0.23.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.OrderedFuture.complete(OrderedFuture.java:368) ~[atomix-utils-0.23.3.jar:0.23.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bootstrapClient$31(NettyMessagingService.java:615) ~[atomix-cluster-0.23.3.jar:0.23.3]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:636) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:655) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /9.139.128.176:26502
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:243) ~[netty-transport-native-unix-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	... 6 more
```

</p>
</details>

**Environment:**
- 16 Core / 16 GB Pod
 - OS: Linux
 - Zeebe Version: 0.23.3
 - Configuration: partitition count 48 / replication factor 3

**Comment by Zelldon** [comment]
Hey @TangJiong 

thanks for reporting. What is the reason for having so big partition count with such a small cluster size? 
This means each node has 36 partitions, whereas you only have 16 CPU's per node. Furthermore you will have a lot of IO contention since all want to write and read to the same disk.

How long do you wait until you decided that they not joining? I would assume it will take a while to join again, since the node needs to catch up on all 36 partitions. 



```
[zell scripts/ ns:long-running]$ ./partitionDistribution.sh 4 48 3
Distribution:
P\N|	N 0|	N 1|	N 2|	N 3
P 0|	L  |	F  |	F  |	-  
P 1|	-  |	L  |	F  |	F  
P 2|	F  |	-  |	L  |	F  
P 3|	F  |	F  |	-  |	L  
P 4|	L  |	F  |	F  |	-  
P 5|	-  |	L  |	F  |	F  
P 6|	F  |	-  |	L  |	F  
P 7|	F  |	F  |	-  |	L  
P 8|	L  |	F  |	F  |	-  
P 9|	-  |	L  |	F  |	F  
P 10|	F  |	-  |	L  |	F  
P 11|	F  |	F  |	-  |	L  
P 12|	L  |	F  |	F  |	-  
P 13|	-  |	L  |	F  |	F  
P 14|	F  |	-  |	L  |	F  
P 15|	F  |	F  |	-  |	L  
P 16|	L  |	F  |	F  |	-  
P 17|	-  |	L  |	F  |	F  
P 18|	F  |	-  |	L  |	F  
P 19|	F  |	F  |	-  |	L  
P 20|	L  |	F  |	F  |	-  
P 21|	-  |	L  |	F  |	F  
P 22|	F  |	-  |	L  |	F  
P 23|	F  |	F  |	-  |	L  
P 24|	L  |	F  |	F  |	-  
P 25|	-  |	L  |	F  |	F  
P 26|	F  |	-  |	L  |	F  
P 27|	F  |	F  |	-  |	L  
P 28|	L  |	F  |	F  |	-  
P 29|	-  |	L  |	F  |	F  
P 30|	F  |	-  |	L  |	F  
P 31|	F  |	F  |	-  |	L  
P 32|	L  |	F  |	F  |	-  
P 33|	-  |	L  |	F  |	F  
P 34|	F  |	-  |	L  |	F  
P 35|	F  |	F  |	-  |	L  
P 36|	L  |	F  |	F  |	-  
P 37|	-  |	L  |	F  |	F  
P 38|	F  |	-  |	L  |	F  
P 39|	F  |	F  |	-  |	L  
P 40|	L  |	F  |	F  |	-  
P 41|	-  |	L  |	F  |	F  
P 42|	F  |	-  |	L  |	F  
P 43|	F  |	F  |	-  |	L  
P 44|	L  |	F  |	F  |	-  
P 45|	-  |	L  |	F  |	F  
P 46|	F  |	-  |	L  |	F  
P 47|	F  |	F  |	-  |	L  

Partitions per Node:
N 0: 36
N 1: 36
N 2: 36
N 3: 36
```

**Comment by TangJiong** [comment]
@Zelldon Thanks for reply.
We are doing pressure test. 
Since increasing partion count can increase the throughput, we set 48 partions and get nearly 4000 instance/sec result with exporters enable and worker polling. The result is accetptable.

When we test fault tolerance, we come across the rejoin problem. As you suggest, so many partitions may cause high load for a broker. We did observe OOM error in alive broker during the rejoin process. We wait nealy a whole night (8 hours) until we give up the test.

Then my question is how to configure the proper partion count, cluster size, thread count and other settings when we need a cluster that can handle 30,000 instance created per second. Any suggestions? 

I opened a discussion in the forum.
https://forum.zeebe.io/t/does-partition-count-affect-the-time-the-cluster-need-to-recover-from-node-failing/1444
If it's not a bug we can continue discussing there.

**Comment by Zelldon** [comment]
Hey @TangJiong 

thanks for the response.

Would it possible for you to also increase the node count? The OOM sounds familiar and we fixed lately something like that, see here https://github.com/zeebe-io/zeebe/pull/4932

> Then my question is how to configure the proper partion count, cluster size, thread count and other settings when we need a cluster that can handle 30,000 instance created per second. Any suggestions?

It's cool to see and to have such a target number, but to be honest I never scaled zeebe so far so I can't really tell what would be the exact configuration for it. I think it makes sense to reduce the partition count per node to a smaller number like 8 or 12 and increase the node count respectively. 


```
[zell scripts/ ns:long-running]$ ./partitionDistribution.sh 16 48 3
Distribution:
P\N|	N 0|	N 1|	N 2|	N 3|	N 4|	N 5|	N 6|	N 7|	N 8|	N 9|	N 10|	N 11|	N 12|	N 13|	N 14|	N 15
P 0|	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 1|	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 2|	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 3|	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 4|	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 5|	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 6|	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 7|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  
P 8|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  
P 9|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  
P 10|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  
P 11|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  
P 12|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  
P 13|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  
P 14|	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  
P 15|	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  
P 16|	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 17|	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 18|	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 19|	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 20|	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 21|	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 22|	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 23|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  
P 24|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  
P 25|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  
P 26|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  
P 27|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  
P 28|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  
P 29|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  
P 30|	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  
P 31|	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  
P 32|	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 33|	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 34|	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 35|	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 36|	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 37|	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 38|	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  
P 39|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  
P 40|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  |	-  
P 41|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  |	-  
P 42|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  |	-  
P 43|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  |	-  
P 44|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  |	-  
P 45|	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  |	F  
P 46|	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  |	F  
P 47|	F  |	F  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	-  |	L  

Partitions per Node:
N 0: 9
N 1: 9
N 2: 9
N 3: 9
N 4: 9
N 5: 9
N 6: 9
N 7: 9
N 8: 9
N 9: 9
N 10: 9
N 11: 9
N 12: 9
N 13: 9
N 14: 9
N 15: 9
```

You can use the script I used to find a good partition distribution, you find it here https://github.com/zeebe-io/zeebe/blob/develop/benchmarks/docs/scripts/partitionDistribution.sh

In the end I think you need to test it for your specific use case to find the best configuration.
Some things which might help:

 * make sure that you set the cpu and io thread count to the similar value as the partition count
 * give the pod some more CPU's then the partition count, since raft and other threads also need to run
 * use SSD's
 * think about replication, do you need it? If not then disable it, then you can also enable memory mapped files
 * scale your gateway and increase the management thread count
 * decrease the max message size to an appropriate value, currently it is 4 MB and we find issues with it https://github.com/zeebe-io/zeebe/issues/4249 you can also reduce the logSegmentSize to a smaller value
 * in general not use big variables

**Comment by npepinpe** [comment]
I'm closing this for now - I hope this was of help to you. Feel free to reopen this if not.
