### ISSUE TITLE
DeploymentClusteredTest.shouldDeployWorkflowAndCreateInstances flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5013]
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no 
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
	at app//io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:133)
	at app//io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32)
	at app//io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201)
	at app//io.zeebe.util.sched.Actor.close(Actor.java:65)
	at app//io.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:56)
	at app//io.zeebe.broker.bootstrap.CloseProcess$$Lambda$1005/0x000000084095cc40.run(Unknown Source)
	at app//io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88)
	at app//io.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:56)
	at app//io.zeebe.broker.bootstrap.CloseProcess$$Lambda$1004/0x000000084095c840.run(Unknown Source)
	at app//io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88)
	at app//io.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:37)
	at app//io.zeebe.broker.Broker.lambda$close$24(Broker.java:405)
	at app//io.zeebe.broker.Broker$$Lambda$1003/0x000000084095c440.accept(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at app//io.zeebe.broker.Broker.lambda$close$25(Broker.java:403)
	at app//io.zeebe.broker.Broker$$Lambda$1002/0x000000084095c040.run(Unknown Source)
	at app//io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21)
	at app//io.zeebe.broker.Broker.close(Broker.java:398)
	at app//io.zeebe.broker.it.clustering.ClusteringRule$$Lambda$1487/0x0000000840b77840.accept(Unknown Source)
	at java.base@11.0.3/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base@11.0.3/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base@11.0.3/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.3/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base@11.0.3/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:1957)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base@11.0.3/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base@11.0.3/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base@11.0.3/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base@11.0.3/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base@11.0.3/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at app//io.zeebe.broker.it.clustering.ClusteringRule.after(ClusteringRule.java:236)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(Fut
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

See attached file : [io.zeebe.broker.it.clustering.DeploymentClusteredTest-it-output.zip](https://github.com/zeebe-io/zeebe/files/4952294/io.zeebe.broker.it.clustering.DeploymentClusteredTest-it-output.zip)

**Comment by korthout** [comment]
This type of failure should be fixed with https://github.com/zeebe-io/zeebe/pull/5717. Close for now
