### ISSUE TITLE
Broker fails to accept new connections

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#507]
I run a client in an endless loop in the shell like:

```
while true; do ./target/release/examples/request-topology; done
```

Which will create a new connection, send a request, read the response and after that closes the connection. After a while the following exception is logged while trying to accept new connections:

```
java.lang.RuntimeException: java.io.IOException: Too many open files
	at io.zeebe.transport.impl.ServerSocketBinding.accept(ServerSocketBinding.java:101)
	at io.zeebe.transport.impl.selector.AcceptTransportPoller.processKey(AcceptTransportPoller.java:68)
	at org.agrona.nio.NioSelectedKeySet.forEach(NioSelectedKeySet.java:136)
	at io.zeebe.transport.impl.selector.AcceptTransportPoller.pollNow(AcceptTransportPoller.java:50)
	at io.zeebe.transport.impl.actor.ServerConductor.doWork(ServerConductor.java:47)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at io.zeebe.transport.impl.ServerSocketBinding.accept(ServerSocketBinding.java:94)
	... 11 more
```

**Comment by menski** [comment]
not able to reproduce anymore
