### ISSUE TITLE
Out of memory if a broker in a cluster is shutdown

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#511]
### Problem

If a broker is shutdown in a cluster the remaining brokers get an `OutOfMemoryError` shortly after that. From a visualvm heap dump it seems that connections are kept in the `Sender` `channelMap`.

This problem means that it is currently not possible to test a cluster scenario where a broker leaves the cluster, as all remaining brokers run out of memory shortly after.

### Stacktrace

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at org.camunda.tngp.transport.impl.TransportChannelImpl.<init>(TransportChannelImpl.java:81)
	at org.camunda.tngp.transport.impl.ClientChannelImpl.<init>(ClientChannelImpl.java:34)
	at org.camunda.tngp.transport.impl.ClientChannelPoolImpl.openNewChannel(ClientChannelPoolImpl.java:207)
	at org.camunda.tngp.transport.impl.ClientChannelPoolImpl.handleChannelRequest(ClientChannelPoolImpl.java:142)
	at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:108)
	at org.camunda.tngp.transport.impl.ClientChannelPoolImpl.doWork(ClientChannelPoolImpl.java:220)
	at org.camunda.tngp.transport.impl.agent.TransportConductor.doWork(TransportConductor.java:73)
	at org.camunda.tngp.util.agent.AgentGroup.doWork(AgentGroup.java:45)
	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
this was fixed during a transport refactoring and does not occur anymore
