### ISSUE TITLE
Failed to install follower partition: Actor is closed

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#5117]
**Describe the bug**
We came across this error in our production cluster (attached stacktrace below). This may lead to a bigger issue ([quoted](https://github.com/zeebe-io/zeebe/issues/5063#issuecomment-669111936)):
>causes us to be unable to install the follower service, which means you will not be getting snapshots and may eventually run out of disk space.

Currently, the standalone gateway is showing a skewed network topology:
```
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.23.4
Brokers:
  Broker 0 - prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501
    Version: 0.23.4
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Leader
  Broker 1 - prod-zeebe-zeebe-broker-1.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501
    Version: 0.23.4
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Follower
  Broker 2 - prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501
    Version: 0.23.4
    Partition 1 : Follower
    Partition 3 : Follower
```
However Grafana shows this:
<img width="1241" alt="Screenshot 2020-08-05 at 5 22 16 PM" src="https://user-images.githubusercontent.com/10865861/89409806-4395f000-d740-11ea-84da-106a2f46102a.png">

**To Reproduce**
Nothing as such. It just happened randomly. Attached stacktrace below if that can help.

**Expected behavior**
Installation of follower service should happen successfully in case of partition role change.

**Log/Stacktrace**
Attached full stacktrace since the start of the issue.
<details><summary>Full Stacktrace</summary>
 <p>

```
2020-08-04 23:39:10.844 [Broker-2-SnapshotDirector-2] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/50514399-209-1596584349885/028389.sst
2020-08-04 23:41:08.498 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=2, group=raft-partition}
2020-08-04 23:41:08.498 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Closing Broker-2-Exporter-2
2020-08-04 23:41:08.498 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Partition role transitioning from LEADER to FOLLOWER
2020-08-04 23:41:08.498 [] [raft-server-2-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 11506225119720.
java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1422) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1407) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.23.4.jar:0.23.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-08-04 23:41:08.498 [] [raft-server-2-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 11506225119920.
java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1422) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1407) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.23.4.jar:0.23.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-08-04 23:41:08.499 [Broker-2-LogAppender-2] [Broker-2-zb-actors-0] ERROR io.zeebe.logstreams - Actor Broker-2-LogAppender-2 failed in phase STARTED.
java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1422) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1407) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.23.4.jar:0.23.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2020-08-04 23:41:08.500 [Broker-2-LogStream-2] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-2
2020-08-04 23:41:08.500 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] ERROR io.zeebe.broker.system - logstream-raft-partition-partition-2 failed, marking it as unhealthy
2020-08-04 23:41:08.500 [logstream-raft-partition-partition-2-write-buffer] [Broker-2-zb-actors-2] DEBUG io.zeebe.dispatcher - Dispatcher closed
2020-08-04 23:41:08.500 [Broker-2-LogStream-2] [Broker-2-zb-actors-2] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-2 close 3 readers
2020-08-04 23:41:08.501 [Broker-2-LogStream-2] [Broker-2-zb-actors-2] INFO  io.zeebe.logstreams - Close log storage with name logstream-raft-partition-partition-2
2020-08-04 23:41:08.501 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Raft-2=HEALTHY, Broker-2-StreamProcessor-2=HEALTHY, logstream-raft-partition-partition-2=UNHEALTHY}
2020-08-04 23:41:08.501 [Broker-2-HealthCheckService] [Broker-2-zb-actors-0] ERROR io.zeebe.broker.system - Partition-2 failed, marking it as unhealthy
2020-08-04 23:41:09.607 [Broker-2-Exporter-2] [Broker-2-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-2-Exporter-2'.
2020-08-04 23:41:09.607 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-2-Exporter-2 successfully
2020-08-04 23:41:09.607 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-2-SnapshotDirector-2
2020-08-04 23:41:09.608 [Broker-2-SnapshotDirector-2] [Broker-2-zb-fs-workers-1] ERROR io.zeebe.logstreams.snapshot - Unexpected error on retrieving commit position
2020-08-04 23:41:09.608 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Unexpected exception on closing Broker-2-SnapshotDirector-2
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:95) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:135) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getCommitPositionAsync(LogStreamImpl.java:105) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$1(AsyncSnapshotDirector.java:108) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
2020-08-04 23:41:09.609 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] ERROR io.zeebe.broker.system - Unexpected exception on removing leader partition!
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:95) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:135) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getCommitPositionAsync(LogStreamImpl.java:105) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$1(AsyncSnapshotDirector.java:108) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
2020-08-04 23:41:09.609 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] ERROR io.zeebe.broker.system - Failed to install follower partition 2
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:95) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:135) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getCommitPositionAsync(LogStreamImpl.java:105) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$1(AsyncSnapshotDirector.java:108) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
2020-08-04 23:41:14.059 [Broker-2-TopologyManager] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 1, partitions {1=FOLLOWER, 2=LEADER, 3=FOLLOWER} terms {2=216}
```

</p>
</details>

**Environment:**
 - Zeebe Version: `0.23.4`
<details><summary>Configuration</summary>
 <p>

```
Starting broker 2 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 26501,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501",
      "address" : "0.0.0.0:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 26502,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502",
      "address" : "0.0.0.0:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 9600,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:9600",
      "address" : "0.0.0.0:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502", "prod-zeebe-zeebe-broker-1.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502", "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 2,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 3,
    "ioThreadCount" : 3
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK"
  },
  "exporters" : {
    "hazelcast" : {
      "jarPath" : "/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar",
      "className" : "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args" : {
        "port" : 5701,
        "enabledValueTypes" : "DEPLOYMENT,JOB,WORKFLOW_INSTANCE,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION",
        "enabledRecordTypes" : "EVENT",
        "name" : "zeebe",
        "capacity" : 10000,
        "timeToLiveInSeconds" : 100,
        "format" : "protobuf"
      },
      "external" : true
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}
```

</p>
</details>

**Comment by npepinpe** [comment]
As first step, let's check if this affects current versions - if not we can reassess the priority.

**Comment by strawhat5** [comment]
Hey @npepinpe sorry for the delayed reply.

We had done the restart of broker 2 couple of days back, and confirmed that snapshot replication began after the restart. We also confirmed that snapshot replication did not occur for partition 2, **since the beginning of the issue till restart of broker 2**. Post the restart everything is back to normal.

**Comment by npepinpe** [comment]
So this has a new impact which we just discovered in our cloud deployment - it may happen that when you transition from leader to follower, if you fail in between, we won't notify the partition listeners of the transition. What we observed was the following:

1. Some services are left floating around (but closed) - I assume they can't be GC'd because something is still holding a reference to them? This made debugging a little more confusing :sweat_smile: 
1. The CommandApiService, as it is not notified of the transition, will not clear the request limiters. This can cause back pressure to be unreasonably high, and may cause it to never clear the existing limiters, resulting in commands being rejected (even if otherwise the broker is healthy).

There may be other issues if we don't clear the resources properly - and this affects 0.24 and 0.25. For this, I would like that we:

1. We should always close all resources. It's important we do so in order (i.e. dependents before dependencies), but even if a dependent fails, we should still close the dependency. At this point, we're anyway in a broken state, so not closing further services doesn't help more than closing them.
1. As a safeguard, on transitioning to a state (especially leader), we should clear any resources that may be previously still around (in this case the CommandApiService).
1. Evaluate if it can be safe to transition to follower/leader even if we failed to transition away from the previous state.
1. Evaluate if we should notify listeners even when the transition fails so they can reset their state.

I'm not sure how we can best test this, but I trust the team will find a solution :sweat_smile:

**Comment by npepinpe** [comment]
One thing to clarify - this is completely recoverable by restarting your node, and won't lead to any long term effects (e.g. data loss or corruption). You can detect this by checking if the back pressure in-flight metrics is constant and greater than or equal the queue size metric for, say, 5 minutes - that should indicate something is wrong.
