### ISSUE TITLE
BrokerClientTest.shouldNotTimeoutIfPartitionLeaderMismatchResponseWhenRetryDisabled flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5165]
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError: 

Expecting a cause with type:
  <"io.zeebe.gateway.cmd.BrokerErrorException">
and message:
  <"Received error from broker (PARTITION_LEADER_MISMATCH): ">
but type was:
  <"java.util.concurrent.TimeoutException">
and message was:
  <"Request timed out after PT3S">.
	at io.zeebe.gateway.broker.BrokerClientTest.shouldNotTimeoutIfPartitionLeaderMismatchResponseWhenRetryDisabled(BrokerClientTest.java:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
05:50:25.587 [main] INFO  io.zeebe.test - Test started: shouldNotTimeoutIfPartitionLeaderMismatchResponseWhenRetryDisabled(io.zeebe.gateway.broker.BrokerClientTest)
05:50:25.607 [main] INFO  io.zeebe.test.util.SocketUtil - Starting socket assignment with testForkNumber 2 and testMavenId 1
05:50:25.707 [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27700 for test fork 2 with range PortRange{host='localhost', basePort=27700, maxOffset=100, currentOffset=1}
05:50:27.994 [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27701 for test fork 2 with range PortRange{host='localhost', basePort=27700, maxOffset=100, currentOffset=2}
05:50:33.298 [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:27701
05:50:33.397 [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
05:50:33.886 [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:27701
05:50:33.896 [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
05:50:34.000 [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
05:50:34.001 [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
05:50:34.001 [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
05:50:34.006 [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
05:50:34.390 [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27702 for test fork 2 with range PortRange{host='localhost', basePort=27700, maxOffset=100, currentOffset=3}
05:50:34.409 [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27703 for test fork 2 with range PortRange{host='localhost', basePort=27700, maxOffset=100, currentOffset=4}
05:50:34.592 [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:27703
05:50:34.595 [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
05:50:34.701 [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:27703
05:50:34.703 [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
05:50:34.785 [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
05:50:34.791 [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
05:50:34.792 [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
05:50:34.800 [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
05:50:39.313 [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
05:50:39.411 [main] DEBUG io.zeebe.gateway - topology manager closed
05:50:39.491 [main] DEBUG io.zeebe.util.actor - Closing blocking task runner
05:50:39.494 [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'gateway-scheduler-zb-fs-workers'
05:50:39.498 [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'gateway-scheduler-zb-fs-workers': closed successfully
05:50:39.500 [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'gateway-scheduler-zb-actors'
05:50:39.589 [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'gateway-scheduler-zb-actors': closed successfully
05:50:39.590 [main] DEBUG io.zeebe.util.actor - Closing blocking task runner: closed successfully
05:50:39.591 [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
05:50:39.592 [main] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
05:50:39.594 [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
05:50:39.695 [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - gateway - Member deactivated: Member{id=gateway, address=localhost:27703, properties={}}
05:50:39.696 [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
05:50:39.699 [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
05:50:39.714 [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
05:50:44.489 [ForkJoinPool.commonPool-worker-3] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
05:50:44.491 [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
05:50:44.503 [main] DEBUG io.zeebe.util.actor - Closing blocking task runner
05:50:44.504 [main] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
05:50:44.587 [main] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors'
05:50:44.590 [main] DEBUG io.zeebe.util.actor - Closing blocking task runner: closed successfully
05:50:44.590 [-zb-fs-workers-1] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
05:50:44.592 [main] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
05:50:44.591 [-zb-actors-0] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
05:50:44.594 [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
05:50:44.595 [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member deactivated: Member{id=0, address=localhost:27701, properties={}}
05:50:44.595 [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
05:50:44.596 [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
05:50:44.596 [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
05:50:48.708 [ForkJoinPool.commonPool-worker-3] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
05:50:48.709 [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
</pre>
</details>

**Comment by npepinpe** [comment]
Still happened a few weeks ago.

**Comment by npepinpe** [comment]
Hasn't happened in a while
