### ISSUE TITLE
DiskSpaceRecoveryITTest.shouldRecoverAfterOutOfDiskSpaceWhenExporterStarts flaky

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5174]
**Summary**

- How often does the test fail? Top 3 in CW 33
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a lambda expression in io.zeebe.broker.it.health.DiskSpaceRecoveryITTest 
Expecting code to raise a throwable within 3 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at io.zeebe.broker.it.health.DiskSpaceRecoveryITTest.shouldRecoverAfterOutOfDiskSpaceWhenExporterStarts(DiskSpaceRecoveryITTest.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
09:49:45.665 [] [main] INFO  org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy - Found docker client settings from environment
09:49:45.757 [] [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=tcp://localhost:2375
09:49:48.654 [] [main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is localhost
09:49:48.945 [] [main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 18.09.4
  API Version: 1.39
  Operating System: Alpine Linux v3.9 (containerized)
  Total Memory: 120871 MB
09:49:49.170 [] [main] WARN  org.testcontainers.utility.RegistryAuthLocator - Failure when attempting to lookup auth config (dockerImageName: testcontainersofficial/ryuk:0.3.0, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
09:49:50.664 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Starting to pull image
09:49:51.245 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
09:49:51.268 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  2 pending,  1 downloaded,  0 extracted, (55 KB/? MB)
09:49:51.269 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  1 pending,  2 downloaded,  0 extracted, (55 KB/? MB)
09:49:51.272 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  0 pending,  3 downloaded,  0 extracted, (59 KB/5 MB)
09:49:51.370 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  0 pending,  3 downloaded,  1 extracted, (2 MB/5 MB)
09:49:51.454 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  0 pending,  3 downloaded,  2 extracted, (2 MB/5 MB)
09:49:51.568 [] [tc-okhttp-stream-35864696] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  0 pending,  3 downloaded,  3 extracted, (5 MB/5 MB)
09:49:56.365 [] [main] INFO  org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
09:49:56.365 [] [main] INFO  org.testcontainers.DockerClientFactory - Checking the system...
09:49:56.367 [] [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
09:49:56.756 [] [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
09:49:57.153 [] [main] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling docker image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11. Please be patient; this may take some time but only needs to be done once.
09:49:57.155 [] [main] WARN  org.testcontainers.utility.RegistryAuthLocator - Failure when attempting to lookup auth config (dockerImageName: docker.elastic.co/elasticsearch/elasticsearch:latest, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
09:49:58.445 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Starting to pull image
09:49:58.447 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
09:49:59.147 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  6 pending,  1 downloaded,  0 extracted, (59 MB/? MB)
09:49:59.847 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  5 pending,  2 downloaded,  0 extracted, (170 MB/? MB)
09:50:00.249 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  4 pending,  3 downloaded,  0 extracted, (219 MB/? MB)
09:50:00.647 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  3 pending,  4 downloaded,  0 extracted, (272 MB/? MB)
09:50:01.848 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  2 pending,  5 downloaded,  0 extracted, (425 MB/? MB)
09:50:02.346 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  0 extracted, (462 MB/? MB)
09:50:04.346 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  1 extracted, (468 MB/? MB)
09:50:09.479 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  2 extracted, (469 MB/? MB)
09:50:11.552 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  3 extracted, (476 MB/? MB)
09:50:11.725 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  4 extracted, (476 MB/? MB)
09:50:17.746 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  5 extracted, (479 MB/? MB)
09:50:19.061 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  6 extracted, (479 MB/? MB)
09:50:19.186 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pulling image layers:  1 pending,  6 downloaded,  7 extracted, (479 MB/? MB)
09:50:19.207 [] [tc-okhttp-stream-673129458] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Pull complete. 7 layers, pulled in 20s (downloaded 479 MB at 23 MB/s)
09:50:19.274 [] [main] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:6.8.11] - Starting an elasticsearch container using [docker.elastic.co/elasticsearch/elasticsearch:6.8.11]
09:50:19.280 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Creating container for image: camunda/zeebe:current-test
09:50:19.692 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Starting container with ID: 3a16353480d7353a5b913b2e10578cada544ac50153643092a9dda4835fd571c
09:50:20.297 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test is starting: 3a16353480d7353a5b913b2e10578cada544ac50153643092a9dda4835fd571c
09:50:20.380 [] [main] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /zeebe-broker-e54Rrw-9NDBQs: Waiting for 60 seconds for URL: http://localhost:32782/ready
09:50:35.952 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test started in PT16.673108S
09:50:35.960 [] [main] INFO  io.zeebe.test - Test started: shouldRecoverAfterOutOfDiskSpaceWhenExporterStarts(io.zeebe.broker.it.health.DiskSpaceRecoveryITTest)
09:50:42.758 [] [main] INFO  io.zeebe.broker.it.health.DiskSpaceRecoveryITTest - Wait until broker is out of disk space
</pre>
</details>

**Comment by npepinpe** [comment]
@korthout was this the one which failed due to resource contention?

**Comment by korthout** [comment]
Yes, it seems fixed with https://github.com/zeebe-io/zeebe/pull/5717. So, I'll close it now
