### ISSUE TITLE
Broker tries to create raft group for system topic twice on startup of cluster

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#523]
When I start a 3 node broker cluster with [docker-compose](https://github.com/zeebe-io/zeebe/blob/747f628e81ab517ee439b1a27bf10767ecdbdec0/docker/compose/docker-compose.yaml) I often see the following exception which indicates that the first broker tries to create the raft group for the system topic twice. Sometimes this also happens on all three brokers on startup.

```
broker-1_1  | 10:40:16.570 [actor-runner-service-container] ERROR io.zeebe.servicecontainer - Failed to build service                                                                                                                                                           
broker-1_1  | java.lang.IllegalStateException: Cannot install service with name 'cluster.raft.internal-system.0'. Service with same name already exists                                                                                                                         
broker-1_1  |   at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$4(ServiceContainerImpl.java:156) ~[zb-service-container-0.4.0-20171020.093946-8.jar:0.4.0-SNAPSHOT]                                                                                
broker-1_1  |   at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$new$0(ServiceContainerImpl.java:53) ~[zb-service-container-0.4.0-20171020.093946-8.jar:0.4.0-SNAPSHOT]
broker-1_1  |   at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:113) [agrona-0.9.6.jar:?]                                                                                                                                       
broker-1_1  |   at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:88) [agrona-0.9.6.jar:?]                                                                                                                                        
broker-1_1  |   at io.zeebe.servicecontainer.impl.ServiceContainerImpl.doWork(ServiceContainerImpl.java:105) [zb-service-container-0.4.0-20171020.093946-8.jar:0.4.0-SNAPSHOT]                                                                                                  
broker-1_1  |   at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [zb-util-0.4.0-20171025.140638-12.jar:0.4.0-SNAPSHOT]                                                                                                                                      
broker-1_1  |   at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138) [zb-util-0.4.0-20171025.140638-12.jar:0.4.0-SNAPSHOT]
broker-1_1  |   at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [zb-util-0.4.0-20171025.140638-12.jar:0.4.0-SNAPSHOT]
broker-1_1  |   at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [zb-util-0.4.0-20171025.140638-12.jar:0.4.0-SNAPSHOT]
broker-1_1  |   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]                  
```

**Comment by menski** [comment]
This actually is a problem with the docker-compose setup and our peer identity. In the docker container the broker uses IP address for the API endpoints but for the initial contact point it uses the DNS name of the first broker. This leads to the case that the first broker discovers itself as a new peer in the cluster and sends an invitation request to itself. I added some more logging to show that:

```
14:03:26.842 [actor-runner-broker-3] DEBUG io.zeebe.broker.clustering - Peer broker-1:51016 joined the cluster
14:03:26.843 [actor-runner-broker-2] DEBUG io.zeebe.broker.clustering - Send invitation request to broker-1:51016 for partition 0 in term 1
14:03:26.921 [actor-runner-broker-2] DEBUG io.zeebe.broker.clustering - Received invitation request from b1f2f4df3f3e:35418 for partition 0
```

This is basically the broker-1 sending itself an invitation to join the system topic.

To prevent that we would have to either use also the IP address in the initial contact point or have a normalized way to detect if peers are equal. So that DNS names and IP addresses can be used interchangeably. We will look into that during the gossip rewrite I guess #343.
