### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Cannot truncate committed index

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#5295]
**Describe the bug**

[Link to logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-09-04T08%3A17%3A02.619000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22dd-medium-load%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.pod_name%3D%22dd-medium-load-zeebe-0%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Atimestamp%3D%222020-09-03T08%3A55%3A57.414779000Z%22%0AinsertId%3D%22rc8wkrr588d4kmov0%22&scrollTimestamp=2020-09-04T07%3A21%3A04.305983000Z)

```
I 2020-09-03T08:55:47.063434Z RaftServer{raft-partition-partition-3} - Transitioning to CANDIDATE 
I 2020-09-03T08:55:47.064499Z RaftServer{raft-partition-partition-3}{role=CANDIDATE} - Starting election 
I 2020-09-03T08:55:47.090446Z RaftServer{raft-partition-partition-3} - Transitioning to LEADER 
I 2020-09-03T08:55:47.091180Z RaftServer{raft-partition-partition-3} - Found leader 0 
I 2020-09-03T08:55:57.372020Z RaftServer{raft-partition-partition-3}{role=LEADER} - Received greater term from 2 
I 2020-09-03T08:55:57.372500Z RaftServer{raft-partition-partition-3} - Transitioning to FOLLOWER 
I 2020-09-03T08:55:57.373437Z RaftServer{raft-partition-partition-3} - Found leader 2 
E 2020-09-03T08:55:57.414779Z RaftServer{raft-partition-partition-3} - An uncaught exception occurred, transition to inactive role 
I 2020-09-03T08:55:57.415719Z RaftServer{raft-partition-partition-3} - Transitioning to INACTIVE 
```
Following exception occured:
```
exception: "java.lang.IndexOutOfBoundsException: Cannot truncate committed index: 75643078
	at io.atomix.storage.journal.SegmentedJournalWriter.truncate(SegmentedJournalWriter.java:107) ~[atomix-storage-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.storage.journal.DelegatingJournalWriter.truncate(DelegatingJournalWriter.java:66) ~[atomix-storage-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.replaceExistingEntry(PassiveRole.java:688) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:627) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:588) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:440) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:197) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$12(RaftContext.java:209) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19(RaftContext.java:220) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Environment:**
 - Zeebe Version: 0.25-SNAPSHOT

**Comment by deepthidevaki** [comment]
Observed this again. [Logs](https://console.cloud.google.com/logs/viewer?interval=P1D&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-09-07T12%3A11%3A52.223000000Z&customFacets=resource.labels.pod_name&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22dd-medium-load-zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22dd-medium-load%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Atimestamp%3D%222020-09-06T18%3A42%3A42.218171000Z%22%0AinsertId%3D%22nbbhavv9005vbgsoe%22&scrollTimestamp=2020-09-06T18%3A53%3A57.309962000Z&dateRangeStart=2020-09-06T12%3A11%3A52.475Z&dateRangeEnd=2020-09-07T12%3A11%3A52.475Z)

There was back-to-back leader changes before this happened. 
zeebe-2 was leader.
zeebe-0 starts election at term 9
Zeebe-1 Accepted VoteRequest{term=9, candidate=0, lastLogIndex=159761338, lastLogTerm=8}
Zeebe-2  Accepted VoteRequest{term=9, candidate=0, lastLogIndex=159761338, lastLogTerm=8}
(Zeebe-0 then probably appends and tries to commit InitialEntry at 159761339)
Then zeebe-1 starts election at term 10
Zeebe-2 Accepted VoteRequest{term=10, candidate=1, lastLogIndex=159761338, lastLogTerm=8} (This indicates that Zeebe-2 did not receive InitialEntry from Zeebe-0)
Zeebe-1 then becomes leader and probably tries to append the initial entry at 159761339. 
But when Zeebe-0 and Zeebe-1 receives it, they have already committed entry at 159761339 at previous term. It is not clear when it was appended on Zeebe-2. If it was appended on Zeebe-2 before the vote request, it should have rejected Vote from 1. If it received the append request after the Vote, it should have rejected the append request. 

```
W 2020-09-06T18:42:26.374516Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1} - AppendRequest{term=8, leader=2, prevLogIndex=159761338, prevLogTerm=8, entries=0, commitIndex=159761338} to 0 failed: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to bootstrap client (address dd-medium-load-zeebe-0.dd-medium-load-zeebe.dd-medium-load.svc.cluster.local:26502 cannot be resolved)  dd-medium-load-zeebe-2
I 2020-09-06T18:42:27.098993368Z dd-medium-load-zeebe-0 {"severity":"WARNING","logging.googleapis.com/sourceLocation":{"function":"handlePollResponse","file":"FollowerRole.java","line":306},"message":"RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Poll request to 1 failed: java.util.concurrent.TimeoutException: Request type raft-partition-partition-1-poll timed out in 5000 milliseconds","serviceContext":{"service":"zeebe-broker","version":"dd-medium-load"},"context":{"threadId":76,"threadPriority":5,"loggerName":"io.atomix.raft.roles.FollowerRole","threadName":"raft-server-0-raft-partition-partition-1"},"timestampSeconds":1599417747,"timestampNanos":98023000,"logger":"io.atomix.raft.roles.FollowerRole","thread":"raft-server-0-raft-partition-partition-1"}{"severity":"WARNING","logging.googleapis.com/sourceLocation":{"function":"handlePollResponse","file":"FollowerRole.java","line":306},"message":"RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Poll request to 1 failed: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-poll timed out in 5000 milliseconds","serviceContext":{"service":"zeebe-broker","version":"dd-medium-load"},"context":{"threadId":59,"threadPriority":5,"loggerName":"io.atomix.raft.roles.FollowerRole","threadName":"raft-server-0-raft-partition-partition-2"},"timestampSeconds":1599417747,"timestampNanos":98023000,"logger":"io.atomix.raft.roles.FollowerRole","thread":"raft-server-0-raft-partition-partition-2"}

  dd-medium-load-zeebe-0
I 2020-09-06T18:42:32.313446Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from DefaultRaftMember{id=2, type=ACTIVE, updated=2020-09-04T11:06:25.620Z} in the last PT3.539S (calculated from last 3539 ms), sending poll requests  dd-medium-load-zeebe-0
I 2020-09-06T18:42:32.316147Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=8, candidate=0, lastLogIndex=159761338, lastLogTerm=8}: candidate's log is up-to-date  dd-medium-load-zeebe-1
I 2020-09-06T18:42:32.320047Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE  dd-medium-load-zeebe-0
I 2020-09-06T18:42:32.321269Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Starting election  dd-medium-load-zeebe-0
I 2020-09-06T18:42:32.330528Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=9, candidate=0, lastLogIndex=159761338, lastLogTerm=8}: candidate's log is up-to-date  dd-medium-load-zeebe-1
I 2020-09-06T18:42:32.336741Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - Transitioning to LEADER  dd-medium-load-zeebe-0
I 2020-09-06T18:42:32.337623Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - Found leader 0  dd-medium-load-zeebe-0
I 2020-09-06T18:42:32.337877Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1}{role=LEADER} - Received greater term from 0  dd-medium-load-zeebe-2
I 2020-09-06T18:42:32.338297Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER  dd-medium-load-zeebe-2
I 2020-09-06T18:42:32.338969Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1}{role=LEADER} - Accepted VoteRequest{term=9, candidate=0, lastLogIndex=159761338, lastLogTerm=8}: candidate's log is up-to-date  dd-medium-load-zeebe-2
I 2020-09-06T18:42:32.457637Z dd-medium-load-zeebe-2 Close appender for log stream logstream-raft-partition-partition-1  dd-medium-load-zeebe-2
I 2020-09-06T18:42:32.458175Z dd-medium-load-zeebe-2 On closing logstream logstream-raft-partition-partition-1 close 3 readers  dd-medium-load-zeebe-2
I 2020-09-06T18:42:32.458452Z dd-medium-load-zeebe-2 Close log storage with name logstream-raft-partition-partition-1  dd-medium-load-zeebe-2
I 2020-09-06T18:42:35.290655Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from null in the last PT2.957S (calculated from last 2957 ms), sending poll requests  dd-medium-load-zeebe-1
W 2020-09-06T18:42:35.292697Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Poll request to 0 failed: java.lang.IllegalStateException: Failed to bootstrap client (address dd-medium-load-zeebe-0.dd-medium-load-zeebe.dd-medium-load.svc.cluster.local:26502 cannot be resolved)  dd-medium-load-zeebe-1
I 2020-09-06T18:42:35.295050Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE  dd-medium-load-zeebe-1
I 2020-09-06T18:42:35.295785Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Starting election  dd-medium-load-zeebe-1
I 2020-09-06T18:42:35.295896Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=9, candidate=1, lastLogIndex=159761338, lastLogTerm=8}: candidate's log is up-to-date  dd-medium-load-zeebe-2
W 2020-09-06T18:42:35.305553Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1}{role=CANDIDATE} - java.lang.IllegalStateException: Failed to bootstrap client (address dd-medium-load-zeebe-0.dd-medium-load-zeebe.dd-medium-load.svc.cluster.local:26502 cannot be resolved)  dd-medium-load-zeebe-1
I 2020-09-06T18:42:35.314417Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=10, candidate=1, lastLogIndex=159761338, lastLogTerm=8}: candidate's log is up-to-date  dd-medium-load-zeebe-2
I 2020-09-06T18:42:35.314923Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1} - Transitioning to LEADER  dd-medium-load-zeebe-1
I 2020-09-06T18:42:35.315824Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1} - Found leader 1  dd-medium-load-zeebe-1
I 2020-09-06T18:42:39.928014Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1} - Found leader 1  dd-medium-load-zeebe-2
I 2020-09-06T18:42:40.035151Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - Found leader 1  dd-medium-load-zeebe-0
I 2020-09-06T18:42:42.201739Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER  dd-medium-load-zeebe-1
I 2020-09-06T18:42:42.203374Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER  dd-medium-load-zeebe-0
I 2020-09-06T18:42:42.205544Z dd-medium-load-zeebe-1 RaftServer{raft-partition-partition-1} - Found leader 1  dd-medium-load-zeebe-1
E 2020-09-06T18:42:42.218171Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role  dd-medium-load-zeebe-0
I 2020-09-06T18:42:42.219883Z dd-medium-load-zeebe-0 RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE  dd-medium-load-zeebe-0
E 2020-09-06T18:42:42.928048Z dd-medium-load-zeebe-0 Raft-1 failed, marking it as unhealthy  dd-medium-load-zeebe-0
E 2020-09-06T18:42:42.933334Z dd-medium-load-zeebe-0 Partition-1 failed, marking it as unhealthy  dd-medium-load-zeebe-0
E 2020-09-06T18:42:43.335240Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role  dd-medium-load-zeebe-2
I 2020-09-06T18:42:43.336Z dd-medium-load-zeebe-2 RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE  dd-medium-load-zeebe-2
```

```
dd-medium-load-zeebe-0
RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role
Expand all | Collapse all
{
 insertId: "nbbhavv9005vbgsoe"  
 
jsonPayload: {
  @type: "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"   
  
context: {…}   
  exception: "java.lang.IndexOutOfBoundsException: Cannot truncate committed index: 159761338
	at io.atomix.storage.journal.SegmentedJournalWriter.truncate(SegmentedJournalWriter.java:107) ~[atomix-storage-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.storage.journal.DelegatingJournalWriter.truncate(DelegatingJournalWriter.java:66) ~[atomix-storage-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:636) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:589) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:441) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.onAppend(LeaderRole.java:548) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$12(RaftContext.java:209) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19(RaftContext.java:220) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
dd-medium-load-zeebe-2
RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role
Expand all | Collapse all
{
 insertId: "3btrgbyf0ertyk0dr"  
 
jsonPayload: {
  @type: "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"   
  
context: {…}   
  exception: "java.lang.IndexOutOfBoundsException: Cannot truncate committed index: 159761338
	at io.atomix.storage.journal.SegmentedJournalWriter.truncate(SegmentedJournalWriter.java:107) ~[atomix-storage-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.storage.journal.DelegatingJournalWriter.truncate(DelegatingJournalWriter.java:66) ~[atomix-storage-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:636) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:589) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:441) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:197) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$12(RaftContext.java:209) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19(RaftContext.java:220) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
"   
```
We can also see that Zeebe-1 and Zeebe-0 have committed upto 159761339

![image](https://user-images.githubusercontent.com/1997478/92390567-69d1f580-f11b-11ea-8ac6-c0db27c20079.png)

We cannot inspect the log because the cluster recovered after a restart.

**Comment by deepthidevaki** [comment]
This might be due to either #5360 or #5356. I will close this for now. Please re-open if we see this again.
