### ISSUE TITLE
Use of unescaped user input in regex

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#535]
The `name` parameter of the [pattern](https://github.com/zeebe-io/zb-logstreams/blob/608fcab6327d4faa192d4061399ee092067eeb15/src/main/java/io/zeebe/logstreams/impl/snapshot/fs/FsSnapshotStorageConfiguration.java#L63) use in the `matchesSnapshotFileNamePattern` is user controlled input. Which means the user defines the regex pattern. Could be a security concern but I'm not sure if there is any attack vector here. Just saw accidentally the following stack trace using an unusual topic name:

```
java.util.regex.PatternSyntaxException: Illegal repetition near index 22
workflow.test-Duration { secs: 1510275619, nanos: 395837140 }.6.processor.incident-(\d+).snapshot
                      ^
	at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_144]
	at java.util.regex.Pattern.closure(Pattern.java:3157) ~[?:1.8.0_144]
	at java.util.regex.Pattern.sequence(Pattern.java:2134) ~[?:1.8.0_144]
	at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_144]
	at java.util.regex.Pattern.compile(Pattern.java:1696) ~[?:1.8.0_144]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_144]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_144]
	at java.util.regex.Pattern.matches(Pattern.java:1133) ~[?:1.8.0_144]
	at java.lang.String.matches(String.java:2121) ~[?:1.8.0_144]
	at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorageConfiguration.matchesSnapshotFileNamePattern(FsSnapshotStorageConfiguration.java:64) ~[zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.lambda$getLastSnapshot$0(FsSnapshotStorage.java:43) ~[zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at java.io.File.listFiles(File.java:1291) ~[?:1.8.0_144]
	at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.getLastSnapshot(FsSnapshotStorage.java:43) ~[zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.getLastSnapshot(FsSnapshotStorage.java:28) ~[zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$RecoveringState.work(StreamProcessorController.java:498) [zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$RecoveringState.work(StreamProcessorController.java:489) [zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.state.TransitionState.doWork(TransitionState.java:26) ~[zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:131) [zb-logstreams-0.5.0-20171107.121757-1.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138) [zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [zb-util-0.5.0-20171109.102117-2.jar:0.5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Zelldon** [comment]
I think this is out dated
