### ISSUE TITLE
NullPointerException in io.zeebe.engine.nwe.behavior.BpmnEventSubscriptionBehavior.triggerEventSubProcess

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5393]
**Describe the bug**

An NPE occurs during reprocessing, causing the broker to enter an endless loop of retrying that particular record. See the following error report: https://console.cloud.google.com/errors/CIzc7_TVt-H01gE?service=zeebe&version=0.24.2&time=P1D&project=camunda-cloud-240911&organizationId=669107107215

**To Reproduce**

Not sure, but this is occurring on a development cluster in Camunda Cloud, so you can ask the SRE team for access to the data in order to inspect it.

**Expected behavior**

1. If the NPE is expected, then we should handle it - if it isn't, then we should root cause why it happens.
1. The broker should not enter an endless loop but rather fail the actor.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.zeebe.engine.nwe.behavior.BpmnEventSubscriptionBehavior.triggerEventSubProcess(BpmnEventSubscriptionBehavior.java:390) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.event.StartEventProcessor.onEventOccurred(StartEventProcessor.java:85) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.event.StartEventProcessor.onEventOccurred(StartEventProcessor.java:20) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:139) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.nwe.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:122) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.workflow.BpmnStepHandlers.handle(BpmnStepHandlers.java:90) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecordValue(BpmnStepProcessor.java:82) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:62) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:287) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:262) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.2.jar:0.24.2]
```

</p>
</details>

**Environment:**
 - OS: official zeebe distro
 - Zeebe Version: 0.24.2
 - Configuration: cloud config

**Comment by saig0** [comment]
I agree that we should avoid an endless loop in the reprocessing if there is no chance to recover from.

Looking at the code, it seems that an event subprocess was triggered but the flow scope was not in the state (anymore). I'm not sure why this happened. But we should avoid an NPE, for example, by adjusting the guard or the start event processor.

**Comment by Zelldon** [comment]
So I have the feeling here we discussing multiple things here, which I would like to split up.

**Current Issue:**
 There is a NPE somewhere, we are not 100% sure why, but it blocks the restarting/reprocessing.

**Proposed Solutions**
 1. Fix the NPE in a way that it not blocks the reprocessing. My question would be here how would be the guard change look like? And what does it mean for the workflow instance then?
 2. Not going in a endless loop when something is bricked. In your opinion endless loop should be avoided and instead the actor failed. I think this should be separated in a different issue, since we need to discuss this further. For example what should happen next? If the actor failed, the starting of the processing failed this will cause the partition to fail, which means we step down. Next Leader will elected and it is likely that this will happen again right?

**Comments**

I have the feeling this is related to the other reprocessing issue which we had. Maybe the refactoring broke also other parts? How likely is this?

**Comment by Zelldon** [comment]
We (@saig0 and me) expect that this is related to the reprocessing issue when generating new key. It might be introduced by by a bug fix https://github.com/zeebe-io/zeebe/issues/4959, which was done for 0.24.2. To verify we need the process model and ideally access to operate to get all necessary data. 
If this is the case then the reprocessing check https://github.com/zeebe-io/zeebe/issues/5381, which was added by @saig0 should find this.

For now we will not add an additional guard, since this should be catch previous by the reprocessing check.

**Comment by npepinpe** [comment]
I'm totally fine with splitting this in different issues, and yeah, my first guess would be this is a reprocessing issue (but it's unclear to me how we would figure that out).

**Comment by Zelldon** [comment]
I was able to extract the workflow from the data snapshot via zdb. Really cool :D 

```sh
zell@inc-65a-vm-20200922-144132:/tmp$ java -jar zdb.jar workflow list -p /data/zeebe-0/raft-partition/partitions/1/runtime/
Workflow[key: 2251799813685264, BPMN-process-id: "ReplyProcess", version: 1]
Workflow[key: 2251799813685288, BPMN-process-id: "ReplyProcess", version: 2]
Workflow[key: 2251799813685337, BPMN-process-id: "ReplyProcess", version: 3]
Workflow[key: 2251799813685467, BPMN-process-id: "ReplyProcess", version: 4]
Workflow[key: 2251799813685469, BPMN-process-id: "ReplyProcess", version: 5]
Workflow[key: 2251799813685479, BPMN-process-id: "ReplyProcess", version: 6]
Workflow[key: 2251799813685522, BPMN-process-id: "Process_0vkhgz5", version: 1]
Workflow[key: 2251799813685525, BPMN-process-id: "Process_0vkhgz5", version: 2]
Workflow[key: 2251799813685540, BPMN-process-id: "SearchTwitterProcess", version: 1]
Workflow[key: 2251799813685850, BPMN-process-id: "SearchTwitterProcess", version: 2]
Workflow[key: 2251799813686064, BPMN-process-id: "SearchTwitterProcess", version: 3]
Workflow[key: 2251799813686196, BPMN-process-id: "SearchTwitterProcess", version: 4]
Workflow[key: 2251799813686251, BPMN-process-id: "SearchTwitterProcess", version: 5]
Workflow[key: 2251799813686877, BPMN-process-id: "SearchTwitterProcess", version: 6]
Workflow[key: 2251799813686914, BPMN-process-id: "lotteryProcess", version: 1]
Workflow[key: 2251799813686931, BPMN-process-id: "SearchTwitterProcess", version: 7]
Workflow[key: 2251799813686953, BPMN-process-id: "SearchTwitterProcess", version: 8]
Workflow[key: 2251799813687048, BPMN-process-id: "lotteryProcess", version: 2]
Workflow[key: 2251799813687050, BPMN-process-id: "lotteryProcess", version: 3]
Workflow[key: 2251799813687123, BPMN-process-id: "lotteryProcess", version: 4]
Workflow[key: 2251799813687260, BPMN-process-id: "ReplyProcess", version: 7]
Workflow[key: 2251799813687325, BPMN-process-id: "lotteryProcess", version: 5]
```
```sh
zell@inc-65a-vm-20200922-144132:/tmp$ java -jar zdb.jar workflow entity 2251799813687325 -p /data/zeebe-0/raft-partition/partitions/1/runtime/
Workflow[key: 2251799813687325, BPMN-process-id: "lotteryProcess", version: 5, resource-name: "lotteryProcess", resource: "<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="Definitions_1gip3o5" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Zeebe Modeler" exporterVersion="0.9.1">
  <bpmn:process id="lotteryProcess" isExecutable="true">
    <bpmn:startEvent id="StartLottery" name="Lottery Started">
      <bpmn:outgoing>Flow_1i2y26w</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1i2y26w" sourceRef="StartLottery" targetRef="tweetAboutLottery" />
    <bpmn:subProcess id="Activity_0jwnffs" triggeredByEvent="true">
      <bpmn:startEvent id="Event_0rxc9jo" name="Partipant tweet found">
        <bpmn:outgoing>Flow_1poe8lo</bpmn:outgoing>
        <bpmn:messageEventDefinition id="MessageEventDefinition_1fs6ysg" messageRef="Message_0nro6hj" />
      </bpmn:startEvent>
      <bpmn:endEvent id="participant" name="Done">
        <bpmn:incoming>Flow_0rowbkz</bpmn:incoming>
      </bpmn:endEvent>
      <bpmn:serviceTask id="Activity_1j1706h" name="Reply to tweet">
        <bpmn:extensionElements>
          <zeebe:taskDefinition type="send-tweet" />
          <zeebe:taskHeaders>
            <zeebe:header key="messageTemplate" value="You have been considered for the lottery" />
          </zeebe:taskHeaders>
          <zeebe:ioMapping>
            <zeebe:input source="=tweetId" target="inReplyToStatusId" />
          </zeebe:ioMapping>
        </bpmn:extensionElements>
        <bpmn:incoming>Flow_085dglq</bpmn:incoming>
        <bpmn:outgoing>Flow_0rowbkz</bpmn:outgoing>
      </bpmn:serviceTask>
      <bpmn:sequenceFlow id="Flow_0rowbkz" sourceRef="Activity_1j1706h" targetRef="participant" />
      <bpmn:sequenceFlow id="Flow_1poe8lo" sourceRef="Event_0rxc9jo" targetRef="Activity_07wdfhn" />
      <bpmn:sequenceFlow id="Flow_085dglq" sourceRef="Activity_07wdfhn" targetRef="Activity_1j1706h" />
      <bpmn:serviceTask id="Activity_07wdfhn" name="Store Tweet">
        <bpmn:extensionElements>
          <zeebe:taskDefinition type="store-tweet" />
          <zeebe:ioMapping>
            <zeebe:input source="=lotteryTag" target="lotteryTag" />
            <zeebe:input source="=tweetId" target="tweet" />
          </zeebe:ioMapping>
        </bpmn:extensionElements>
        <bpmn:incoming>Flow_1poe8lo</bpmn:incoming>
        <bpmn:outgoing>Flow_085dglq</bpmn:outgoing>
      </bpmn:serviceTask>
    </bpmn:subProcess>
    <bpmn:sequenceFlow id="Flow_18nfvkw" sourceRef="tweetAboutLottery" targetRef="lotteryTimer" />
    <bpmn:intermediateCatchEvent id="lotteryTimer" name="Wait for lottery to finish">
      <bpmn:incoming>Flow_18nfvkw</bpmn:incoming>
      <bpmn:outgoing>Flow_16dl4m7</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_0zl0jtg">
        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT30S</bpmn:timeDuration>
      </bpmn:timerEventDefinition>
    </bpmn:intermediateCatchEvent>
    <bpmn:sequenceFlow id="Flow_16dl4m7" sourceRef="lotteryTimer" targetRef="determineWinner" />
    <bpmn:sequenceFlow id="Flow_0voof9p" sourceRef="determineWinner" targetRef="notifyWinner" />
    <bpmn:endEvent id="lotteryEnded" name="Lottery Ended">
      <bpmn:incoming>Flow_0dmwd0r</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0dmwd0r" sourceRef="notifyWinner" targetRef="lotteryEnded" />
    <bpmn:serviceTask id="tweetAboutLottery" name="Tweet about Lottery">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="send-tweet" />
        <zeebe:taskHeaders>
          <zeebe:header key="messageTemplate" value="Lottery has started! Use the {{lotteryTag}} to participate!" />
        </zeebe:taskHeaders>
        <zeebe:ioMapping>
          <zeebe:input source="=lotteryTag" target="lotteryTag" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1i2y26w</bpmn:incoming>
      <bpmn:outgoing>Flow_18nfvkw</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:serviceTask id="determineWinner" name="Determine winner">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="get-winner" />
        <zeebe:ioMapping>
          <zeebe:input source="=lotteryTag" target="lotteryTag" />
          <zeebe:output source="=winnerName" target="winnerName" />
          <zeebe:output source="=winnerTweetId" target="winnerTweetId" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_16dl4m7</bpmn:incoming>
      <bpmn:outgoing>Flow_0voof9p</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:serviceTask id="notifyWinner" name="Notify Winner">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="send-tweet" />
        <zeebe:ioMapping>
          <zeebe:input source="=winnerName" target="winnerName" />
          <zeebe:input source="=winnerTweetId" target="inReplyToStatusId" />
        </zeebe:ioMapping>
        <zeebe:taskHeaders>
          <zeebe:header key="messageTemplate" value="Congrats, you won @{{winnerName}}!!" />
        </zeebe:taskHeaders>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0voof9p</bpmn:incoming>
      <bpmn:outgoing>Flow_0dmwd0r</bpmn:outgoing>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmn:message id="Message_0nro6hj" name="tweetFound">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=lotteryTag" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="lotteryProcess">
      <bpmndi:BPMNEdge id="Flow_0dmwd0r_di" bpmnElement="Flow_0dmwd0r">
        <di:waypoint x="820" y="120" />
        <di:waypoint x="872" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0voof9p_di" bpmnElement="Flow_0voof9p">
        <di:waypoint x="660" y="120" />
        <di:waypoint x="720" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_16dl4m7_di" bpmnElement="Flow_16dl4m7">
        <di:waypoint x="498" y="120" />
        <di:waypoint x="560" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_18nfvkw_di" bpmnElement="Flow_18nfvkw">
        <di:waypoint x="410" y="120" />
        <di:waypoint x="462" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1i2y26w_di" bpmnElement="Flow_1i2y26w">
        <di:waypoint x="208" y="120" />
        <di:waypoint x="310" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartLottery">
        <dc:Bounds x="172" y="102" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="154" y="145" width="73" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1rcy59m_di" bpmnElement="Activity_0jwnffs" isExpanded="true">
        <dc:Bounds x="210" y="240" width="662" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1poe8lo_di" bpmnElement="Flow_1poe8lo">
        <di:waypoint x="278" y="340" />
        <di:waypoint x="390" y="340" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0rowbkz_di" bpmnElement="Flow_0rowbkz">
        <di:waypoint x="690" y="340" />
        <di:waypoint x="782" y="340" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_085dglq_di" bpmnElement="Flow_085dglq">
        <di:waypoint x="490" y="340" />
        <di:waypoint x="590" y="340" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0rxc9jo_di" bpmnElement="Event_0rxc9jo">
        <dc:Bounds x="242" y="322" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="223" y="365" width="74" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1bqntiv_di" bpmnElement="participant">
        <dc:Bounds x="782" y="322" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="787" y="365" width="27" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1j1706h_di" bpmnElement="Activity_1j1706h">
        <dc:Bounds x="590" y="300" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_08k0hr8_di" bpmnElement="Activity_07wdfhn">
        <dc:Bounds x="390" y="300" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1ywjnek_di" bpmnElement="lotteryTimer">
        <dc:Bounds x="462" y="102" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="439" y="145" width="83" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1yno3sj_di" bpmnElement="lotteryEnded">
        <dc:Bounds x="872" y="102" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="856" y="145" width="69" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1oh40v8_di" bpmnElement="tweetAboutLottery">
        <dc:Bounds x="310" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_14q6xbi_di" bpmnElement="determineWinner">
        <dc:Bounds x="560" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1yarmqc_di" bpmnElement="notifyWinner">
        <dc:Bounds x="720" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
"]
```

![lottery](https://user-images.githubusercontent.com/2758593/95757320-4adcfb00-0ca7-11eb-8074-64e493893c9f.png)

I can now try to reproduce this issue. I will deploy it with 0.24 and then migrate to 0.24.2, lets see what happens.

**Comment by Zelldon** [comment]
Was able to reproduce it with [docker compose](https://github.com/zeebe-io/zeebe-docker-compose/tree/master/simple-monitor).

I started the docker compose with:

```
version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.24.1
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../lib/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
      - /tmp/test:/usr/local/zeebe/data
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.19.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    # volumes:
    #   - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
```

Deployed the workflow above, created a new instance.

![publish](https://user-images.githubusercontent.com/2758593/95761384-84643500-0cac-11eb-90a8-63d0d2f9fdb3.png)

Publish a message and in the same moment try to force kill the docker image (twice CTRL+C), then change the version to `0.24.3` and restart the docker-compose.

When the message was received but not completely processed, especially the event sub process then we on reprocessing we can see the error in a endless loop.

```
 2020-10-12 14:57:28.675 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR io.zeebe.util.retry.EndlessRetryStrategy - Catched exception class java.lang.NullPointerException with message null, will retry...
zeebe_broker | java.lang.NullPointerException: null
zeebe_broker | 	at io.zeebe.engine.nwe.behavior.BpmnEventSubscriptionBehavior.triggerEventSubProcess(BpmnEventSubscriptionBehavior.java:390) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.event.StartEventProcessor.onEventOccurred(StartEventProcessor.java:85) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.event.StartEventProcessor.onEventOccurred(StartEventProcessor.java:20) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:139) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:122) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.workflow.BpmnStepHandlers.handle(BpmnStepHandlers.java:90) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecordValue(BpmnStepProcessor.java:82) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:62) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:287) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:262) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 2020-10-12 14:57:28.676 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR io.zeebe.util.retry.EndlessRetryStrategy - Catched exception class java.lang.NullPointerException with message null, will retry...
zeebe_broker | java.lang.NullPointerException: null
zeebe_broker | 	at io.zeebe.engine.nwe.behavior.BpmnEventSubscriptionBehavior.triggerEventSubProcess(BpmnEventSubscriptionBehavior.java:390) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.event.StartEventProcessor.onEventOccurred(StartEventProcessor.java:85) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.event.StartEventProcessor.onEventOccurred(StartEventProcessor.java:20) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:139) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.nwe.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:122) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.workflow.BpmnStepHandlers.handle(BpmnStepHandlers.java:90) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecordValue(BpmnStepProcessor.java:82) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.workflow.BpmnStepProcessor.processRecord(BpmnStepProcessor.java:62) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:287) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:262) ~[zeebe-workflow-engine-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.3.jar:0.24.3]
zeebe_broker | 	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.3.jar:0.24.3]
```

\cc @npepinpe @saig0

**Comment by saig0** [comment]
Nice job @Zelldon :+1:

**Comment by npepinpe** [comment]
Closed as we confirmed this was an upgrade issue (which is covered by other solutions, i.e. inconsistency detection).
