### ISSUE TITLE
Lower log level of connect exceptions in the gateway

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5397]
**Description**

Connection exceptions are bound to happen in a distributed system - reporting on them as errors every time they occur isn't particularly useful, and is more useful as debugging information to diagnose what is going on. At the moment, in the gateway, we will get the following log: "Expected to handle gRPC request, but an unexpected error occurred", with the stack trace:

```
io.netty.channel.ConnectTimeoutException: connection timed out: zeebe-2.zeebe-broker-service.2f0480c8-5d8a-4d3b-861b-178f6f7a36b3-zeebe.svc.cluster.local/10.4.11.168:26501
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:575) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

I would prefer to log these as a debugging information, as it's only useful to figure out what's going on if anything goes wrong - however a case can be made for WARN, as such errors may cause oddities to occur (even if they are recovered).

EDIT: This also occurs when the connection is refused (though it will be retried again - see https://console.cloud.google.com/errors/COLP4ZfE4drbdQ?service=zeebe&version=0.24.2&time=P1D&project=camunda-cloud-240911&organizationId=669107107215)

**Comment by sccalabr** [comment]
Id like to try working on this
