### ISSUE TITLE
NPE when claiming log entry after becoming follower

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#540]
#### Scenario

- running a 3 broker cluster
- sending create task requests using the NonBlockingTaskCreator

#### Problem

- NPE when trying to write in the client API message handler
- could be related to the fact that the broker lost leader ship for the raft group
- maybe a race condition with closing the log stream controller and the client API message handler

#### Log

```
14:37:11.956 [actor-runner-broker-2] DEBUG io.zeebe.raft - internal-system.0 - localhost:51017 - Transitioned to follower in term 2
java.lang.NullPointerException
	at io.zeebe.logstreams.log.LogStreamWriterImpl.claimLogEntry(LogStreamWriterImpl.java:243)
	at io.zeebe.logstreams.log.LogStreamWriterImpl.tryWrite(LogStreamWriterImpl.java:190)
	at io.zeebe.broker.transport.clientapi.ClientApiMessageHandler.handleExecuteCommandRequest(ClientApiMessageHandler.java:164)
	at io.zeebe.broker.transport.clientapi.ClientApiMessageHandler.onRequest(ClientApiMessageHandler.java:264)
	at io.zeebe.transport.impl.ServerReceiveHandler.onFragment(ServerReceiveHandler.java:75)
	at io.zeebe.transport.impl.TransportChannel.handleMessage(TransportChannel.java:152)
	at io.zeebe.transport.impl.TransportChannel.receive(TransportChannel.java:124)
	at io.zeebe.transport.impl.selector.ReadTransportPoller.pollNow(ReadTransportPoller.java:44)
	at io.zeebe.transport.impl.actor.Receiver.doWork(Receiver.java:43)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by meyerdan** [comment]
Closing for now. If we can still reproduce it we can reopen
