### ISSUE TITLE
Duplicate Workflows in Deployment create workflows with the same process id and version

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#546]
Deploying a duplicate workflows in one deployment will cause a problem since different workflows can be deploy with the same bpmn process id and version. See the following test case.

```java
@Test
    public void shouldCreateDeploymentWithMultipleResources()
    {
        // given
        final WorkflowDefinition definition1 = Bpmn.createExecutableWorkflow("process1").startEvent().done();
        final WorkflowDefinition definition2 = Bpmn.createExecutableWorkflow("process2").startEvent().done();
        final WorkflowDefinition definition3 = Bpmn.createExecutableWorkflow("process2").startEvent().serviceTask().taskType("j").taskHeader("k", "v").done().done();

        final List<Map<String, Object>> resources = Arrays.asList(deploymentResource(definition1, "process1.bpmn"),
                                                                  deploymentResource(definition2, "process2.bpmn"),
                                                                  deploymentResource(definition3, "process2.bpmn")
        );

        // when
        final ExecuteCommandResponse resp = apiRule.createCmdRequest()
                .partitionId(Protocol.SYSTEM_PARTITION)
                .eventType(EventType.DEPLOYMENT_EVENT)
                .command()
                    .put(PROP_STATE, "CREATE_DEPLOYMENT")
                    .put("topicName", ClientApiRule.DEFAULT_TOPIC_NAME)
                    .put("resources", resources)
                .done()
                .sendAndAwait();

        // then
        assertThat(resp.key()).isGreaterThanOrEqualTo(0L);
        assertThat(resp.getEvent()).containsEntry(PROP_STATE, "DEPLOYMENT_CREATED");

        final List<SubscribedEvent> workflowEvents = apiRule.topic().receiveEvents(workflowEvents("CREATED"))
                .limit(3)
                .collect(toList());

        assertThat(workflowEvents)
            .extracting(s -> s.event().get(PROP_WORKFLOW_BPMN_PROCESS_ID))
            .contains("process1", "process2", "process2");
    }


        assertThat(workflowEvents)
            .extracting(s -> s.event().get(PROP_WORKFLOW_VERSION))
            .contains(1, 1, 1);

```

One solution would be to increment the  version.

**Comment by Zelldon** [comment]
Why we removed this feature? Does this make sense?

**Comment by menski** [comment]
Let's talk about that in the team meeting tomorrow

**Comment by meyerdan** [comment]
current state:
* You can still deploy a collaboration and a workflow is created for each executable process in the collaboration
* You cannot deploy multiple bpmn files in the same deployment

Reason: code got very complex and we do not need that feature for now. User can do multiple deployments.

**Comment by Zelldon** [comment]
Updated test scenario:

```
  @Test
  public void shouldRejectDeploymentWithDuplicateResources() {
    // given
    final BpmnModelInstance definition1 =
        Bpmn.createExecutableProcess("process1").startEvent().done();
    final BpmnModelInstance definition2 =
        Bpmn.createExecutableProcess("process2").startEvent().done();
    final BpmnModelInstance definition3 =
        Bpmn.createExecutableProcess("process2")
            .startEvent()
            .serviceTask("task", (t) -> t.zeebeTaskType("j").zeebeTaskHeader("k", "v"))
            .done();

    // when
    ENGINE
        .deployment()
        .withXmlResource(definition1)
        .withXmlResource(definition2)
        .withXmlResource(definition3)
        .deploy();
}
```

Processing seems to fail:
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_222]
	at io.zeebe.engine.state.deployment.WorkflowPersistenceCache.updateInMemoryState(WorkflowPersistenceCache.java:159) ~[classes/:?]
	at io.zeebe.engine.state.deployment.WorkflowPersistenceCache.lookupPersistenceStateForWorkflowByKey(WorkflowPersistenceCache.java:275) ~[classes/:?]
	at io.zeebe.engine.state.deployment.WorkflowPersistenceCache.getWorkflowByKey(WorkflowPersistenceCache.java:266) ~[classes/:?]
	at io.zeebe.engine.state.deployment.WorkflowState.getWorkflowByKey(WorkflowState.java:63) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.deployment.TransformingDeploymentCreateProcessor.createTimerIfTimerStartEvent(TransformingDeploymentCreateProcessor.java:99) ~[classes/:?]
	at io.zeebe.engine.processor.workflow.deployment.TransformingDeploymentCreateProcessor.processRecord(TransformingDeploymentCreateProcessor.java:76) ~[classes/:?]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[classes/:?]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$processInTransaction$1(ProcessingStateMachine.java:258) ~[classes/:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:77) ~[classes/:?]
	at io.zeebe.engine.processor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:249) ~[classes/:?]
	at io.zeebe.engine.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:218) ~[classes/:?]
	at io.zeebe.engine.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:195) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:88) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:51) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:177) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:142) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:126) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:104) [classes/:?]
```

**Expected** deployment successful, with incremented version of the workflow OR we reject it with a corresponding error message.

**Comment by saig0** [comment]
I would expect that the deployment is rejected. It doesn't make sense to deploy processes with the same bpmn process id because only one of them can be executed. To reject the deployment save the user from wondering why the process is not executed :sweat_smile:

**Comment by Zelldon** [comment]
> t doesn't make sense to deploy processes with the same bpmn process id because only one of them can be executed.

You could choose the different version than :) But I'm also fine with rejecting it
