### ISSUE TITLE
Provide test rules for broker/client tests as artifact

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#551]
#### Problem

Currently all projects which want to use the EmbeddedBrokerRule or ClientRule have to copy paste it from another project.

#### Idea

- provide java library which contains useful test utilities to write java tests for Zeebe Broker/Client
- library should be usable by Zeebe itself and user projects

**Comment by jangalinski** [comment]
Well the test tool will have dependencies to zeebe broker and client I suppose, so it wont be possible to use it from within the broker and client modules ...

**Comment by menski** [comment]
Yeah I kind of expected that but at least wanted to give it a try. But if we have the code only in two place that would already be an improvement :slightly_smiling_face:

**Comment by jangalinski** [comment]
module in zeebe or extra repo in zeebe-io?

**Comment by menski** [comment]
not sure yet, any suggestions from a user perspective?

**Comment by jangalinski** [comment]
From a user perspective its just a dependency in test-scope ... so the developer preference is what counts.
I suppose we have a better chance of somehow reuse the rules in broker/client when we have them in the same repo (zeebe), but you also already have the fine-granular repo setup for all supporting libs instead of one big multi-module build, so I would think a repo is the cleaner choice.

**Comment by menski** [comment]
The zeebe repo already contains multiple projects so this would not be a problem. If I find some time this week I will give it a try.

**Comment by jangalinski** [comment]
I can also work on it ... I mean, basically it's just putting the template code in a module, right?

**Comment by menski** [comment]
If you have the time go for it :+1:

**Comment by jangalinski** [comment]
Assign it to me, please. Challenge accepted :-)

**Comment by jangalinski** [comment]
A new repo would allow separate release/versioning, otherwise this would have to be a 0.4.1 patch, right?

**Comment by menski** [comment]
As the test lib is probably tightly coupled to changes to the broker/client I think it's best to keep it in the zeebe repo for now. We can later still extract it if need to a separate repo. @jangalinski I invited you to join the collaborator team of Zeebe to assign you to the ticket.

**Comment by jangalinski** [comment]
I cannot build (mvn clean install) the zeebe repo currently. QA/integration fails. Is this a local issue or known?

**Comment by menski** [comment]
Currently we don't have problems on the Jenkins. So it should build. Could you provide a stacktrace and your environment?

**Comment by jangalinski** [comment]
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
```
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files\JetBrains\IntelliJ IDEA 2017.1.4\plugins\maven\lib\maven3
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\opt\jdk1.8.0_131\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

```

Stack:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.zeebe.broker.it.clustering.BrokerLeaderChangeTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.04 s - in io.zeebe.broker.it.clustering.BrokerLeaderChangeTest
[INFO] Running io.zeebe.broker.it.clustering.CreateTopicClusteredTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.613 s - in io.zeebe.broker.it.clustering.CreateTopicClusteredTest
[INFO] Running io.zeebe.broker.it.clustering.DeploymentClusteredTest
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 9.933 s <<< FAILURE! - in io.zeebe.broker.it.clustering.DeploymentClusteredTest
[ERROR] shouldDeployWorkflowAndCreateInstances(io.zeebe.broker.it.clustering.DeploymentClusteredTest)  Time elapsed: 9.867 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:87)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:65)
        at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
        at io.zeebe.broker.it.clustering.DeploymentClusteredTest.shouldDeployWorkflowAndCreateInstances(DeploymentClusteredTest.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)

[INFO] Running io.zeebe.broker.it.incident.IncidentTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.127 s - in io.zeebe.broker.it.incident.IncidentTest
[INFO] Running io.zeebe.broker.it.network.ClientReconnectTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.6 s - in io.zeebe.broker.it.network.ClientReconnectTest
[INFO] Running io.zeebe.broker.it.network.MultipleClientTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.743 s - in io.zeebe.broker.it.network.MultipleClientTest
[INFO] Running io.zeebe.broker.it.startup.BrokerRecoveryTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.168 s - in io.zeebe.broker.it.startup.BrokerRecoveryTest
[INFO] Running io.zeebe.broker.it.startup.BrokerRestartTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.57 s - in io.zeebe.broker.it.startup.BrokerRestartTest
[INFO] Running io.zeebe.broker.it.subscription.IncidentTopicSubscriptionTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.669 s - in io.zeebe.broker.it.subscription.IncidentTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.PersistentTopicSubscriptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.579 s - in io.zeebe.broker.it.subscription.PersistentTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.TaskTopicSubscriptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.551 s - in io.zeebe.broker.it.subscription.TaskTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.TopicSubscriptionRaftEventTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in io.zeebe.broker.it.subscription.TopicSubscriptionRaftEventTest
[INFO] Running io.zeebe.broker.it.subscription.TopicSubscriptionTest
[WARNING] Tests run: 17, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 31.071 s - in io.zeebe.broker.it.subscription.TopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.WorkflowInstanceTopicSubscriptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.036 s - in io.zeebe.broker.it.subscription.WorkflowInstanceTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.WorkflowTopicSubscriptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.07 s - in io.zeebe.broker.it.subscription.WorkflowTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.task.TaskQueueTest
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 8.09 s - in io.zeebe.broker.it.task.TaskQueueTest
[INFO] Running io.zeebe.broker.it.task.TaskSubscriptionTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.221 s - in io.zeebe.broker.it.task.TaskSubscriptionTest
[INFO] Running io.zeebe.broker.it.topic.CreateTopicTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.28 s - in io.zeebe.broker.it.topic.CreateTopicTest
[INFO] Running io.zeebe.broker.it.workflow.CancelWorkflowInstanceTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.704 s - in io.zeebe.broker.it.workflow.CancelWorkflowInstanceTest
[INFO] Running io.zeebe.broker.it.workflow.CreateDeploymentTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.17 s - in io.zeebe.broker.it.workflow.CreateDeploymentTest
[INFO] Running io.zeebe.broker.it.workflow.CreateWorkflowInstanceTest
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 13.421 s - in io.zeebe.broker.it.workflow.CreateWorkflowInstanceTest
[INFO] Running io.zeebe.broker.it.workflow.ExclusiveGatewayTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.597 s - in io.zeebe.broker.it.workflow.ExclusiveGatewayTest
[INFO] Running io.zeebe.broker.it.workflow.ServiceTaskTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.86 s - in io.zeebe.broker.it.workflow.ServiceTaskTest
[INFO] Running io.zeebe.broker.it.workflow.UpdatePayloadTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.375 s - in io.zeebe.broker.it.workflow.UpdatePayloadTest
[INFO] Running io.zeebe.broker.it.workflow.YamlWorkflowTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.202 s - in io.zeebe.broker.it.workflow.YamlWorkflowTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DeploymentClusteredTest.shouldDeployWorkflowAndCreateInstances:89 expected:<[tru]e> but was:<[fals]e>
[INFO]
[ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 10

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Zeebe Root ......................................... SUCCESS [  7.706 s]
[INFO] Zeebe Core Parent .................................. SUCCESS [  0.490 s]
[INFO] Zeebe Protocol Test Util ........................... SUCCESS [  8.387 s]
[INFO] Zeebe Broker Core .................................. SUCCESS [04:35 min]
[INFO] Zeebe Client Java .................................. SUCCESS [ 58.559 s]
[INFO] Zeebe QA ........................................... SUCCESS [  0.352 s]
[INFO] Zeebe QA Integration Tests ......................... FAILURE [04:54 min]
[INFO] Zeebe QA Performance Tests ......................... SKIPPED
[INFO] Zeebe Samples ...................................... SKIPPED
[INFO] Zeebe Distribution ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

**Comment by menski** [comment]
Okay we saw this test failing sometimes on Jenkins in the past, so I assume it is still an issue. For now you could ignore it locally if that helps you. I could try to look into the test later and she if I can reproduce it and find the root cause. Thanks for reporting :balloon:

**Comment by menski** [comment]
see new repo https://github.com/zeebe-io/zeebe-test
