### ISSUE TITLE
BufferOverflowException: null

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5517]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CK62_IPX_6nzIg?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by MiguelPires** [comment]
Observed something similar in 0.23.7:

Both errors occurred while truncating a follower's log after it step down from leader (because its log doesn't match the new leader's log). 

Broker 2 also fails to delete a pending snapshot because of `java.lang.NumberFormatException: For input string: "1602602977932.tmp"`. This doesn't seem related but probably shouldn't happen either.

Link: https://console.cloud.google.com/errors/CNmEsa_Y8rjxdw?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1
```
java.nio.BufferOverflowException: null
	at java.nio.HeapByteBuffer.put(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:?]
	at sun.nio.ch.FileChannelImpl.read(Unknown Source) ~[?:?]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext(FileChannelJournalSegmentReader.java:180) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.reset(FileChannelJournalSegmentReader.java:133) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.reset(FileChannelJournalSegmentReader.java:141) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.MappableJournalSegmentReader.reset(MappableJournalSegmentReader.java:123) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.SegmentedJournalReader.reset(SegmentedJournalReader.java:141) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.SegmentedJournal.resetTail(SegmentedJournal.java:607) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.SegmentedJournalWriter.lambda$truncate$0(SegmentedJournalWriter.java:125) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.prometheus.client.Histogram$Child.time(Histogram.java:204) ~[simpleclient-0.8.1.jar:?]
	at io.atomix.storage.statistics.JournalMetrics.observeSegmentTruncation(JournalMetrics.java:62) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.SegmentedJournalWriter.truncate(SegmentedJournalWriter.java:110) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.storage.journal.DelegatingJournalWriter.truncate(DelegatingJournalWriter.java:66) ~[atomix-storage-0.23.7.jar:0.23.7]
	at io.atomix.raft.roles.PassiveRole.replaceExistingEntry(PassiveRole.java:913) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:852) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:813) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:667) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:197) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$20(RaftContext.java:248) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$31(RaftContext.java:278) ~[atomix-cluster-0.23.7.jar:0.23.7]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.23.7.jar:0.23.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Logs: https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%2236b3e092-3bfa-4af2-a688-32e19d5dcfb4-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-25T16:49:41.187Z%2F2020-10-25T17:49:41.187Z;pinnedLogId=2020-10-25T17:19:11.187765Z%2Fr1eisunts6r355ghy?authuser=1&project=camunda-cloud-240911

**Comment by npepinpe** [comment]
Need to verify if the partition transitioned to inactive, or the exception was caught and the operation retried.

**Comment by saig0** [comment]
This happened again on `0.25.1`.
* [Error](https://console.cloud.google.com/errors/CPLdrZy8yrn5swE?service=zeebe&time=P7D&project=camunda-cloud-240911)
* [Logs](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2213f3c38b-6734-410c-8589-d5f0bdcc38c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-11-30T20:13:33.499Z%2F2020-11-30T21:13:33.499Z;pinnedLogId=2020-11-30T20:43:03.499046Z%2Fwww7jo976kzhy5mbk?project=camunda-cloud-240911)
* it seems that the error occurred while closing the stream processor: ![screenshot of the logs](https://user-images.githubusercontent.com/4305769/100698492-e41bba00-3398-11eb-8a01-c1106f8e098d.png)

**Comment by deepthidevaki** [comment]
It happens because of https://github.com/zeebe-io/zeebe/issues/4198. Our assumption was that on followers there are no concurrent readers, because we have no streamProcessor or exporters reading from it. But due to asynchronous role transitions, even though raft role has transitioned to follower, ZeebePartition has still leader services running. 

See following logs:
ZeebePartition is installing LeaderServices, while raft is already in FollowerRole (UncaughtException in follower role). After that ZeebePartition is still running leaderServices. Later it transition to follower and then after that to inactive.

```
D 2020-12-13T00:45:50.062329Z Partition role transitioning from null to LEADER 
D 2020-12-13T00:45:50.062959Z Partition 1 closed all previous open resources, before transitioning. 
E 2020-12-13T00:45:55.685040Z RaftServer{raft-partition-partition-1} - An uncaught exception occurrehttps://github.com/zeebe-io/zeebe/issues/4198d, transition to inactive role 
W 2020-12-13T00:45:55.700785Z Unexpected non-empty log failed to read the last block 
D 2020-12-13T00:45:55.706458Z The components are healthy. The current health status of components: {logstream-raft-partition-partition-1=HEALTHY} 
D 2020-12-13T00:45:57.001703Z Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/42943799-376-1607819856721-69595167-69594647, metadata=FileBasedSnapshotMetadata{index=42943799, term=376, timestamp=2020-12-13 12:37:36,721, processedPosition=69595167, exporterPosition=69594647}} 
D 2020-12-13T00:46:31.310333Z Opened database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'. 
D 2020-12-13T00:46:31.310927Z Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/42943799-376-1607819856721-69595167-69594647, metadata=FileBasedSnapshotMetadata{index=42943799, term=376, timestamp=2020-12-13 12:37:36,721, processedPosition=69595167, exporterPosition=69594647}}' 
D 2020-12-13T00:46:34.588128Z Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled 
D 2020-12-13T00:46:34.616885Z Recovering state of partition 1 from snapshot 
I 2020-12-13T00:46:34.878011Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@724ee06d)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1495d920, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@a2370cc, configuration: Configuration(false)] 
I 2020-12-13T00:46:37.930595Z Recovered state of partition 1 from snapshot at position 69595167 
I 2020-12-13T00:46:37.962744Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@53dabf8e)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@6d09028d, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@40cde85d, configuration: Configuration(false)] 
I 2020-12-13T00:46:37.988610Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1809ef93)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@905bd0e, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@8f9f09, configuration: Configuration(false)] 
D 2020-12-13T00:46:38.159036Z Partition 1 transition complete, installed 11 resources! 
D 2020-12-13T00:46:38.159135Z Recovering exporter from snapshot 
D 2020-12-13T00:46:38.175761Z Partition role transitioning from LEADER to FOLLOWER 
D 2020-12-13T00:46:38.185104Z Partition role transitioning from FOLLOWER to INACTIVE 

```

Hence eventhough in theory there shouldn't be any concurrent reads in follower, in practice due to asynchronous role transitions between raft and zeebe, there are concurrent readers when the log is truncated.
So we should either:
- Fix https://github.com/zeebe-io/zeebe/issues/4198
- Or Refactor role transitions. Raft should transition to follower only after zeebe has removed all leader services. We had also other non-critical errors due to asynchronous role transitions.

**Comment by npepinpe** [comment]
Current plan is to fix #4198 - please close this when that's done as well.

**Comment by npepinpe** [comment]
We fixed the above issue, we can close this now.
