### ISSUE TITLE
RequestRetriesExhaustedException: Expected to execute the command on one of the partitions, but all failed

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5539]
**Describe the bug**
Observed as error in the production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CL2RrKb-yLGuuAE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.gateway.impl.broker.RequestRetriesExhaustedException: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator
	at io.zeebe.gateway.impl.broker.RequestRetryHandler.sendRequestWithRetry(RequestRetryHandler.java:128) ~[zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.impl.broker.RequestRetryHandler.lambda$sendRequestWithRetry$1(RequestRetryHandler.java:115) ~[zeebe-gateway-0.24.3.jar:0.24.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:148) ~[zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:130) ~[zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.3.jar:0.24.3]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.3.jar:0.24.3]
	Suppressed: io.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (RESOURCE_EXHAUSTED): Reached maximum capacity of requests handled
		at io.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:148) ~[zeebe-gateway-0.24.3.jar:0.24.3]
		at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:130) ~[zeebe-gateway-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.3.jar:0.24.3]
		at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.3.jar:0.24.3]
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by pihme** [comment]
duplicate of #5186
