### ISSUE TITLE
Nullpointer on broker close in FsLogSegment

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#554]
In the end of any integration test the broker is closed and *sometimes* a NullPointerException is printed.

```java
java.lang.NullPointerException: null
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:135) ~[zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:254) ~[zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:239) ~[zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:222) ~[zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readMore(BufferedLogStreamReader.java:323) ~[zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:406) ~[zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:274) [zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:265) [zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111) [zb-util-0.5.0-20171120.094615-16.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) [zb-util-0.5.0-20171120.094615-16.jar:0.5.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:125) [zb-logstreams-0.5.0-20171120.095734-9.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165) [zb-util-0.5.0-20171120.094615-16.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:145) [zb-util-0.5.0-20171120.094615-16.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114) [zb-util-0.5.0-20171120.094615-16.jar:0.5.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71) [zb-util-0.5.0-20171120.094615-16.jar:0.5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by menski** [comment]
@Zelldon I think this is a duplicate of #398. What do you think?

**Comment by Zelldon** [comment]
Oh yeah I think you're right. I searched for NPE but found nothing :)

-> Closed duplicate
