### ISSUE TITLE
StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5544]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CPrSnu_tr4DxuQE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:397) ~[zeebe-gateway-0.23.6.jar:0.23.6]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$5(EndpointManager.java:331) ~[zeebe-gateway-0.23.6.jar:0.23.6]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:151) ~[zeebe-gateway-0.23.6.jar:0.23.6]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:191) ~[zeebe-gateway-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) [zeebe-util-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.6.jar:0.23.6]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.6.jar:0.23.6]
Caused by: io.zeebe.gateway.cmd.BrokerResponseException: java.util.concurrent.RejectedExecutionException: event executor terminated
	... 9 more
Caused by: java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.grpc.netty.WriteQueue.scheduleFlush(WriteQueue.java:67) ~[grpc-netty-1.28.1.jar:1.28.1]
	at io.grpc.netty.NettyServerStream$Sink.writeFrameInternal(NettyServerStream.java:150) ~[grpc-netty-1.28.1.jar:1.28.1]
	at io.grpc.netty.NettyServerStream$Sink.writeFrame(NettyServerStream.java:175) ~[grpc-netty-1.28.1.jar:1.28.1]
	at io.grpc.internal.AbstractServerStream.deliverFrame(AbstractServerStream.java:122) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.MessageFramer.commitToSink(MessageFramer.java:352) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.MessageFramer.close(MessageFramer.java:328) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.AbstractStream.endOfMessages(AbstractStream.java:72) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:131) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:218) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.28.1.jar:1.28.1]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:360) ~[grpc-stub-1.28.1.jar:1.28.1]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$5(EndpointManager.java:331) ~[zeebe-gateway-0.23.6.jar:0.23.6]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:148) ~[zeebe-gateway-0.23.6.jar:0.23.6]
	... 8 more
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.23.4, 0.23.6

**Comment by Zelldon** [comment]
Logs are no longer available. Last seen on 21 Oct 2020

**Comment by npepinpe** [comment]
Same as others, for now let's close it until we can inspect it again.
