### ISSUE TITLE
StatusRuntimeException: NOT_FOUND: Expected to execute command, but ...

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5545]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CK_KsKz0ipGPoAE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.grpc.StatusRuntimeException: NOT_FOUND: Expected to execute command, but this command refers to an element that doesn't exist.
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:397) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:311) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:148) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:174) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$4(BrokerRequestManager.java:162) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
Caused by: io.zeebe.gateway.cmd.PartitionNotFoundException: Expected to execute command, but this command refers to an element that doesn't exist.
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.determineBrokerNodeIdProvider(BrokerRequestManager.java:206) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:172) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	... 7 more
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.23.4

**Comment by pihme** [comment]
wrong log level

**Comment by npepinpe** [comment]
Closed by https://github.com/zeebe-io/zeebe/issues/4665
