### ISSUE TITLE
IllegalStateException: LeaderRole is closed and cannot be used as appender

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5546]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CLrc5aeIuMGltQE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
ava.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:682) ~[atomix-cluster-0.24.1.jar:0.24.1]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$10(LeaderRole.java:667) ~[atomix-cluster-0.24.1.jar:0.24.1]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.1.jar:0.24.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.23.4, 0.23.6, 0.24.2, 0.24.3

**Comment by Zelldon** [comment]
This can happen when the leader step down. This is not logged as error anymore with 0.25 see https://github.com/zeebe-io/zeebe/pull/5287

**Comment by npepinpe** [comment]
Closed as this is mostly noise and doesn't affect the latest versions anymore.
