### ISSUE TITLE
StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5548]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CJ_A97zNyaeZtgE?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CILJi8Tx8t2nkQE?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:397) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:311) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:148) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:194) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
Caused by: io.zeebe.gateway.cmd.ClientResponseException: java.lang.IllegalStateException: call already closed
	... 8 more
Caused by: java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-28.2-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.28.1.jar:1.28.1]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.28.1.jar:1.28.1]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.28.1.jar:1.28.1]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:360) ~[grpc-stub-1.28.1.jar:1.28.1]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:311) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:151) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:191) ~[zeebe-gateway-0.23.4.jar:0.23.4]
	... 7 more
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.23.4, 0.23.6

**Comment by Zelldon** [comment]
@npepinpe I assume this is now fixed or better handleded with the gw refactoring?

Btw I miss some labels here? Is the bot not working?

**Comment by npepinpe** [comment]
Yes, this should be fixed now. Please reopen if this happens again in 0.26+
