### ISSUE TITLE
Failing Test: BrokerLeaderChangeTest

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#558]
IDEA 2017.2, Java8, maven 3.3.9

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.zeebe.broker.it.clustering.BrokerLeaderChangeTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.027 s - in io.zeebe.broker.it.clustering.BrokerLeaderChangeTest
[INFO] Running io.zeebe.broker.it.clustering.CreateTopicClusteredTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 26.655 s <<< FAILURE! - in io.zeebe.broker.it.clustering.CreateTopicClusteredTest
[ERROR] shouldReplicateNewTopic(io.zeebe.broker.it.clustering.CreateTopicClusteredTest)  Time elapsed: 19.349 s  <<< FAILURE!
java.lang.AssertionError: Failed to wait for [localhost:51015, localhost:41015] become leader of partition 1
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:118)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:80)
	at io.zeebe.broker.it.clustering.TopologyObserver.waitForLeader(TopologyObserver.java:57)
	at io.zeebe.broker.it.clustering.CreateTopicClusteredTest.shouldReplicateNewTopic(CreateTopicClusteredTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

[INFO] Running io.zeebe.broker.it.clustering.DeploymentClusteredTest
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 11.056 s - in io.zeebe.broker.it.clustering.DeploymentClusteredTest
[INFO] Running io.zeebe.broker.it.incident.IncidentTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.115 s - in io.zeebe.broker.it.incident.IncidentTest
[INFO] Running io.zeebe.broker.it.network.ClientReconnectTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.511 s - in io.zeebe.broker.it.network.ClientReconnectTest
[INFO] Running io.zeebe.broker.it.network.MultipleClientTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.77 s - in io.zeebe.broker.it.network.MultipleClientTest
[INFO] Running io.zeebe.broker.it.startup.BrokerRecoveryTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.904 s - in io.zeebe.broker.it.startup.BrokerRecoveryTest
[INFO] Running io.zeebe.broker.it.startup.BrokerRestartTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 49.035 s - in io.zeebe.broker.it.startup.BrokerRestartTest
[INFO] Running io.zeebe.broker.it.subscription.IncidentTopicSubscriptionTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.613 s - in io.zeebe.broker.it.subscription.IncidentTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.PersistentTopicSubscriptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.731 s - in io.zeebe.broker.it.subscription.PersistentTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.TaskTopicSubscriptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.347 s - in io.zeebe.broker.it.subscription.TaskTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.TopicSubscriptionRaftEventTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 s - in io.zeebe.broker.it.subscription.TopicSubscriptionRaftEventTest
[INFO] Running io.zeebe.broker.it.subscription.TopicSubscriptionTest
[WARNING] Tests run: 17, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 33.75 s - in io.zeebe.broker.it.subscription.TopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.WorkflowInstanceTopicSubscriptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.256 s - in io.zeebe.broker.it.subscription.WorkflowInstanceTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.subscription.WorkflowTopicSubscriptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.107 s - in io.zeebe.broker.it.subscription.WorkflowTopicSubscriptionTest
[INFO] Running io.zeebe.broker.it.task.TaskQueueTest
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 8.154 s - in io.zeebe.broker.it.task.TaskQueueTest
[INFO] Running io.zeebe.broker.it.task.TaskSubscriptionTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.606 s - in io.zeebe.broker.it.task.TaskSubscriptionTest
[INFO] Running io.zeebe.broker.it.topic.CreateTopicTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.425 s - in io.zeebe.broker.it.topic.CreateTopicTest
[INFO] Running io.zeebe.broker.it.workflow.CancelWorkflowInstanceTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.632 s - in io.zeebe.broker.it.workflow.CancelWorkflowInstanceTest
[INFO] Running io.zeebe.broker.it.workflow.CreateDeploymentTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.849 s - in io.zeebe.broker.it.workflow.CreateDeploymentTest
[INFO] Running io.zeebe.broker.it.workflow.CreateWorkflowInstanceTest
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 13.651 s - in io.zeebe.broker.it.workflow.CreateWorkflowInstanceTest
[INFO] Running io.zeebe.broker.it.workflow.ExclusiveGatewayTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.001 s - in io.zeebe.broker.it.workflow.ExclusiveGatewayTest
[INFO] Running io.zeebe.broker.it.workflow.ServiceTaskTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.09 s - in io.zeebe.broker.it.workflow.ServiceTaskTest
[INFO] Running io.zeebe.broker.it.workflow.UpdatePayloadTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.698 s - in io.zeebe.broker.it.workflow.UpdatePayloadTest
[INFO] Running io.zeebe.broker.it.workflow.YamlWorkflowTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.491 s - in io.zeebe.broker.it.workflow.YamlWorkflowTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CreateTopicClusteredTest.shouldReplicateNewTopic:113 Failed to wait for [localhost:51015, localhost:41015] become leader of partition 1
[INFO] 
[ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 10
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeebe Root ......................................... SUCCESS [ 15.931 s]
[INFO] Zeebe Core Parent .................................. SUCCESS [  1.257 s]
[INFO] Zeebe Protocol Test Util ........................... SUCCESS [ 12.834 s]
[INFO] Zeebe Broker Core .................................. SUCCESS [05:07 min]
[INFO] Zeebe Client Java .................................. SUCCESS [01:00 min]
[INFO] Zeebe QA ........................................... SUCCESS [  0.493 s]
[INFO] Zeebe QA Integration Tests ......................... FAILURE [05:20 min]
```

**Comment by Zelldon** [comment]
should be more stable with #610
