### ISSUE TITLE
CreateTopicClusteredTest is unstable

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#561]
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.539 s <<< FAILURE! - in io.zeebe.broker.it.clustering.CreateTopicClusteredTest
[ERROR] shouldCreateTopic(io.zeebe.broker.it.clustering.CreateTopicClusteredTest)  Time elapsed: 7.535 s  <<< ERROR!
io.zeebe.client.cmd.ClientException: No response received (timeout 5 seconds). Request was: [ topic = internal-system, partition = 0, event type = TOPIC ]. Request receivers: [RemoteAddress{streamId=1, addr=localhost:51015}]
        at io.zeebe.client.cmd.ClientException.newInCurrentContext(ClientException.java:45)
        at io.zeebe.client.impl.RequestManager.waitAndResolve(RequestManager.java:150)
        at io.zeebe.client.impl.RequestManager.execute(RequestManager.java:109)
        at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:38)
        at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:25)
        at io.zeebe.broker.it.clustering.CreateTopicClusteredTest.shouldCreateTopic(CreateTopicClusteredTest.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.zeebe.client.cmd.ClientException: No response received (timeout 5 seconds). Request was: [ topic = internal-system, partition = 0, event type = TOPIC ]. Request receivers: [RemoteAddress{streamId=1, addr=localhost:51015}]
        at io.zeebe.client.impl.RequestController.generateTimeoutException(RequestController.java:179)
        at io.zeebe.client.impl.RequestController$ExecuteRequestState.doWork(RequestController.java:385)
        at io.zeebe.client.impl.RequestController$ExecuteRequestState.doWork(RequestController.java:350)
        at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111)
        at io.zeebe.client.impl.RequestController.doWork(RequestController.java:163)
        at io.zeebe.client.impl.RequestManager.doWork(RequestManager.java:81)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:165)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:138)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:114)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:71)
        ... 1 more
```

**Comment by Zelldon** [comment]
should be more stable with #610
