### ISSUE TITLE
Re-processing detects inconsistency due to Deployment rejection 

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5610]
**Describe the bug**

Looks related to https://github.com/zeebe-io/zeebe/issues/5568.
After roll out of 0.23.7 in camunda cloud a new error was reported today

Related error group

https://console.cloud.google.com/errors/CKi8ndiBx7_KJA?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

An E2E cluster is failing because of this.

**To Reproduce**
Need to be investigated.

**Expected behavior**
No issues.

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.engine.processor.InconsistentReprocessingException: Reprocessing issue detected! Restore the data from a backup and follow the recommended upgrade procedure. [cause: "The intent of the record on the log stream doesn't match to the record from reprocessing.", log-stream-record: {"partitionId":3,"value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPGJwbW46ZGVmaW5pdGlvbnMgeG1sbnM6YnBtbj0iaHR0cDovL3d3dy5vbWcub3JnL3NwZWMvQlBNTi8yMDEwMDUyNC9NT0RFTCIgeG1sbnM6YnBtbmRpPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L0RJIiB4bWxuczpkYz0iaHR0cDovL3d3dy5vbWcub3JnL3NwZWMvREQvMjAxMDA1MjQvREMiIHhtbG5zOnplZWJlPSJodHRwOi8vY2FtdW5kYS5vcmcvc2NoZW1hL3plZWJlLzEuMCIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iRGVmaW5pdGlvbnNfMG1iOWxhZiIgdGFyZ2V0TmFtZXNwYWNlPSJodHRwOi8vYnBtbi5pby9zY2hlbWEvYnBtbiIgZXhwb3J0ZXI9IlplZWJlIE1vZGVsZXIiIGV4cG9ydGVyVmVyc2lvbj0iMC42LjIiPgogIDxicG1uOnByb2Nlc3MgaWQ9ImUyZSIgbmFtZT0iZTJlIiBpc0V4ZWN1dGFibGU9InRydWUiPgogICAgPGJwbW46c3RhcnRFdmVudCBpZD0iU3RhcnRFdmVudF8xIj4KICAgICAgPGJwbW46b3V0Z29pbmc+U2VxdWVuY2VGbG93XzBkeTN2Z3Y8L2JwbW46b3V0Z29pbmc+CiAgICA8L2JwbW46c3RhcnRFdmVudD4KICAgIDxicG1uOmVuZEV2ZW50IGlkPSJFbmRFdmVudF8wYjhpamF5Ij4KICAgICAgPGJwbW46aW5jb21pbmc+U2VxdWVuY2VGbG93XzB2bG1oMWU8L2JwbW46aW5jb21pbmc+CiAgICA8L2JwbW46ZW5kRXZlbnQ+CiAgICA8YnBtbjpzZXJ2aWNlVGFzayBpZD0iU2VydmljZVRhc2tfMWNpcnF5cyIgbmFtZT0iY2FsbCB3b3JrZXIiPgogICAgICA8YnBtbjpleHRlbnNpb25FbGVtZW50cz4KICAgICAgICA8emVlYmU6dGFza0RlZmluaXRpb24gdHlwZT0iZTJlLXdvcmtlciIgcmV0cmllcz0iMSIgLz4KICAgICAgPC9icG1uOmV4dGVuc2lvbkVsZW1lbnRzPgogICAgICA8YnBtbjppbmNvbWluZz5TZXF1ZW5jZUZsb3dfMGR5M3ZndjwvYnBtbjppbmNvbWluZz4KICAgICAgPGJwbW46b3V0Z29pbmc+U2VxdWVuY2VGbG93XzB2bG1oMWU8L2JwbW46b3V0Z29pbmc+CiAgICA8L2JwbW46c2VydmljZVRhc2s+CiAgICA8YnBtbjpzZXF1ZW5jZUZsb3cgaWQ9IlNlcXVlbmNlRmxvd18wZHkzdmd2IiBzb3VyY2VSZWY9IlN0YXJ0RXZlbnRfMSIgdGFyZ2V0UmVmPSJTZXJ2aWNlVGFza18xY2lycXlzIiAvPgogICAgPGJwbW46c2VxdWVuY2VGbG93IGlkPSJTZXF1ZW5jZUZsb3dfMHZsbWgxZSIgc291cmNlUmVmPSJTZXJ2aWNlVGFza18xY2lycXlzIiB0YXJnZXRSZWY9IkVuZEV2ZW50XzBiOGlqYXkiIC8+CiAgPC9icG1uOnByb2Nlc3M+CiAgPGJwbW5kaTpCUE1ORGlhZ3JhbSBpZD0iQlBNTkRpYWdyYW1fMSI+CiAgICA8YnBtbmRpOkJQTU5QbGFuZSBpZD0iQlBNTlBsYW5lXzEiIGJwbW5FbGVtZW50PSJlMmUiPgogICAgICA8YnBtbmRpOkJQTU5TaGFwZSBpZD0iX0JQTU5TaGFwZV9TdGFydEV2ZW50XzIiIGJwbW5FbGVtZW50PSJTdGFydEV2ZW50XzEiPgogICAgICAgIDxkYzpCb3VuZHMgeD0iMTc5IiB5PSI4MCIgd2lkdGg9IjM2IiBoZWlnaHQ9IjM2IiAvPgogICAgICA8L2JwbW5kaTpCUE1OU2hhcGU+CiAgICAgIDxicG1uZGk6QlBNTlNoYXBlIGlkPSJFbmRFdmVudF8wYjhpamF5X2RpIiBicG1uRWxlbWVudD0iRW5kRXZlbnRfMGI4aWpheSI+CiAgICAgICAgPGRjOkJvdW5kcyB4PSI2MDUiIHk9IjgwIiB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIC8+CiAgICAgIDwvYnBtbmRpOkJQTU5TaGFwZT4KICAgICAgPGJwbW5kaTpCUE1OU2hhcGUgaWQ9IlNlcnZpY2VUYXNrXzFjaXJxeXNfZGkiIGJwbW5FbGVtZW50PSJTZXJ2aWNlVGFza18xY2lycXlzIj4KICAgICAgICA8ZGM6Qm91bmRzIHg9IjM1MyIgeT0iNTgiIHdpZHRoPSIxMDAiIGhlaWdodD0iODAiIC8+CiAgICAgIDwvYnBtbmRpOkJQTU5TaGFwZT4KICAgICAgPGJwbW5kaTpCUE1ORWRnZSBpZD0iU2VxdWVuY2VGbG93XzBkeTN2Z3ZfZGkiIGJwbW5FbGVtZW50PSJTZXF1ZW5jZUZsb3dfMGR5M3ZndiI+CiAgICAgICAgPGRpOndheXBvaW50IHg9IjIxNSIgeT0iOTgiIC8+CiAgICAgICAgPGRpOndheXBvaW50IHg9IjM1MyIgeT0iOTgiIC8+CiAgICAgIDwvYnBtbmRpOkJQTU5FZGdlPgogICAgICA8YnBtbmRpOkJQTU5FZGdlIGlkPSJTZXF1ZW5jZUZsb3dfMHZsbWgxZV9kaSIgYnBtbkVsZW1lbnQ9IlNlcXVlbmNlRmxvd18wdmxtaDFlIj4KICAgICAgICA8ZGk6d2F5cG9pbnQgeD0iNDUzIiB5PSI5OCIgLz4KICAgICAgICA8ZGk6d2F5cG9pbnQgeD0iNjA1IiB5PSI5OCIgLz4KICAgICAgPC9icG1uZGk6QlBNTkVkZ2U+CiAgICA8L2JwbW5kaTpCUE1OUGxhbmU+CiAgPC9icG1uZGk6QlBNTkRpYWdyYW0+CjwvYnBtbjpkZWZpbml0aW9ucz4K","resourceName":"e2e.bpmn","resourceType":"BPMN_XML"}],"deployedWorkflows":[{"version":1,"resourceName":"e2e.bpmn","bpmnProcessId":"e2e","workflowKey":2251799813685249}]},"sourceRecordPosition":390842023936,"position":390842026552,"key":2251799813693954,"intent":"CREATED","rejectionType":"NULL_VAL","rejectionReason":"","valueType":"DEPLOYMENT","timestamp":1602833936098,"recordType":"EVENT"}, reprocessing-record: {key=2251799813693954, sourceRecordPosition=390842023936, intent=DeploymentIntent:CREATE, recordType=COMMAND_REJECTION}]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$verifyRecordMatchesToReprocessing$12(ReProcessingStateMachine.java:407) ~[zeebe-workflow-engine-0.23.7.jar:0.23.7]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.zeebe.engine.processor.ReProcessingStateMachine.verifyRecordMatchesToReprocessing(ReProcessingStateMachine.java:394) ~[zeebe-workflow-engine-0.23.7.jar:0.23.7]
	at io.zeebe.engine.processor.ReProcessingStateMachine.reprocessEvent(ReProcessingStateMachine.java:258) ~[zeebe-workflow-engine-0.23.7.jar:0.23.7]
	at io.zeebe.engine.processor.ReProcessingStateMachine.reprocessNextEvent(ReProcessingStateMachine.java:226) ~[zeebe-workflow-engine-0.23.7.jar:0.23.7]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.7.jar:0.23.7]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.7.jar:0.23.7]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.7.jar:0.23.7]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.7.jar:0.23.7]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.7.jar:0.23.7]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.7.jar:0.23.7]
```

</p>
</details>

**Environment:**
 - OS: camunda cloud
 - Zeebe Version: [0.23.7] 
 - Configuration: -

**Comment by saig0** [comment]
This failure might be expected. We fixed some deployment issues in this version (#5253, #5248, #5247). If one of the deployment issues happened before then the deployment is rejected now. So, it is detected as inconsistent.

**Comment by Zelldon** [comment]
Thanks @saig0, so actually this also means you can't use this cluster anymore.

**Comment by saig0** [comment]
Well. In order to rescue the cluster :medical_symbol:, you can restore the last version and follow the new update procedure (i.e. creating a snapshot before the upgrade to avoid reprocessing).

**Comment by Zelldon** [comment]
@afirth are you are interested in rescuing your e2e cluster ? :laughing: :sweat_smile:

**Comment by afirth** [comment]
cc @urbanisierung @ztombol
me personally.... :fire:

**Comment by ztombol** [comment]
This is an old cluster still running 0.22.1. Let's upgrade if upgradable and see if it comes alive. If not, let's burn it.

**Comment by ztombol** [comment]
Just found out that this is not an upgradable generation. Let's burn it.

**Comment by npepinpe** [comment]
As we didn't follow the upgrade procedure described in the docs, this was an expected error and the inconsistency detection worked as expected, so nothing to fix.
