### ISSUE TITLE
Handle out of disc space while reprocessing

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#5676]
**Describe the bug**
When the broker becomes the leader of a partition then it will do reprocessing. If it runs out of disc space while reprocessing then it will retry all the time until more space is available.

It will log something like this:
```
Catched exception class io.zeebe.db.ZeebeDbException with message 
Unexpected error occurred during RocksDB transaction commit., will retry...
```

**To Reproduce**
This issue occurred in Camunda Cloud: https://console.cloud.google.com/errors/CPr0lsrgjvCYigE?service=zeebe&time=P7D&project=camunda-cloud-240911

This issue was logged over 7M times.

**Expected behavior**
The reprocessing is stopped until more space is available. 

**Log/Stacktrace**
From the Camunda cloud: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%224e6de936-a992-4f41-b171-2025b4f182e6-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-16T13:56:00.626Z%2F2020-10-16T15:56:00.626Z;pinnedLogId=2020-10-16T15:08:28.395469Z%2Fvg0mqv7m67z8rxiui?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.db.ZeebeDbException: Unexpected error occurred during RocksDB transaction commit.
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commit(ZeebeTransaction.java:96) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$updateStateUntilDone$6(ReProcessingStateMachine.java:324) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.4.jar:0.24.4]
Caused by: org.rocksdb.RocksDBException: While appending to file: /usr/local/zeebe/data/raft-partition/partitions/1/runtime/000552.log: No space left on device
	at org.rocksdb.Transaction.commit(Native Method) ~[rocksdbjni-6.8.1.jar:?]
	at org.rocksdb.Transaction.commit(Transaction.java:206) ~[rocksdbjni-6.8.1.jar:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal(ZeebeTransaction.java:117) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commit(ZeebeTransaction.java:92) ~[zeebe-db-0.24.4.jar:0.24.4]
	... 9 more
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `0.24.4`
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
I think the issue here is covered by https://github.com/zeebe-io/zeebe/issues/5470, which is to remove OOD errors from the error reporting tool, so I would close this for now.
