### ISSUE TITLE
StorageException$OutOfDiskSpace: Not enough space to allocate a new journal segment

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#5714]
**Describe the bug**
Append fails on Broker 1 because there's no space to allocate a segment. Before it there's a lot of logs on Broker 2 with `Skipping compaction of non-compactable index 105387017 (first log index: {})` which is probably related.

**To Reproduce**
Link: https://console.cloud.google.com/errors/CM7hiaX6yOm6_gE?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1

**Log/Stacktrace**
Logs: https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%226c7e13b4-733a-4010-b9ad-edf3e169df96-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-21T07:14:58.483Z%2F2020-10-21T08:14:58.483Z;pinnedLogId=2020-10-21T07:44:28.475491Z%2Frkfmmlbyeunlr703q?authuser=1&project=camunda-cloud-240911

```
io.atomix.storage.StorageException$OutOfDiskSpace: Not enough space to allocate a new journal segment
	at io.atomix.storage.journal.SegmentedJournal.assertDiskSpace(SegmentedJournal.java:297) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.SegmentedJournal.getNextSegment(SegmentedJournal.java:385) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.SegmentedJournalWriter.createNewSegment(SegmentedJournalWriter.java:142) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.prometheus.client.Histogram$Child.time(Histogram.java:204) ~[simpleclient-0.9.0.jar:?]
	at io.atomix.storage.statistics.JournalMetrics.observeSegmentCreation(JournalMetrics.java:54) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.SegmentedJournalWriter.append(SegmentedJournalWriter.java:61) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.DelegatingJournalWriter.append(DelegatingJournalWriter.java:46) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.LeaderRole.tryToAppend(LeaderRole.java:636) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.LeaderRole.append(LeaderRole.java:608) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:693) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$10(LeaderRole.java:667) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.24.2.jar:0.24.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.24.4
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Closing in favor of https://github.com/zeebe-io/zeebe/issues/5470
