### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#5764]
**Summary**

Many different tests fail once in a while because of `io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use`.

I know the issue is already discussed multiple times in individual flaky test issues, but I'd like to open this issue to find a solution to the bigger problem, rather than fix each individual flake.

**Failures**
<details><summary>Example stacktrace from `io.zeebe.broker.it.clustering.SnapshotReplicationTest.shouldReceiveNewSnapshotsOnRejoin`</summary>
<pre>
[ERROR] io.zeebe.broker.it.clustering.SnapshotReplicationTest.shouldReceiveNewSnapshotsOnRejoin  Time elapsed: 11.895 s  <<< ERROR!
 java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
 	at io.zeebe.broker.it.clustering.ClusteringRule.after(ClusteringRule.java:237)
 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)
 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 	at org.junit.runners.Suite.runChild(Suite.java:128)
 	at org.junit.runners.Suite.runChild(Suite.java:27)
 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
 Caused by: java.util.concurrent.CompletionException: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
 	at io.zeebe.broker.Broker.lambda$close$27(Broker.java:491)
 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21)
 	at io.zeebe.broker.Broker.close(Broker.java:486)
 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
 Caused by: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
 	at io.zeebe.broker.Broker.internalStart(Broker.java:186)
 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21)
 	at io.zeebe.broker.Broker.start(Broker.java:159)
 	at io.zeebe.broker.it.clustering.ClusteringRule.startBroker(ClusteringRule.java:475)
 	at io.zeebe.broker.it.clustering.ClusteringRule.restartBroker(ClusteringRule.java:471)
 	at io.zeebe.broker.it.clustering.SnapshotReplicationTest.shouldReceiveNewSnapshotsOnRejoin(SnapshotReplicationTest.java:84)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 	at org.junit.runners.Suite.runChild(Suite.java:128)
 	at org.junit.runners.Suite.runChild(Suite.java:27)
 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
 Caused by: java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:777)
 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
 	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$32(NettyMessagingService.java:618)
 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
 	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:998)
 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:552)
 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
</pre>
</details>

**Known tests that were flaky due to this**

Issues open at time of writing:
- #4940 ExporterManagerPartitionTest.shouldRunExporterForEveryPartition
- #4941 BrokerTest.shouldStartAndStopBroker
- #5182 WorkflowTest.shouldCompleteWorkflowInstance
- #5231 RaftRolesTest.testStepDownInRoleChangedListener
- #5471: SingleBrokerDataDeletionTest.shouldCompactWhenExporterHasBeenRemoved

Test flakes from just today:
- SnapshotReplicationTest.shouldReceiveNewSnapshotsOnRejoin
- GossipClusteringTest.shouldReAddToCluster
- BrokerLeaderChangeTest.shouldBecomeFollowerAfterRestartLeaderChange

**Comment by npepinpe** [comment]
I'd like to wait and see how this will look like as we add more agents - if, however, this is still blocking, then we should invest time to track down the last remaining collisions. Please let me know if you (here this is a generic you :sweat_smile:) are blocked by this.

**Comment by npepinpe** [comment]
Should have been fixed hopefully when we lowered the base port and tuned the agents/stages/fork counts.
