### ISSUE TITLE
Requests can time out on leader change

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#578]
Scenario: Send a request to a partition leader that is in the progress of becoming a follower. Closing the log stream and stream processors is propagated asynchronously, so it may happen that a client sends a request to the now follower (of which it believes is still the leader), the broker publishes the event on the log stream, but the event is never processed. This results in a request that is never responded to.

Side note: Note that a shared `LogStream` object is essentially shared mutable state with the known implications and solutions.

**Comment by ThorbenLindhauer** [comment]
Similar case:

`NullPointerException`s like the following. `ClientApiMessageHandler` tries to write to a log stream that is not valid for use anymore. It has not processed the async removal notification yet.

```
java.lang.NullPointerException
	at io.zeebe.logstreams.log.LogStreamWriterImpl.claimLogEntry(LogStreamWriterImpl.java:243)
	at io.zeebe.logstreams.log.LogStreamWriterImpl.tryWrite(LogStreamWriterImpl.java:190)
	at io.zeebe.broker.transport.clientapi.ClientApiMessageHandler.handleExecuteCommandRequest(ClientApiMessageHandler.java:167)
	at io.zeebe.broker.transport.clientapi.ClientApiMessageHandler.onRequest(ClientApiMessageHandler.java:270)
	at io.zeebe.transport.impl.ServerReceiveHandler.onFragment(ServerReceiveHandler.java:75)
	at io.zeebe.transport.impl.TransportChannel.handleMessage(TransportChannel.java:152)
	at io.zeebe.transport.impl.TransportChannel.receive(TransportChannel.java:124)
	at io.zeebe.transport.impl.selector.ReadTransportPoller.pollNow(ReadTransportPoller.java:44)
	at io.zeebe.transport.impl.actor.Receiver.doWork(Receiver.java:43)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:190)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:163)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:139)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:96)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ThorbenLindhauer** [comment]
Or the JVM can crash with `EXCEPTION_ACCESS_VIOLATION` for apparently the same reason.

**Comment by ThorbenLindhauer** [comment]
related: https://github.com/zeebe-io/zeebe/issues/540

**Comment by menski** [comment]
@ThorbenLindhauer I think this is kind of expected behavior. This can also happen when the request is send to the actual leader, but before the stream processors can process the event and send a response the leader becomes follower. Then the request will also never be answered. Not sure if we can do anything about it.

**Comment by ThorbenLindhauer** [comment]
We should probably avoid the NPE and the JVM crash at least.

**Comment by Zelldon** [comment]
@menski I think we can close this?
