### ISSUE TITLE
NullPointerException: log block index controller still running when log is closed

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#579]
Similar to #398, slightly different stack trace. I observed this in a test where a leader of a partition becomes a follower.

```
10:28:26.676 [localhost:31015] [actor-runner-broker-2] DEBUG io.zeebe.broker.system - Got request for partition 1
java.lang.NullPointerException
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:135)
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:254)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:239)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:1)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:190)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:163)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:139)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:96)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Also this error appears directly below:

```
10:28:26.703 [localhost:31015] [actor-runner-broker-2] ERROR io.zeebe.logstreams - Can't read from illegal address: 5504
```

**Comment by menski** [comment]
Hopefully fixed with the latest orchestration service dependency refactoring. Will close for now. If we see this again we can reopen this issue or create a new one.

**Comment by ThorbenLindhauer** [comment]
I saw it last week the last time.

**Comment by menski** [comment]
:cry: thanks for reporting. If you see it again please post a updated stack trace in case you catch it. Thanks

**Comment by Zelldon** [comment]
We removed the log block index with https://github.com/zeebe-io/zeebe/pull/2711
