### ISSUE TITLE
I can ran 1 million wf instances with 40 different task types

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#581]

**Comment by Zelldon** [comment]
Deploying the large WF seems to be a problem.

```java
o.zeebe.client.cmd.BrokerErrorException: Request exception (INVALID_MESSAGE): Cannot deserialize command: 'Could not deserialize object. Deserialization stuck at offset -10490; Could not read property 'resources'.; Could not read property 'resource'.; offset=12177 length=-22667 not valid for capacity=55140'.


	at io.zeebe.client.cmd.BrokerErrorException.newInCurrentContext(BrokerErrorException.java:55)
	at io.zeebe.client.impl.RequestManager.waitAndResolve(RequestManager.java:152)
	at io.zeebe.client.impl.RequestManager.execute(RequestManager.java:111)
	at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:38)
	at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:25)
	at io.zeebe.broker.it.workflow.LargeWorkflowTest.deployProcess(LargeWorkflowTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

On deserialization a negative length is read on MsgPackReader#116 . I think the problem is that the header Byte16 is set, since java only support signed types this means Short.Maxvalue is = 2^15. The process model size is 42k. I would assume that we get a overflow here. 

I checked the serialization part on the client with jackson. After serialization the content can be read again with jackson, perhaps they use some magic?
```
byte bytes[] = new byte[1024 * 1024];

serializedCommand.getBytes(serializedCommandOffset, bytes, 0, out.position - serializedCommandOffset);

new ObjectMapper(new MessagePackFactory()).readTree(bytes)
```

Next step is to write an test in the msg pack lib, which writes with jackson a huge msg pack and deserialize with our msg pack lib.

**Comment by Zelldon** [comment]
Was a problem in the MsgPackReader class, see #582 . This is fixed.

But now we have out of memory problems :-1: 
```java
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at io.zeebe.util.allocation.DirectBufferAllocator.allocate(DirectBufferAllocator.java:28)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.ensureRemainingBufferCapacity(BufferedLogStreamReader.java:352)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readMore(BufferedLogStreamReader.java:317)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:406)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:464)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:34)
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:278)
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:265)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:111)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:125)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:190)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:163)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:139)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:96)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zelldon** [comment]
Even without DI it is not possible to deploy and start a WF instance. It seems the WF definition is to large. If I deploy two of the extended WF definitions I get the same error.

**Comment by Zelldon** [comment]
Found the problem, see https://github.com/zeebe-io/zeebe/issues/584 . Now it is possible to deploy the processes and run the test. I run the test with 100_000 workflow instances with 40 tasks each, after completing 3_000_000 the broker stucks again. Wrote 13G log. I think this is the same problem like before on the other large wf test. @menski  maybe we execute the test on server 3?

**Comment by Zelldon** [comment]
Ok made it work with 100_000 workflow instances, which means completing 4_000_000 tasks with 40 subscriptions ! :tada: 

Test takes on my machine 53 mins and 57 secs :D

**Comment by menski** [comment]
Current observations imply that the server 3 is not setup in a way that it can finish this test as the disk space required is bigger then a single disk of the server. Therefore I will resetup the server to use LVM and have a single big partition to host the resulting log.

**Comment by menski** [comment]
The test finished on the server yesterday. What is missing is to commit the job using JobDSL to the repository.
