### ISSUE TITLE
Job worker name should be optional

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5819]
**Describe the bug**

Split away from https://github.com/zeebe-io/zeebe/issues/5812 - the job worker name is currently optional in the Java and Go clients as we provide a default client side, but there is no reason to enforce its presence on the broker as well, as its primarily used for debugging purposes. As we document it for clients as optional, we should also accept that it is absent on the broker side and simply log the client as anonymous.

**To Reproduce**

```
 await client
                        .NewActivateJobsCommand()
                        .JobType("benchmark-task")
                        .MaxJobsToActivate(100)
                        .Timeout(TimeSpan.FromMilliseconds(totalMilli))
                        .Send(TimeSpan.FromSeconds(30));
```

**Expected behavior**

I don't need to set a worker name.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.gateway.cmd.BrokerRejectionException: Command (ACTIVATE) rejected (INVALID_ARGUMENT): Expected to activate job batch with worker to be present, but it was blank
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:185) ~[zeebe-gateway-0.25.0.jar:0.25.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:137) ~[zeebe-gateway-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0.jar:0.25.0]
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.24.4
 - Configuration: prod s

**Comment by aivinog1** [comment]
@npepinpe Hi! I think I can take this. As I understand I should modify `io.zeebe.engine.processing.job.JobBatchActivateProcessor#isValid` to accept messages with an empty worker. Also, modify `io.zeebe.engine.processing.job.JobBatchActivateProcessor#rejectCommand` and `io.zeebe.engine.processing.job.JobBatchActivateProcessor#collectJobsToActivate`. And I should see that `io.zeebe.engine.processing.job.ActivateJobsTest#shouldRejectInvalidWorker` starts failing.

**Comment by npepinpe** [comment]
That should be about it. You might have to also check in `JobBatchRecord#getWorker`, which takes the underlying buffer and creates a string for it - I'm not sure how it handles it if you have an empty buffer. It might already work or not, I don't remember. Just check in general where that's used (if any), and where the `getWorkerBuffer` is used as well to be safe that all consumers can handle empty buffers.
