### ISSUE TITLE
Stream processor fails to deserialize message pack

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#596]
In the [long running test suite](https://github.com/zeebe-io/zeebe/tree/master/qa/long-running-tests) we repeatly see that a stream processor gets stuck while deserializing message pack values. This prevents the [test](https://hq2.camunda.com/jenkins/zeebe/job/zeebe-long-running-tests) to finish processing all workflow/tasks instances. 

Current observations indicate that this problem appears earlier if the test is run with more threads (11) and busy spin idle strategy. It is not clear if this is related or if the bug is just triggered earlier as there are more work ressources available.

Also it seems that the message pack itself is valid as it is possible to reprocess all events and read the produced log using a log reader.

Related to #447 and #448. Blocks #581.

See example stack trace below.

```
10:21:27 10:21:27.785 [0.0.0.0:51015] [actor-runner-broker-2] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems20' failed.
10:21:27 java.lang.RuntimeException: Could not deserialize object. Deserialization stuck at offset 322
10:21:27 	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:46) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:153) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onEvent(LockTaskStreamProcessor.java:247) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:317) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
10:21:27 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
10:21:27 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
10:21:27 Caused by: java.lang.RuntimeException: Not a string
10:21:27 	at io.zeebe.msgpack.spec.MsgPackReader.readStringLength(MsgPackReader.java:141) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.msgpack.value.StringValue.read(StringValue.java:149) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:115) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:42) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
10:21:27 	... 16 more
```

**Comment by menski** [comment]
I was able to catch this exception multiple times with a debugger. What I did to analyze the bug:

- Verify byter buffer content is correct:
  - saved the current byte buffer content to a file
  - load the buffer locally and deserialize it with `LoggedEventImpl` and `TaskEvent` with the offsets/length values which triggered the exception on the server
  - result: the logged event and task event where read correctly without any errors
- Retry deserialization in debugger:
  - when the [break point on the exception](https://github.com/zeebe-io/zb-msgpack-json-path/blob/a54986fafab588d4348d6d7bb16750c82bab08ac/msgpack-value/src/main/java/io/zeebe/msgpack/UnpackedObject.java#L46) was triggered I used the code execution of the IDE to re-execute the following lines:
  ```
  reader.wrap(buff, offset, length);
  read(reader);
  ```
  - result: the deserialization worked without any errors and the TaskEvent was initialized correctly

Other observations, if I add more break points on lines which throw exceptions inside the msgpack deserializations the deserialization lows immensely down and I wasn't able to trigger the bug as task completion was really slow and I didn't wanted to wait for a day.

**Comment by menski** [comment]
I disabled the rescheduling of the actors in the actor scheduler and run the LargeWorkflowTest again. The test run for 4 1/2 h, it finished 50% of the tasks and did not triggered any bug on the broker. This again may indicate that the bug is related to multi-threading and the initial scheduling of the threads did not create a situation in which the bug would have been triggered. As a next step I will reenable actor scheduling again and try to verify if a concurrent access to the buffered log stream reader exists or similiar issues.

**Comment by menski** [comment]
In this example the buffer changes everytime on 3 sequential deserizalizing attemps and ends up in a invalid view which is not aligned with any event at all. What is also interesting is that the size of the view changes, not sure how this is possible 🤔 

https://hq2.camunda.com/jenkins/zeebe/job/zeebe-long-running-tests/87/consoleText

```
16:21:34 16:21:34.724 [0.0.0.0:51015] [actor-runner-broker-4] ERROR io.zeebe.msgpack - Retry 1 could not deserialize object. Deserialization stuck at offset 305 of length 320 with last read byte 0x64.
16:21:34 Buffer on first invocation:
16:21:34 88 A5 73 74 61 74 65 A6 43 52 45 41 54 45 A8 6C 6F 63 6B 54 69 6D 65 D3 80 00 00 00 00 00 00 00 |..state.CREATE.lockTime.........|
16:21:34 A9 6C 6F 63 6B 4F 77 6E 65 72 A0 A7 72 65 74 72 69 65 73 03 A4 74 79 70 65 B2 72 65 73 65 72 76 |.lockOwner..retries..type.reserv|
16:21:34 65 4F 72 64 65 72 49 74 65 6D 73 31 A7 68 65 61 64 65 72 73 86 AD 62 70 6D 6E 50 72 6F 63 65 73 |eOrderItems1.headers..bpmnProces|
16:21:34 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 B9 77 6F 72 6B 66 6C 6F 77 |sId.forty-tasks-process.workflow|
16:21:34 44 65 66 69 6E 69 74 69 6F 6E 56 65 72 73 69 6F 6E 01 AB 77 6F 72 6B 66 6C 6F 77 4B 65 79 CF 00 |DefinitionVersion..workflowKey..|
16:21:34 00 00 01 00 02 9E E8 B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 02 |........workflowInstanceKey.....|
16:21:34 00 36 BC 90 AA 61 63 74 69 76 69 74 79 49 64 AF 70 72 6F 63 65 73 73 2D 70 61 79 6D 65 6E 74 B3 |.6...activityId.process-payment.|
16:21:34 61 63 74 69 76 69 74 79 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 D2 00 38 1E 38 AD 63 75 73 |activityInstanceKey......8.8.cus|
16:21:34 74 6F 6D 48 65 61 64 65 72 73 81 AF 72 65 73 65 72 76 61 74 69 6F 6E 54 69 6D 65 A5 50 54 31 35 |tomHeaders..reservationTime.PT15|
16:21:34 4D A7 70 61 79 6C 6F 61 64 C4 15 81 AA 6F 72 64 65 72 49 74 65 6D 73 93 CD 01 B3 CC B6 CD 01 78 |M.payload....orderItems........x|
16:21:34                                                                 
16:21:34 Buffer after last invocation:
16:21:34 88 A5 73 74 61 74 65 A6 4C 4F 43 4B 45 44 A8 6C 6F 63 6B 54 69 6D 65 CF 00 00 01 60 C6 EE 4A C0 |..state.LOCKED.lockTime....`..J.|
16:21:34 A9 6C 6F 63 6B 4F 77 6E 65 72 A4 74 65 73 74 A7 72 65 74 72 69 65 73 03 A4 74 79 70 65 B3 72 65 |.lockOwner.test.retries..type.re|
16:21:34 73 65 72 76 65 4F 72 64 65 72 49 74 65 6D 73 32 38 A7 68 65 61 64 65 72 73 86 AD 62 70 6D 6E 50 |serveOrderItems28.headers..bpmnP|
16:21:34 72 6F 63 65 73 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 B9 77 6F 72 |rocessId.forty-tasks-process.wor|
16:21:34 6B 66 6C 6F 77 44 65 66 69 6E 69 74 69 6F 6E 56 65 72 73 69 6F 6E 01 AB 77 6F 72 6B 66 6C 6F 77 |kflowDefinitionVersion..workflow|
16:21:34 4B 65 79 CF 00 00 00 01 00 02 9E E8 B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 65 4B 65 79 |Key..........workflowInstanceKey|
16:21:34 CF 00 00 00 01 00 10 27 B0 AA 61 63 74 69 76 69 74 79 49 64 B3 53 65 72 76 69 63 65 54 61 73 6B |.......'..activityId.ServiceTask|
16:21:34 5F 31 6A 63 70 66 6D 38 B3 61 63 74 69 76 69 74 79 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 |_1jcpfm8.activityInstanceKey....|
16:21:34 D1 00 48 0E B0 AD 63 75 73 74 6F 6D 48 65 61 64 65 72 73 81 AF 72 65 73 65 72 76 61 74 69 6F 6E |..H...customHeaders..reservation|
16:21:34 54 69 6D 65 A5 50 54 31 35 4D A7 70 61 79 6C 6F 61 64 C4 15 81 AA 6F 72 64 65 72 49 74 65 6D 73 |Time.PT15M.payload....orderItems|
16:21:34 93 CD 01 B3 CC B6 CD 01 78                                                                  |........x|
16:21:34 
16:21:34 java.lang.RuntimeException: Unable to determine map type, found unknown header byte 0xff at reader offset 0
16:21:34 	at io.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader(MsgPackReader.java:488) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.spec.MsgPackReader.readMapHeader(MsgPackReader.java:70) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:111) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:60) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:153) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onEvent(LockTaskStreamProcessor.java:247) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:321) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
16:21:34 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
16:21:34 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
16:21:34 16:21:34.738 [0.0.0.0:51015] [actor-runner-broker-4] ERROR io.zeebe.msgpack - Retry 2 could not deserialize object. Deserialization stuck at offset 270 of length 320 with last read byte 0x73.
16:21:34 Buffer on first invocation:
16:21:34 88 A5 73 74 61 74 65 A6 43 52 45 41 54 45 A8 6C 6F 63 6B 54 69 6D 65 D3 80 00 00 00 00 00 00 00 |..state.CREATE.lockTime.........|
16:21:34 A9 6C 6F 63 6B 4F 77 6E 65 72 A0 A7 72 65 74 72 69 65 73 03 A4 74 79 70 65 B2 72 65 73 65 72 76 |.lockOwner..retries..type.reserv|
16:21:34 65 4F 72 64 65 72 49 74 65 6D 73 31 A7 68 65 61 64 65 72 73 86 AD 62 70 6D 6E 50 72 6F 63 65 73 |eOrderItems1.headers..bpmnProces|
16:21:34 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 B9 77 6F 72 6B 66 6C 6F 77 |sId.forty-tasks-process.workflow|
16:21:34 44 65 66 69 6E 69 74 69 6F 6E 56 65 72 73 69 6F 6E 01 AB 77 6F 72 6B 66 6C 6F 77 4B 65 79 CF 00 |DefinitionVersion..workflowKey..|
16:21:34 00 00 01 00 02 9E E8 B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 02 |........workflowInstanceKey.....|
16:21:34 00 36 BC 90 AA 61 63 74 69 76 69 74 79 49 64 AF 70 72 6F 63 65 73 73 2D 70 61 79 6D 65 6E 74 B3 |.6...activityId.process-payment.|
16:21:34 61 63 74 69 76 69 74 79 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 D2 00 38 1E 38 AD 63 75 73 |activityInstanceKey......8.8.cus|
16:21:34 74 6F 6D 48 65 61 64 65 72 73 81 AF 72 65 73 65 72 76 61 74 69 6F 6E 54 69 6D 65 A5 50 54 31 35 |tomHeaders..reservationTime.PT15|
16:21:34 4D A7 70 61 79 6C 6F 61 64 C4 15 81 AA 6F 72 64 65 72 49 74 65 6D 73 93 CD 01 B3 CC B6 CD 01 78 |M.payload....orderItems........x|
16:21:34                                                                 
16:21:34 Buffer after last invocation:
16:21:34 88 A5 73 74 61 74 65 A7 43 52 45 41 54 45 44 A8 6C 6F 63 6B 54 69 6D 65 D3 80 00 00 00 00 00 00 |..state.CREATED.lockTime........|
16:21:34 00 A9 6C 6F 63 6B 4F 77 6E 65 72 A0 A7 72 65 74 72 69 65 73 03 A4 74 79 70 65 B2 72 65 73 65 72 |..lockOwner..retries..type.reser|
16:21:34 76 65 4F 72 64 65 72 49 74 65 6D 73 30 A7 68 65 61 64 65 72 73 86 AD 62 70 6D 6E 50 72 6F 63 65 |veOrderItems0.headers..bpmnProce|
16:21:34 73 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 B9 77 6F 72 6B 66 6C 6F |ssId.forty-tasks-process.workflo|
16:21:34 77 44 65 66 69 6E 69 74 69 6F 6E 56 65 72 73 69 6F 6E 01 AB 77 6F 72 6B 66 6C 6F 77 4B 65 79 CF |wDefinitionVersion..workflowKey.|
16:21:34 00 00 00 01 00 02 9E E8 B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 |.........workflowInstanceKey....|
16:21:34 D2 00 20 6C A8 AA 61 63 74 69 76 69 74 79 49 64 B3 72 65 73 65 72 76 65 2D 6F 72 64 65 72 2D 69 |.. l..activityId.reserve-order-i|
16:21:34 74 65 6D 73 B3 61 63 74 69 76 69 74 79 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 D2 00 3A 1D |tems.activityInstanceKey......:.|
16:21:34 C8 AD 63 75 73 74 6F 6D 48 65 61 64 65 72 73 81 AF 72 65 73 65 72 76 61 74 69 6F 6E 54 69 6D 65 |..customHeaders..reservationTime|
16:21:34 A5 50 54 31 35 4D A7 70 61 79 6C 6F 61 64 C4 15 81 AA 6F 72 64 65 72 49 74 65 6D 73 93 CD 01 B3 |.PT15M.payload....orderItems....|
16:21:34 CC B6 CD 01 78                                                                  |....x|
16:21:34 
16:21:34 java.lang.RuntimeException: Unable to determine map type, found unknown header byte 0xff at reader offset 57
16:21:34 	at io.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader(MsgPackReader.java:488) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.spec.MsgPackReader.readMapHeader(MsgPackReader.java:70) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:111) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:60) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:153) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onEvent(LockTaskStreamProcessor.java:247) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:321) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
16:21:34 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
16:21:34 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
16:21:34 16:21:34.739 [0.0.0.0:51015] [actor-runner-broker-4] ERROR io.zeebe.msgpack - Retry 3 could not deserialize object. Deserialization stuck at offset 1 of length 320 with last read byte 0xff.
16:21:34 Buffer on first invocation:
16:21:34 88 A5 73 74 61 74 65 A6 43 52 45 41 54 45 A8 6C 6F 63 6B 54 69 6D 65 D3 80 00 00 00 00 00 00 00 |..state.CREATE.lockTime.........|
16:21:34 A9 6C 6F 63 6B 4F 77 6E 65 72 A0 A7 72 65 74 72 69 65 73 03 A4 74 79 70 65 B2 72 65 73 65 72 76 |.lockOwner..retries..type.reserv|
16:21:34 65 4F 72 64 65 72 49 74 65 6D 73 31 A7 68 65 61 64 65 72 73 86 AD 62 70 6D 6E 50 72 6F 63 65 73 |eOrderItems1.headers..bpmnProces|
16:21:34 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 B9 77 6F 72 6B 66 6C 6F 77 |sId.forty-tasks-process.workflow|
16:21:34 44 65 66 69 6E 69 74 69 6F 6E 56 65 72 73 69 6F 6E 01 AB 77 6F 72 6B 66 6C 6F 77 4B 65 79 CF 00 |DefinitionVersion..workflowKey..|
16:21:34 00 00 01 00 02 9E E8 B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 02 |........workflowInstanceKey.....|
16:21:34 00 36 BC 90 AA 61 63 74 69 76 69 74 79 49 64 AF 70 72 6F 63 65 73 73 2D 70 61 79 6D 65 6E 74 B3 |.6...activityId.process-payment.|
16:21:34 61 63 74 69 76 69 74 79 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 00 D2 00 38 1E 38 AD 63 75 73 |activityInstanceKey......8.8.cus|
16:21:34 74 6F 6D 48 65 61 64 65 72 73 81 AF 72 65 73 65 72 76 61 74 69 6F 6E 54 69 6D 65 A5 50 54 31 35 |tomHeaders..reservationTime.PT15|
16:21:34 4D A7 70 61 79 6C 6F 61 64 C4 15 81 AA 6F 72 64 65 72 49 74 65 6D 73 93 CD 01 B3 CC B6 CD 01 78 |M.payload....orderItems........x|
16:21:34                                                                 
16:21:34 Buffer after last invocation:
16:21:34 FF FF FF FF FF A8 C4 46 00 D2 00 00 00 27 00 00 00 1F 00 C8 00 00 00 01 00 01 00 00 00 AC 9E 06 |.......F.....'..................|
16:21:34 00 00 00 00 00 FF FF FF FF FF FF FF FF 01 00 05 FF FF FF FF FF FF FF FF 86 A5 73 74 61 74 65 B8 |..........................state.|
16:21:34 43 52 45 41 54 45 5F 57 4F 52 4B 46 4C 4F 57 5F 49 4E 53 54 41 4E 43 45 AD 62 70 6D 6E 50 72 6F |CREATE_WORKFLOW_INSTANCE.bpmnPro|
16:21:34 63 65 73 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 A7 76 65 72 73 69 |cessId.forty-tasks-process.versi|
16:21:34 6F 6E FF AB 77 6F 72 6B 66 6C 6F 77 4B 65 79 FF B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 |on..workflowKey..workflowInstanc|
16:21:34 65 4B 65 79 FF A7 70 61 79 6C 6F 61 64 C4 30 83 A7 6F 72 64 65 72 49 64 CD 7A 0B AB 6F 72 64 65 |eKey..payload.0..orderId.z..orde|
16:21:34 72 53 74 61 74 75 73 A3 4E 45 57 AA 6F 72 64 65 72 49 74 65 6D 73 93 CD 01 B3 CC B6 CD 01 78 00 |rStatus.NEW.orderItems........x.|
16:21:34 00 06 01 00 00 00 00 00 00 01 00 00 00 00 00 00 00 B0 C5 46 00 D2 00 00 00 01 00 00 00 FF FF FF |...................F............|
16:21:34 FF FF FF FF FF FF FF FF FF FF FF FF FF B0 C5 46 00 D2 00 00 00 27 00 00 00 1F 00 C8 00 00 00 01 |...............F.....'..........|
16:21:34 00 01 00 00 00 DB A2 06 00 00 00 00 00 FF FF FF FF FF FF FF FF 01 00 05 FF FF FF FF FF FF FF FF |................................|
16:21:34                                                                 
16:21:34 java.lang.RuntimeException: Unable to determine map type, found unknown header byte 0xff at reader offset 1
16:21:34 	at io.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader(MsgPackReader.java:488) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.spec.MsgPackReader.readMapHeader(MsgPackReader.java:70) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:111) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:60) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:153) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onEvent(LockTaskStreamProcessor.java:247) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:321) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:21:34 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
16:21:34 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
16:21:34 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by menski** [comment]
This was apperently fixed with https://github.com/zeebe-io/zb-util/commit/f399bd0a2718bbeb9da6fc86ed44f6bef743a5dd
