### ISSUE TITLE
FsLogSegment fails to read from disk with bad address

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#597]
During the long running test suite the following error occurred which broke the log block index.

```
java.lang.IndexOutOfBoundsException: index=-1140846464 length=4 capacity=65536
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1285)
	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:491)
	at io.zeebe.logstreams.impl.LogEntryDescriptor.getFragmentLength(LogEntryDescriptor.java:124)
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.calculateCorrectReadResult(CompleteEventsInBlockProcessor.java:79)
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.process(CompleteEventsInBlockProcessor.java:51)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:248)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
io.zeebe.util.state.NoSuchTransitionException: Cannot take transition 0 when in state io.zeebe.logstreams.impl.LogBlockIndexController$OpenState@7e9f44bd
	at io.zeebe.util.state.StateMachine.take(StateMachine.java:57)
	at io.zeebe.util.state.SimpleStateMachineContext.take(SimpleStateMachineContext.java:29)
	at io.zeebe.logstreams.impl.LogBlockIndexController$BlockIndexCreationState.createBlockIdx(LogBlockIndexController.java:472)
	at io.zeebe.logstreams.impl.LogBlockIndexController$BlockIndexCreationState.doWork(LogBlockIndexController.java:446)
	at io.zeebe.logstreams.impl.LogBlockIndexController$BlockIndexCreationState.doWork(LogBlockIndexController.java:438)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: java.io.IOException: Bad address
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:276)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:243)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Bad address
	at sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727)
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:272)
	... 15 more
java.lang.IllegalArgumentException: Illegal value for position.Value=1365799801336, last value in index=7018130661608484197. Must provide positions in ascending order.
	at io.zeebe.logstreams.impl.log.index.LogBlockIndex.addBlock(LogBlockIndex.java:186)
	at io.zeebe.logstreams.impl.LogBlockIndexController$BlockIndexCreationState.createBlockIdx(LogBlockIndexController.java:462)
	at io.zeebe.logstreams.impl.LogBlockIndexController$BlockIndexCreationState.doWork(LogBlockIndexController.java:446)
	at io.zeebe.logstreams.impl.LogBlockIndexController$BlockIndexCreationState.doWork(LogBlockIndexController.java:438)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:226)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727)
	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:272)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:243)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
Let's hope this is fixed with https://github.com/zeebe-io/zb-util/commit/f399bd0a2718bbeb9da6fc86ed44f6bef743a5dd
