### ISSUE TITLE
On FsLogSegment readBytes a invalid new position is passed

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#598]
During the long running test suite a invalid new position was passed to `Buffer#position`.

```
public final Buffer position(int newPosition) {
    if ((newPosition > limit) || (newPosition < 0))
        throw new IllegalArgumentException();
    position = newPosition;
    if (mark > position) mark = -1;
    return this;
}
```

```
13:46:00 13:46:00.755 [0.0.0.0:51015] [actor-runner-broker-8] ERROR io.zeebe.logstreams - The log stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems23' failed to process event. It stop processing further events.
13:46:00 java.lang.IllegalArgumentException: null
13:46:00 	at java.nio.Buffer.position(Buffer.java:244) ~[?:1.8.0_152]
13:46:00 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:226) ~[?:1.8.0_152]
13:46:00 	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_152]
13:46:00 	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741) ~[?:1.8.0_152]
13:46:00 	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727) ~[?:1.8.0_152]
13:46:00 	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:272) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:243) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:320) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:381) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:214) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:275) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
13:46:00 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
13:46:00 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
13:46:00 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
13:46:00 io.zeebe.util.state.NoSuchTransitionException: Cannot take transition 0 when in state io.zeebe.logstreams.processor.StreamProcessorController$FailedState@44ebd4c9
13:46:00 	at io.zeebe.util.state.StateMachine.take(StateMachine.java:57)
13:46:00 	at io.zeebe.util.state.SimpleStateMachineContext.take(SimpleStateMachineContext.java:29)
13:46:00 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:326)
13:46:00 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63)
13:46:00 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
13:46:00 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
13:46:00 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128)
13:46:00 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
13:46:00 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
13:46:00 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
13:46:00 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
13:46:00 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
13:46:00 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
13:46:00 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:46:00 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:46:00 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
I was able to catch this once with a debugger. The following situation existed:

- the [`readResult` in `FsLogStorage#read`](https://github.com/zeebe-io/zb-logstreams/blob/8416af8ba59a76b7570b2967e0ccea6609263668/src/main/java/io/zeebe/logstreams/impl/log/fs/FsLogStorage.java#L243) was 4194304
- the `readBuffer` had the following properties set after the read `java.nio.DirectByteBuffer[pos=2519240 lim=2519240 cap=4194304]`
- the [`CompleteEventsInBlockProcessor`](https://github.com/zeebe-io/zb-logstreams/blob/master/src/main/java/io/zeebe/logstreams/impl/CompleteEventsInBlockProcessor.java#L55) tried to set the position to `startPosition + readResult`, i.e. `0 + 4194304 = 4194304 ` which exceeds the limit at this moment as the limit is set [after the position to the same value](https://github.com/zeebe-io/zb-logstreams/blob/master/src/main/java/io/zeebe/logstreams/impl/CompleteEventsInBlockProcessor.java#L56)

**Comment by menski** [comment]
In another instance the invalid position is passed by Java NIO code. In this case the call of [`fileChannel.read`](https://github.com/zeebe-io/zb-logstreams/blob/8416af8ba59a76b7570b2967e0ccea6609263668/src/main/java/io/zeebe/logstreams/impl/log/fs/FsLogSegment.java#L272) tries to set the position to 131072 on a buffer with the properties `java.nio.DirectByteBuffer[pos=130664 lim=130664 cap=131072]`

As I'm not able to find the source code of `sun.nio.ch.IOUtil#readIntoNativeBuffer` I can only debug using the decompiled code:

```
  private static int readIntoNativeBuffer(FileDescriptor var0, ByteBuffer var1, long var2, NativeDispatcher var4) throws IOException {
    int var5 = var1.position();
    int var6 = var1.limit();

    assert var5 <= var6;

    int var7 = var5 <= var6 ? var6 - var5 : 0;
    if (var7 == 0) {
      return 0;
    } else {
      boolean var8 = false;
      int var9;
      if (var2 != -1L) {
        var9 = var4.pread(var0, ((DirectBuffer)var1).address() + (long)var5, var7, var2);
      } else {
        var9 = var4.read(var0, ((DirectBuffer)var1).address() + (long)var5, var7);
      }

      if (var9 > 0) {
        var1.position(var5 + var9);
      }

      return var9;
    }
  }
```

In the debugger it seems that the variable `var6 = var1.limit()` is 131072 before the read operation (probably `var4.pread` is called). At the moment when the position is set `var1.limit()` returns 130664. Where I'm not sure when this value should change in the above code. 🤔

**Comment by menski** [comment]
I assume that the values in the debugger for the decompiled NIO code are not correct as in another instance the IllegalArgumentException is throw although the debugger shows that the `newPosition` is equal to the `limit`. Which should be valid and not trigger the exeception.

**Comment by menski** [comment]
For reference the source of the Java NIO classes in question for the openjdk version used on the server can be found here:
- http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/31bc1a681b51/src/share/classes/sun/nio/ch/FileChannelImpl.java
- http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/31bc1a681b51/src/share/classes/sun/nio/ch/IOUtil.java
- http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/31bc1a681b51/src/solaris/classes/sun/nio/ch/FileDispatcherImpl.java
- http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/31bc1a681b51/src/solaris/native/sun/nio/ch/FileDispatcherImpl.c

Full src tree: http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/archive/31bc1a681b51.tar.bz2

**Comment by menski** [comment]
Regarding the observed behavior descirbed in comment https://github.com/zeebe-io/zeebe/issues/598#issuecomment-354775030, I think this is again an invalid read of an offset or similiar. In general `readResult` cannot exceed `readBuffer.limit()` as it is used as limit of the read operation so `readResult <= readBuffer.limit()` should always be true.

**Comment by menski** [comment]
Let's hope this is fixed with https://github.com/zeebe-io/zb-util/commit/f399bd0a2718bbeb9da6fc86ed44f6bef743a5dd
