### ISSUE TITLE
BufferedLogStreamReader passes invalid value as limit for buffer

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#599]
During the long running test suite a invalid new position was passed to `Buffer#limit`.

```
14:29:24 14:29:24.368 [0.0.0.0:51015] [actor-runner-broker-2] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems22' failed.
14:29:24 java.lang.IllegalArgumentException: null
14:29:24 	at java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_152]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.allocateBuffer(BufferedLogStreamReader.java:256) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:325) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:381) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextEvent(BufferedLogStreamReader.java:405) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:385) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:214) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:275) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
14:29:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
14:29:24 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
14:29:24 14:29:24.370 [0.0.0.0:51015] [actor-runner-broker-8] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems22' failed.
14:29:24 java.lang.IllegalArgumentException: null
14:29:24 	at java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_152]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.allocateBuffer(BufferedLogStreamReader.java:256) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:325) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:381) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextEvent(BufferedLogStreamReader.java:405) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:385) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextEvent(BufferedLogStreamReader.java:405) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:385) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:214) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:275) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
14:29:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
14:29:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
14:29:24 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
14:29:24 io.zeebe.util.state.NoSuchTransitionException: Cannot take transition 3 when in state io.zeebe.logstreams.processor.StreamProcessorController$FailedState@38cc9daf
14:29:24 	at io.zeebe.util.state.StateMachine.take(StateMachine.java:57)
14:29:24 	at io.zeebe.util.state.SimpleStateMachineContext.take(SimpleStateMachineContext.java:29)
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController.lambda$new$3(StreamProcessorController.java:239)
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.onFailure(StreamProcessorController.java:294)
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.onFailure(StreamProcessorController.java:266)
14:29:24 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:128)
14:29:24 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
14:29:24 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128)
14:29:24 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
14:29:24 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
14:29:24 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
14:29:24 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
14:29:24 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
14:29:24 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
14:29:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:29:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:29:24 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
Again I think this is related to an invalid offset read or similiar which triggered and negative integer overflow which lead to an invalid limit value. I assume this is now prevented with the following two commits:
- https://github.com/zeebe-io/zb-logstreams/commit/d728bf87f8295bc7fc16f0a9a8ab913ff3466479
- https://github.com/zeebe-io/zb-logstreams/commit/6afbd9f6950c274cf717129401c0d4f515d3ae4f
