### ISSUE TITLE
IndexOutOfBoundsException while reading fragment length

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#600]
During the long running test suite a invalid `LogEntryDescriptor.getFragmentLength` was called with an negative offset?

```
15:01:49 15:01:49.377 [0.0.0.0:51015] [actor-runner-broker-3] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems3' failed.
15:01:49 java.lang.IndexOutOfBoundsException: index=-845922536 length=4 capacity=131072
15:01:49 	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1285) ~[agrona-0.9.6.jar:?]
15:01:49 	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:491) ~[agrona-0.9.6.jar:?]
15:01:49 	at io.zeebe.logstreams.impl.LogEntryDescriptor.getFragmentLength(LogEntryDescriptor.java:124) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.calculateCorrectReadResult(CompleteEventsInBlockProcessor.java:79) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.process(CompleteEventsInBlockProcessor.java:51) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:248) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:320) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:381) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextEvent(BufferedLogStreamReader.java:405) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:235) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:33) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:279) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
15:01:49 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
15:01:49 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
15:01:49 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
15:01:49 io.zeebe.util.state.NoSuchTransitionException: Cannot take transition 0 when in state io.zeebe.logstreams.processor.StreamProcessorController$FailedState@e317db2
15:01:49 	at io.zeebe.util.state.StateMachine.take(StateMachine.java:57)
15:01:49 	at io.zeebe.util.state.SimpleStateMachineContext.take(SimpleStateMachineContext.java:29)
15:01:49 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:326)
15:01:49 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63)
15:01:49 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
15:01:49 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
15:01:49 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128)
15:01:49 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
15:01:49 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
15:01:49 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
15:01:49 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
15:01:49 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
15:01:49 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
15:01:49 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:01:49 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:01:49 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
Another stack trace:

```
17:03:02.290 [0.0.0.0:51015] [actor-runner-broker-11] INFO  io.zeebe.broker.clustering - Write Gossip snapshot.
17:03:10.701 [0.0.0.0:51015] [actor-runner-broker-3] ERROR io.zeebe.logstreams - Can't read from illegal address: 13198684592
17:03:10.702 [0.0.0.0:51015] [actor-runner-broker-5] ERROR io.zeebe.logstreams - Can't read from illegal address: 13200711216
java.lang.IndexOutOfBoundsException: index=-65536 length=4 capacity=65536
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1285)
	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:491)
	at io.zeebe.logstreams.impl.LogEntryDescriptor.getFragmentLength(LogEntryDescriptor.java:124)
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.calculateCorrectReadResult(CompleteEventsInBlockProcessor.java:79)
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.process(CompleteEventsInBlockProcessor.java:51)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:248)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IndexOutOfBoundsException: index=-96 length=4 capacity=65536
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1285)
	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:491)
	at io.zeebe.logstreams.impl.LogEntryDescriptor.getFragmentLength(LogEntryDescriptor.java:124)
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.calculateCorrectReadResult(CompleteEventsInBlockProcessor.java:79)
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.process(CompleteEventsInBlockProcessor.java:51)
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:248)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
Let's hope this is fixed with https://github.com/zeebe-io/zb-util/commit/f399bd0a2718bbeb9da6fc86ed44f6bef743a5dd
