### ISSUE TITLE
Stream Process Controller reads invalid metadata version

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#601]
During the long running test suite the `StreamProcessorController` reads an invalid metadata version.

```
16:07:00.591 [0.0.0.0:51015] [actor-runner-broker-10] ERROR io.zeebe.logstreams - Stream processor 'log.default-topic.1.subscription.management' failed.
java.lang.RuntimeException: Cannot handle event with version newer than what is implemented by broker (65535 > 1)
	at io.zeebe.broker.logstreams.processor.StreamProcessorService.lambda$new$0(StreamProcessorService.java:51) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.MetadataFilter.lambda$and$0(MetadataFilter.java:42) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.StreamProcessorService$MetadataEventFilter.applies(StreamProcessorService.java:173) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:282) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:181) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:161) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:130) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:87) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:78) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
io.zeebe.util.state.NoSuchTransitionException: Cannot take transition 3 when in state io.zeebe.logstreams.processor.StreamProcessorController$FailedState@4c58599d
	at io.zeebe.util.state.StateMachine.take(StateMachine.java:57)
	at io.zeebe.util.state.SimpleStateMachineContext.take(SimpleStateMachineContext.java:29)
	at io.zeebe.logstreams.processor.StreamProcessorController.lambda$new$3(StreamProcessorController.java:239)
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.onFailure(StreamProcessorController.java:294)
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.onFailure(StreamProcessorController.java:266)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:128)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:181)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:161)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:130)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:87)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
Other stack traces for this issue:

```
19:55:17.215 [0.0.0.0:51015] [actor-runner-broker-11] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems28' failed.
java.lang.RuntimeException: Cannot handle event with version newer than what is implemented by broker (25972 > 1)
	at io.zeebe.broker.logstreams.processor.StreamProcessorService.lambda$new$0(StreamProcessorService.java:51) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.MetadataFilter.lambda$and$0(MetadataFilter.java:42) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.StreamProcessorService$MetadataEventFilter.applies(StreamProcessorService.java:173) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:282) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:181) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:161) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:130) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:87) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:78) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
19:55:17.214 [0.0.0.0:51015] [actor-runner-broker-4] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems28' failed.
java.lang.RuntimeException: Cannot handle event with version newer than what is implemented by broker (25972 > 1)
	at io.zeebe.broker.logstreams.processor.StreamProcessorService.lambda$new$0(StreamProcessorService.java:51) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.MetadataFilter.lambda$and$0(MetadataFilter.java:42) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.StreamProcessorService$MetadataEventFilter.applies(StreamProcessorService.java:173) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:282) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:181) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:161) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:130) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:87) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:78) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by menski** [comment]
Let's hope this is fixed with https://github.com/zeebe-io/zb-util/commit/f399bd0a2718bbeb9da6fc86ed44f6bef743a5dd
