### ISSUE TITLE
BufferedLogStreamReader tries to allocate an negative capacity buffer

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#602]
During the long running test suite the BufferedLogStreamReader tried to allocate a buffer with negative capacity:

```
16:31:29 16:31:29.817 [0.0.0.0:51015] [actor-runner-broker-8] ERROR io.zeebe.logstreams - Stream processor 'taskqueue.default-topic.1.processor.lock.reserveOrderItems19' failed.
16:31:29 java.lang.IllegalArgumentException: null
16:31:29 	at java.nio.Buffer.position(Buffer.java:244) ~[?:1.8.0_152]
16:31:29 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:226) ~[?:1.8.0_152]
16:31:29 	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_152]
16:31:29 	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741) ~[?:1.8.0_152]
16:31:29 	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727) ~[?:1.8.0_152]
16:31:29 	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:272) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:243) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:327) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:388) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:214) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:275) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:31:29 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
16:31:29 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
16:31:29 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
16:31:30 java.lang.IllegalArgumentException: Negative capacity: -2147483648
16:31:30 	at java.nio.Buffer.<init>(Buffer.java:199)
16:31:30 	at java.nio.ByteBuffer.<init>(ByteBuffer.java:281)
16:31:30 	at java.nio.ByteBuffer.<init>(ByteBuffer.java:289)
16:31:30 	at java.nio.MappedByteBuffer.<init>(MappedByteBuffer.java:89)
16:31:30 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:119)
16:31:30 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
16:31:30 	at io.zeebe.util.allocation.DirectBufferAllocator.allocate(DirectBufferAllocator.java:28)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.allocateBuffer(BufferedLogStreamReader.java:246)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:332)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:335)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:388)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextEvent(BufferedLogStreamReader.java:412)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:235)
16:31:30 	at io.zeebe.logstreams.log.BufferedLogStreamReader.next(BufferedLogStreamReader.java:33)
16:31:30 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:279)
16:31:30 	at io.zeebe.logstreams.processor.StreamProcessorController$OpenedState.doWork(StreamProcessorController.java:266)
16:31:30 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
16:31:30 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
16:31:30 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128)
16:31:30 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
16:31:30 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
16:31:30 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
16:31:30 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
16:31:30 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
16:31:30 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
16:31:30 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:31:30 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:31:30 	at java.lang.Thread.run(Thread.java:748)`

```

**Comment by menski** [comment]
Although I'm quite sure that this was triggered by a invalid read of a fragment size or similiar I added a general fix which limits the maximal size of the log stream reader buffer. I set the maximal size to 128MB but am not sure if this is reasonable. Happy to disguess that further.

**Comment by menski** [comment]
Ignore commit https://github.com/zeebe-io/zb-logstreams/commit/6afbd9f6950c274cf717129401c0d4f515d3ae4f it mixed up max and min 😦

**Comment by Zelldon** [comment]
OK I think is good to limit the buffer, but there is still the question why he tries to resize the buffer to the point that the int overflows. I mean we have no large events in the LargeWorkflow test so there is no need to resize at all. I think I have to review the BufferedReader code at first. :)

**Comment by menski** [comment]
As I wrote earlier I think this was due to an invalid fragment offset read which was triggered by the multithreading bug.

**Comment by Zelldon** [comment]
Ah sorry I read over it.
