### ISSUE TITLE
Object value does not accept valid enum value for task event property 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#603]
During the long running test suite the deserialization of a task event failed with the hint that `CREATE` is not a valid value for the `state` property which is not true.

```
16:01:33 16:01:33.380 [0.0.0.0:51015] [actor-runner-broker-7] ERROR io.zeebe.msgpack - Retry 0 could not deserialize object. Deserialization stuck at offset 324 of length 324 with last read byte 0x00. Buffer:
16:01:33 88 A5 73 74 61 74 65 A7 43 52 45 41 54 45 44 A8 6C 6F 63 6B 54 69 6D 65 D3 80 00 00 00 00 00 00
16:01:33 00 A9 6C 6F 63 6B 4F 77 6E 65 72 A0 A7 72 65 74 72 69 65 73 03 A4 74 79 70 65 B2 72 65 73 65 72
16:01:33 76 65 4F 72 64 65 72 49 74 65 6D 73 30 A7 68 65 61 64 65 72 73 86 AD 62 70 6D 6E 50 72 6F 63 65
16:01:33 73 73 49 64 B3 66 6F 72 74 79 2D 74 61 73 6B 73 2D 70 72 6F 63 65 73 73 B9 77 6F 72 6B 66 6C 6F
16:01:33 77 44 65 66 69 6E 69 74 69 6F 6E 56 65 72 73 69 6F 6E 01 AB 77 6F 72 6B 66 6C 6F 77 4B 65 79 CF
16:01:33 00 00 00 01 00 02 9E E8 B3 77 6F 72 6B 66 6C 6F 77 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 01
16:01:33 26 00 01 04 30 AA 61 63 74 69 76 69 74 79 49 64 B3 72 65 73 65 72 76 65 2D 6F 72 64 65 72 2D 69
16:01:33 74 65 6D 73 B3 61 63 74 69 76 69 74 79 49 6E 73 74 61 6E 63 65 4B 65 79 CF 00 00 01 26 00 0C FE
16:01:33 60 AD 63 75 73 74 6F 6D 48 65 61 64 65 72 73 81 AF 72 65 73 65 72 76 61 74 69 6F 6E 54 69 6D 65
16:01:33 A5 50 54 31 35 4D A7 70 61 79 6C 6F 61 64 C4 15 81 AA 6F 72 64 65 72 49 74 65 6D 73 93 CD 01 B3
16:01:33 CC B6 CD 01 78 
16:01:33 java.lang.RuntimeException: Could not read property 'state'.
16:01:33 	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:142) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:58) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:153) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onEvent(LockTaskStreamProcessor.java:247) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:317) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
16:01:33 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
16:01:33 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
16:01:33 Caused by: java.lang.RuntimeException: Illegal enum value: CREATE.
16:01:33 	at io.zeebe.msgpack.value.EnumValue.read(EnumValue.java:93) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.msgpack.property.BaseProperty.read(BaseProperty.java:99) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:138) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
16:01:33 	... 17 more
```

**Comment by menski** [comment]
https://hq2.camunda.com/jenkins/zeebe/job/zeebe-long-running-tests/77/consoleText

**Comment by menski** [comment]
Let's hope this is fixed with https://github.com/zeebe-io/zb-util/commit/f399bd0a2718bbeb9da6fc86ed44f6bef743a5dd
