### ISSUE TITLE
java.nio.file.FileSystemException: No Space Left on Device

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#6038]
**Describe the bug**
This error was observed in production logs. https://console.cloud.google.com/errors/CMaf_tS4rq6nowE?time=P30D&project=camunda-cloud-240911

This error is somewhat peculiar, because at the time that the error occurred there was ample of disk space available. All persistent volumes were around 20% usage and flat throughout the time.

Error happened twice with a 5 minute period in between

![image](https://user-images.githubusercontent.com/14032870/102894417-59901d00-4463-11eb-96ff-7d661499591f.png)

Cluster seems healthy to me. It's serving traffic, and aside from some small dips, Yield over 1 week is 99.89%.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
<p>
<pre>
java.nio.file.FileSystemException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/7228399-350-1608639478170-8206587-8206587-1/416435.sst: No space left on device

        at sun.nio.fs.UnixException.translateToIOException (Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException (Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException (Unknown Source)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel (Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newOutputStream (Unknown Source)
        at java.nio.file.Files.newOutputStream (Unknown Source)
        at java.nio.file.Files.write (Unknown Source)
        at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk (FileBasedReceivedSnapshot.java:175)
        at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.apply (FileBasedReceivedSnapshot.java:132)
        at io.zeebe.broker.system.partitions.impl.StateControllerImpl$ReplicationContext.apply (StateControllerImpl.java:343)
        at io.zeebe.broker.system.partitions.impl.StateControllerImpl.consumeSnapshotChunk (StateControllerImpl.java:226)
        at io.zeebe.broker.system.partitions.impl.StateReplication.lambda$consume$1 (StateReplication.java:70)
        at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:308)
        at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:297)
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$3 (NettyMessagingService.java:186)
        at java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run (Unknown Source)
        at java.lang.Thread.run (Unknown Source)
</pre>
</p>
</details>

**Environment:**
 - OS: Camunda Cloud/US East
 - Zeebe Version: 0.25.3
 - Configuration: `Test S - Low Latency`

**Comment by pihme** [comment]
Hpothesis by @ztombol:
> I'm wondering if the error message is incorrect. There were pod restarts around that time. What if the directory was not writeable (because the PVC was not attached in time). But this is just a hypothesis.

**Comment by pihme** [comment]
Likely a prequel to this incident:
https://docs.google.com/document/d/1EKKTKpxFm874kSyXcZ48AJcwg1EFFZTPCG-b0Hb4OdQ/edit#

**Comment by pihme** [comment]
Bumped severity up, because we think it led to an incident.

**Comment by pihme** [comment]
New and similar bug: https://console.cloud.google.com/errors/CKazi-yqg-awvgE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Comment by pihme** [comment]
current hypothesis is that there are not enough inodes available. We see 900K inodes out of 1M inodes used on one of the brokers.

**Comment by pihme** [comment]
Hypothesis is confirmed.

The snapshot has about 138K files while only 100K free inodes are available.

The broker when trying to become leader cannot copy the files.

The broker also cannot receive a new snapshot:

```
"java.nio.file.FileSystemException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/7294199-639-1608724409551-8283797-8283798-6/415510.sst: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source) ~[?:?]
	at java.nio.file.Files.newOutputStream(Unknown Source) ~[?:?]
	at java.nio.file.Files.write(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk(FileBasedReceivedSnapshot.java:175) ~[zeebe-snapshots-0.25.3.jar:0.25.3]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.apply(FileBasedReceivedSnapshot.java:132) ~[zeebe-snapshots-0.25.3.jar:0.25.3]
	at io.zeebe.broker.system.partitions.impl.StateControllerImpl$ReplicationContext.apply(StateControllerImpl.java:343) ~[zeebe-broker-0.25.3.jar:0.25.3]
	at io.zeebe.broker.system.partitions.impl.StateControllerImpl.consumeSnapshotChunk(StateControllerImpl.java:226) ~[zeebe-broker-0.25.3.jar:0.25.3]
	at io.zeebe.broker.system.partitions.impl.StateReplication.lambda$consume$1(StateReplication.java:70) ~[zeebe-broker-0.25.3.jar:0.25.3]
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:308) ~[atomix-cluster-0.25.3.jar:0.25.3]
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:297) ~[atomix-cluster-0.25.3.jar:0.25.3]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$3(NettyMessagingService.java:186) ~[atomix-cluster-0.25.3.jar:0.25.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by pihme** [comment]
VM with snapshot of disks:  https://console.cloud.google.com/compute/instancesDetail/zones/us-east1-d/instances/inc77-vm-20201223-123445?project=camunda-cloud-240911

**Comment by pihme** [comment]
Interesting detail is that many of the files were old snapshots. We found about 10 folder of these. After deleting all but the last two snapshots the system recovered.
