### ISSUE TITLE
zb-map merge uses invalid bucket id

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#605]
During the long running test suite a stream processor failed because there was an exception in the zb-map merge.

```
19:45:34.545 [0.0.0.0:51015] [actor-runner-broker-10] ERROR io.zeebe.logstreams - The log stream processor 'taskqueue.default-topic.1.processor.instance' failed to process event. It stop processing further events.
java.lang.IllegalArgumentException: Bucket id is larger then capacity!
	at io.zeebe.map.HashTable.getBucketAddress(HashTable.java:111) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeSplitBucket(ZbMapBucketMergeHelper.java:352) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergingBuckets(ZbMapBucketMergeHelper.java:231) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.map.ZbMap.remove(ZbMap.java:331) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.map.Long2BytesZbMap.remove(Long2BytesZbMap.java:74) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.task.map.TaskInstanceMap.remove(TaskInstanceMap.java:74) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.task.processor.TaskInstanceStreamProcessor$CompleteTaskProcessor.updateState(TaskInstanceStreamProcessor.java:357) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$3(StreamProcessorController.java:347) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.ComposedState$FailSafeStep.doWork(ComposedState.java:41) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by menski** [comment]
This happend again yesterday on the server running the `LargeWorkflowTest#shouldCreateAndCompleteWorkflowInstances` test.

```
22:53:57 22:53:57.214 [0.0.0.0:51015] [actor-runner-broker-11] ERROR io.zeebe.logstreams - The log stream processor 'taskqueue.default-topic.1.processor.instance' failed to process event. It stop processing further events.
22:53:57 java.lang.IllegalArgumentException: Bucket id is larger then capacity!
22:53:57 	at io.zeebe.map.HashTable.getBucketAddress(HashTable.java:111) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergeSplitBucket(ZbMapBucketMergeHelper.java:352) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.map.ZbMapBucketMergeHelper.tryMergingBuckets(ZbMapBucketMergeHelper.java:231) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.map.ZbMap.remove(ZbMap.java:331) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.map.Long2BytesZbMap.remove(Long2BytesZbMap.java:74) ~[zb-map-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.broker.task.map.TaskInstanceMap.remove(TaskInstanceMap.java:74) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.broker.task.processor.TaskInstanceStreamProcessor$CompleteTaskProcessor.updateState(TaskInstanceStreamProcessor.java:357) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$3(StreamProcessorController.java:347) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.state.ComposedState$FailSafeStep.doWork(ComposedState.java:41) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
22:53:57 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
22:53:57 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
22:53:57 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by menski** [comment]
It seems the problem is related to the fact that a buffer still exists which is equal to the capacity of the hash table. From a debugging session the following information was extracted:

Call which lead to exception:
```
ZbMapBucketMergeHelper#tryMergeSplitBucket(4, 6, 6, 0)
```

State when exception occurred:
```
hashTable.getCapacity() == 32
```

```
bucketBufferArray.getHighestBucketId() == 32
```

```
Map:[ Buckets:33, Blocks: 347], Buckets:[
        0% 36 blocks, is 10.37463976945245 % of all. Have 0 overflows
        10% 33 blocks, is 9.510086455331413 % of all. Have 0 overflows
        20% 38 blocks, is 10.951008645533141 % of all. Have 0 overflows
        30% 33 blocks, is 9.510086455331413 % of all. Have 0 overflows
        40% 30 blocks, is 8.645533141210375 % of all. Have 0 overflows
        50% 47 blocks, is 13.544668587896252 % of all. Have 0 overflows
        60% 32 blocks, is 9.221902017291066 % of all. Have 0 overflows
        70% 24 blocks, is 6.9164265129683 % of all. Have 0 overflows
        80% 34 blocks, is 9.798270893371757 % of all. Have 0 overflows
        90% 35 blocks, is 10.086455331412104 % of all. Have 0 overflows
], 0 indices point to the same bucket. Table size: 32
```

```
Bucket Array
    Bucket-0 contains 1.729106628242075 % of all blocks:[ Blocks:6 ,Overflow:0]
    Bucket-1 contains 3.170028818443804 % of all blocks:[ Blocks:11 ,Overflow:0]
    Bucket-2 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-3 contains 2.881844380403458 % of all blocks:[ Blocks:10 ,Overflow:0]
    Bucket-4 contains 2.881844380403458 % of all blocks:[ Blocks:10 ,Overflow:0]
    Bucket-5 contains 4.034582132564841 % of all blocks:[ Blocks:14 ,Overflow:0]
    Bucket-7 contains 4.034582132564841 % of all blocks:[ Blocks:14 ,Overflow:0]
    Bucket-6 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-9 contains 2.881844380403458 % of all blocks:[ Blocks:10 ,Overflow:0]
    Bucket-11 contains 2.881844380403458 % of all blocks:[ Blocks:10 ,Overflow:0]
    Bucket-14 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-10 contains 4.322766570605188 % of all blocks:[ Blocks:15 ,Overflow:0]
    Bucket-12 contains 2.3054755043227666 % of all blocks:[ Blocks:8 ,Overflow:0]
    Bucket-8 contains 4.034582132564841 % of all blocks:[ Blocks:14 ,Overflow:0]
    Bucket-13 contains 3.45821325648415 % of all blocks:[ Blocks:12 ,Overflow:0]
    Bucket-15 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-27 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-25 contains 2.0172910662824206 % of all blocks:[ Blocks:7 ,Overflow:0]
    Bucket-17 contains 2.881844380403458 % of all blocks:[ Blocks:10 ,Overflow:0]
    Bucket-18 contains 3.7463976945244957 % of all blocks:[ Blocks:13 ,Overflow:0]
    Bucket-19 contains 3.7463976945244957 % of all blocks:[ Blocks:13 ,Overflow:0]
    Bucket-29 contains 3.45821325648415 % of all blocks:[ Blocks:12 ,Overflow:0]
    Bucket-23 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-30 contains 3.45821325648415 % of all blocks:[ Blocks:12 ,Overflow:0]
    Bucket-22 contains 2.5936599423631126 % of all blocks:[ Blocks:9 ,Overflow:0]
    Bucket-16 contains 3.170028818443804 % of all blocks:[ Blocks:11 ,Overflow:0]
    Bucket-20 contains 3.7463976945244957 % of all blocks:[ Blocks:13 ,Overflow:0]
    Bucket-28 contains 4.034582132564841 % of all blocks:[ Blocks:14 ,Overflow:0]
    Bucket-24 contains 2.3054755043227666 % of all blocks:[ Blocks:8 ,Overflow:0]
    Bucket-21 contains 2.881844380403458 % of all blocks:[ Blocks:10 ,Overflow:0]
    Bucket-31 contains 3.170028818443804 % of all blocks:[ Blocks:11 ,Overflow:0]
    Bucket-32 contains 1.440922190201729 % of all blocks:[ Blocks:5 ,Overflow:0]
    Bucket-26 contains 3.170028818443804 % of all blocks:[ Blocks:11 ,Overflow:0]
```

Snapshot of map during the exception (remove `.txt`):
[zb-map.snapshot.txt](https://github.com/zeebe-io/zeebe/files/1615021/zb-map.snapshot.txt)
