### ISSUE TITLE
Request exception during long running test suite

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#608]
```
15:44:37.066 [] [actor-runner-executors-1] INFO  io.zeebe.client.subscription.task - An error ocurred when handling task 2551210996568. Reporting failure to broker.                                                               
io.zeebe.client.cmd.BrokerErrorException: Request exception (SBE_UNKNOWN): ��subscriberKey^G�taskType��lockDuration^@�lockOwner�default�credits^W                                                                                  

        at io.zeebe.client.cmd.BrokerErrorException.newInCurrentContext(BrokerErrorException.java:55) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.RequestManager.waitAndResolve(RequestManager.java:152) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.RequestManager.execute(RequestManager.java:111) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:38) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:25) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.broker.it.workflow.LargeWorkflowTest.lambda$getTaskHandler$1(LargeWorkflowTest.java:172) ~[test-classes/:?]
        at io.zeebe.client.task.impl.subscription.TaskSubscriber.lambda$pollEvents$0(TaskSubscriber.java:60) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.task.impl.subscription.EventSubscriber.pollEvents(EventSubscriber.java:369) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.task.impl.subscription.TaskSubscriber.pollEvents(TaskSubscriber.java:53) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.task.impl.subscription.TaskSubscriberGroup.poll(TaskSubscriberGroup.java:55) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.task.impl.subscription.TaskSubscriberGroup.poll(TaskSubscriberGroup.java:46) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]                                                                     
        at io.zeebe.client.task.impl.subscription.EventSubscribers.lambda$pollManagedSubscribers$5(EventSubscribers.java:183) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]                                               
        at io.zeebe.client.task.impl.subscription.EventSubscribers.forAllDo(EventSubscribers.java:167) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.task.impl.subscription.EventSubscribers.pollManagedSubscribers(EventSubscribers.java:183) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.task.impl.subscription.SubscriptionExecutor.doWork(SubscriptionExecutor.java:34) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: io.zeebe.client.cmd.BrokerErrorException: Request exception (SBE_UNKNOWN): ��subscriberKey^G�taskType��lockDuration^@�lockOwner�default�credits^W

        at io.zeebe.client.impl.RequestController$FailedState.doWork(RequestController.java:463) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.RequestController$FailedState.doWork(RequestController.java:449) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.RequestController.doWork(RequestController.java:165) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.client.impl.RequestManager.doWork(RequestManager.java:83) ~[zeebe-client-java-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
        ... 1 more
```

**Comment by menski** [comment]
Didn't saw this for a long time. The test suite in question was also rewritten and some fixes applied to the stream processors.
