### ISSUE TITLE
Synchronous creation of a million workflow instance hangs

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#609]
The test `LargeWorkflowTest#shouldCreateWorkflowInstancesSynchronously` often hangs on the test server and fails with a client command request timeout. Inspecting the logstream showed that the workflow instance created event was written, but it seems to not reach the client.

**Comment by menski** [comment]
It seems the request is received on the client side but the test still stops and ends with a client timeout:

```
11:37:09.704 [0.0.0.0:51015] [actor-runner-broker-4] INFO  io.zeebe.broker.workflow.processor.WorkflowInstanceStreamProcessor - Workflow instance 85904801216 created, send response: true
11:37:09.705 [] [actor-runner-default] INFO  io.zeebe.client - Workflow instance 85904801216 created, received response
```

```
io.zeebe.client.cmd.ClientException: No response received (timeout 180 seconds). Request was: [ topic = default-topic, partition = 1, event type = WORKFLOW_INSTANCE, state = CREATE_WORKFLOW_INSTANCE ]. Request receivers: [RemoteAddress{streamId=1, addr=0.0.0.0:51015}]
        at io.zeebe.client.cmd.ClientException.newInCurrentContext(ClientException.java:45)
        at io.zeebe.client.impl.RequestManager.waitAndResolve(RequestManager.java:152)
        at io.zeebe.client.impl.RequestManager.execute(RequestManager.java:111)
        at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:38)
        at io.zeebe.client.impl.cmd.CommandImpl.execute(CommandImpl.java:25)
        at io.zeebe.broker.it.workflow.LargeWorkflowTest.shouldCreateWorkflowInstancesSynchronously(LargeWorkflowTest.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: io.zeebe.client.cmd.ClientException: No response received (timeout 180 seconds). Request was: [ topic = default-topic, partition = 1, event type = WORKFLOW_INSTANCE, state = CREATE_WORKFLOW_INSTANCE ]. Request receivers: [RemoteAddress{streamId=1, addr=0.0.0.0:51015}]
        at io.zeebe.client.impl.RequestController.generateTimeoutException(RequestController.java:181)
        at io.zeebe.client.impl.RequestController$ExecuteRequestState.doWork(RequestController.java:386)
        at io.zeebe.client.impl.RequestController$ExecuteRequestState.doWork(RequestController.java:351)
        at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
        at io.zeebe.client.impl.RequestController.doWork(RequestController.java:165)
        at io.zeebe.client.impl.RequestManager.doWork(RequestManager.java:83)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
        at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
More logging showed that actually another request was send by the client which is then timeouting.

**Comment by menski** [comment]
From debugging it looks like we lose a event on the logstream 🤷‍♂️

**Comment by menski** [comment]
Closing for now as a lot changed and we should create a new issue if we experience something like this again.
