### ISSUE TITLE
Unexpected increase of request after preemption

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#6139]
**Describe the bug**
In the last [chaos day](https://zeebe-io.github.io/zeebe-chaos/chaos_experiment/broker/network/2021/01/19/network-partition.html) I observed that after a node preemption (which killed the gateway and leader) the activate job request accumulate to a number which the broker can't handle. 

![grpc-after-restart](https://user-images.githubusercontent.com/2758593/105135149-d3add300-5aef-11eb-89e2-c8c01ab90691.png)

Later it went down again:

![grpc-stabilized](https://user-images.githubusercontent.com/2758593/105135179-e1635880-5aef-11eb-8dbf-a3743f056c60.png)

I would like to understand why this happens and whether we can do something against it.

**To Reproduce**

I assume it has something to do with pod restarts, we need to find out.

**Expected behavior**

No scaling up of requests.

**Environment:**
 - OS: k8s
 - Zeebe Version: 0.27.0-SNAPSHOT
 - Configuration: 1 partition, replication factor 5, 5 nodes

**Comment by Zelldon** [comment]
Migth be related to https://github.com/zeebe-io/zeebe/issues/5812 :thinking:

**Comment by npepinpe** [comment]
Related to: https://github.com/zeebe-io/zeebe/issues/4443

**Comment by npepinpe** [comment]
Please check if these were failing requests, as this is a known issue where the job worker impl will retry immediately and send tons of requests.

**Comment by Zelldon** [comment]
Looks like we got a lot of `RESOURCES_EXHAUSTED`, which is kind of expected if we have 3 k requests. Is this what you're looking for @npepinpe ?

![failures](https://user-images.githubusercontent.com/2758593/105180253-9a468900-5b2a-11eb-8a7b-6183601cd103.png)

Interesting is that the other gw metrics doesn't show much, is this expected?
![gw-failures](https://user-images.githubusercontent.com/2758593/105180251-99155c00-5b2a-11eb-8c6b-f3f12d97bf15.png)

**Comment by npepinpe** [comment]
Partially - it was kick started by different errors though, right? UNAVAILABLE or something? That it switches gears to RESOURCE_EXHAUSTED after makes sense to some extent (esp. since it recovers). I can't quite read the metrics - when the gateway/leader died, did it immediately start getting RESOURCE_EXHAUSTED? Because that wouldn't be expected :thinking:

**Comment by Zelldon** [comment]
I checked the logs of the worker and indeed it gets exceptions from the grpc client, [because the gateway is not available.](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-01-19T10:39:45.000000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-chaos%22%0Alabels.%22k8s-pod%2Fapp%22%3D%22worker%22&scrollTimestamp=2021-01-19T10:39:45.034737354Z&dateRangeStart=2021-01-19T09:39:45.000Z&dateRangeEnd=2021-01-19T11:39:45.000Z&pinnedLogId=15ct6akg3efld8o&pinnedLogTimestamp=2021-01-19T10:39:45.034737354Z)

```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:0.24.2]

	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460) [app.jar:0.24.2]

	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [app.jar:0.24.2]

	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [app.jar:0.24.2]

	at me.dinowernli.grpc.prometheus.MonitoringClientCallListener.onClose(MonitoringClientCallListener.java:50) [app.jar:0.24.2]

	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) [app.jar:0.24.2]

	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) [app.jar:0.24.2]

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) [app.jar:0.24.2]

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) [app.jar:0.24.2]

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) [app.jar:0.24.2]

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) [app.jar:0.24.2]

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [app.jar:0.24.2]

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [app.jar:0.24.2]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]

	at java.lang.Thread.run(Unknown Source) [?:?]

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: zell-chaos-zeebe-gateway/10.4.1.233:26500

Caused by: java.net.ConnectException: Connection refused

	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]

	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:?]

	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[app.jar:0.24.2]

	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[app.jar:0.24.2]

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[app.jar:0.24.2]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[app.jar:0.24.2]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[app.jar:0.24.2]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[app.jar:0.24.2]

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[app.jar:0.24.2]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[app.jar:0.24.2]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[app.jar:0.24.2]

	... 1 more
```

**Comment by npepinpe** [comment]
Then it's what we expected - I would propose to close it as we won't tackle this yet from the server side (though eventually we should), for now we'll implement backoff in the clients.
