### ISSUE TITLE
Calling toString on Unpacked Object Topology changes serialization and breaks deserialization in the client

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#616]
If `toString()` is called on a Topology object, e.g. by logging the topology, the serialized buffer of the topology differs from not calling `toString()` before. Also the client is not able to deserialize this bytes correctly and will set the brokers list to null.

The following test case reproduces the problem, if the `toString` call is removed before the `write` call the serialization/deserialization works as expected.

```
@Test
public void foo()
{
    // init
    final DirectBuffer foo = BufferUtil.wrapString("foo");
    final DirectBuffer bar = BufferUtil.wrapString("bar");
    
    final MsgPackConverter msgPackConverter = new MsgPackConverter();

    final MessagePackFactory messagePackFactory = new MessagePackFactory()
        .setReuseResourceInGenerator(false)
        .setReuseResourceInParser(false);
    final ObjectMapper objectMapper = new ObjectMapper(messagePackFactory);
    objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);

    final InjectableValues injectionContext = new InjectableValues.Std()
        .addValue(MsgPackConverter.class, msgPackConverter);
    objectMapper.setInjectableValues(injectionContext);

    // given
    final Topology topology = new Topology();
    topology.brokers().add()
            .setHost(foo, 0, foo.capacity())
            .setPort(12);
    topology.brokers().add()
            .setHost(bar, 0, bar.capacity())
            .setPort(13);

    topology.topicLeaders().add()
            .setHost(foo, 0, foo.capacity())
            .setPort(12)
            .setPartitionId(0)
            .setTopicName(foo, 0, foo.capacity());

    final byte[] bytes = new byte[1024];
    final UnsafeBuffer buffer = new UnsafeBuffer(bytes);

    // when
    topology.toString();
    topology.write(buffer, 0);

    // then
    final DirectBufferInputStream inStream = new DirectBufferInputStream(
        buffer,
        0,
        topology.getLength());

    final TopologyResponse response;
    try
    {
        response = objectMapper.readValue(inStream, TopologyResponse.class);
    }
    catch (final Exception e)
    {
        throw new RuntimeException("Cannot deserialize event in response", e);
    }

    System.out.println(response);
    assertThat(response.getBrokers()).isNotNull();
}
```

**Comment by menski** [comment]
It seems that every `toString` call will expand the serialized output. For example in the topology every `toString` call will duplicate all brokers in the list.

Expected message pack:
```
00000000  82 ac 74 6f 70 69 63 4c  65 61 64 65 72 73 91 84  |..topicLeaders..|                                                                                                                                                                                                  
00000010  a4 68 6f 73 74 a3 66 6f  6f a4 70 6f 72 74 0c a9  |.host.foo.port..|
00000020  74 6f 70 69 63 4e 61 6d  65 a3 66 6f 6f ab 70 61  |topicName.foo.pa|
00000030  72 74 69 74 69 6f 6e 49  64 00 a7 62 72 6f 6b 65  |rtitionId..broke|
00000040  72 73 92 82 a4 68 6f 73  74 a3 66 6f 6f a4 70 6f  |rs...host.foo.po|
00000050  72 74 0c 82 a4 68 6f 73  74 a3 62 61 72 a4 70 6f  |rt...host.bar.po|
00000060  72 74 0d                                          |rt.|
```

Actual message pack after calling `toString` once:
```
00000000  82 ac 74 6f 70 69 63 4c  65 61 64 65 72 73 91 84  |..topicLeaders..|                                                                                                                                                                                                  
00000010  a4 68 6f 73 74 a3 66 6f  6f a4 70 6f 72 74 0c a9  |.host.foo.port..|
00000020  74 6f 70 69 63 4e 61 6d  65 a3 66 6f 6f ab 70 61  |topicName.foo.pa|
00000030  72 74 69 74 69 6f 6e 49  64 00 84 a4 68 6f 73 74  |rtitionId...host|
00000040  a3 66 6f 6f a4 70 6f 72  74 0c a9 74 6f 70 69 63  |.foo.port..topic|
00000050  4e 61 6d 65 a3 66 6f 6f  ab 70 61 72 74 69 74 69  |Name.foo.partiti|
00000060  6f 6e 49 64 00 a7 62 72  6f 6b 65 72 73 92 82 a4  |onId..brokers...|
00000070  68 6f 73 74 a3 66 6f 6f  a4 70 6f 72 74 0c 82 a4  |host.foo.port...|
00000080  68 6f 73 74 a3 62 61 72  a4 70 6f 72 74 0d 82 a4  |host.bar.port...|
00000090  68 6f 73 74 a3 66 6f 6f  a4 70 6f 72 74 0c 82 a4  |host.foo.port...|
000000a0  68 6f 73 74 a3 62 61 72  a4 70 6f 72 74 0d        |host.bar.port.|
```

**Comment by Zelldon** [comment]
The integration test seem to fail because an deserialization issue, perhaps is related to the array value changes?

```java
08:17:28.971 [localhost:51015] [actor-runner-broker-2] ERROR io.zeebe.logstreams - The log stream processor 'deployment' failed to process event. It stop processing further events.
java.lang.RuntimeException: Could not deserialize object. Deserialization stuck at offset 753 of length 839
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:48) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.LoggedEventImpl.readValue(LoggedEventImpl.java:153) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor.onEvent(TypedStreamProcessor.java:121) ~[zeebe-broker-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$ProcessState.lambda$new$0(StreamProcessorController.java:317) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.ComposedState.doWork(ComposedState.java:63) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.doWork(StreamProcessorController.java:128) ~[zb-logstreams-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [zb-util-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.RuntimeException: Unable to determine string type, found unknown header byte 0x63 at reader offset 752
	at io.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader(MsgPackReader.java:488) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.msgpack.spec.MsgPackReader.readStringLength(MsgPackReader.java:141) ~[zb-msgpack-core-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.msgpack.value.StringValue.read(StringValue.java:149) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:115) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	at io.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:44) ~[zb-msgpack-value-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
	... 16 more
```

**Comment by menski** [comment]
I reverted my changes on master and will try to fix the issue with the undeclared property first
