### ISSUE TITLE
Removing leader from cluster does not work as expected

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#617]
Removing leader should be the same as removing a normal follower from the cluster.

RAFT cluster should choose a new leader and work as expected. It should be possible to request the topology and get as response a list of the remaining brokers.

See failing test case  `GossipClusteringTest#shouldRemoveLeaderFromCluster` which was created in #610

**Comment by Zelldon** [comment]
I'm not sure but I think one problem is that if the leader dies the followers triggering a poll after election timeout. The poll are send to the dead lead as well, which will again timeout.


```java
11:17:16.473 [localhost:41015] [actor-runner-broker-1] DEBUG io.zeebe.raft - foo.1 - localhost:41017 - Triggering poll after election timeout reached
11:17:16.474 [localhost:41015] [actor-runner-broker-1] DEBUG io.zeebe.raft - foo.1 - localhost:41017 - Transitioned to follower in term 1
11:17:16.475 [localhost:41015] [actor-runner-broker-1] DEBUG io.zeebe.raft - foo.1 - localhost:41017 - poll request send to 2 other members
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.zeebe.transport.impl.TransportChannel.finishConnect(TransportChannel.java:262)
	at io.zeebe.transport.impl.selector.ConnectTransportPoller.processKey(ConnectTransportPoller.java:128)
	at org.agrona.nio.NioSelectedKeySet.forEach(NioSelectedKeySet.java:136)
	at io.zeebe.transport.impl.selector.ConnectTransportPoller.pollNow(ConnectTransportPoller.java:111)
	at io.zeebe.transport.impl.selector.ConnectTransportPoller.doWork(ConnectTransportPoller.java:52)
	at io.zeebe.transport.impl.actor.ClientConductor.doWork(ClientConductor.java:43)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
11:17:16.520 [localhost:41015] [actor-runner-broker-1] DEBUG io.zeebe.raft - foo.1 - localhost:41017 - Failed to receive poll response
```

**Comment by Zelldon** [comment]
Ok the main reason behind this is that if we use `client.requestTopology()` this will not update the internal topology. I changed that and the test is most of the time green.

Sometimes there is a problem that a remaining broker returns a topology with only himself in the list.

**Comment by ThorbenLindhauer** [comment]
Just noticed: The solution does not work when `RequestTopologyCmdImpl#executeAsync` is used.

**Comment by Zelldon** [comment]
Ah thanks you are right

**Comment by menski** [comment]
Reopening cause my refactoring broke the test suite. I reverted my changes and have to investigate what is going on.

**Comment by menski** [comment]
My changes broke everything because my assumption that `execute` uses `executeAsync` internally was totally wrong. :see_no_evil:
