### ISSUE TITLE
NPE in BufferLogStreamReader

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#627]
On running the deployment clustered tests I got a NPE in the BufferedlogStreamReader

```java
java.lang.NullPointerException
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:325)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readNextAddress(BufferedLogStreamReader.java:393)
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:215)
	at io.zeebe.raft.RaftMember.getNextEvent(RaftMember.java:130)
	at io.zeebe.raft.controller.ReplicateLogController$OpenState.doWork(ReplicateLogController.java:130)
	at io.zeebe.raft.controller.ReplicateLogController$OpenState.doWork(ReplicateLogController.java:104)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.raft.controller.ReplicateLogController.doWork(ReplicateLogController.java:56)
	at io.zeebe.raft.Raft.doWork(Raft.java:265)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zelldon** [comment]
See complete log
[deploymentClusteredTest.zip](https://github.com/zeebe-io/zeebe/files/1652337/deploymentClusteredTest.zip)

**Comment by Zelldon** [comment]
```java
java.lang.IllegalStateException: Iterator not initialized
	at io.zeebe.logstreams.log.BufferedLogStreamReader.hasNext(BufferedLogStreamReader.java:221)
	at io.zeebe.raft.RaftMember.getNextEvent(RaftMember.java:130)
	at io.zeebe.raft.controller.ReplicateLogController$OpenState.doWork(ReplicateLogController.java:130)
	at io.zeebe.raft.controller.ReplicateLogController$OpenState.doWork(ReplicateLogController.java:104)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:115)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.raft.controller.ReplicateLogController.doWork(ReplicateLogController.java:56)
	at io.zeebe.raft.Raft.doWork(Raft.java:265)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
[brokerDies.zip](https://github.com/zeebe-io/zeebe/files/1654929/brokerDies.zip)

**Comment by Zelldon** [comment]
I would assume this is fixed
