### ISSUE TITLE
Inconsistent configuration (cluster size 1 although we have a 5 node cluster)

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#6277]
**Describe the bug**
Observed in error logs: https://console.cloud.google.com/errors/CP7yzJvgm6mnWA?service=zeebe&time=P7D&project=camunda-cloud-240911

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.2.jar:2.4.2]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [zeebe-distribution-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Node id 5 needs to be non negative and smaller then cluster size 1.
	at io.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:80) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:55) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.SystemContext.<init>(SystemContext.java:48) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.Broker.<init>(Broker.java:150) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.StandaloneBroker.createBrokerInBaseDirectory(StandaloneBroker.java:84) ~[zeebe-distribution-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:55) ~[zeebe-distribution-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.2.jar:2.4.2]
	... 5 more
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
Info 2021-02-08 05:59:06.759 CET zeebe-5 ZEEBE_CLUSTER_SIZE=1
Info 2021-02-08 05:59:06.759 CET zeebe-5 ELASTICSEARCH_PORT_9200_TCP_PORT=9200
Info 2021-02-08 05:59:06.759 CET zeebe-5 ZEEBE_LOG_LEVEL=debug
Info 2021-02-08 05:59:06.759 CET zeebe-5 KUBERNETES_SERVICE_PORT=443
Info 2021-02-08 05:59:06.759 CET zeebe-5 TASKLIST_SERVICE_PORT_8081_TCP_ADDR=10.0.61.94
Info 2021-02-08 05:59:06.759 CET zeebe-5 OPERATE_SERVICE_PORT_8081_TCP_PROTO=tcp
Info 2021-02-08 05:59:06.759 CET zeebe-5 ELASTICSEARCH_PORT_9200_TCP_ADDR=10.0.51.163
Info 2021-02-08 05:59:06.759 CET zeebe-5 ELASTICSEARCH_SERVICE_HOST=10.0.51.163
Info 2021-02-08 05:59:06.759 CET zeebe-5 ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
Info 2021-02-08 05:59:06.759 CET zeebe-5 HOSTNAME=zeebe-5
Info 2021-02-08 05:59:06.759 CET zeebe-5 ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=zeebe-5.zeebe-broker-service.679df52c-3996-4209-a5c0-c00925aa7501-zeebe.svc.cluster.local
Info 2021-02-08 05:59:06.759 CET zeebe-5 TASKLIST_SERVICE_SERVICE_PORT_METRICS=8081
Info 2021-02-08 05:59:06.759 CET zeebe-5 OPERATE_SERVICE_PORT_8080_TCP_ADDR=10.0.50.251
Info 2021-02-08 05:59:06.759 CET zeebe-5 JAVA_HOME=/usr/local/openjdk-11
Info 2021-02-08 05:59:06.759 CET zeebe-5 OPERATE_SERVICE_PORT_8080_TCP_PROTO=tcp
Info 2021-02-08 05:59:06.759 CET zeebe-5 TASKLIST_SERVICE_SERVICE_HOST=10.0.61.94
Info 2021-02-08 05:59:06.759 CET zeebe-5 ZEEBE_BROKER_CLUSTER_NODEID=5 
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud Int
 - Zeebe Version: zeebe:1.0.0-SNAPSHOT-4c58c08cb904a85ff239c9f53da2a6743cbf9017, zeebe:SNAPSHOT

**Comment by pihme** [comment]
Analysis:
* It is a 5 node cluster
* For some reason the 5th node is called with cluster size = 1

**Comment by npepinpe** [comment]
This was a bug in Camunda Cloud due to a race condition when creating clusters in a very short time span.
