### ISSUE TITLE
Test suite hangs during maven run with "Address already in use"

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#642]
Sometimes the test suite stops and fails as it cannot bind to the given network address as it claims it is still in use.

```
11:59:15.834 [localhost:51015] [service-container-action-0] INFO  io.zeebe.broker.services - Using /tmp/junit4316972134707707111/persistent-broker/metrics/metrics.zeebe for counters
Exception in thread "actor-runner-service-container" java.lang.RuntimeException: Failed to bind to address: localhost/127.0.0.1:51017
        at io.zeebe.transport.impl.ServerSocketBinding.doBind(ServerSocketBinding.java:58)
        at io.zeebe.transport.ServerTransportBuilder.buildTransportContext(ServerTransportBuilder.java:124)
        at io.zeebe.transport.ServerTransportBuilder.buildBuffering(ServerTransportBuilder.java:111)
        at io.zeebe.broker.transport.BufferingServerTransportService.start(BufferingServerTransportService.java:63)
        at io.zeebe.servicecontainer.impl.ServiceController$InvokeStartState.doWork(ServiceController.java:269)
        at io.zeebe.servicecontainer.impl.ServiceController.doWork(ServiceController.java:138)
        at io.zeebe.servicecontainer.impl.ServiceContainerImpl.doWork(ServiceContainerImpl.java:119)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
        at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157)
        at io.zeebe.transport.impl.ServerSocketBinding.doBind(ServerSocketBinding.java:53)
        ... 13 more
```

**Comment by Zelldon** [comment]
Perhaps related with https://github.com/zeebe-io/zeebe/issues/643#issuecomment-361946520

**Comment by menski** [comment]
Didn't saw this in a while. Maybe fixed with the clustering layer rewrite. Closing for now
