### ISSUE TITLE
Create Deployment clustering tests

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#643]
The following  should be tested  for deployments in a cluster:

- [x] simply deploy
- [X] deploy and create instances
- [X] stop broker and deploy on remaining
- [x] stop, deploy, restart broker and start instances
- [x] restart broker and deploy
- [x] deploy on topic with many partitions
- [x] deploy on different topics
- [x] deploy multiple resources
- [x] deploy unparsable
- [x] invalid bpmn
- [x] not deploy non executable
- [x] not deploy empty
- [x] deploy yaml
- [x] reject deployment for non existing topic

**Comment by Zelldon** [comment]
After creating this test cases and running them separately, I executed all of them.

Problem I observed is that after running `shouldDeployOnTopicWithManyPartitions`
The service controller dies in the on shutdown. 


```java
15:12:56.919 [localhost:51015] [main] INFO  io.zeebe.broker.system - Closing...
Exception in thread "actor-runner-service-container" java.lang.IllegalStateException: Queue is full
	at org.agrona.concurrent.AbstractConcurrentArrayQueue.add(AbstractConcurrentArrayQueue.java:142)
	at io.zeebe.servicecontainer.impl.ServiceController.onReferencedServiceStop(ServiceController.java:930)
	at io.zeebe.servicecontainer.impl.ServiceGroup.onServiceRemoved(ServiceGroup.java:75)
	at io.zeebe.servicecontainer.impl.ServiceGroup.removeService(ServiceGroup.java:54)
	at io.zeebe.servicecontainer.impl.ServiceController$RemoveReferencesState.doWork(ServiceController.java:341)
	at io.zeebe.servicecontainer.impl.ServiceController.doWork(ServiceController.java:138)
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.doWork(ServiceContainerImpl.java:119)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.lang.Thread.run(Thread.java:748)
15:13:06.920 [localhost:51015] [main] ERROR io.zeebe.broker.system - Failed to close broker within 10 seconds
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_144]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_144]
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.close(ServiceContainerImpl.java:249) ~[classes/:?]
	at io.zeebe.broker.system.SystemContext.close(SystemContext.java:132) ~[classes/:?]
	at io.zeebe.broker.Broker.lambda$close$1(Broker.java:91) ~[classes/:?]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [classes/:?]
	at io.zeebe.broker.Broker.close(Broker.java:87) [classes/:?]
	at io.zeebe.test.util.AutoCloseableRule.after(AutoCloseableRule.java:48) [classes/:?]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]
15:13:06.924 [localhost:51015] [main] INFO  io.zeebe.broker.system - Broker closed
```

The next tests are not able to start there brokers,
since they are not shutdown correctly and the addresses are still in use. The problem is that the service controller has to kill more services than he has capacity. 

```java
public class ServiceController {
...
protected final ManyToOneConcurrentArrayQueue<Runnable> cmdQueue = new ManyToOneConcurrentArrayQueue<>(8);
..
}
```

Fixed that with increasing the capacity.

**Comment by menski** [comment]
Just noticed that these test take 2:30min on Jenkins. Is there any potential to speed the tests up?

**Comment by saig0** [comment]
Review Hint:
* I think we don't need so many test cases. Some of them already exist in `CreateDeploymentTest`. We should focus on the cluster behavior. 
* we should add test cases to verify that a deployment is removed if it fails to distribute it to all partitions (including workflow instances if any exist) -> then we can close #545

**Comment by Zelldon** [comment]
Which are not necessary on your opinion? So we can discuss this. 
How it is possible that there exist a WF instance if the deployment is not replicated?
