### ISSUE TITLE
NPE in FSLogSegment on read

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#649]
The LogBlockIndexController tries to read a block this fails with a NPE in the FsLogSegment.
Saw this the first time with the `LargeCreateTaskClusterTest`

```java
20:42:00 java.lang.RuntimeException: java.lang.NullPointerException
20:42:00 	at io.zeebe.util.state.State.onFailure(State.java:35)
20:42:00 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:137)
20:42:00 	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
20:42:00 	at io.zeebe.logstreams.impl.LogBlockIndexController.doWork(LogBlockIndexController.java:155)
20:42:00 	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
20:42:00 	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160)
20:42:00 	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
20:42:00 	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
20:42:00 	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
20:42:00 	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
20:42:00 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:42:00 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:42:00 	at java.lang.Thread.run(Thread.java:748)
20:42:00 Caused by: java.lang.NullPointerException
20:42:00 	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:135)
20:42:00 	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.readBytes(FsLogSegment.java:255)
20:42:00 	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:243)
20:42:00 	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:230)
20:42:00 	at io.zeebe.logstreams.impl.LogBlockIndexController$OpenState.doWork(LogBlockIndexController.java:217)
20:42:00 	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:124)
20:42:00 	... 11 more
20:42:00 java.lang.RuntimeException: java.lang.NullPointerException
```

This is repeated really often until the following is printed.

```java

20:42:00 20:42:00.071 [localhost:51015] [actor-runner-broker-2] ERROR io.zeebe.logstreams - Can't read from illegal address: 104322304
20:42:00 20:42:00.071 [localhost:51015] [actor-runner-broker-2] ERROR io.zeebe.logstreams - Can't read from illegal address: 104322304
```

**Comment by menski** [comment]
similar to #579 and #452

**Comment by menski** [comment]
Hopefully fixed with the latest orchestration service dependency refactoring. Will close for now. If we see this again we can reopen this issue or create a new one.
