### ISSUE TITLE
InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#6504]
**Describe the bug**
Observed in logs: https://console.cloud.google.com/errors/CMHr6Oj_nM3WDQ?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at com.esotericsoftware.kryo.pool.SoftReferenceQueue.offer(SoftReferenceQueue.java:53) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.pool.SoftReferenceQueue.offer(SoftReferenceQueue.java:33) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.release(KryoPoolQueueImpl.java:52) ~[kryo-4.0.2.jar:?]
	at io.atomix.utils.serializer.NamespaceImpl.release(NamespaceImpl.java:321) ~[atomix-utils-0.26.1.jar:0.26.1]
	at io.atomix.utils.serializer.NamespaceImpl.serialize(NamespaceImpl.java:154) ~[atomix-utils-0.26.1.jar:0.26.1]
	at io.atomix.utils.serializer.FallbackNamespace.serialize(FallbackNamespace.java:71) ~[atomix-utils-0.26.1.jar:0.26.1]
	at io.atomix.storage.journal.MappedJournalSegmentWriter.append(MappedJournalSegmentWriter.java:112) ~[atomix-storage-0.26.1.jar:0.26.1]
	at io.atomix.storage.journal.SegmentedJournalWriter.append(SegmentedJournalWriter.java:54) ~[atomix-storage-0.26.1.jar:0.26.1]
	at io.atomix.storage.journal.DelegatingJournalWriter.append(DelegatingJournalWriter.java:46) ~[atomix-storage-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.PassiveRole.appendEntry(PassiveRole.java:710) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.PassiveRole.appendEntry(PassiveRole.java:665) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:643) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:587) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:440) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:195) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$14(RaftContext.java:220) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$21(RaftContext.java:231) ~[atomix-cluster-0.26.1.jar:0.26.1]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.26.1.jar:0.26.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.26.1
 - Configuration: Camunda Cloud

**Comment by pihme** [comment]
No real insight into why this happened. One thing to note is that this happened after: https://github.com/zeebe-io/zeebe/issues/6505

Not sure if these two are related, but there is a correlation between the two symptoms.

How do memory mapped files work? Could it be that we cannot write to memory because we cannot allocate the disk space that is mapped to memory?

**Comment by npepinpe** [comment]
That's possible - we don't pre-allocate the file but we already define the mapping length. AFAIK, as dirty pages are flushed to disk, the file is then grown accordingly. It could be that we map the file with mapping length ~128MB with less than that left which results in us running out of disk space. However I would expect the disk watermarks to be breached before that and prevent the disk from really running out of space (barring any bugs). Still, it's a likely explanation.

With network storage, this can also happen if you lose access to the volume where the file was mapped - now GKE PVCs aren't common network storage like an NFS mount, so I'm not sure if that's possible there, but if so then it could be that too.

Could it also happen if we deleted the file in the meantime? That also shouldn't happen barring a bug, but it could be that. I know you can get internal error if you truncate the file, but I'm not sure what happens if you just plain delete it. Would you get an IOException or an InternalError? :thinking:

**Comment by npepinpe** [comment]
@MiguelPires let's have a look at the status of this cluster - if it's not recovered we should treat it as an incident, otherwise we can treat it as a normal bug. Please let me know when you find out.

**Comment by npepinpe** [comment]
We need to decide what we want to do here. My understanding of the problem is that the InternalError is thrown where normally we would get an IOException. What I'd like to investigate is if this is the only possible case, as catching InternalError could be problematic if it's not equivalent to IOException in some cases here.

**Comment by npepinpe** [comment]
This does not happen if you just delete the file, as the file descriptor still points to the old inode. However, I can confirm this will happen if you:

## Write to a truncated mapped file

```java
    final File f = new File("/home/nicolas/tmp/sandbox/test");
    final MappedByteBuffer buffer = IoUtil.mapNewFile(f, 1024 * 1024, true);
    buffer.position(512 * 1024).putLong(1L);
    try (final FileChannel c = FileChannel.open(f.toPath(), StandardOpenOption.WRITE)) {
      c.truncate(4096);
      c.force(true);
      buffer.putLong(2L);
    } finally {
      f.delete();
    }
```

## Read from a truncated mapped file

```java
    final File f = new File("/home/nicolas/tmp/sandbox/test");
    final MappedByteBuffer buffer = IoUtil.mapNewFile(f, 1024 * 1024, true);
    buffer.position(512 * 1024).putLong(1L);
    try (final FileChannel c = FileChannel.open(f.toPath(), StandardOpenOption.WRITE)) {
      c.truncate(4096);
      buffer.get(5000);
    } finally {
      f.delete();
    }
```

## Insufficient disk space to grow the underlying file

To simulate this, we launch a Java container with a small test file that will try to write 2MB of data using a mapped byte buffer, but we only give it a 1MB disk.

```java
  @Rule public final TemporaryFolder temporaryFolder = new TemporaryFolder();

  @Test
  public void shouldThrowInternalError() throws IOException, InterruptedException {
    final File file = temporaryFolder.newFile("test.java");
    final GenericContainer<?> c =
        new GenericContainer<>(DockerImageName.parse("azul/zulu-openjdk-alpine:11-jre-headless"));
    final Map<String, String> volumeOptions =
        Map.of("type", "tmpfs", "device", "tmpfs", "o", "size=1m");
    final ManagedVolume v =
        ManagedVolume.newVolume(cmd -> cmd.withDriver("local").withDriverOpts(volumeOptions));
    c.withCreateContainerCmdModifier(v::attachVolumeToContainer);
    Files.write(file.toPath(), List.of(
        "import java.io.IOException;",
        "import java.nio.MappedByteBuffer;",
        "import java.nio.channels.FileChannel;",
        "import java.nio.file.Path;",
        "import static java.nio.channels.FileChannel.MapMode.READ_ONLY;",
        "import static java.nio.channels.FileChannel.MapMode.READ_WRITE;",
        "import static java.nio.file.StandardOpenOption.*;",
        "public final class Test {",
          "public static void main(final String args[]) throws IOException {",
            "MappedByteBuffer mappedByteBuffer = null;",
            "try (FileChannel channel = FileChannel.open(Path.of(\"/usr/local/zeebe/data/test\"), CREATE, READ, WRITE)) {",
              "mappedByteBuffer = channel.map(READ_WRITE, 0, 2 * 1024 * 1024);",
              "int position = 0;",
              "while (position < mappedByteBuffer.capacity()) {",
                "mappedByteBuffer.put(position, (byte)0);",
                "mappedByteBuffer.force();",
                "position += 4096;",
              "}",
            "}",
          "}",
        "}"
    ));

    c.withCopyFileToContainer(MountableFile.forHostPath(file.toPath()), "/test.java")
        .withCreateContainerCmdModifier(cmd -> cmd.withEntrypoint("java"))
        .withCommand("/test.java")
        .withLogConsumer(new Slf4jLogConsumer(LoggerFactory.getLogger("test")));
    c.start();

    // give some time for it to compile and run the code, as well as print out the error
    Thread.sleep(10_000);
    c.stop();
  }
```

In my opinion we should handle these cases. I can't confirm that `InternalError` cannot be thrown for other cases however, but if we handle it specifically around the write and read cases, as close to the source as possible to avoid any errors. The out of disk space should be obvious, but the truncated file...it's a bit of a pain that we can't differentiate the cases. The OOD is easy to recover from, just retry when there's more disk space. The truncated file...you basically have to go back and start from the last correct offset. We don't truncate files however, so the only expected truncation could occur from the outside at the moment. We can assume for now that if we get this error, it's because of OOD, and we should handle it properly. If we ever do truncate files (maybe to save space or someting), then we should handle this, but that will require more coordination (as you have to basically detect the underlying FD is invalid, remap the file, pass this mapping to existing readers/writers in a thread safe way, etc.).

For now, let's focus on the OOD case, and add a comment that we assume it means OOD as we don't handle truncation.

**Comment by npepinpe** [comment]
@deepthidevaki if you have time, could you have a look at this today or next week? Let me know if you have any questions.

**Comment by npepinpe** [comment]
After discussion with @deepthidevaki, we think pre-allocating files is most likely a better option here.

**Comment by npepinpe** [comment]
Options for pre-allocation:

1. JNI bindings to fallocate (i.e. using `jnr-ffi` or something). Pros: most likely the fastest. Cons: only available on Linux.
1. Copy a pre-allocated template file. Pros: OS/FS independent, can transfer between `FileChannel` to avoid going into the JVM. Cons: need to pre-allocate the template file on start up (i.e. if segment size config changed), need to copy the file anyway
1. "Fill" with zero the way Agrona does - write a single 0 byte every page size and at the end, such that you've touched all expected pages, and force the file. Pros: OS/FS independent, flexible with different segment size. Cons: slowest (most likely), need to flush the whole file.

I would opt for 1, with a fallback when `fallocate` is not available to 3, primarily because our supported environment _is_ Linux, so the fallback would only be for development/demo use cases, not for production.

**Comment by npepinpe** [comment]
Should be fixed by https://github.com/camunda-cloud/zeebe/issues/7607
