### ISSUE TITLE
If a node leaves the cluster but is not know by the current node a NullPointerException is thrown

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#653]
```
13:20:40.424 [actor-runner-broker] INFO  io.zeebe.gossip - Remove member 'localhost:41016', status = LEAVE, gossip-term: [epoch=1517573756451, heartBeat=2]
13:20:40.426 [actor-runner-broker] DEBUG io.zeebe.broker.clustering - Remove member null from member list.
java.lang.NullPointerException
        at io.zeebe.broker.clustering.management.memberList.ClusterMemberListManager$MembershipListener.lambda$onRemove$1(ClusterMemberListManager.java:154)
        at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:113)
        at org.agrona.concurrent.ManyToOneConcurrentArrayQueue.drain(ManyToOneConcurrentArrayQueue.java:88)
        at io.zeebe.util.DeferredCommandContext.doWork(DeferredCommandContext.java:66)
        at io.zeebe.broker.clustering.management.memberList.ClusterMemberListManager.doWork(ClusterMemberListManager.java:101)
        at io.zeebe.broker.clustering.management.ClusterManager.doWork(ClusterManager.java:189)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
        at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
The code in question does not exist anymore
