### ISSUE TITLE
Log client request failures more user friendly

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#661]
If a user tries to use the Zeebe Java client to create a topic, resources, instance or subscription but the broker is not available the exception printed is kind of complex to understand. Maybe we find a way to give a better reasoning to the user. For example the following exception stack trace is printed if I try to create a task subscription with Zeebe 0.7.0 without an broker running.

```
13:48:58.633 [] [actor-runner-default] ERROR io.zeebe.client.subscription - Subscriber Group [topic=default-topic, taskHandler=io.zeebe.workflow.WorkflowInstanceWorker$$Lambda$36/1529060733@6f9f0f30, taskType=foo, lockTime=10000, lockOwner=worker-1, capacity=32]: Could not fetch topics
Exception in thread "main" io.zeebe.client.cmd.ClientException: Could not open subscription: io.zeebe.client.cmd.ClientException: Could not create subscriber group [topic=default-topic, taskHandler=io.zeebe.workflow.WorkflowInstanceWorker$$Lambda$36/1529060733@6f9f0f30, taskType=foo, lockTime=10000, lockOwner=worker-1, capacity=32]: Could not fetch topics
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup.open(EventSubscriberGroup.java:417)
	at io.zeebe.client.task.impl.subscription.TaskSubscriptionBuilderImpl.open(TaskSubscriptionBuilderImpl.java:92)
java.util.concurrent.ExecutionException: io.zeebe.client.cmd.ClientException: Cannot determine leader for partition (timeout 15 seconds). Request was: [ target topic = null, target partition = 0, type = REQUEST_PARTITIONS]. Request receivers: []
	at io.zeebe.workflow.WorkflowInstanceWorker.main(WorkflowInstanceWorker.java:63)
Caused by: java.util.concurrent.ExecutionException: io.zeebe.client.cmd.ClientException: Could not create subscriber group [topic=default-topic, taskHandler=io.zeebe.workflow.WorkflowInstanceWorker$$Lambda$36/1529060733@6f9f0f30, taskType=foo, lockTime=10000, lockOwner=worker-1, capacity=32]: Could not fetch topics
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_162]
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup.open(EventSubscriberGroup.java:413)
	... 2 more
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup$DeterminePartitionsState.determinePartitions(EventSubscriberGroup.java:152) ~[classes/:?]
Caused by: io.zeebe.client.cmd.ClientException: Could not create subscriber group [topic=default-topic, taskHandler=io.zeebe.workflow.WorkflowInstanceWorker$$Lambda$36/1529060733@6f9f0f30, taskType=foo, lockTime=10000, lockOwner=worker-1, capacity=32]: Could not fetch topics
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup$ClosedState.work(EventSubscriberGroup.java:340)
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup$DeterminePartitionsState.doWork(EventSubscriberGroup.java:129) ~[classes/:?]
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup$ClosedState.work(EventSubscriberGroup.java:331)
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup$DeterminePartitionsState.doWork(EventSubscriberGroup.java:114) ~[classes/:?]
	at io.zeebe.util.state.WaitState.doWork(WaitState.java:25)
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:124) ~[classes/:?]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:124)
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53) ~[classes/:?]
	at io.zeebe.util.state.StateMachineAgent.doWork(StateMachineAgent.java:53)
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup.maintainState(EventSubscriberGroup.java:457) ~[classes/:?]
	at io.zeebe.client.task.impl.subscription.EventSubscriberGroup.maintainState(EventSubscriberGroup.java:457)
	at io.zeebe.client.task.impl.subscription.EventSubscribers.lambda$maintainState$3(EventSubscribers.java:156) ~[classes/:?]
	at io.zeebe.client.task.impl.subscription.EventSubscribers.lambda$maintainState$3(EventSubscribers.java:156)
	at io.zeebe.client.task.impl.subscription.EventSubscribers.forAllDo(EventSubscribers.java:167) ~[classes/:?]
	at io.zeebe.client.task.impl.subscription.EventSubscribers.forAllDo(EventSubscribers.java:167)
	at io.zeebe.client.task.impl.subscription.EventSubscribers.maintainState(EventSubscribers.java:156) ~[classes/:?]
	at io.zeebe.client.task.impl.subscription.EventSubscribers.maintainState(EventSubscribers.java:156)
	at io.zeebe.client.task.impl.subscription.EventAcquisition.doWork(EventAcquisition.java:53) ~[classes/:?]
	at io.zeebe.client.task.impl.subscription.EventAcquisition.doWork(EventAcquisition.java:53)
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[classes/:?]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153) ~[classes/:?]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129) ~[classes/:?]
	at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86) ~[classes/:?]
	at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34) [classes/:?]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77) [classes/:?]
	at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.zeebe.client.cmd.ClientException: Cannot determine leader for partition (timeout 15 seconds). Request was: [ target topic = null, target partition = 0, type = REQUEST_PARTITIONS]. Request receivers: []
	at io.zeebe.client.impl.RequestController.generateTimeoutException(RequestController.java:188) ~[classes/:?]
	at io.zeebe.client.impl.RequestController.generateTimeoutException(RequestController.java:182) ~[classes/:?]
	at io.zeebe.client.impl.RequestController$DetermineRemoteState.doWork(RequestController.java:280) ~[classes/:?]
	at io.zeebe.client.impl.RequestController$DetermineRemoteState.doWork(RequestController.java:261) ~[classes/:?]
	at io.zeebe.util.state.StateMachine.doWork(StateMachine.java:124) ~[classes/:?]
	at io.zeebe.client.impl.RequestController.doWork(RequestController.java:167) ~[classes/:?]
	at io.zeebe.client.impl.RequestManager.doWork(RequestManager.java:87) ~[classes/:?]
	at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180) ~[classes/:?]
	at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:160) ~[classes/:?]
	... 5 more
```

**Comment by Zelldon** [comment]
I think we introduced the StatusCodes and Error responses. Clearly we can always improve but I think this issue is outdated
