### ISSUE TITLE
ConcurrentModificationException if running subscription performance test with multiple brokers

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#676]
While running the [SubscriptionTest](https://github.com/zeebe-io/zeebe-cluster-tests/blob/725ea68d87aab90e234ea5aca186c6e864e5e35f/java/src/test/java/io/zeebe/SubscriptionTest.java) on the test cluster I saw the following exception.

```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at io.zeebe.client.task.impl.subscription.TaskSubscriberGroup.poll(TaskSubscriberGroup.java:53)
        at io.zeebe.client.task.impl.subscription.TaskSubscriberGroup.poll(TaskSubscriberGroup.java:46)
        at io.zeebe.client.task.impl.subscription.EventSubscribers.lambda$pollManagedSubscribers$5(EventSubscribers.java:183)
        at io.zeebe.client.task.impl.subscription.EventSubscribers.forAllDo(EventSubscribers.java:167)
        at io.zeebe.client.task.impl.subscription.EventSubscribers.pollManagedSubscribers(EventSubscribers.java:183)
        at io.zeebe.client.task.impl.subscription.SubscriptionExecutor.doWork(SubscriptionExecutor.java:34)
        at io.zeebe.util.actor.ActorRunner.tryRunActor(ActorRunner.java:180)
        at io.zeebe.util.actor.ActorRunner.runActor(ActorRunner.java:153)
        at io.zeebe.util.actor.ActorRunner.doWork(ActorRunner.java:129)
        at io.zeebe.util.actor.ActorRunner.doWorkUntilClose(ActorRunner.java:86)
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:34)
        at io.zeebe.util.actor.ActorRunner.run(ActorRunner.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
If you have an idea how to test this I would be happy to add a test case but wasn't sure how to reproduce this. :disappointed:

**Comment by ThorbenLindhauer** [comment]
Tested here: https://github.com/zeebe-io/zeebe/commit/eaa224e6a54aa98ac910f3f100fb4b8e7a46df22
Will push it with https://github.com/zeebe-io/zeebe/issues/666

**Comment by menski** [comment]
Thanks for the test :+1:
