### ISSUE TITLE
Stabilize gossip test cases

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#712]
After porting the gossip tests to the new actor framework the test became unstable. Ensure that the test suite is stable again.

**Comment by menski** [comment]
The Gossip cluster test in the IT suite fails regularly on my machine and Jenkins

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 29.334 s <<< FAILURE! - in io.zeebe.broker.it.clustering.GossipClusteringTest
[ERROR] shouldRemoveLeaderFromCluster(io.zeebe.broker.it.clustering.GossipClusteringTest)  Time elapsed: 14.623 s  <<< FAILURE!
java.lang.AssertionError:

Expecting:
  <[localhost:31015, localhost:41015, localhost:51015]>
to contain exactly in any order:
  <[localhost:41015, localhost:31015]>
but the following elements were unexpected:
  <[localhost:51015]>

        at io.zeebe.broker.it.clustering.GossipClusteringTest.shouldRemoveLeaderFromCluster(GossipClusteringTest.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zelldon** [comment]
@menski do you have still this issue?

**Comment by menski** [comment]
let's ignore the qa cluster tests for now. there are multiple cluster tests regularly failing. I hope it will get better with the cluster improvements we are planning.

**Comment by Zelldon** [comment]
Ok thanks
