### ISSUE TITLE
NullPointerException while creating topic

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#766]
In the cluster test suite we see a NullPointerException on creating a new topic in a cluster. Felix reported the same issue in his setup on AWS.

```
18:02:59.336 [192.168.0.11:51015-zb-actors-0] ERROR io.zeebe.logstreams - Stream processor 'create-topics' failed to process event. It stop processing further events.
java.lang.NullPointerException: null
        at io.zeebe.transport.SocketAddress.wrap(SocketAddress.java:154) ~[zb-transport-0.8.0-20180321.103832-54.jar:0.8.0-SNAPSHOT]
        at io.zeebe.broker.system.log.RoundRobinSelectionStrategy.selectBrokerForNewPartition(RoundRobinSelectionStrategy.java:47) ~[zeebe-broker-core-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
        at io.zeebe.broker.system.log.CreateTopicProcessor.writeEvent(CreateTopicProcessor.java:99) ~[zeebe-broker-core-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
        at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.writeEvent(TypedStreamProcessor.java:215) ~[zeebe-broker-core-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
        at io.zeebe.logstreams.processor.StreamProcessorController.writeEvent(StreamProcessorController.java:399) ~[zb-logstreams-0.8.0-20180321.074509-36.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:117) [zb-util-0.8.0-20180321.073825-39.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.8.0-20180321.073825-39.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:205) [zb-util-0.8.0-20180321.073825-39.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:172) [zb-util-0.8.0-20180321.073825-39.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:147) [zb-util-0.8.0-20180321.073825-39.jar:0.8.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.8.0-20180321.073825-39.jar:0.8.0-SNAPSHOT]
```

**Comment by menski** [comment]
This happens because the create topic request is received before the gossip API message is received for the cluster member in question. The code does check that the management endpoint is set when choosing the node to create the topic on.
