### ISSUE TITLE
Exception on task subscription close

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#768]
```
15:34:56.894 [0.0.0.0:51015-zb-actors-0] DEBUG io.zeebe.broker.system - Problem on closing LockTaskStreamProcessor.
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:277) ~[classes/:?]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:106) ~[classes/:?]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:22) ~[classes/:?]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:178) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:128) ~[classes/:?]
	at io.zeebe.broker.task.processor.LockTaskStreamProcessor.onClientChannelCloseAsync(LockTaskStreamProcessor.java:159) ~[classes/:?]
	at io.zeebe.broker.task.TaskSubscriptionManager.lambda$onClientChannelCloseAsync$12(TaskSubscriptionManager.java:376) ~[classes/:?]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:145) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:101) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:205) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [classes/:?]
```

**Comment by menski** [comment]
Only saw this happen during test execution yet. Also it seemed to not break anything. So this is low priority.

**Comment by Zelldon** [comment]
Outdated.
