### ISSUE TITLE
Cannot start broker via ./bin/broker

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe#803]
__Environment__

* Zeebe Version: `v0.8.0`
* Operating System: Linux

__Reproduce__

* Download zeebe
* Extract
* Go to extracted directory `$ZEEBE_DIR`
* Execute `./bin/broker`
* Fails, because it tries to load config the config file relative to `$ZEEBE_DIR` rather than `$ZEEBE_DIR/bin` directory:

```plain
~/Downloads/zeebe-broker-0.8.0
❯ ./bin/broker 
11:41:30.246 [main] INFO  io.zeebe.broker.system - Using config file ~/Downloads/zeebe-broker-0.8.0/../conf/zeebe.cfg.toml
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: ../conf/zeebe.cfg.toml (No such file or directory)
        at com.moandjiezana.toml.Toml.read(Toml.java:74)
        at io.zeebe.broker.system.ConfigurationManagerImpl.<init>(ConfigurationManagerImpl.java:50)
        at io.zeebe.broker.system.SystemContext.<init>(SystemContext.java:63)
        at io.zeebe.broker.Broker.<init>(Broker.java:51)
        at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:35)
Caused by: java.io.FileNotFoundException: ../conf/zeebe.cfg.toml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.moandjiezana.toml.Toml.read(Toml.java:72)
        ... 4 more
```

This is related to the fact that the start script tries to resolve the configuration from the current working directory, rather than the bin directory.

__Expected Behavior__

* [ ] I can start the broker via `./bin/zeebe` from the Zeebe home directory

**Comment by meyerdan** [comment]
Fixed with #815
