### ISSUE TITLE
Broker fails to write snapshot

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#845]
I saw this multiple times with Zeebe 0.9.0-SNAPSHOT. Just happens from time to time. Not sure how to reproduce.

```
15:04:27.977 [logstream.internal-system-0.blockIdx.writer] [0.0.0.0:51015-zb-io-actors-1] WARN  io.zeebe.logstreams - Failed to create snapshot of block index logstream.internal-system-0.blockIdx.writer
java.lang.RuntimeException: Cannot write snapshot /home/menski/github/zeebe-io/zeebe/dist/target/zeebe-broker/data/internal-system-0/segments/logstream.internal-system-0.blockIdx.writer-0.snapshot, file already exists.
        at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.createSnapshot(FsSnapshotStorage.java:114) ~[zb-logstreams-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.logstreams.impl.snapshot.fs.FsSnapshotStorage.createSnapshot(FsSnapshotStorage.java:28) ~[zb-logstreams-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.logstreams.impl.LogBlockIndexWriter.createSnapshot(LogBlockIndexWriter.java:328) ~[zb-logstreams-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [zb-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
15:04:29.342 [logstream.POFjQOPJUHQMzzzxtJloEfxPk-6.blockIdx.writer] [0.0.0.0:51015-zb-io-actors-0] INFO  io.zeebe.logstreams - Delete last snapshot file /home/menski/github/zeebe-io/zeebe/dist/target/zeebe-broker/data/POFjQOPJUHQMzzzxtJloEfxPk-6/segments/logstream.POFjQOPJUHQMzzzxtJloEfxPk-6.blockIdx.writer-12886948448.snapshot.
```

**Comment by menski** [comment]
@saig0  please review this issue today as I should be part of the patch release. Thanks
