### ISSUE TITLE
Create default topic using configuration in tests

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#873]
With #835 it is possible to configure the list of topics to create on bootstrap in the configuration file. We should migrate the test rules to not create the topics over a client request but instead use the configuration file.

**Comment by menski** [comment]
It seems that we see on Jenkins now multiple tests fail with `PARTITION_NOT_FOUND` error. For example the `io.zeebe.broker.event.TopicSubscriptionTest.shouldPushEvents` test. I will investigate that.

```
Error Message
Unexpected error response from broker: PARTITION_NOT_FOUND - Cannot execute command. Partition with id '1' not found

Stacktrace
java.lang.RuntimeException: Unexpected error response from broker: PARTITION_NOT_FOUND - Cannot execute command. Partition with id '1' not found
	at io.zeebe.test.broker.protocol.clientapi.ExecuteCommandResponse.wrap(ExecuteCommandResponse.java:102)
	at io.zeebe.test.broker.protocol.clientapi.ExecuteCommandRequest.await(ExecuteCommandRequest.java:107)
	at io.zeebe.test.broker.protocol.clientapi.ExecuteCommandRequestBuilder.sendAndAwait(ExecuteCommandRequestBuilder.java:40)
	at io.zeebe.broker.event.TopicSubscriptionTest.shouldPushEvents(TopicSubscriptionTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

**Comment by menski** [comment]
I added some retry logic to the broker test suite https://github.com/zeebe-io/zeebe/commit/3df0ed3c47fa85fb7edd44bc6cd9a5ca86ab3b1b.

It's not really optimal but solves the problem for now.
