### ISSUE TITLE
Broker fails to reinstall composite cluster orchestration service after replication factor of internal system is lost

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#880]
### Scenario
3 node cluster with an internal system topic and a replication factor 3. After reaching the replication factor one of the follower nodes is restarted.

### Observation
The node is removed from the cluster. The system topic leader removes the partition service as the replication factor is no longer reached. When the node rejoins the replication factor is reached again and the partition service is installed. This triggers also the installation of the composite cluster orchestration service, which fails with the error that this service already exists.

### Log

This behavior can be reproduced with the `GossipClusteringTest`/`GossipDifferentNodeJoinTest` `shouldReAddToCluster` tests.

The log of the system topic leader is similar to

```
12:51:07.395 [172.19.0.3:51016] [172.19.0.3:51015-zb-actors-0] INFO  io.zeebe.gossip - Remove member '172.19.0.4:51016', status = LEAVE, gossip-term: [epoch=1526820647361, heartBeat=2]
12:51:07.396 [172.19.0.3:51016] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Removing Node{clientApi=172.19.0.4:51015, managementApi=172.19.0.4:51016, replicationApi=172.19.0.4:51017} from list of known members
12:51:07.397 [node-selector] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Remove node Node{clientApi=172.19.0.4:51015, managementApi=172.19.0.4:51016, replicationApi=172.19.0.4:51017} from current state.
12:51:07.405 [internal-system-0] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.raft - Member 172.19.0.4:51017 leaving the cluster
12:51:07.406 [internal-system-0] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Removing partition service for Partition{topic=internal-system, partitionId=0, replicationFactor=3}. Replication factor not reached, got 2/3.
12:51:07.408 [deployment] [172.19.0.3:51015-zb-actors-0] INFO  io.zeebe.logstreams - Write snapshot for stream processor deployment at event position 4294967936.
12:51:07.408 [topics] [172.19.0.3:51015-zb-actors-1] INFO  io.zeebe.logstreams - Write snapshot for stream processor topics at event position 4294968216.
12:51:07.420 [topics] [172.19.0.3:51015-zb-actors-1] INFO  io.zeebe.logstreams - Creation of snapshot topics took 12 ms.
12:51:07.421 [id-generator] [172.19.0.3:51015-zb-actors-1] INFO  io.zeebe.logstreams - Write snapshot for stream processor id-generator at event position 4294968104.
12:51:07.422 [id-generator] [172.19.0.3:51015-zb-actors-1] INFO  io.zeebe.logstreams - Creation of snapshot id-generator took 0 ms.
12:51:07.424 [deployment] [172.19.0.3:51015-zb-actors-0] INFO  io.zeebe.logstreams - Creation of snapshot deployment took 17 ms.
12:51:07.428 [internal-system-0] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.raft - Raft event for term 1 was committed on position 4294968912
12:51:09.509 [172.19.0.3:51016] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.gossip - Update member '172.19.0.4:51016', status = ALIVE, gossip-term: [epoch=1526820669365, heartBeat=1]
12:51:09.673 [internal-system-0] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.raft - New member 172.19.0.4:51017 joining the cluster
12:51:09.674 [internal-system-0] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Installing partition service for Partition{topic=internal-system, partitionId=0, replicationFactor=3}. Replication factor reached, got 3/3.
12:51:09.675 [service-controller] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Installing cluster topic state service
12:51:09.698 [service-container-main] [172.19.0.3:51015-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.IllegalStateException: Cannot install service with name 'cluster.orchestration.composite'. Service with same name already exists
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$1(ServiceContainerImpl.java:138) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
12:51:09.713 [service-container-main] [172.19.0.3:51015-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.IllegalStateException: Cannot install service with name 'cluster.orchestration.nodeSelector'. Service with same name already exists
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.lambda$onServiceBuilt$1(ServiceContainerImpl.java:138) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
12:51:09.714 [internal-system-0] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.raft - Raft event for term 1 was committed on position 4294969080
12:51:09.736 [io.zeebe.servicecontainer.CompositeServiceBuilder$CompositeInstallCompletion] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.util.actor - Continuing on future completion failed
java.lang.IllegalStateException: Cannot complete future, the future is already completed exceptionally with 'Could not complete installation of cluster.orchestration.composite: Failed to install cluster.orchestration.nodeSelector'
	at io.zeebe.util.sched.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:227) ~[zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:235) ~[zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.CompositeServiceBuilder$CompositeInstallCompletion.lambda$null$0(CompositeServiceBuilder.java:103) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:41) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
12:51:09.737 [service-container-main] [172.19.0.3:51015-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.RuntimeException: Could not start service cluster.orchestration.knownTopics removed while starting
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.onStarted(ServiceController.java:243) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:213) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:203) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController.onServiceEvent(ServiceController.java:110) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
12:51:09.738 [service-container-main] [172.19.0.3:51015-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to build service
java.lang.RuntimeException: Could not start service cluster.orchestration.idGenerator removed while starting
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.onStarted(ServiceController.java:243) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:213) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController$AwaitStartState.accept(ServiceController.java:203) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceController.onServiceEvent(ServiceController.java:110) ~[zb-service-container-0.10.0-20180515.140017-10.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180515.133943-5.jar:0.10.0-SNAPSHOT]
12:51:09.740 [service-container-main] [172.19.0.3:51015-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to remove service cluster.orchestration.composite: java.lang.IllegalArgumentException: Cannot remove service with name 'cluster.orchestration.composite': no such service registered.
12:51:09.740 [service-container-main] [172.19.0.3:51015-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to remove service cluster.orchestration.composite: java.lang.IllegalArgumentException: Cannot remove service with name 'cluster.orchestration.composite': no such service registered.
12:51:10.035 [topology] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Adding Node{clientApi=172.19.0.4:51015, managementApi=172.19.0.4:51016, replicationApi=172.19.0.4:51017} to list of known members
12:51:10.036 [topology] [172.19.0.3:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=internal-system, partitionId=0, replicationFactor=3} and state FOLLOWER
12:51:10.037 [node-selector] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Add node Node{clientApi=172.19.0.4:51015, managementApi=172.19.0.4:51016, replicationApi=172.19.0.4:51017} to current state.
12:51:10.037 [node-selector] [172.19.0.3:51015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Increased load of node Node{clientApi=172.19.0.4:51015, managementApi=172.19.0.4:51016, replicationApi=172.19.0.4:51017} by partition Partition{topic=internal-system, partitionId=0, replicationFactor=3}
```

**Comment by menski** [comment]
The clustering orchestration services are now removed when the system partition is removed. The ignored tests still fail because of #898
