### ISSUE TITLE
Client runs out of memory in the long running test suite

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#884]
When running the long running test suite on Jenkins the tests fail with an out of memory error message:
```
15:26:14 Running io.zeebe.cluster.LongRunningClusterBrokerTest
15:29:17 Tests run: 8, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 183.632 sec <<< FAILURE! - in io.zeebe.cluster.LongRunningClusterBrokerTest
15:29:17 shouldCreateWorkflowInstancesAsynchronously{ThroughputReporter}  Time elapsed: 31.518 sec  <<< ERROR!
15:29:17 io.zeebe.client.cmd.ClientOutOfMemoryException: Zeebe client is out of buffer memory and cannot make new requests until memory is reclaimed.
15:29:17 	at io.zeebe.client.impl.RequestManager.executeAsync(RequestManager.java:90)
15:29:17 	at io.zeebe.client.impl.RequestManager.send(RequestManager.java:207)
15:29:17 	at io.zeebe.client.impl.CommandImpl.send(CommandImpl.java:34)
15:29:17 	at io.zeebe.client.impl.workflow.CreateWorkflowInstanceCommandImpl.send(CreateWorkflowInstanceCommandImpl.java:31)
15:29:17 	at io.zeebe.LongRunningTest.lambda$createWorkflowInstanceAsync$11(LongRunningTest.java:283)
15:29:17 	at io.zeebe.BenchmarkRunner.executeAsynchronously(BenchmarkRunner.java:242)
15:29:17 	at io.zeebe.LongRunningTest.createWorkflowInstancesAsynchronously(LongRunningTest.java:232)
15:29:17 	at io.zeebe.LongRunningTest.lambda$shouldCreateWorkflowInstancesAsynchronously$5(LongRunningTest.java:129)
15:29:17 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:100)
15:29:17 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:134)
15:29:17 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:29:17 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:29:17 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:29:17 	at java.lang.Thread.run(Thread.java:748)
15:29:17 
15:29:17 shouldCreateStandaloneTasksAsynchronously{ThroughputReporter}  Time elapsed: 30.797 sec  <<< ERROR!
15:29:17 io.zeebe.client.cmd.ClientOutOfMemoryException: Zeebe client is out of buffer memory and cannot make new requests until memory is reclaimed.
15:29:17 	at io.zeebe.client.impl.RequestManager.executeAsync(RequestManager.java:90)
15:29:17 	at io.zeebe.client.impl.RequestManager.send(RequestManager.java:207)
15:29:17 	at io.zeebe.client.impl.CommandImpl.send(CommandImpl.java:34)
15:29:17 	at io.zeebe.client.impl.job.CreateJobCommandImpl.send(CreateJobCommandImpl.java:32)
15:29:17 	at io.zeebe.LongRunningTest.lambda$createJobAsync$8(LongRunningTest.java:258)
15:29:17 	at io.zeebe.BenchmarkRunner.executeAsynchronously(BenchmarkRunner.java:242)
15:29:17 	at io.zeebe.LongRunningTest.createStandaloneTasksAsynchronously(LongRunningTest.java:204)
15:29:17 	at io.zeebe.LongRunningTest.lambda$shouldCreateStandaloneTasksAsynchronously$2(LongRunningTest.java:91)
15:29:17 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:100)
15:29:17 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:134)
15:29:17 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:29:17 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:29:17 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:29:17 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
We will wait for further improvements related to transport before looking into this #858

**Comment by meyerdan** [comment]
Closing this until it reappears
