### ISSUE TITLE
GossipFailureDetectionTest fails

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#890]
This test fails consistently on my machine, apparently not on Jenkins.

Test result:

```
-------------------------------------------------------------------------------
Test set: io.zeebe.gossip.GossipFailureDetectionTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 5.6 s <<< FAILURE! - in io.zeebe.gossip.GossipFailureDetectionTest
shouldSpreadSuspectEvent(io.zeebe.gossip.GossipFailureDetectionTest)  Time elapsed: 1.54 s  <<< FAILURE!
java.lang.AssertionError: condition is not satisfied
	at io.zeebe.gossip.util.GossipClusterRule.waitUntil(GossipClusterRule.java:107)
	at io.zeebe.gossip.GossipFailureDetectionTest.shouldSpreadSuspectEvent(GossipFailureDetectionTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

shouldSpreadConfirmEvent(io.zeebe.gossip.GossipFailureDetectionTest)  Time elapsed: 1.26 s  <<< FAILURE!
java.lang.AssertionError: condition is not satisfied
	at io.zeebe.gossip.util.GossipClusterRule.waitUntil(GossipClusterRule.java:107)
	at io.zeebe.gossip.GossipFailureDetectionTest.shouldSpreadConfirmEvent(GossipFailureDetectionTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

shouldCounterSuspectEventIfAlive(io.zeebe.gossip.GossipFailureDetectionTest)  Time elapsed: 1.37 s  <<< FAILURE!
java.lang.AssertionError: condition is not satisfied
	at io.zeebe.gossip.util.GossipClusterRule.waitUntil(GossipClusterRule.java:107)
	at io.zeebe.gossip.GossipFailureDetectionTest.shouldCounterSuspectEventIfAlive(GossipFailureDetectionTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


```

[io.zeebe.gossip.GossipFailureDetectionTest-output.txt](https://github.com/zeebe-io/zeebe/files/2030960/io.zeebe.gossip.GossipFailureDetectionTest-output.txt)

**Comment by ThorbenLindhauer** [comment]
@saig0 and I did some root cause investigations. Regarding the test `io.zeebe.gossip.GossipFailureDetectionTest.shouldSpreadSuspectEvent()` we found out:

* The test can fail on the line `cluster.waitUntil(() -> gossip1.receivedMembershipEvent(MembershipEventType.SUSPECT, gossip3));`. This seems to be a timing problem, i.e. if we wait a little longer in `GossipClusterRule#waitUntil`, then the test passes this assertion
* The test can fail on the line `assertThat(gossip1.hasMember(gossip3)).isTrue();`. This can happen when the suspected member is already removed from the member list of the gossip. This is the case when the `suspicionTimeout` timeout has expired (see `Gossip#onSuspectMember`). This timeout is 10 seconds in this case. However, time moves faster in our tests, because `GossipClusterRule#waitUntil` adds the probe interval (1 second here) on each iteration. In consequence, the suspicion timeout expires after 100 millisconds in this test case which can be too soon.

**Comment by menski** [comment]
Still sometimes failing on jenkins

```
06:45:10 [ERROR] shouldInvokeCustomEventListenersFailsafe(io.zeebe.gossip.CustomEventTest)  Time elapsed: 10.003 s  <<< ERROR!
06:45:10 org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
06:45:10 	at sun.misc.Unsafe.park(Native Method)
06:45:10 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
06:45:10 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
06:45:10 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:144)
06:45:10 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:118)
06:45:10 	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:28)
06:45:10 	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:224)
06:45:10 	at io.zeebe.transport.ServerTransport.close(ServerTransport.java:63)
06:45:10 	at io.zeebe.gossip.util.GossipRule.after(GossipRule.java:160)
06:45:10 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
06:45:10 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
06:45:10 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
06:45:10 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
06:45:10 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
06:45:10 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06:45:10 	at java.lang.Thread.run(Thread.java:748)
06:45:10 

10:47:05 [ERROR] shouldInvokeCustomEventListenerOfAllNodes(io.zeebe.gossip.CustomEventTest)  Time elapsed: 10.003 s  <<< ERROR!
10:47:05 org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
10:47:05 	at sun.misc.Unsafe.park(Native Method)
10:47:05 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
10:47:05 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
10:47:05 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:144)
10:47:05 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:118)
10:47:05 	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:28)
10:47:05 	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:224)
10:47:05 	at io.zeebe.transport.ServerTransport.close(ServerTransport.java:63)
10:47:05 	at io.zeebe.gossip.util.GossipRule.after(GossipRule.java:160)
10:47:05 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
10:47:05 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
10:47:05 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
10:47:05 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
10:47:05 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
10:47:05 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:47:05 	at java.lang.Thread.run(Thread.java:748)
10:47:05 
10:47:05 [ERROR] shouldSpreadCustomEvent(io.zeebe.gossip.CustomEventTest)  Time elapsed: 10 s  <<< ERROR!
10:47:05 org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
10:47:05 	at sun.misc.Unsafe.park(Native Method)
10:47:05 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
10:47:05 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
10:47:05 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:144)
10:47:05 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:118)
10:47:05 	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:28)
10:47:05 	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:224)
10:47:05 	at io.zeebe.transport.ServerTransport.close(ServerTransport.java:63)
10:47:05 	at io.zeebe.gossip.util.GossipRule.after(GossipRule.java:160)
10:47:05 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
10:47:05 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
10:47:05 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
10:47:05 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
10:47:05 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
10:47:05 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:47:05 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by menski** [comment]
We will replace the gossip module
