### ISSUE TITLE
Exceptions after job-activating stream processor is closed

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#906]
```
09:02:27.702 [jobqueue.subscription.manager] [0.0.0.0:51015-zb-actors-1] DEBUG io.zeebe.broker.system - Problem on closing job activating stream processor.
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:269) ~[zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:106) ~[zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:22) ~[zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:181) ~[zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:141) ~[zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.broker.job.processor.ActivateJobStreamProcessor.onClientChannelCloseAsync(ActivateJobStreamProcessor.java:154) ~[zeebe-broker-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
	at io.zeebe.broker.job.JobSubscriptionManager.lambda$onClientChannelCloseAsync$11(JobSubscriptionManager.java:372) ~[zeebe-broker-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:158) ~[zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:95) [zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180524.114536-8.jar:0.10.0-SNAPSHOT]
```

Happens in the Go client test suite regularly. See log file below.

[OMG_STACKOVERFLOW_.log](https://github.com/zeebe-io/zeebe/files/2047997/OMG_STACKOVERFLOW_.log)

**Comment by ThorbenLindhauer** [comment]
One of the reasons this may occur is that the `JobSubscriptionManager` keeps the job subscriptions and stream processors referenced when they should be removed on client connection loss. If this happens a second time, the manager may attempt to close the stream processor a second time which fails. There are also a couple of other race conditions possible that would cause this problem due to the asynchronous coupling of manager and stream processors.

**Comment by menski** [comment]
@Zelldon please review this issue today as I should be part of the patch release. Thanks

**Comment by Zelldon** [comment]
# Review
 ### ActivateJobStreamProcessor 
 * A bit unrelated to the issue but in  `#addSubscription` we throwing an runtime exception instead of complete exceptionally, perhaps we can change this.

 ### JobSubscriptionManager
 * #removeSubscription we get here a NPE if called twice or if the id does not exist
 * #stopStreamProcessor returned future is never used - we can simplify the method
  
 ### Subscriptions 
  * As discussed remove the comment (is a left over)
  * Perhaps we can move this in own file
