### ISSUE TITLE
Improve deployment rejection messages

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#912]
A BPMN deployment can fail due to an exception thrown by the BPMN model API (e.g. content is not XML). In this case, the broker sends back the exception's stacktrace as the rejection reason. In the Java client, we use that reason to build the message of the `ClientCommandRejectedException` that the user receives. 

Logging this exception results in quite a mess where both stacktraces are mixed, see example below. The broker-side stacktrace is also mostly not relevant to the client. The root exception message(s) are. We could try to improve the model API such that it collects failure reasons better.

```
io.zeebe.client.cmd.ClientCommandRejectedException: Command (CREATE) was rejected. It has an invalid value. Failed to deploy resource 'invalid.bpmn':
java.lang.RuntimeException: Failed to read BPMN model
	at io.zeebe.model.bpmn.impl.BpmnParser.readFromStream(BpmnParser.java:98)
	at io.zeebe.model.bpmn.BpmnModelApi.readFromXmlStream(BpmnModelApi.java:53)
	at io.zeebe.model.bpmn.BpmnModelApi.readFromXmlBuffer(BpmnModelApi.java:64)
	at io.zeebe.broker.system.workflow.repository.processor.DeploymentCreateEventProcessor.readWorkflowDefinition(DeploymentCreateEventProcessor.java:180)
	at io.zeebe.broker.system.workflow.repository.processor.DeploymentCreateEventProcessor.readAndValidateWorkflows(DeploymentCreateEventProcessor.java:121)
	at io.zeebe.broker.system.workflow.repository.processor.DeploymentCreateEventProcessor.processRecord(DeploymentCreateEventProcessor.java:62)
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:38)
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:183)
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:361)
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:338)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content ist nicht zulässig in Prolog.]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:470)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371)
	at io.zeebe.model.bpmn.impl.BpmnParser.readFromStream(BpmnParser.java:92)
	... 15 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content ist nicht zulässig in Prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:149)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400)
	... 17 more

	at io.zeebe.client.cmd.ClientCommandRejectedException.newInCurrentContext(ClientCommandRejectedException.java:40)
	at io.zeebe.client.impl.RequestManager$ResponseFuture.join(RequestManager.java:482)
	at io.zeebe.broker.it.workflow.CreateDeploymentTest.shouldNotDeployUnparsableModel(CreateDeploymentTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: io.zeebe.client.cmd.ClientCommandRejectedException: Command (CREATE) was rejected. It has an invalid value. Failed to deploy resource 'invalid.bpmn':
java.lang.RuntimeException: Failed to read BPMN model
	at io.zeebe.model.bpmn.impl.BpmnParser.readFromStream(BpmnParser.java:98)
	at io.zeebe.model.bpmn.BpmnModelApi.readFromXmlStream(BpmnModelApi.java:53)
	at io.zeebe.model.bpmn.BpmnModelApi.readFromXmlBuffer(BpmnModelApi.java:64)
	at io.zeebe.broker.system.workflow.repository.processor.DeploymentCreateEventProcessor.readWorkflowDefinition(DeploymentCreateEventProcessor.java:180)
	at io.zeebe.broker.system.workflow.repository.processor.DeploymentCreateEventProcessor.readAndValidateWorkflows(DeploymentCreateEventProcessor.java:121)
	at io.zeebe.broker.system.workflow.repository.processor.DeploymentCreateEventProcessor.processRecord(DeploymentCreateEventProcessor.java:62)
	at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:38)
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:183)
	at io.zeebe.logstreams.processor.StreamProcessorController.processEvent(StreamProcessorController.java:361)
	at io.zeebe.logstreams.processor.StreamProcessorController.readNextEvent(StreamProcessorController.java:338)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content ist nicht zulässig in Prolog.]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:470)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371)
	at io.zeebe.model.bpmn.impl.BpmnParser.readFromStream(BpmnParser.java:92)
	... 15 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content ist nicht zulässig in Prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:149)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400)
	... 17 more

	at io.zeebe.client.impl.CommandRequestHandler.getResult(CommandRequestHandler.java:162)
	at io.zeebe.client.impl.CommandRequestHandler.getResult(CommandRequestHandler.java:1)
	at io.zeebe.client.impl.RequestManager$ResponseFuture.handleExpectedResponse(RequestManager.java:383)
	at io.zeebe.client.impl.RequestManager$ResponseFuture.ensureResponseAvailable(RequestManager.java:315)
	at io.zeebe.client.impl.RequestManager$ResponseFuture.get(RequestManager.java:438)
	at io.zeebe.client.impl.RequestManager$ResponseFuture.get(RequestManager.java:427)
	at io.zeebe.client.impl.RequestManager$ResponseFuture.join(RequestManager.java:473)
	... 29 more
```

**Comment by menski** [comment]
I thinks this is fine with the current state, example exception for an invalid workflow:

```
Exception in thread "main" io.zeebe.client.cmd.ClientException: Command (CREATE) was rejected. It has an invalid value. Resource '/home/menski/github/menski/the-life-of-a-workflow/sum.bpmn':
- Element: sum > extensionElements > taskDefinition
    - ERROR: Task type must be present and not empty
- Element: definitions
    - ERROR: Must contain at least one executable process

  at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
  at io.zeebe.example.workflow.WorkflowDeployer.main(WorkflowDeployer.java:39)
```
