### ISSUE TITLE
Zeebe tries to create a partition multiple times

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#913]
### Scenario

12 nodes and create topic with 48 partitions and replication factor 3

### Log

```
10:19:12.631 [ec2-18-184-135-23.eu-central-1.compute.amazonaws.com:51015-zb-actors-3] ERROR io.zeebe.broker.clustering - Exception while creating partition
java.lang.RuntimeException: Partition with with 13 already exists
        at io.zeebe.broker.clustering.base.raft.RaftPersistentConfigurationManager.lambda$createConfiguration$3(RaftPersistentConfigurationManager.java:108) ~[zeebe-broker-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
10:19:20.753 [ec2-18-184-135-23.eu-central-1.compute.amazonaws.com:51015-zb-actors-2] ERROR io.zeebe.broker.clustering - Exception while creating partition
java.lang.RuntimeException: Partition with with 1 already exists
        at io.zeebe.broker.clustering.base.raft.RaftPersistentConfigurationManager.lambda$createConfiguration$3(RaftPersistentConfigurationManager.java:108) ~[zeebe-broker-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
```

**Comment by menski** [comment]
I can reproduce something similar if I have a 3 node cluster and create a topic with a single partition and replication factor 3.

If I send restart one node which is follower for all topics I get the following exception in the log:

```
13:31:35.479 [main] INFO  io.zeebe.broker.system - Using configuration file /home/menski/github/zeebe-io/zeebe/qa/integration-tests/src/test/resources/zeebe.cluster.2.cfg.toml
13:31:35.542 [main] DEBUG io.zeebe.broker.system - Initializing configuration with base path /tmp/cluster2
13:31:35.602 [main] INFO  io.zeebe.broker.system - Scheduler configuration: Threads{cpu-bound: 2, io-bound: 2}.
13:31:35.667 [main] INFO  io.zeebe.broker.system - Version: development
13:31:35.692 [0.0.0.0:41015-zb-actors-1] DEBUG io.zeebe.broker.system - Writing metrics to file /tmp/cluster2/metrics/zeebe.prom. Reporting interval 5s.
13:31:35.722 [main] INFO  io.zeebe.broker.clustering - Starting clustered broker.
13:31:35.730 [0.0.0.0:41015-zb-actors-1] INFO  io.zeebe.broker.transport - Bound managementApi.server to /0.0.0.0:41016
13:31:35.752 [0.0.0.0:41015-zb-actors-1] INFO  io.zeebe.transport - Bound replicationApi.server to /0.0.0.0:41017
13:31:35.760 [0.0.0.0:41015-zb-actors-0] INFO  io.zeebe.transport - Bound clientApi.server to /0.0.0.0:41015
13:31:35.790 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Adding Node{clientApi=0.0.0.0:41015, managementApi=0.0.0.0:41016, replicationApi=0.0.0.0:41017} to list of known members
13:31:35.916 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.gossip - Received SYNC response.
13:31:35.916 [0.0.0.0:41015-zb-actors-0] INFO  io.zeebe.gossip - Add member '0.0.0.0:51016' with status ALIVE, gossip-term: [epoch=1527766219844, heartBeat=0]
13:31:35.917 [0.0.0.0:41015-zb-actors-0] INFO  io.zeebe.gossip - Add member '0.0.0.0:31016' with status ALIVE, gossip-term: [epoch=1527766222442, heartBeat=1]
13:31:35.919 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.gossip - Joined cluster successfully
13:31:35.919 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Adding Node{clientApi=0.0.0.0:51015, managementApi=0.0.0.0:51016, replicationApi=0.0.0.0:51017} to list of known members
13:31:35.920 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Adding Node{clientApi=0.0.0.0:31015, managementApi=0.0.0.0:31016, replicationApi=0.0.0.0:31017} to list of known members
13:31:35.921 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=internal-system, partitionId=0, replicationFactor=3} and state LEADER
13:31:35.922 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=foo, partitionId=1, replicationFactor=3} and state FOLLOWER
13:31:35.922 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=foo, partitionId=1, replicationFactor=3} and state LEADER
13:31:35.922 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=internal-system, partitionId=0, replicationFactor=3} and state FOLLOWER
13:31:36.008 [0.0.0.0:41015-zb-actors-0] INFO  io.zeebe.raft - Created raft with configuration: RaftConfiguration{heartbeatIntervalMs=250ms, electionIntervalMs=1s}
13:31:36.008 [0.0.0.0:41015-zb-actors-1] INFO  io.zeebe.raft - Created raft with configuration: RaftConfiguration{heartbeatIntervalMs=250ms, electionIntervalMs=1s}
13:31:36.041 [0.0.0.0:41015-zb-actors-1] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=1} from state null
13:31:36.041 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_FOLLOWER, term=1} from state null
13:31:36.084 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=internal-system, partitionId=0, replicationFactor=3} and state null
13:31:36.084 [0.0.0.0:41015-zb-actors-1] DEBUG io.zeebe.raft - Send join configuration request to RemoteAddress{streamId=2, addr=0.0.0.0:31017}
13:31:36.085 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=foo, partitionId=1, replicationFactor=3} and state null
13:31:36.085 [0.0.0.0:41015-zb-actors-0] DEBUG io.zeebe.raft - Send join configuration request to RemoteAddress{streamId=1, addr=0.0.0.0:51017}
13:31:36.086 [0.0.0.0:41015-zb-io-actors-1] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 1
13:31:36.086 [0.0.0.0:41015-zb-io-actors-0] DEBUG io.zeebe.raft - Transitioned to state FOLLOWER in term 1
13:31:36.087 [0.0.0.0:41015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=foo, partitionId=1, replicationFactor=3} and state FOLLOWER
13:31:36.088 [0.0.0.0:41015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Updating partition information for partition Partition{topic=internal-system, partitionId=0, replicationFactor=3} and state FOLLOWER
13:31:36.103 [0.0.0.0:41015-zb-io-actors-1] DEBUG io.zeebe.raft - Configuration request was accepted in term 1
13:31:36.103 [0.0.0.0:41015-zb-io-actors-1] INFO  io.zeebe.raft - Joined raft in term 1
13:31:36.109 [0.0.0.0:41015-zb-io-actors-1] DEBUG io.zeebe.raft - Configuration request was accepted in term 1
13:31:36.109 [0.0.0.0:41015-zb-io-actors-1] INFO  io.zeebe.raft - Joined raft in term 1
13:31:37.119 [0.0.0.0:41015-zb-actors-0] ERROR io.zeebe.broker.clustering - Exception while creating partition
java.lang.RuntimeException: Partition with with 0 already exists
	at io.zeebe.broker.clustering.base.raft.RaftPersistentConfigurationManager.lambda$createConfiguration$3(RaftPersistentConfigurationManager.java:108) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [classes/:?]
```

**Comment by menski** [comment]
Seems that the topic creation just takes longer then our check interval is configured so we send the invitation request multiple times. Which is not a real problem imo.

node 192.168.0.11:
```
[camunda@cam-int-1 logs]$ ag "send.*partitionid=36"
zeebe.log:133:11:50:34.617 [create-topic] [192.168.0.11:51015-zb-actors-1] DEBUG io.zeebe.broker.clustering - Send create partition request for topic foo to node 192.168.0.11:51016 with partitionId=36
zeebe.log:527:11:50:34.848 [replication-reviser] [192.168.0.11:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Send invite request for partition Partition{topic=foo, partitionId=36, replicationFactor=3} to node 192.168.0.31:51016
zeebe.log:528:11:50:34.849 [replication-reviser] [192.168.0.11:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Send invite request for partition Partition{topic=foo, partitionId=36, replicationFactor=3} to node 192.168.0.21:51016
zeebe.log:3267:11:51:05.509 [replication-reviser] [192.168.0.11:51015-zb-actors-0] DEBUG io.zeebe.broker.clustering - Send invite request for partition Partition{topic=foo, partitionId=36, replicationFactor=3} to node 192.168.0.31:51016
```

node 192.168.0.31:
```
[camunda@cam-int-3 logs]$ ag "rec.*partitionid=36" 
zeebe.log:35:11:50:34.851 [io.zeebe.broker.clustering.api.ManagementApiRequestHandlerService] [192.168.0.31:51015-zb-actors-1] INFO  io.zeebe.broker.clustering - Received invitation request for topicName=foo, partitionId=36, replicationFactor=3 with members=[192.168.0.11:51017]
zeebe.log:2326:11:51:05.510 [io.zeebe.broker.clustering.api.ManagementApiRequestHandlerService] [192.168.0.31:51015-zb-actors-0] INFO  io.zeebe.broker.clustering - Received invitation request for topicName=foo, partitionId=36, replicationFactor=3 with members=[192.168.0.11:51017, 192.168.0.21:51017]
```
