### ISSUE TITLE
Possible Null Pointer Exception in gossip join controller

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#914]
```
09:14:47.729 [ec2-18-184-135-23.eu-central-1.compute.amazonaws.com:51015-zb-actors-2] DEBUG io.zeebe.util.actor - Continuing on future completion failed
java.lang.NullPointerException: null
       at io.zeebe.gossip.failuredetection.JoinController.lambda$sendSyncRequest$2(JoinController.java:168) ~[zb-gossip-0.10.0-20180529.125538-33.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:41) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
       at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180528.142631-10.jar:0.10.0-SNAPSHOT]
```

**Comment by menski** [comment]
We will replace the gossip module
