### ISSUE TITLE
Segfault and index out of bounds read when creating a lot of partitions

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#915]
### Scenario

- 3 Node dev cluster on localhost
- Creating topic `foo` with 48 partitions and replication factor 3

### Observation

One node generates a index out of bounds exception when reading the fragment length after a segfault

```
13:38:01.625 [0.0.0.0:31015-zb-io-actors-0] DEBUG io.zeebe.raft - Received message with higher term 1 > 0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f694d8d3877, pid=2884, tid=0x00007f6912974700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.172-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x81877]13:38:01.628 [0.0.0.0:31015-zb-io-actors-1] DEBUG io.zeebe.raft - Configuration request was accepted in term 1
13:38:01.629 [0.0.0.0:31015-zb-io-actors-1] INFO  io.zeebe.raft - Joined raft in term 1
13:38:01.629 [0.0.0.0:31015-zb-io-actors-1] DEBUG io.zeebe.raft - Configuration request was accepted in term 1
13:38:01.629 [0.0.0.0:31015-zb-io-actors-1] INFO  io.zeebe.raft - Joined raft in term 1
13:38:01.626 [0.0.0.0:31015-zb-io-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.IndexOutOfBoundsException: index=-671088512 length=4 capacity=1024
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1340) ~[agrona-0.9.13.jar:0.9.13]
	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:503) ~[agrona-0.9.13.jar:0.9.13]
	at io.zeebe.logstreams.impl.LogEntryDescriptor.getFragmentLength(LogEntryDescriptor.java:121) ~[classes/:?]
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.calculateCorrectReadResult(CompleteEventsInBlockProcessor.java:79) ~[classes/:?]
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.process(CompleteEventsInBlockProcessor.java:51) ~[classes/:?]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:256) ~[classes/:?]
	at io.zeebe.logstreams.impl.LogBlockIndexWriter.readLogStorage(LogBlockIndexWriter.java:224) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [classes/:?]
13:38:01.632 [0.0.0.0:31015-zb-actors-0] INFO  io.zeebe.raft - Created raft with configuration: RaftConfiguration{heartbeatIntervalMs=250ms, electionIntervalMs=1s}
13:38:01.633 [0.0.0.0:31015-zb-actors-0] DEBUG io.zeebe.util.actor - Continuing on future completion failed
java.lang.IndexOutOfBoundsException: index=-671088408 length=4 capacity=32768
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1340) ~[agrona-0.9.13.jar:0.9.13]
	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:503) ~[agrona-0.9.13.jar:0.9.13]
	at io.zeebe.logstreams.impl.LogEntryDescriptor.getFragmentLength(LogEntryDescriptor.java:121) ~[classes/:?]
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.calculateCorrectReadResult(CompleteEventsInBlockProcessor.java:79) ~[classes/:?]
	at io.zeebe.logstreams.impl.CompleteEventsInBlockProcessor.process(CompleteEventsInBlockProcessor.java:51) ~[classes/:?]
	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.read(FsLogStorage.java:256) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.readBlockIntoBuffer(BufferedLogStreamReader.java:330) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:140) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(BufferedLogStreamReader.java:116) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(BufferedLogStreamReader.java:98) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(BufferedLogStreamReader.java:91) ~[classes/:?]
	at io.zeebe.logstreams.log.BufferedLogStreamReader.<init>(BufferedLogStreamReader.java:85) ~[classes/:?]
	at io.zeebe.raft.BufferedLogStorageAppender.<init>(BufferedLogStorageAppender.java:72) ~[classes/:?]
	at io.zeebe.raft.state.AbstractRaftState.<init>(AbstractRaftState.java:69) ~[classes/:?]
	at io.zeebe.raft.state.FollowerState.<init>(FollowerState.java:29) ~[classes/:?]
	at io.zeebe.raft.Raft.transitionToFollower(Raft.java:171) ~[classes/:?]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:41) [classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [classes/:?]
```

**Comment by menski** [comment]
Following the stack of the segfault in a docker container with alpine == libmusl:

```Stack: [0x00007fc54d531000,0x00007fc54d631aa8],  sp=0x00007fc54d630b18,  free space=1022k                                                                                                               
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)                                                                                                                         
C  [ld-musl-x86_64.so.1+0x237f6]  __expand_heap+0x1b8                                                                                                                                                   
                                                                                                                                                                                                        
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)                                                                                                                                          
j  sun.misc.Unsafe.allocateMemory(J)J+0                                                                                                                                                                 
j  java.nio.DirectByteBuffer.<init>(I)V+49                                                                                                                                                              
j  java.nio.ByteBuffer.allocateDirect(I)Ljava/nio/ByteBuffer;+5                                                                                                                                         
j  io.zeebe.util.allocation.DirectBufferAllocator.allocate(I)Lio/zeebe/util/allocation/AllocatedBuffer;+5                                                                                               
j  io.zeebe.logstreams.log.BufferedLogStreamReader.allocateBuffer(I)V+40                                                                                                                                
j  io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(Lio/zeebe/logstreams/spi/LogStorage;Lio/zeebe/logstreams/impl/log/index/LogBlockIndex;J)V+20                                                    
j  io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(Lio/zeebe/logstreams/log/LogStream;J)V+19                                                                                                       
j  io.zeebe.logstreams.log.BufferedLogStreamReader.wrap(Lio/zeebe/logstreams/log/LogStream;)V+5                                                                                                         
j  io.zeebe.logstreams.log.BufferedLogStreamReader.<init>(Lio/zeebe/logstreams/log/LogStream;Z)V+7                                                                                                      
j  io.zeebe.raft.state.AbstractRaftState.<init>(Lio/zeebe/raft/Raft;Lio/zeebe/util/sched/ActorControl;)V+164                                                                                            
j  io.zeebe.raft.state.FollowerState.<init>(Lio/zeebe/raft/Raft;Lio/zeebe/util/sched/ActorControl;)V+3                                                                                                  
j  io.zeebe.raft.Raft.transitionToFollower(Ljava/lang/Void;Ljava/lang/Throwable;)V+37                                                                                                                   
j  io.zeebe.raft.Raft$$Lambda$176.accept(Ljava/lang/Object;Ljava/lang/Object;)V+12                                                                                                                      
J 2169 C1 io.zeebe.util.sched.future.FutureContinuationRunnable.run()V (71 bytes) @ 0x00007fc55e574fdc [0x00007fc55e574ce0+0x2fc]                                                                       
J 2377 C2 io.zeebe.util.sched.ActorJob.execute(Lio/zeebe/util/sched/ActorThread;)V (211 bytes) @ 0x00007fc55e585cb4 [0x00007fc55e585ba0+0x114]                                                          
J 1257 C1 io.zeebe.util.sched.ActorTask.execute(Lio/zeebe/util/sched/ActorThread;)Z (183 bytes) @ 0x00007fc55e3141dc [0x00007fc55e313fa0+0x23c]                                                         
J 2445 C1 io.zeebe.util.sched.ActorThread.executeCurrentTask()V (293 bytes) @ 0x00007fc55e58a92c [0x00007fc55e58a5c0+0x36c]                                                                             
J 2419 C1 io.zeebe.util.sched.ActorThread.doWork()V (103 bytes) @ 0x00007fc55e2621ac [0x00007fc55e261b00+0x6ac]                                                                                         
J 1956% C2 io.zeebe.util.sched.ActorThread.run()V (56 bytes) @ 0x00007fc55e52185c [0x00007fc55e5217c0+0x9c]                                                                                             
v  ~StubRoutines::call_stub        
```

**Comment by menski** [comment]
can reproduce anymore
