### ISSUE TITLE
Negative capacity in log block index writer

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#918]
While playing with the test cluster and creating a topic with 48 partitions and replication 3 I saw once this exception in one of the brokers:

```
13:19:09.277 [logstream.foo-33.blockIdx.writer] [192.168.0.21:51015-zb-io-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.IllegalArgumentException: Negative capacity: -2147483648
        at java.nio.Buffer.<init>(Buffer.java:199) ~[?:1.8.0_161]
        at java.nio.ByteBuffer.<init>(ByteBuffer.java:281) ~[?:1.8.0_161]
        at java.nio.ByteBuffer.<init>(ByteBuffer.java:289) ~[?:1.8.0_161]
        at java.nio.MappedByteBuffer.<init>(MappedByteBuffer.java:89) ~[?:1.8.0_161]
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:119) ~[?:1.8.0_161]
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_161]
        at io.zeebe.util.allocation.DirectBufferAllocator.allocate(DirectBufferAllocator.java:28) ~[zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.allocation.BufferAllocators.allocateDirect(BufferAllocators.java:26) ~[zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.logstreams.impl.LogBlockIndexWriter.increaseBufferSize(LogBlockIndexWriter.java:313) ~[zb-logstreams-0.10.0-20180531.130522-27.jar:0.10.0-SNAPSHOT]
        at io.zeebe.logstreams.impl.LogBlockIndexWriter.readLogStorage(LogBlockIndexWriter.java:234) ~[zb-logstreams-0.10.0-20180531.130522-27.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) ~[zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.10.0-20180531.125127-12.jar:0.10.0-SNAPSHOT]
```

**Comment by Zelldon** [comment]
We remove the LogBlockIndex with https://github.com/zeebe-io/zeebe/pull/2711
