### ISSUE TITLE
Reprocessing exception when opening second job subscriber

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#925]
`io.zeebe.broker.workflow.WorkflowInstanceFunctionalTest#shouldCreateAndCompleteInstanceOfYamlWorkflow` contains these lines:

```
        testClient.completeJobOfType("foo");
        testClient.completeJobOfType("bar");
```

The second line fails repeatedly. This method invocation opens a job subscription for the given type. Currently this succeds but the corresponding stream processor fails reprocessing with the following stacktrace:

```
java.lang.IllegalStateException: Stream processor 'job-activate.bar' failed to reprocess. Cannot find source event position: 4294968968
	at io.zeebe.logstreams.processor.StreamProcessorController.reprocessNextEvent(StreamProcessorController.java:233) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:111) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [classes/:?]
```

It could be that the job activating stream processor interfere each other during reprocessing.

via @Zelldon

**Comment by ThorbenLindhauer** [comment]
I split this into #926 and #927. #926 is the cause for the stack trace in the log. #927 is the reason why the test fails.
