### ISSUE TITLE
Race condition on recovery between deployment and workflow instance stream processor 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#929]
### Scenario

1. deploy a workflow
2. start an instance of that workflow
3. restart the broker with deleting the snapshots

### Observation

When the workflow instance stream processor does reprocessing it has to fetch the workflow definition again from the `internal-system` topic. If the deployment stream processor was not fast enough in reprocessing the workflow might not yet known in the state and the response of the request handler is basically empty. The workflow instance stream processor does not check for this condition and a null pointer is thrown when accessing the fetch workflow.

**Note:** this race condition is probably also possible in other scenarios, which we should also handle correctly.

### Test

We see this happening often in the `BrokerRecoveryTest` locally and on Jenkins.

### Exception

```
java.lang.RuntimeException: Error while processing fetched workflow
	at io.zeebe.broker.workflow.processor.WorkflowInstanceStreamProcessor.lambda$fetchWorkflow$10(WorkflowInstanceStreamProcessor.java:1089) ~[zeebe-broker-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:41) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:116) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:60) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:193) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:173) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:148) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:119) [zb-util-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
Caused by: java.lang.NullPointerException
	at io.zeebe.broker.workflow.processor.WorkflowInstanceStreamProcessor$FlowElementEventProcessor.resolveCurrentFlowNode(WorkflowInstanceStreamProcessor.java:1121) ~[zeebe-broker-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.zeebe.broker.workflow.processor.WorkflowInstanceStreamProcessor.lambda$fetchWorkflow$10(WorkflowInstanceStreamProcessor.java:1083) ~[zeebe-broker-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	... 7 more
```

**Comment by ThorbenLindhauer** [comment]
Which response is sent under which circumstances?

* deployment stream processor is not opened (i.e. request handler not registered)
  => NotLeaderResponse
* deployment stream processor has workflow available
  => non-empty FetchWorkflowResponse
* deployment stream processor has workflow not available (e.g. workflow does not exist; deployment stream processor has not reprocessed log; deployment stream processor has not yet processed deployment)
  => empty FetchWorkflowResponse
  
How does the requesting WorkflowInstanceStreamProcessor handle the response?

* non-empty FetchWorkflowResponse
  => all fine, stream processor continues
* empty FetchWorkflowResponse
  * on workflow instance creation
    => instance creation request is rejected
  * on workflow instance processing
    => NullPointerException
* any other response (e.g. NotLeaderResponse)
  => retry request until success or request timeout
* request timeout (30 seconds) (or any other transport exception)
  => stream processor is closed
