### ISSUE TITLE
JobTimeOutStreamProcessorTest#shouldTimeOutIfAfterDeadlineForTwoJobs is unstable

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#941]
The test fails sometime on my machine.

```java
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.018 s <<< FAILURE! - in io.zeebe.broker.job.processor.JobTimeOutStreamProcessorTest
[ERROR] shouldTimeOutIfAfterDeadlineForTwoJobs(io.zeebe.broker.job.processor.JobTimeOutStreamProcessorTest)  Time elapsed: 10.015 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:96)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:74)
        at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:45)
        at io.zeebe.broker.job.processor.JobTimeOutStreamProcessorTest.shouldTimeOutIfAfterDeadlineForTwoJobs(JobTimeOutStreamProcessorTest.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

```

**Comment by menski** [comment]
Did that happen on master? We already iterated multiple times over this test case.

**Comment by Zelldon** [comment]
Yes, locally. I tried it just now three times until it failed again.

**Comment by menski** [comment]
I tried to reproduce this locally but even after 10 minutes in a loop the test didn't failed once. Did you only run this test alone when it failed or the whole test suite?

**Comment by Zelldon** [comment]
Yes `[zeebe/broker-core]$ mvn clean install`. Failed for me again after I tried it once :sweat_smile:

**Comment by Zelldon** [comment]
Add new branch on master and logstream which contains the print lines.

**Comment by Zelldon** [comment]
Should be fixed now. The problem was that it could happen that the consumer in the TestStreams was registered to late and that's why the commit position was not set.
