### ISSUE TITLE
Test case shouldNotReplicateLogBlockIndex in SnapshotReplicationTest unstable

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#953]
If I run the SnapshotReplicationTest in a loop sometimes the test case shouldNotReplicateLogBlockIndex fails. I didn't looked further into it.

```
menski@bork ~/github/zeebe-io/zeebe/qa/integration-tests
$ while [ $? -eq 0 ]; do mvn clean test -Dtest=SnapshotReplicationTest; done
```

```
[INFO] Running io.zeebe.broker.it.clustering.SnapshotReplicationTest
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 33.825 s <<< FAILURE! - in io.zeebe.broker.it.clustering.SnapshotReplicationTest                                              
[ERROR] shouldNotReplicateLogBlockIndex(io.zeebe.broker.it.clustering.SnapshotReplicationTest)  Time elapsed: 13.492 s  <<< FAILURE!                                                                  
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                                                      
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                                                               
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                       
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:96)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:69)
        at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:41)
        at io.zeebe.broker.it.clustering.SnapshotReplicationTest.waitForReplication(SnapshotReplicationTest.java:250)
        at io.zeebe.broker.it.clustering.SnapshotReplicationTest.shouldNotReplicateLogBlockIndex(SnapshotReplicationTest.java:198)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

[io.zeebe.broker.it.clustering.SnapshotReplicationTest-output.txt](https://github.com/zeebe-io/zeebe/files/2114206/io.zeebe.broker.it.clustering.SnapshotReplicationTest-output.txt)

**Comment by menski** [comment]
Seems to happen with different test cases in this class.

```
[INFO] Running io.zeebe.broker.it.clustering.SnapshotReplicationTest
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 34.696 s <<< FAILURE! - in io.zeebe.broker.it.clustering.SnapshotReplicationTest                                              
[ERROR] shouldReplicateNewerSnapshotAndRemoveOlderOne(io.zeebe.broker.it.clustering.SnapshotReplicationTest)  Time elapsed: 15.03 s  <<< FAILURE!                                                     
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                                                      
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                                                               
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                       
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:96)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:69)
        at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:41)
        at io.zeebe.broker.it.clustering.SnapshotReplicationTest.waitForReplication(SnapshotReplicationTest.java:250)                                                                                 
        at io.zeebe.broker.it.clustering.SnapshotReplicationTest.shouldReplicateNewerSnapshotAndRemoveOlderOne(SnapshotReplicationTest.java:159)                                                      
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by npepinpe** [comment]
I can't really say. It runs consistently well (ignoring the segmentation fault) on my local machine. Did you get these errors in CI or locally?

**Comment by menski** [comment]
I think I only saw them locally when trying to reproduce the segfault. Can't remember that I saw them on Jenkins. I will test it again when I find time for it. Thanks.

**Comment by npepinpe** [comment]
I figured out the issue. All tests follow a common pattern:

1. Start cluster
2. Get leader for partition P
3. Get follower for partition P
... test stuff

The issue is, very seldom the follower changes. So we check if the follower replicated the snapshot, which is not true since right after checking who was the follower it changed, so we're checking the wrong node.

One possible fix is to then operate on the cluster as a whole, but again that assumes the leader never changes. Is there a way to enforce cluster stability for tests? Or can I be sure the leader won't change?

**Comment by menski** [comment]
thanks for checking again

**Comment by npepinpe** [comment]
Assigned to you to review, primarily because I guess you're the one who has the most chance to notice if the tests are still unstable. At this point running it in the loop, it works except when I get the occasional segfaults, so maybe you can already rebase your branch against develop and see.
