### ISSUE TITLE
Could not close transport in time

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#969]
Failed for the first time

https://hq2.camunda.com/jenkins/zeebe/job/zeebe/job/965-release-sockets/8/console

```java
09:51:32 [ERROR] Tests run: 25, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.444 s <<< FAILURE! - in io.zeebe.transport.ClientTransportTest
09:51:32 [ERROR] shouldCloseTransportWithUnreachableRemote(io.zeebe.transport.ClientTransportTest)  Time elapsed: 10.019 s  <<< FAILURE!
09:51:32 java.lang.AssertionError: Could not close transport in time
09:51:32 	at io.zeebe.transport.ClientTransportTest.shouldCloseTransportWithUnreachableRemote(ClientTransportTest.java:775)
09:51:32 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:51:32 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:51:32 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:51:32 	at java.lang.reflect.Method.invoke(Method.java:498)
09:51:32 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
09:51:32 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
09:51:32 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
09:51:32 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
09:51:32 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
09:51:32 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
09:51:32 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
09:51:32 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
09:51:32 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
09:51:32 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
09:51:32 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
09:51:32 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
09:51:32 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
09:51:32 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
09:51:32 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
09:51:32 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
09:51:32 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
09:51:32 	at org.junit.runners.Suite.runChild(Suite.java:128)
09:51:32 	at org.junit.runners.Suite.runChild(Suite.java:27)
09:51:32 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
09:51:32 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
09:51:32 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
09:51:32 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
09:51:32 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
09:51:32 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
09:51:32 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
09:51:32 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
09:51:32 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
09:51:32 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
09:51:32 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
09:51:32 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
09:51:32 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
09:51:32 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
09:51:32 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
09:51:32 Caused by: java.util.concurrent.TimeoutException: Timeout after: 10 SECONDS
09:51:32 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:141)
09:51:32 	at io.zeebe.transport.ClientTransportTest.shouldCloseTransportWithUnreachableRemote(ClientTransportTest.java:773)
09:51:32 	... 38 more
09:51:32 
```

**Comment by Zelldon** [comment]
Never saw this again
