### ISSUE TITLE
CustomEventTest are unstable

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#975]
Run on jenkins two builds a test fails in two different ways.

https://hq2.camunda.com/jenkins/zeebe/job/zeebe/job/972-logstreams-tests/2/console

```java
13:28:41 [INFO] Running io.zeebe.gossip.GossipJoinTest
13:28:41 [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.722 s - in io.zeebe.gossip.GossipJoinTest
13:28:41 [INFO] Running io.zeebe.gossip.CustomEventTest
13:28:41 [ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.994 s <<< FAILURE! - in io.zeebe.gossip.CustomEventTest
13:28:41 [ERROR] shouldRemoveCustomEventListener(io.zeebe.gossip.CustomEventTest)  Time elapsed: 0.095 s  <<< FAILURE!
13:28:41 org.junit.ComparisonFailure: expected:<[2]> but was:<[0]>
13:28:41 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
13:28:41 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
13:28:41 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
13:28:41 	at io.zeebe.gossip.CustomEventTest.shouldRemoveCustomEventListener(CustomEventTest.java:285)
13:28:41 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:28:41 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:28:41 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:28:41 	at java.lang.reflect.Method.invoke(Method.java:498)
13:28:41 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
13:28:41 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
13:28:41 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
13:28:41 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
13:28:41 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
13:28:41 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:28:41 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:28:41 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:28:41 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:28:41 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
13:28:41 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
13:28:41 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:28:41 	at java.lang.Thread.run(Thread.java:748)
```
https://hq2.camunda.com/jenkins/zeebe/job/zeebe/job/972-logstreams-tests/1/console
```java

13:18:58 [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.755 s - in io.zeebe.gossip.GossipJoinTest
13:18:58 [INFO] Running io.zeebe.gossip.CustomEventTest
13:18:58 [ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.095 s <<< FAILURE! - in io.zeebe.gossip.CustomEventTest
13:18:58 [ERROR] shouldRemoveCustomEventListener(io.zeebe.gossip.CustomEventTest)  Time elapsed: 10.014 s  <<< ERROR!
13:18:58 org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
13:18:58 	at sun.misc.Unsafe.park(Native Method)
13:18:58 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
13:18:58 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
13:18:58 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:144)
13:18:58 	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:118)
13:18:58 	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:28)
13:18:58 	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:224)
13:18:58 	at io.zeebe.transport.ServerTransport.close(ServerTransport.java:63)
13:18:58 	at io.zeebe.gossip.util.GossipRule.after(GossipRule.java:160)
13:18:58 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
13:18:58 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:18:58 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:18:58 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
13:18:58 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
13:18:58 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:18:58 	at java.lang.Thread.run(Thread.java:748)
13:18:58 
```

**Comment by Zelldon** [comment]
In the gossip rule there is a `ReceivedEventsCollector`. These collector is an FragmentHandler and ClientInputListener, which will be register on the client transport as input listener. Every time an gossip node receives an event this collector receives this event as well and put this into his own list of events.

In the test `shouldRemoveCustomEventListener` we add and remove CustomEventListener to a GossipNode. After publishing an event on another node we wait until the `ReceivedEventsCollector` has seen this event. After that, we assert that our listeners are called. In 80% of the runs this will succeed because the code is quite fast, but as you can image the race condition can happen, that `ReceivedEventsCollector` has seen this event but the listeners NOT YET. If we now assert that the listeners was called the test fails. In the log we see, that after the assertion failed the listeners are invoked.

**Comment by Zelldon** [comment]
This also explains why the following tests are unstable:

```java

  @Test
  @Category(UnstableTest.class)
  public void shouldSpreadSuspectEvent() {
    // given
    cluster.interruptConnectionBetween(gossip3, gossip1);
    cluster.interruptConnectionBetween(gossip3, gossip2);

    // when send SUSPECT event
    cluster.waitUntil(() -> gossip1.receivedMembershipEvent(MembershipEventType.SUSPECT, gossip3));
    cluster.waitUntil(() -> gossip2.receivedMembershipEvent(MembershipEventType.SUSPECT, gossip3));

    assertThat(gossip1.hasMember(gossip3)).isTrue();
    assertThat(gossip2.hasMember(gossip3)).isTrue();
  }

  @Test
  @Category(UnstableTest.class)
  public void shouldSpreadConfirmEvent() {
    // given
    cluster.interruptConnectionBetween(gossip3, gossip1);
    cluster.interruptConnectionBetween(gossip3, gossip2);

    // when send CONFIRM event after suspicion timeout
    cluster.waitUntil(() -> gossip1.receivedMembershipEvent(MembershipEventType.CONFIRM, gossip3));
    cluster.waitUntil(() -> gossip2.receivedMembershipEvent(MembershipEventType.CONFIRM, gossip3));

    assertThat(gossip1.hasMember(gossip3)).isFalse();
    assertThat(gossip2.hasMember(gossip3)).isFalse();
  }
```
