### ISSUE TITLE
SegFault in Gossip CustomEventTest

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#987]
Saw this today twice on my windows machine in the gossip test suite (on 975-customevent-test branch)

```java
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.zeebe.gossip.CustomEventTest
[WARNING] Corrupted stdin stream in forked JVM 1. See the dump file C:\Users\zell\development\zeebe\gossip\target\surefire-reports\2018-06-22T12-46-54_504-jvmRun1.dumpstream
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.035 s
[INFO] Finished at: 2018-06-22T12:47:07+02:00
[INFO] Final Memory: 31M/324M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project zb-gossip: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\zell\development\zeebe\gossip\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_161\jre\bin\java" -jar C:\Users\zell\development\zeebe\gossip\target\surefire\surefirebooter8437183087581004648.jar C:\Users\zell\development\zeebe\gossip\target\surefire 2018-06-22T12-46-54_504-jvmRun1 surefire498728527348712257tmp surefire_05091638377408589920tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] io.zeebe.gossip.CustomEventTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_161\jre\bin\java" -jar C:\Users\zell\development\zeebe\gossip\target\surefire\surefirebooter8437183087581004648.jar C:\Users\zell\development\zeebe\gossip\target\surefire 2018-06-22T12-46-54_504-jvmRun1 surefire498728527348712257tmp surefire_05091638377408589920tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] io.zeebe.gossip.CustomEventTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

[io.zeebe.gossip.CustomEventTest-output.txt](https://github.com/zeebe-io/zeebe/files/2127334/io.zeebe.gossip.CustomEventTest-output.txt)
[2018-06-22T12-46-54_504-jvmRun1.txt](https://github.com/zeebe-io/zeebe/files/2127339/2018-06-22T12-46-54_504-jvmRun1.txt)

**Comment by menski** [comment]
Do you still have the file `C:\Users\zell\development\zeebe\gossip\hs_err_pid9008.log` and could attach it?

**Comment by Zelldon** [comment]
Sure here from the last two seg faults: 
[hs_err_pid9008.txt](https://github.com/zeebe-io/zeebe/files/2127346/hs_err_pid9008.txt)
[hs_err_pid9236.txt](https://github.com/zeebe-io/zeebe/files/2127347/hs_err_pid9236.txt)

**Comment by menski** [comment]
I now also saw it once on linux. A litte bit more stack in the error report.
[hs_err_pid13620.log](https://github.com/zeebe-io/zeebe/files/2127858/hs_err_pid13620.log)

**Comment by Zelldon** [comment]
The error also happens in `GossipFailureDetectionTest`

[hs_err_pid8184.log](https://github.com/zeebe-io/zeebe/files/2129968/hs_err_pid8184.log)

**Comment by Zelldon** [comment]
I assume it is also "fixed" with https://github.com/zeebe-io/zeebe/issues/986, will close it until it happens again.
