### ISSUE TITLE
RaftRule acess log after close

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#990]
First time I saw this on jenkins:

https://hq2.camunda.com/jenkins/zeebe/job/zeebe/job/975-customevent-test/2/console

```java
23:09:02 [ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 67.21 s <<< FAILURE! - in io.zeebe.raft.RaftThreeNodesTest
23:09:02 [ERROR] shouldTruncateLog(io.zeebe.raft.RaftThreeNodesTest)  Time elapsed: 24.196 s  <<< ERROR!
23:09:02 java.lang.NullPointerException
23:09:02 	at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:126)
23:09:02 	at io.zeebe.logstreams.impl.log.fs.FsLogStorage.getFirstBlockAddress(FsLogStorage.java:462)
23:09:02 	at io.zeebe.logstreams.log.BufferedLogStreamReader.lookUpBlockAddressForPosition(BufferedLogStreamReader.java:338)
23:09:02 	at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:119)
23:09:02 	at io.zeebe.logstreams.log.BufferedLogStreamReader.seekToFirstEvent(BufferedLogStreamReader.java:134)
23:09:02 	at io.zeebe.raft.util.RaftRule.eventCommitted(RaftRule.java:381)
23:09:02 	at io.zeebe.raft.util.RaftClusterRule.lambda$null$11(RaftClusterRule.java:191)
23:09:02 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
23:09:02 	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
23:09:02 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
23:09:02 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
23:09:02 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
23:09:02 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
23:09:02 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
23:09:02 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
23:09:02 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
23:09:02 	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
23:09:02 	at io.zeebe.raft.util.RaftClusterRule.lambda$awaitInitialEventCommittedOnAll$12(RaftClusterRule.java:191)
23:09:02 	at io.zeebe.test.util.TestUtil.lambda$waitUntil$8(TestUtil.java:58)
23:09:02 	at io.zeebe.test.util.TestUtil$Invocation.lambda$until$10(TestUtil.java:136)
23:09:02 	at io.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:180)
23:09:02 	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:135)
23:09:02 	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:86)
23:09:02 	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:58)
23:09:02 	at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:277)
23:09:02 	at io.zeebe.raft.util.RaftClusterRule.awaitInitialEventCommittedOnAll(RaftClusterRule.java:190)
23:09:02 	at io.zeebe.raft.RaftThreeNodesTest.shouldTruncateLog(RaftThreeNodesTest.java:218)
23:09:02 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:09:02 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:09:02 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:09:02 	at java.lang.reflect.Method.invoke(Method.java:498)
23:09:02 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
23:09:02 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
23:09:02 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
23:09:02 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
23:09:02 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
23:09:02 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
23:09:02 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
23:09:02 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
23:09:02 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
23:09:02 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
23:09:02 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
23:09:02 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
23:09:02 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
23:09:02 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
23:09:02 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
23:09:02 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
23:09:02 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
23:09:02 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
23:09:02 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
23:09:02 	at org.junit.runners.Suite.runChild(Suite.java:128)
23:09:02 	at org.junit.runners.Suite.runChild(Suite.java:27)
23:09:02 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
23:09:02 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
23:09:02 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
23:09:02 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
23:09:02 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
23:09:02 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
23:09:02 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
23:09:02 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
23:09:02 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
23:09:02 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
23:09:02 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
23:09:02 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
23:09:02 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
23:09:02 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
23:09:02 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
23:09:02 
```

After that I run the raft suite in a loop and had this error also locally.

```java
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 96.676 s <<< FAILURE! - in io.zeebe.raft.RaftFiveNodesTest
[ERROR] shouldTruncateLog(io.zeebe.raft.RaftFiveNodesTest)  Time elapsed: 36.845 s  <<< ERROR!
java.lang.NullPointerException
        at io.zeebe.logstreams.impl.log.fs.FsLogSegment.getSizeVolatile(FsLogSegment.java:126)
        at io.zeebe.logstreams.impl.log.fs.FsLogStorage.getFirstBlockAddress(FsLogStorage.java:462)
        at io.zeebe.logstreams.log.BufferedLogStreamReader.lookUpBlockAddressForPosition(BufferedLogStreamReader.java:338)
        at io.zeebe.logstreams.log.BufferedLogStreamReader.seek(BufferedLogStreamReader.java:119)
        at io.zeebe.logstreams.log.BufferedLogStreamReader.seekToFirstEvent(BufferedLogStreamReader.java:134)
        at io.zeebe.raft.util.RaftRule.eventCommitted(RaftRule.java:381)
        at io.zeebe.raft.util.RaftClusterRule.lambda$null$11(RaftClusterRule.java:191)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
        at io.zeebe.raft.util.RaftClusterRule.lambda$awaitInitialEventCommittedOnAll$12(RaftClusterRule.java:191)
        at io.zeebe.test.util.TestUtil.lambda$waitUntil$8(TestUtil.java:58)
        at io.zeebe.test.util.TestUtil$Invocation.lambda$until$10(TestUtil.java:136)
        at io.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:180)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:135)
        at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:86)
        at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:58)
        at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:277)
        at io.zeebe.raft.util.RaftClusterRule.awaitInitialEventCommittedOnAll(RaftClusterRule.java:190)
        at io.zeebe.raft.RaftFiveNodesTest.shouldTruncateLog(RaftFiveNodesTest.java:214)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

**Comment by Zelldon** [comment]
Maybe related to https://github.com/zeebe-io/zeebe/issues/984

**Comment by menski** [comment]
We will replace the raft module
