### ISSUE TITLE
WorkflowTaskIOMappingTest flaky

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#991]
First failed 
https://hq2.camunda.com/jenkins/zeebe/job/zeebe/job/975-customevent-test/1/console

```java
18:07:44 [ERROR] Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.214 s <<< FAILURE! - in io.zeebe.broker.workflow.WorkflowTaskIOMappingTest
18:07:44 [ERROR] shouldUseEmptyObjectIfCreatedWithNoPayload(io.zeebe.broker.workflow.WorkflowTaskIOMappingTest)  Time elapsed: 0.056 s  <<< ERROR!
18:07:44 java.lang.RuntimeException: no more events available
18:07:44 	at io.zeebe.test.broker.protocol.clientapi.RawMessageCollector.get(RawMessageCollector.java:51)
18:07:44 	at io.zeebe.test.broker.protocol.clientapi.RawMessageCollector.get(RawMessageCollector.java:25)
18:07:44 	at java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(StreamSpliterators.java:1356)
18:07:44 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
18:07:44 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
18:07:44 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
18:07:44 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
18:07:44 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
18:07:44 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
18:07:44 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
18:07:44 	at io.zeebe.test.util.stream.StreamWrapper.findFirst(StreamWrapper.java:218)
18:07:44 	at io.zeebe.test.broker.protocol.clientapi.SubscribedRecordStream.getFirst(SubscribedRecordStream.java:67)
18:07:44 	at io.zeebe.test.broker.protocol.clientapi.TestTopicClient.receiveFirstJobCommand(TestTopicClient.java:396)
18:07:44 	at io.zeebe.broker.workflow.WorkflowTaskIOMappingTest.shouldUseEmptyObjectIfCreatedWithNoPayload(WorkflowTaskIOMappingTest.java:121)
18:07:44 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:07:44 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:07:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:07:44 	at java.lang.reflect.Method.invoke(Method.java:498)
18:07:44 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
18:07:44 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
18:07:44 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
18:07:44 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
18:07:44 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
18:07:44 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
18:07:44 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
18:07:44 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
18:07:44 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
18:07:44 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
18:07:44 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
18:07:44 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:07:44 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:07:44 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:07:44 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:07:44 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:07:44 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:07:44 	at org.junit.runners.Suite.runChild(Suite.java:128)
18:07:44 	at org.junit.runners.Suite.runChild(Suite.java:27)
18:07:44 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:07:44 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:07:44 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:07:44 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:07:44 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:07:44 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:07:44 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
18:07:44 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
18:07:44 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
18:07:44 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
18:07:44 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
18:07:44 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
18:07:44 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
18:07:44 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
18:07:44 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

**Comment by Zelldon** [comment]
Was deleted
